### ISSUE TITLE
"Remote key not fetched correctly from keyserver" error during compilation.

### ISSUE THREAD

**Issue by bslava** [pikvm/pikvm#10]
Hi,

I'm trying to compile the image and received the following error:
```
Step 26/73 : RUN pacman-key --keyserver pgp.mit.edu -r 912C773ABBD1B584 && pacman-key --lsign-key 912C773ABBD1B584 && echo -e "\n[pikvm]" >> /etc/pacman.conf && case "$BOARD" in zero|zerow) echo "Server = https://pikvm.org/repos/rpi" >> /etc/pacman.conf;; *) echo "Server = https://pikvm.org/repos/$BOARD" >> /etc/pacman.conf;; esac && echo "SigLevel = Required DatabaseOptional" >> /etc/pacman.conf
---> Running in e505b452212b
gpg: keyserver receive failed: No keyserver available
==> ERROR: Remote key not fetched correctly from keyserver.
The command '/bin/sh -c pacman-key --keyserver pgp.mit.edu -r 912C773ABBD1B584 && pacman-key --lsign-key 912C773ABBD1B584 && echo -e "\n[pikvm]" >> /etc/pacman.conf && case "$BOARD" in zero|zerow) echo "Server = https://pikvm.org/repos/rpi" >> /etc/pacman.conf;; *) echo "Server = https://pikvm.org/repos/$BOARD" >> /etc/pacman.conf;; esac && echo "SigLevel = Required DatabaseOptional" >> /etc/pacman.conf' returned a non-zero code: 1
make[1]: *** [Makefile:208: os] Error 1
```
What I'm doing wrong? Please help!

Regards,
Slava

**Comment by mdevaev** [comment]
Hello! Just try build again, it looks like a temporary problem

**Comment by bslava** [comment]
I found a w/a -t define BOARD variable from the command line. After that make completed. I do not understand why it wasn't initialized from config.mk file.

**Comment by mdevaev** [comment]
Strange issue, no one has ever encountered this

**Comment by JsBergbau** [comment]
I've encountered this issue several times when building the OS. After a second `make os` it went on and finally completed the build process.

**Comment by mdevaev** [comment]
Still can't reproduce :/

**Comment by dogmachine** [comment]
i ran into this.  retried 10 times and same problem. changed pgp.mit.edu to hkps://pgp.mit.edu and it worked.  but also the http frontend for http://pgp.mit.edu was sometimes failing to read from its upstream proxy so i suspect it was just semi-broken at the time.  probably would have worked without making that change had i tried again at that time.  maybe chuck some alternative key servers in there?

**Comment by mdevaev** [comment]
Well, if hkps://pgp.mit.edu is working fine I will add it. Ironically, many people had a correlation of this problem with specifying the BOARD variable. I was beginning to think I was going mad.

**Comment by mdevaev** [comment]
Wait, I understand correctly that you think that sometimes hkps does not respond?

**Comment by mdevaev** [comment]
Yes, it is. Now we will use. hkps://hkps.pool.sks-keyservers.net
Thank you for the diagnostics!
