### ISSUE TITLE
EZCOO and VNC: Detail missing

### ISSUE THREAD

**Issue by pompfe** [pikvm/pikvm#1002]
I use the EZCOO KVM switch with PiKVM (with USB switching) and installed the VNC server on PiKVM.

I can attach my VNC viewer with PiKVM but I am bound to the port (session) on the EZCOO that is currently set up via web interface (and USB).  I don't access it via web, only via VNC viewer.

My problem is, I found no way to change the KVM switch port remotely (on PiKVM from command line that I can access in parallel via SSH).

Is there an easy way to change the active EZCOO KVM switch port from a command line?  A script or a snippet or something I can send to the USB port to switch input ports?  If there is such a way, does the web interface "see" that change in the menu?

Thank you!
-pompfe

**Comment by mdevaev** [comment]
Hello. There is an API for switching channels. Unfortunately, this is the only thing I can offer you now:
* https://docs.pikvm.org/api
* Example: `curl -XPOST -HX-KVMD-User:admin -HX-KVMD-Passwd:foobar -k 'https://pikvm/api/gpio/pulse?channel=ch0_button'

**Comment by pompfe** [comment]
> ... Unfortunately, this is the only thing I can offer you now:

This is exactly what I was looking for.  Sorry for not checking the api docs beforehand.
Thank you!

**Comment by mdevaev** [comment]
Welcome!
