### ISSUE TITLE
Feature Request: Add option to move some items from Shortcuts to the Top of the PiKVM bar.

### ISSUE THREAD

**Issue by Vladimir2989** [pikvm/pikvm#1003]
As I use PiKVM predominantly with Domain Joined Windows machines, so use CTRL+ALT+DEL quite a lot and would appreciate option to have shortcut sit on the top bar at all times.
Or maybe add option to add custom shortcuts to the top bar, like I could do with CTRL+ALT+END too for RDP sessions.

**Comment by mdevaev** [comment]
Merged with #207
