### ISSUE TITLE
Add another menu like GPIO or ATX if GPIO menu becomes full

### ISSUE THREAD

**Issue by pompfe** [pikvm/pikvm#1004]
Is there a way to add another menu that references gpio.  The one gpio menu becomes overloaded.
I mean a menu like GPIO or ATX.  The EZCOO and ipmi entries fill up the GPIO menu.  I tried with multiple view/header/table entries in override.yaml but it always seems to take the last entry only.
This was already asked here:  https://discord.com/channels/580094191938437144/880066200959328328/1006614348615139398

**Comment by mdevaev** [comment]
Hello. Why you need it?

**Comment by mdevaev** [comment]
I've made scrollable GPIO menu. This should be enough in the first approximation.
