### ISSUE TITLE
Ability to Set Network Config Via pikvm.txt

### ISSUE THREAD

**Issue by jtoland** [pikvm/pikvm#1010]
**Is your feature request related to a problem? Please describe.**
It would be nice to set the network config for static ip addresses via pikvm.txt (Especially for WIFI)
This would be really useful so I can get Datacenter engineer to redeploy PIKVMs on the fly without them needing access to SSH to do this.

**Describe the solution you'd like**
To be able to add static WLAN Config via PIKVM.txt so users don't need to do this via ssh.

**Comment by mdevaev** [comment]
Sup. This is already implemented: https://github.com/pikvm/kvmd/blob/master/scripts/kvmd-bootconfig#L121
