### ISSUE TITLE
Get current state of mouse coordinates (relative mode)

### ISSUE THREAD

**Issue by d7laungani** [pikvm/pikvm#1012]
**Is your feature request related to a problem? Please describe.**

I am trying to track the mouse to see if it is moved. If we can return the mouse location as part of an info event then I can build logic around that. 

**Describe the solution you'd like**

I would like the mouse coordinates to be a part of a regular event so I can compare it to the next so I can tell if the mouse moved or not .

**Describe alternatives you've considered**

I have considered using the streamer event but that just will allow me to know when the stream is broken but I need to specifically check when the mouse has moved. 

**Additional context**
I did look through this code -- https://github.com/pikvm/kvmd/blob/master/kvmd/plugins/hid/_mcu/proto.py

But i don't understand how to modify the hex values to make a request to get the current coordinates.

**Comment by mdevaev** [comment]
Hello. There is no way to get the mouse position back from the host. It's a USB HID limitation.
