### ISSUE TITLE
Pi-KVM Video Stream Issue in Web Sites

### ISSUE THREAD

**Issue by wohenipinle** [pikvm/pikvm#1018]
When connecting Pi-KVM in web sites, the video stream would keep appearing  and disappearing.
During this period, the usb signal would work still (the traget board could be controlled.).

Steps to reproduce the behavior, like:
1. Open PI-KVM websites
2. Turn on the controlled target board 
3. Video stream starts appear and disappear

Screen Shots:
![image](https://github.com/pikvm/pikvm/assets/80097053/5edcc591-428a-4fca-b1a9-48e41dc480e8)
![image](https://github.com/pikvm/pikvm/assets/80097053/52ee30c4-63cf-4e4b-b90d-7d7b591c499d)
![image](https://github.com/pikvm/pikvm/assets/80097053/5689d887-a3d7-4a90-900e-bddafd77be6d)

Environment:
  - Raspberry Pi board version: RPi 4B
  - Video capture type: HDMI-CSI bridge
  - OS: Target Board (Win11 22H2), 
           Pi-KVM (Default image for Pi 4B)
  - Browser: Microsoft Edge

**Comment by mdevaev** [comment]
Also try Chrome instead of Edge.

**Comment by mdevaev** [comment]
Closed because there is no feedback from user.
