### ISSUE TITLE
use HDMI output as a normal RPI linux desktop

### ISSUE THREAD

**Issue by ale-novo** [pikvm/pikvm#1019]
Hi, this is more of a question rather than a feature request.

if i install pikvm software in a RPI, Is it possible to use the RPI hdmi output as a normal RPI desktop? 

My use case is that i want to be able to forward my webcam from my laptop to the computer connected to PIKVM
since this feature is not supported by pikvm out of the box, my idea is to have a cheap usb to hdmi capture card connected to the remote computer that is connected to pikvm.
then use another computers hdmi output connected to this capture card, and the select is as a webcam source.
i would have to use 2 rpis for this, one for pikvm and another for the hdmi output. it would be great if everything could be done from one pi.
the idea is to join a meeting like google hangouts from both the rpi and my laptop to share my webcam and use the rpi hdmi output connected to the usb capture card and act as a webcam

hope that makes sense.
cheers.

**Comment by mdevaev** [comment]
Hello. I strongly do not recommend running a desktop, as this will require remounting the root file system for writing and will greatly reduce the reliability of the entire system. If you need to stream the camera, I recommend running [ustreamer](https://github.com/pikvm/ustreamer) as a service on one of the ports.
