### ISSUE TITLE
Virtual Rom Feature Fail

### ISSUE THREAD

**Issue by wohenipinle** [pikvm/pikvm#1020]
Hi,

When I use virtual rom feature on Pi KVM websites, it failed to install windows11 22H2 iso.
Failed as follow:
![image](https://github.com/pikvm/pikvm/assets/80097053/17ad3e99-d967-4285-af28-b88210ef18a7)

Environment as below:
1.Pi KVM 4B
2.Pi KVM default image
3.Drive Mode: Flash
![image](https://github.com/pikvm/pikvm/assets/80097053/21451fcc-3fbc-4780-b3cd-64b245149e44)

4.Connect Main USB to server: on
![image](https://github.com/pikvm/pikvm/assets/80097053/87f8508b-e3f7-43f3-ae38-5c8ca04a7374)

Any suggestions for this failure?

Thanks for your help!
BR,

**Comment by mdevaev** [comment]
I suppose the installer requires exactly cdrom drive. As I remember, in Windows there are ways to create an installation image for a flash drive, try to look for something in this direction.
