### ISSUE TITLE
Now a issue but a question.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [pikvm/pikvm#1023]
Hello, Is it possible to run our own capture cards as well does the pikvm work on the pi3?

Joseph

**Comment by Therealjosephchrzempiec** [comment]
I'm using this card from Amazon.

BlueAVS HDMI to USB Video Capture Card 1080P for Live Video Streaming Record via DSLR Camcorder Action Cam (Black) 

https://a.co/d/bnNsWXI

**Comment by mdevaev** [comment]
It should work.

**Comment by Therealjosephchrzempiec** [comment]
I'm over there now thank you.
