### ISSUE TITLE
USB splitter not working

### ISSUE THREAD

**Issue by mtz29** [pikvm/pikvm#1032]
I bought https://www.amazon.co.uk/dp/B09PFQXJR3 ( I've got usbc PSU for my rpi4), but it does not work (no usb detected).

A the moment I am running rpi4 over usb hub, because my Mac [M2 Max] does not provide current if RPI4 is plugged in directly. RPI is obviously under powered. What am I missing?

**Comment by mdevaev** [comment]
Hello. Please use the support chat for this and similar questions: https://discord.gg/bpmXfz5
