### ISSUE TITLE
Start connected PC after power loss

### ISSUE THREAD

**Issue by martinjung7109** [pikvm/pikvm#1034]
**Is your feature request related to a problem? Please describe.**
We want to use an old consumer motherboard for our backup server which doesn't have the BIOS setting to automatically start the server after a power loss. We plan to use PiKVM 4 for remote access.

**Describe the solution you'd like**
I'd like the PiKVM to be able to start the server when power is restored, using the ATX power button.

**Describe alternatives you've considered**
We considered buying a motherboard which supports starting the server after a power loss but we want to save money by using the components we already have.

**Additional context**

**Comment by mdevaev** [comment]
Hello. You could use PiKVM ATX API to monitor the power state and send the power click signal when needed: https://docs.pikvm.org/api/#atx-power-management

**Comment by martinjung7109** [comment]
I didn't come across this solution. Thank you, I will try it.

**Comment by mdevaev** [comment]
Let me know if you'll need a help
