### ISSUE TITLE
build of kvmd fails against setuptools 68.0.0

### ISSUE THREAD

**Issue by stanislavlevin** [pikvm/pikvm#1037]
Build of `kvmd` fails against `setuptools` `68.0.0` with:
```
AttributeError: type object '_ScriptWriter' has no attribute 'get_script_args'. Did you mean: '_get_script_args'?
```

`setuptools` `68.0.0` introduced many breaking changes https://setuptools.pypa.io/en/stable/history.html#v68-0-0
one of them:
> pypa/setuptools#3948: Remove deprecated APIs in easy_install: get_script_args, get_script_header and get_writer. The direct usage of easy_install has been deprecated since v58.3.0, and the warnings regarding these APIs predate that version.

**Comment by mdevaev** [comment]
Fixed, thank you
