### ISSUE TITLE
Agent / Interface

### ISSUE THREAD

**Issue by Mightyretro** [pikvm/pikvm#1038]
Hi guys hope your doing well.

is there possible to have like implement something similar to interface and maybe host it yourself x86 machine if you have bunch of lab computers or friends or familys computer need remote management but still use (Pikvm x86 --->> friends house Pikvm arm)

https://github.com/amidaware/tacticalrmm

https://rport.io/

Kind Regards // Mighty

**Comment by mdevaev** [comment]
Hi. Unfortunately, I didn't understand anything from your request. What exactly do you want to get?

**Comment by mdevaev** [comment]
Sup?

**Comment by Mightyretro** [comment]
Sorry for late answer ;)

1. is it possible to update interface a bit something similar to down below its mutch easier categorise vm or computer you connect to for example "Homelab" etc
https://github.com/amidaware/tacticalrmm
https://rport.io/

2. is it possible to run pikvm on your own x86 hardware and you perhaps install an "Agent on client side" or also Pikvm / BliKVM PCIe...?

Kind Regards // Mighty
