### ISSUE TITLE
CM4 version

### ISSUE THREAD

**Issue by KuDeSnik33ra** [pikvm/pikvm#104]
Hello! Are you having any plans on making PCI bracket based RPi CM4 version of board?

**Comment by mdevaev** [comment]
Yes, we plan to do this after the release of v3.

**Comment by KuDeSnik33ra** [comment]
Will it have mobo header power button switch - to poweron pc remotely (and locally via pass through)?

**Comment by mdevaev** [comment]
Yes. The current version is also have it.
