### ISSUE TITLE
Macro script - non-int mouse move X

### ISSUE THREAD

**Issue by Majestic7979** [pikvm/pikvm#1041]
**Describe the bug**
I saw the JS file and I can see the function that expects only an int.

I am trying to use this snippet on my code:
```
    {
        "event_type": "mouse_move",
        "event": {
            "to": {
                "x": "Math.floor(Math.random() * 10000) + 1",
                "y": "Math.floor(Math.random() * 10000) + 1"
            }
        }
    },
```
I also tried this way:
```
    {
        "event_type": "mouse_move",
        "event": {
            "to": {
                "x": "paseInt(Math.floor(Math.random() * 10000) + 1)",
                "y": "parseInt(Math.floor(Math.random() * 10000) + 1)"
            }
        }
    },
```
Same thing.

I need to randomize the mouse move, so that it's not always on the same spot, the above function would take care of that without having to create scripts and mess with python. I would like to propose that this is a bug, because it expects Int number which the above code generates, but it doesn't accept it until it's a hard-coded value. Int should be int regardless how you get it, whether it's randomized or hard-coded. This is how the error message puts it: "give me an int". It shouldn't matter how the Int is defined.

It would be great if the js code in recorder.js was amended to accept stuff like the above. Still getting an int value but not just hard-coded.

I do not know coding, my knowledge in the area is very limited, otherwise I would definitely amend and do a pull.

**Comment by mdevaev** [comment]
You are using incorrect syntax. In your example, the value is a string. This is the correct code:
```js
    {
        "event_type": "mouse_move",
        "event": {
            "to": {
                "x": Math.floor(Math.random() * 10000) + 1,
                "y": Math.floor(Math.random() * 10000) + 1
            }
        }
    },
```

**Comment by Majestic7979** [comment]
Yes, I tried that before but it doesn't work:
![image](https://github.com/pikvm/pikvm/assets/128995501/db666859-1e5a-4fd6-a285-cfdfd75f3411)
This is why I raised this bug report

**Comment by Majestic7979** [comment]
Would be amazing if you are able to fix please and thanks.

**Comment by mdevaev** [comment]
It can't be fixed in this way because this is a json file, not js. If you want to have a mouse jiggler this way, you can just record the chaotic movement of the cursor and just play it back. I really don't understand why randomization is needed here.

**Comment by Majestic7979** [comment]
> It can't be fixed in this way because this is a json file, not js. If you want to have a mouse jiggler this way, you can just record the chaotic movement of the cursor and just play it back. I really don't understand why randomization is needed here.

Because the machine is monitored, and if the cursor is always moving the same way they will know it's being jiggled artificially. It needs to be truly random, and I bought your PiKVM specifically because of this Macro function thinking that because it's based on javascript it would just work. I know you can absolutely make it work, the question is do you want to do it, or not? The randomization is also for the delay by the way. It's for anything that accepts integer values. I have two of your V3 boards, I am not just an internet whiner, I actually supported your business by buying two of your things, if you can fix this issue that will be appreciated.

**Comment by mdevaev** [comment]
I said it couldn't be fixed that way, but I didn't say it couldn't be solved at all :)

Give me a little time out to think. I think I could add something like a string operator.

By the way, you do realize that this only works while your browser is open and the connection to PiKVM is established? Maybe some kind of server solution from the PiKVM side would suit you better?

**Comment by Majestic7979** [comment]
> I said it couldn't be fixed that way, but I didn't say it couldn't be solved at all :)
> 
> Give me a little time out to think. I think I could add something like a string operator.
> 
> By the way, you do realize that this only works while your browser is open and the connection to PiKVM is established? Maybe some kind of server solution from the PiKVM side would suit you better?

Thank you, I hope you can think something soon.

I don't mind leaving a browser tab open with pikvm on the background, this is what I do now. Does the tab have to be active in the foreground? It seems to keep running when I toggle the loop function. Even if I navigate to a new tab or minimize the web browser.

Running on the server would be awesome! Then the macro button could interface with the server code and show status but the server daemon would handle the events transparently.

**Comment by mdevaev** [comment]
As a quick solution, I can offer you a new type of event. What do you say? For example:
```json
    {
        "event_type": "mouse_move_random",
        "event": {
            "range": {
                "min": -1000,
                "max": 1000,
            }
        }
    },
```
In fact, what you want is called "Mouse Jiggler" and [I have a task for this](https://github.com/pikvm/pikvm/issues/57). I'm getting closer to it little by little.

**Comment by Majestic7979** [comment]
> As a quick solution, I can offer you a new type of event. What do you say? For example (range both for X and Y):
> 
> ```json
>     {
>         "event_type": "mouse_move_random",
>         "event": {
>             "range": {
>                 "min": -1000,
>                 "max": 1000,
>             }
>         }
>     },
> ```
> 
> In fact, [I have a task for the mouse jiggler](https://github.com/pikvm/pikvm/issues/57). I'm getting closer to it little by little.

100000% Love you! 💖💖💖 Amazing. How long to basically get this?

Could you also offer a random for the time? I want to also have a random for the milliseconds.... then it will look like the moves are happening at random times, just like a real person would be using a computer.

**Comment by mdevaev** [comment]
Ofc. Please test it. Place:
* https://raw.githubusercontent.com/pikvm/kvmd/master/web/share/js/tools.js to `/usr/share/kvmd/web/share/js/`
* https://raw.githubusercontent.com/pikvm/kvmd/master/web/share/js/kvm/recorder.js to /usr/share/kvmd/web/share/js/kvm/`

Clear the browser cache and reload page.

Delay format:
```json
    {
        "event_type": "delay_random",
        "event": {
            "range": { // Milliseconds!
                "min": 100,
                "max": 1000,
            }
        }
    },
```

**Comment by Majestic7979** [comment]
Did that, this is what happens:
![image](https://github.com/pikvm/pikvm/assets/128995501/edff7b01-431d-4db8-ac86-7774214fcac3)

My updated script on pastebin (it will disappear after you view one so please copy into notepad if you need to keep a record) - the password is pikvm: https://pastebin.com/hRuP7ism

**Comment by mdevaev** [comment]
Remove commas after all "max" lines: `"max": 10000,`

**Comment by mdevaev** [comment]
Please update `recorder.js` again from that link and try it.

**Comment by Majestic7979** [comment]
Did that. Still not doing anything. The "script time" is now showing zero, which I understand because it's random each time. Before I updated the files first time and before you told me to update again now, it was still showing the script time. Not sure if related whatsoever. New copy of pastebin just in case - password pikvm and it will burn after you read it: https://pastebin.com/jWqxF8m7

**Comment by Majestic7979** [comment]
Now even the script that had fixed values isn't working...

**Comment by mdevaev** [comment]
I'm fising it now. Just found two problems.

**Comment by mdevaev** [comment]
Okay, I've tested it, everything should work now. Please update entire OS / KVMD to 2.234 and reboot.

**Comment by Majestic7979** [comment]
so to confirm, pacman -Syu and reboot?

**Comment by mdevaev** [comment]
Yes.

**Comment by Majestic7979** [comment]
Brother I can't tell you how much I appreciate you. I am laughing my ass off as I watch the cursor move randomly and they are unaware it's not a person. Thank you! That's your mouse jiggler right there. All you got to do now is to remove the F5 key from my script and just make a button to trigger this script and you have your mouse jiggler. Just make a little popup with sliders to configure the randomness values and you've got the jiggler that everyone's been asking for. You've just killed two birds with one stone. Thanks again for doing this so quickly for me, bless you 🙏

**Comment by mdevaev** [comment]
Ur welcome :ok_hand: 

I want to make a server-side jiggler that would work independently of the web interface. I'm hatching an idea of how to implement it.

**Comment by Majestic7979** [comment]
> Ur welcome 👌
> 
> I want to make a server-side jiggler that would work independently of the web interface. I'm hatching an idea of how to implement it.

Good luck I have absolutely 100% confidence that you can pull this off.
