### ISSUE TITLE
Scroll distance for mouse wheel

### ISSUE THREAD

**Issue by visit1985** [pikvm/pikvm#1043]
I'm using PiKVM for quite some time now. And I'm pretty happy  with it.

I own a Logitech MX Master 2S Mouse, which has this SmartShift feature which allows you to scroll short distances with kind of a "snap in" haptic feedback after around 3mm of finger movement.

The problem is, that PiKVM reacts after around 2-3 snaps to the scroll action, which sometimes leads to a page jump on the viewed document. Is there a way to influence this?

The "Mouse polling rate" setting seems to have no effect on it.

If you need any further information, I can help you debug it.

Thanks in advance!

**Comment by mdevaev** [comment]
Mouse scrolling is a pain. Try to play with this options:
![image](https://github.com/pikvm/pikvm/assets/416259/f68379bc-0e94-49d2-bc4b-1ca1c45c12b8)
In my case, the config above works acceptable.

Which browser and OS (on both sides) you use?

**Comment by visit1985** [comment]
Thanks for the hint.

> Which browser and OS (on both sides) you use?

Google Chrome (macOS Monterey) --> PiKVM --> Google Chrome (Windows 10) 

I had to upgrade to find this option in the interface. Didn't do that for more than a year. 😄 The system is just so stable, I didn't feel the need to do it.

A quick test shows improvement. I will see how it behaves during normal workdays.

**Comment by mdevaev** [comment]
:ok_hand:
