### ISSUE TITLE
Call to action for fan failure doesn't tell you where to look

### ISSUE THREAD

**Issue by voltagex** [pikvm/pikvm#1047]
What log, where?

![image](https://github.com/pikvm/pikvm/assets/83080728/f26bf31e-5014-4415-bc62-21deb3e17088)

This is a web interface, why not make this a clickable link to the log?

**Comment by voltagex** [comment]
Yes

**Comment by mdevaev** [comment]
Edit the fan config `/etc/kvmd/fan.ini` and set `idle` and `low` values from 27 to 30, for example, then restart the service: `systemctl restart kvmd-fan`.

Don't forget to remount `ro`.

**Comment by voltagex** [comment]
> Edit the fan config `/etc/kvmd/fan.ini` and set `idle` and `low` values from 27 to 30, for example, then restart the service: `systemctl restart kvmd-fan`.
> 
> 
> 
> Don't forget to remount `ro`.

Sure, that fixes the underlying issue but it doesn't improve the UI.

Thanks though.

**Comment by mdevaev** [comment]
Great! I will add a link to the log.

**Comment by mdevaev** [comment]
I've added the link to the log in this dropdown. Solved, I guess

**Comment by voltagex** [comment]
Thanks!
