### ISSUE TITLE
Possible to reset the USB-HDMI dongle via cmd ?

### ISSUE THREAD

**Issue by manasmgkar** [pikvm/pikvm#1058]
cant ge the hmdi-csi2 bridge due to chinese shipping bans in my country, with the USB-HDMI capture card/dongle if there is a black screen issue or some other issue it is possible to reset it remotely via the command line in pikvm ? basically, simulate a disconnect and reconnect ? i wont be having physical access to the pikvm for months once its deployed,is there a software way to do this.

**Comment by mdevaev** [comment]
USB capture is a black box that we cannot influence in any way, alas.

**Comment by manasmgkar** [comment]
> USB capture is a black box that we cannot influence in any way, alas.

but cant the usb port that it is connected to be reset to simulate a dissconnect/reconnect ? i have seen online people mentioning how simply dissconnecting/reseting the usb-hdmi physically solves a lot of the problems,software bassed disconnect/reconnect of the usb port itself could sort of mimic that.

**Comment by thomae** [comment]
You can try if usbreset from the usbutils package suits your need.

```
rw
pacman -Syy
pacman -S usbutils
ro
usbreset

Usage:
  usbreset PPPP:VVVV - reset by product and vendor id
  usbreset BBB/DDD   - reset by bus and device number
  usbreset "Product" - reset by product name
```

**Comment by mdevaev** [comment]
If it will work, you can bind these commands to web ui: https://docs.pikvm.org/gpio/#cmd

**Comment by mdevaev** [comment]
Answered, I guess.
