### ISSUE TITLE
Two pikvms for two displays for same pc - VNC to second pikvm "ignores" mouse/keyboard input

### ISSUE THREAD

**Issue by plia7** [pikvm/pikvm#1071]
**Describe the bug**
I have two pikvms which gives me two displays. If I VNC to second pikvm it "ignores" mouse/keyboard input.

**Prerequisites:** Connect pikvm 1 to first hdmi port in pc 1 and usb port. Connect pikvm 2 to second hdmi port in pc 1. Go into Windows display settings in the host pc and set the display mode as Extended.

**Note:** I didn't connect pikvm 2 to a second usb in pc 1, but if you do connect it, it doesn't seem to fix the issue although it looks like it's actually applying/showing the mouse/keyboard input on the other screen (you can see it in the web ui for the other screen).

**To Reproduce**
Steps to reproduce the behavior, like:
1. VNC to pikvm 2.

**Actual behavior**
You can see the display but mouse and keyboard input is being "ignored" (if you connect the second usb, it looks like it's actually  applying/showing the mouse/keyboard input on the other screen (you can see it in the web ui for the other screen)).

**Expected behavior**
Mouse and keyboard input work just like they do when you vnc to pikvm 1.

**Screenshots**

**Desktop (please complete the following information):**
 Windows 11
 - VNC client (if used)
Windows TigerVNC Viewer v1.13.1
or
iOS Jump Desktop v9.7.8

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4]
 PiKVM v3 Pre-Assembled
  - PiKVM platform [e.g. v2-hdmi]
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `pacman -Q | grep kvmd`
kvmd 3.236-1
kvmd-fan 0.26-1
kvmd-oled 0.24-1
kvmd-platform-v3-hdmi-rpi4 3.236-1
kvmd-webterm 0.43-1
  - uStreamer version: `pacman -Q | grep ustreamer`
  ustreamer 5.41-1
  - Linux kernel: `uname -a`
 Linux pikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux

**Additional context**
It seems like if you connect the second usb, when you connect to either one of the two vnc, it shows you the right screen, but on one of them, it doesn't seem to show/apply mouse/keyboard input, but it looks like it's actually applying/showing the mouse/keyboard input on the other screen (you can see it in the web ui for the other screen) which you don't see in the current vnc display connection where mouse/keyboard input doesn't work.

**Comment by plia7** [comment]
This is related to https://github.com/pikvm/pikvm/issues/1070

**Comment by mdevaev** [comment]
USB devices are not tied to the screen and have a single input field. In any case, I'm closing this since we already have https://github.com/pikvm/pikvm/issues/1070 issue about it, and within the described, everything works as it should.
