### ISSUE TITLE
H.264/ WebRTC not working behind Apache2 Reverse Proxy

### ISSUE THREAD

**Issue by jbyerline** [pikvm/pikvm#1081]
**Describe the bug**
H.264/ WebRTC not working behind Apache2 Reverse Proxy

The MJPEG and all other functionality works except for WebRTC

**Proxy Config**
```
<VirtualHost *:80>
  ServerName kvm.byerline.me
  Redirect permanent / https://kvm.byerline.me/
</VirtualHost>

<VirtualHost *:443>
    ServerName kvm.byerline.me

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/ca.crt
    SSLCertificateKeyFile /etc/apache2/ssl/ca.key
    SSLCertificateChainFile /etc/apache2/ssl/ca.ca-bundle
    
    SSLProxyEngine On
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    RewriteEngine on
    RewriteCond ${HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond ${HTTP:CONNECTION} ^Upgrade$ [NC]
    RewriteRule .* wss:/10.0.0.173%{REQUEST_URI} [P,L]

    ProxyPass /extras/webterm/ttyd/ws wss://10.0.0.173/extras/webterm/ttyd/ws
    ProxyPass /extras/webterm/ttyd/ https://10.0.0.173/extras/webterm/ttyd/
    ProxyPassReverse /extras/webterm/ttyd/ https://10.0.0.173/extras/webterm/ttyd/

    ProxyPass / https://10.0.0.173/
    ProxyPassReverse / https://10.0.0.173/

    <Location /api/ws>
            Order allow,deny
            Allow from all
            ProxyPass wss://10.0.0.173/api/ws
            ProxyPassReverse wss://10.0.0.173/api/ws
    </Location>

    ProxyRequests off
</VirtualHost>
```

**Expected behavior**
Expect WebRTC to work over proxy

**Screenshots**
<img width="994" alt="Screenshot 2023-08-03 at 10 46 48 PM" src="https://github.com/pikvm/pikvm/assets/47374239/7de38f32-50ee-4317-adad-576c1213f0ee">
<img width="997" alt="Screenshot 2023-08-03 at 10 46 54 PM" src="https://github.com/pikvm/pikvm/assets/47374239/fe316e06-a920-450c-ad1e-54be13e208c7">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser - Chrome

**PiKVM info:**
  - PiKVM platform v4 plus

**Additional context**
Followed guide from here: https://znil.net/index.php/PiKVM_hinter_Apache_Reverse_Proxy

**Comment by mdevaev** [comment]
Hello. You should also pass `/janus/ws` as websocket.

**Comment by jbyerline** [comment]
Thank you, that fixed it. I had to add:

```
<Location /janus/ws>
            Order allow,deny
            Allow from all
            ProxyPass wss://10.0.0.173/janus/ws
            ProxyPassReverse wss://10.0.0.173/janus/ws
</Location>
```

Now WebRTC works
