### ISSUE TITLE
Unit file kvmd-certbot.timer does not exist

### ISSUE THREAD

**Issue by ericswpark** [pikvm/pikvm#1087]
**Describe the bug**
When enabling automatic certificate renewal following [the Cloudflare DNS tutorial found here](https://docs.pikvm.org/letsencrypt/#cloudflare-dns), `systemctl` says the unit file does not exist.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Follow [the Cloudflare DNS tutorial](https://docs.pikvm.org/letsencrypt/#cloudflare-dns).
2. As the last step of the Cloudflare DNS tutorial tell you to refer to the previous section, go back to ["Basic Setup" and start from step 3](https://docs.pikvm.org/letsencrypt/#basic-setup).
3. Follow "Basic Setup" from step 3 to step 5
4. Run the commands in step 5 in order.

**Expected behavior**
The timer is enabled

**Screenshots**
Will attach output below

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] N/A
 - VNC client (if used) N/A

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4] RPi 4 compute module
  - PiKVM platform [e.g. v2-hdmi] PiKVM v4 Plus
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `pacman -Q | grep kvmd`

```
[root@dipper-pikvm ~]# pacman -Q | grep kvmd
kvmd 3.244-1
kvmd-fan 0.26-1
kvmd-oled 0.24-1
kvmd-platform-v4plus-hdmi-rpi4 3.244-1
kvmd-webterm 0.43-1
[root@dipper-pikvm ~]#
```

  - uStreamer version: `pacman -Q | grep ustreamer` ustreamer 5.41-1
  - Linux kernel: `uname -a` `Linux dipper-pikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux`

**Additional context**
Relevant command output:

```
# Before this line, I did use `rw` to remount the disk, so that's not the problem.
# I also ran a full upgrade and a reboot, and verified that PST storage support is there
[root@dipper-pikvm ~]# systemctl enable --now kvmd-certbot.timer
Failed to enable unit: Unit file kvmd-certbot.timer does not exist.
[root@dipper-pikvm ~]# pacman -Ql kvmd | grep kvmd-certbot
kvmd /usr/bin/kvmd-certbot
kvmd /usr/lib/systemd/system/kvmd-certbot.service
kvmd /usr/share/kvmd/configs.default/os/services/kvmd-certbot.service
kvmd /usr/share/kvmd/configs.default/os/services/kvmd-certbot.timer
[root@dipper-pikvm ~]# rw
[root@dipper-pikvm ~]# systemctl enable --now kvmd-certbot.timer
Failed to enable unit: Unit file kvmd-certbot.timer does not exist.
[root@dipper-pikvm ~]#
```

**Comment by mdevaev** [comment]
Fixed. Update after a hour, I'll build the new release now.
