### ISSUE TITLE
Input Latency on video window

### ISSUE THREAD

**Issue by Krotu** [pikvm/pikvm#1091]
If you find the input latency to be an issue, it is not always obvious what settings are making it better/worse.

If the latency was shown on the video stream (eg 20ms latency) along with the bandwidth/fps values then you could see this value going up/down while making adjustments.

**Comment by mdevaev** [comment]
Currently there is no way to calculate end-to-end latency robustly. And I don't see a technical way to do that, sorry.

See also: #784
