### ISSUE TITLE
Files in /etc/kvmd/override.d/ not properly merging

### ISSUE THREAD

**Issue by spoelstraethan** [pikvm/pikvm#1092]
**Describe the bug**
I attempted to define a TESmart KVM GPIO block in one file and a USB OTG configuration section in another file, but only one was getting loaded and the other seemed to be ignored. I had defined everything from the parent `kvmd:` section down through the GPIO sections and drivers, and I expected it would merge the `view:` sections using all the views from the first file alphabetically and then the second file etc.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Define two GPIO configs with different drivers etc in two files in /etc/kvmd/override.d/
2. Reload kvmd or reboot and view the GPIO dropdown, and only see one set of views.

**Expected behavior**
Per [this comment](https://github.com/pikvm/pikvm/issues/73#issuecomment-962724552) they should merge?

**PiKVM info:**
  - Raspberry Pi board version: PiKVM v4
  - PiKVM platform: PiKVM v4
  - Video capture type: CSI Bridge
  - KVMD version: `pacman -Q | grep kvmd`
  - uStreamer version: `pacman -Q | grep ustreamer`
  - Linux kernel: `uname -a`

I was able to work around this temporarily by stuffing everything together into one file (still in the override.d so at least that is getting sourced and used if override.yaml is empty/commented.

**Comment by mdevaev** [comment]
Hello. Only nested parameter trees are merged. The list is a regular value, like a string or a number, so it is completely replaced. At the moment there is no way to do it otherwise, we are still trying to find it.
