### ISSUE TITLE
Ability to invert horizontal scroll individually from vertical scroll

### ISSUE THREAD

**Issue by MDproductions-dev** [pikvm/pikvm#1094]
**Is your feature request related to a problem? Please describe.**
I use my macbook to remote into my desktop pc, but the scrolling is all inverted with apple's natural scrolling. The problem comes when i am editing a code file, when i scroll down it also often scrolls right which is extremely frustrating. So for that reason i would like to be able to invert horizontal scrolling individually from vertical scrolling

**Describe the solution you'd like**
Be able to invert horizontal scrolling individually from vertical scrolling.

**Comment by mdevaev** [comment]
Released in KVMD 3.251.
