### ISSUE TITLE
Download floppy drive icon missing/broken on macOS

### ISSUE THREAD

**Issue by reedy** [pikvm/pikvm#1095]
**Describe the bug**
Use of apparently not widely supported `🖪`/`U+1F5AA`/`BLACK HARD SHELL FLOPPY DISK Emoji`

**To Reproduce**
Steps to reproduce the behavior, like:
1. Click on Drive
2. Look at the `Download image` button

**Expected behavior**
Floppy Disk Emoji to actually appear

**Screenshots**
Chrome:
![Screenshot 2023-08-24 at 23 17 00](https://github.com/pikvm/pikvm/assets/67615/a83e1f63-ca97-4239-806c-c0e0cf442e8a)
FF:
![Screenshot 2023-08-24 at 23 17 10](https://github.com/pikvm/pikvm/assets/67615/c8d462b1-65ee-433f-8bbd-5043602f0053)

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Browser Chrome/FF
 - Version 116.0.5845.96/116.0.3

**Comment by reedy** [comment]
Same on iOS.

https://emojipedia.org/black-hard-shell-floppy-disk#technical apple maybe hasn't implemented/drawn it?

https://emojipedia.org/floppy-disk#technical might be a replacement...

**Comment by reedy** [comment]
![Screenshot 2023-08-25 at 00 26 02](https://github.com/pikvm/pikvm/assets/67615/b3ea77ac-f2d5-4e62-b6ac-925f5d87d67c)

**Comment by mdevaev** [comment]
I've replaced it to "arrow down"
