### ISSUE TITLE
How to replace or update mouse driver?

### ISSUE THREAD

**Issue by lxf920125** [pikvm/pikvm#1096]
Dear,
I have a question, the Rasberry connected to the test device, the test device is one PC(OS is windows), while we use mouse to click the UI page under the OS environment, it works well, however, while we use mouse under the BIOS environment, sometimes it didn't work, so I want to know, if there exists one way that we can update the mouse driver for PIKVM?()

**Comment by mdevaev** [comment]
Hello. The mouse driver on PiKVM is fine, Tte source of problems is buggy
USB implementation in some BIOSes. To solve it we have a more traditional
relative mouse mode besides the default absolute one. See here:
https://docs.pikvm.org/mouse

Вт, 29 авг. 2023 г. в 04:37, lxf920125 ***@***.***>:
