### ISSUE TITLE
Renewing LetsEncrypt using DNS challenge?

### ISSUE THREAD

**Issue by off-ice** [pikvm/pikvm#1099]
Sorry if I'm posting this in the wrong place, but I have no idea where else.

I renewed my certificate using DNS challenge (other options do not work for me):
```
sudo certbot certonly --manual --preferred-challenges dns  --agree-tos -d <my-domain>
```
and then run the:
```
kvmd-certbot install_nginx <my-domain>
```
but the new certificate is still not installed.

Can someone please tell me how to make NGINX use the new certificate?
Thanks!

**Comment by mdevaev** [comment]
Please attach full log of these actions.

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
No answer
