### ISSUE TITLE
Distorted KVM text display

### ISSUE THREAD

**Issue by BackSeat** [pikvm/pikvm#1102]
PiKVM + ezCoo connecting to three servers, two of them Linux servers without X installed (so just a text mode console). Both Linux servers running Debian 12 (Bookworm). One of those servers displays fine; the other has a a very distorted display (see attached). That server is an HP ProLiant MicroServer Gen 10.

Any suggestions for getting this text mode display working correctly?
<img width="1008" alt="pikvm-hp" src="https://github.com/pikvm/pikvm/assets/827233/12136449-052c-42da-9b0d-94afc0d0d1a5">

**Comment by mdevaev** [comment]
Hello. Probably the server does not respect EDID. Try to change it: https://docs.pikvm.org/edid

**Comment by BackSeat** [comment]
Thanks for the suggestion. That wasn't the fix, but [this was](https://unix.stackexchange.com/questions/583585/setting-the-most-basic-text-console-video-mode-on-linux).

Appreciate your help.

**Comment by mdevaev** [comment]
:ok_hand:
