### ISSUE TITLE
Term Window On-Close Confirmation Issues

### ISSUE THREAD

**Issue by adamoutler** [pikvm/pikvm#1105]
**Describe the bug**
1. Closing the term provides a Confirm/Cancel that is not respected by the close behavior.  
2. Reopening Term after pressing Cancel, causes another popup.

**To Reproduce**

1. Open Term
3. Click X on Term and then observe popup - expected behavior
4. Click "Cancel" on popup and observe Term close. - **bug**
5. Reopen Term and observe popup again  - **bug**
6. Reclose Term and observe popup again. - expected behavior
7. Click "Leave" on popup and observe Term close. - expected behavior

**Expected behavior**
In the example above
- Step 3 should not close the Term window
- Step 4 should not provide a Confirm/Cancel popup

**Screenshots**
When closing the term both the Leave and Cancel buttons function the same way
![image](https://github.com/pikvm/pikvm/assets/527919/64c3f22d-16b1-447c-83d7-7ba648fab32a)

After "Cancel" the close of Term, the Term button provides another popup
![image](https://github.com/pikvm/pikvm/assets/527919/45e0a87f-f0fb-40e7-bea8-1cdbee562dc2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**PiKVM info:**
  - Raspberry Pi board version: `v4 Plus`
  - PiKVM platform: `v4 Plus`
  - KVMD version: `3.229-1`
  -   - uStreamer version: `0.43-1`
  - Linux kernel: `Linux pikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux`

**Additional context**
The behavior of the popup was originally discussed here https://discord.com/channels/580094191938437144/896216359963332628/1149357441545420810

**Comment by mdevaev** [comment]
The only way to fix it is disable confirmation completely. Maybe I'll add some hack to bring it back in the future. Fixed.
