### ISSUE TITLE
Unable to see / access BIOS / UEFI

### ISSUE THREAD

**Issue by bigjohns97** [pikvm/pikvm#1107]
After switching to an intel a380 video card I am unable to access the BIOS / UEFI

**To Reproduce**
Reboot the PC connected to the PoKVM and don't see a video signal until the Windows login screen

**Expected behavior**
Expect to see a BIOS boot image with option to enter the BIOS and make changes

**Screenshots**
Not needed IMO

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 116
 - VNC client: not used

**PiKVM info:**
  - Raspberry Pi 4 Model B Rev 1.5
  - hdmi
  - Intel A380
  - KVMD version: 3.121-1
  - uStreamer version: 5.16-1
  - Linux kernel: Linux pikvm 5.15.34-4-rpi-ARCH #1 SMP Tue Jul 5 12:10:16 MSK 2022 armv7l GNU/Linux

**Additional context**
This was working previously with a nvidia 1660
EDIT 1: I have tried all of the custom EDID options in this thread https://github.com/pikvm/pikvm/issues/78
EDIT 2: I just ordered a DP to HDMI cable since there are 3x dp and only 1x HDMI so I am guessing the first DP is only active until driver init, will post back later today when I find out.
EDIT 3: After update these are now the versions

kvmd 3.256-1
kvmd-fan 0.26-1
kvmd-oled 0.25-1
kvmd-platform-v3-hdmi-rpi4 3.256-1
kvmd-webterm 0.43-1

ustreamer 5.42-1

Linux pikvm 5.15.92-1-rpi-ARCH #2 SMP Sat Sep 9 00:58:18 MSK 2023 armv7l GNU/Linux

**Comment by bigjohns97** [comment]
Odd, I just ran the update procedure and now the WebUI is telling me that the page requires javascript and I need to disable my ad blocker...

**Comment by bigjohns97** [comment]
Added the PiKVM back to the block internet rule on my router and rebooted the device and now I can't access the webUI at all, is internet connectivity required for the latest version?

**Comment by bigjohns97** [comment]
Intel A380 does require resizable bar enabled as well as using the DP connection for the first attempt to enable resizable bar.

https://www.reddit.com/r/IntelArc/comments/z2t0rs/a380_giving_black_screen_until_loaded_in_windows/

https://www.reddit.com/r/IntelArc/comments/16j5ea8/no_display_output_without_resizeable_bar_enabled/

Either enable this before installing your card or get a DP to HDMI cable like I had to do.

**Comment by mdevaev** [comment]
Good to know, thank you.
