### ISSUE TITLE
Add api to send text

### ISSUE THREAD

**Issue by onlineapps-cloud** [pikvm/pikvm#1113]
hi, i tried to search in API, but i don't found option to send (paste) text to remote machine using API,
It's possible to add this feature as API?
![image](https://github.com/pikvm/pikvm/assets/69077240/4fa77b18-e93b-4790-a887-0d242edcdba8)

**Comment by mdevaev** [comment]
Hello. This API is not documented, but it's available here: https://github.com/pikvm/kvmd/blob/master/kvmd/apps/kvmd/api/hid.py#L129
