### ISSUE TITLE
644 permissions on wpa_supplicant-wlan0.conf file

### ISSUE THREAD

**Issue by sixcorners** [pikvm/pikvm#1115]
https://github.com/pikvm/pikvm/blob/4a2bfc7c63998c7e6979f94ff206ef618fd105ea/docs/wifi.md?plain=1#L57

Could we add a note here to suggest people `chmod go-rw wpa_supplicant-wlan0.conf` file or something? Currently this file ends up readable by everyone

**Comment by mdevaev** [comment]
Done
