### ISSUE TITLE
Add option to send user predefined key combination for change HDMI channel

### ISSUE THREAD

**Issue by onlineapps-cloud** [pikvm/pikvm#1121]
Hi, many kvm switches have option to switch hdmi source truth special hotkeys, different kvm have different hotkeys.
few examples:
https://www.aliexpress.com/item/1005003667051661.html
![image](https://github.com/pikvm/pikvm/assets/69077240/ce6d5594-287b-4012-accd-1c0fa803a3bc)
https://www.aliexpress.com/item/1005005196576991.html
![image](https://github.com/pikvm/pikvm/assets/69077240/f68fcf78-c3a9-482a-9f9d-bda8b3f3183e)
https://www.aliexpress.com/item/1005005795738045.html
![image](https://github.com/pikvm/pikvm/assets/69077240/6c5aed3b-857f-4718-8336-861f93e8bcb4)
it will be great to add some like this:
![image](https://github.com/pikvm/pikvm/assets/69077240/1483a425-561b-40da-8e12-a0edbc6d6bdc)
to create own menu with channel switching.

**Comment by mdevaev** [comment]
Hello. We already have a task about this, so I'm closing this as a duplicate: #207
