### ISSUE TITLE
The service could not be started after I enabled ATX

### ISSUE THREAD

**Issue by meisekiyou** [pikvm/pikvm#1127]
**Expected behavior**
The service could not be started after I enabled ATX.

**Screenshots**
![20231001181205](https://github.com/xe5700/kvmd-armbian/assets/61874558/64a26096-dcab-4af9-88e4-0efc5a4c0954)
log and config file.

**PiKVM info:**
- Raspberry Pi board version: PiKVM_NanoPi-Neo
- Video capture type [MS2109 HDMI to USB]
- KVMD version: 3.227
- uStreamer version: 5.39 (ustreamer)
- Linux kernel: 6.1.30-sunxi

**Comment by mdevaev** [comment]
Hello. We don't  support non-raspberry devices.
