### ISSUE TITLE
Mouse issue with dual PiKVMs

### ISSUE THREAD

**Issue by DigitalYemeni** [pikvm/pikvm#1131]
i saw quite a number of discussions related to dual monitor support and would like to add in that whereby i used 2 PiKVMs and they work as expected except for the mouse which I couldn’t get it to move from the 1st PiKVM to the second!

Any workaround to this issue?

**Comment by mdevaev** [comment]
The only way is using the relative mouse: https://docs.pikvm.org/mouse
