### ISSUE TITLE
Green Zone on screen 

### ISSUE THREAD

**Issue by sennalb** [pikvm/pikvm#1134]
Hi, 
when I use PiKVMv4 on server Dell T440 i see a green zone on bottom e some underline green glitches on various  row, but when I connect the same PiKVMv4 on HP Microserver gen10 all is OK
Why this happen ?
Thanks
Alberto

I append a screenshot for Dell T440

![Istantanea_2023-10-13_14-49-36](https://github.com/pikvm/pikvm/assets/8162135/c039b091-4afc-4128-bcba-9c169206f0f4)

**Comment by arch1mede** [comment]
Hi, this is likely due to needing a different EDID, please see [here](https://docs.pikvm.org/edid/)

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
Probably solved.
