### ISSUE TITLE
pacman cannot get community.files

### ISSUE THREAD

**Issue by pompfe** [pikvm/pikvm#1138]
**Describe the bug**
Just tried to update via pacman and was unable to get community.files (others were ok).  Looked at the mirror (de3 in Germany), the file does not exist.  Looked at other mirrors.  This file is missing there, too.  Directory in mirrors is pretty empty...

**To Reproduce**
Just run pacman to update installation...

**Expected behavior**
No error.

**PiKVM info:**
  - KVMD: 3.214
  - Streamer: 5.38 (ustreamer)
  - HAS_PDEATHSIG: Yes
  - WITH_GPIO: Yes
  - WITH_PTHREAD_NP: Yes
  - WITH_SETPROCTITLE: Yes
  - WITH_SYSTEMD: Yes
  - Machine: armv7l
  - Release: 5.15.68-3-rpi-ARCH
  - Version: #1 SMP Mon Oct 31 20:56:54 MSK 2022
  - Raspberry Pi board version: RPi 4
  - Linux nxpikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Which directory is empty? Please attach the log.

**Comment by pompfe** [comment]
The directory in the repository does not have a "community.files":
https://de3.mirror.archlinuxarm.org/armv7h/community/
Missing in other mirrors, too.
Maybe the mirrors are currently broken...
But I have no clue about this flavor, I come from debian.

**Comment by mdevaev** [comment]
Ah, I understand. Just remove community repo from /etc/pacman.conf.

**Comment by pompfe** [comment]
Thanks a lot!

**Comment by mdevaev** [comment]
:ok_hand:
