### ISSUE TITLE
raspberrypi-utils and raspberrypi-firmware-pikvm are in conflict

### ISSUE THREAD

**Issue by johnseed** [pikvm/pikvm#1141]
**Describe the bug**
pacman -Syu get error

**To Reproduce**
Steps to reproduce the behavior, like:
```bash
[root@pikvm ~]# pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
 pikvm is up to date
:: Starting full system upgrade...
warning: python-ajsonrpc: local (1.2.0-4) is newer than extra (1.2.0-3)
:: Replace raspberrypi-bootloader-x-pikvm with pikvm/raspberrypi-bootloader-pikvm? [Y/n] Y
:: Replace rpi-eeprom with alarm/rpi4-eeprom? [Y/n] Y
resolving dependencies...
looking for conflicting packages...
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: raspberrypi-utils and raspberrypi-firmware-pikvm are in conflict
[root@pikvm ~]#
```
**Expected behavior**
Update the OS.

**Screenshots**
<img width="1095" alt="image" src="https://github.com/pikvm/pikvm/assets/48501700/b0fc9822-4bdd-43b6-8f0a-9f312e4346f3">

**Desktop (please complete the following information):**
 - OS: Windows cmd ssh

**PiKVM info:**
  - Raspberry Pi board version RPi 4
  - PiKVM platform V3 HAT
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `kvmd 3.238-1
kvmd-fan 0.26-1
kvmd-oled 0.24-1
kvmd-platform-v3-hdmi-rpi4 3.238-1
kvmd-webterm 0.43-1`
  - uStreamer version: `ustreamer 5.41-1`
  - Linux kernel: `Linux pikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux`

**Additional context**

**Comment by mdevaev** [comment]
Hello. Please see this post: https://www.reddit.com/r/pikvm/comments/17dm3is/the_big_pikvm_os_update/
