### ISSUE TITLE
Larger then one line OCR causes error in firefox

### ISSUE THREAD

**Issue by damige** [pikvm/pikvm#1148]
When in firefox when selecting multiple lines to OCR, the error: 
"Can't copy text to the clipboard: NotAllowedError: Clipboard write was blocked due to lack of user activation."  appears

Steps to reproduce the behavior, are
1. Click Text on menu
2. Select area for eng
3. Select an area that's more then one line (selecting one line works, chromium works regardless of line count)

I would have expected no error, and text is copied
issue was also raised here: https://www.reddit.com/r/pikvm/comments/sxkijf/kvmd_355_copying_text_from_the_pc/

This is on:
 - OS: Linux (Arch)
 - Firefox 119

PiKVM v4 running latest updates + reboot

**Comment by mdevaev** [comment]
Note for me: https://web.dev/articles/async-clipboard?hl=en

**Comment by mdevaev** [comment]
I made a workaround, but I want to point out that [Firefox lives in its own world](https://bugzilla.mozilla.org/show_bug.cgi?id=1560373).

**Comment by damige** [comment]
Confirmed fixed, thanks!
