### ISSUE TITLE
Audio not working when HDMI-USB connected

### ISSUE THREAD

**Issue by sreedharch** [pikvm/pikvm#1150]
Hi,
I'm streaming using HDMI-USB connection. I notice that the stream is working fine but unable to get the audio. Tried couple of ways to configure but didn't work. Any help on this part.

Thanks.

**Comment by mdevaev** [comment]
Do you mean you're using HDMI USB capture?

**Comment by sreedharch** [comment]
yes

**Comment by mdevaev** [comment]
Audio only works on our own PiKVM V3 and V4 devices.
