### ISSUE TITLE
Please consider adding a feature comparison table to the website

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1151]
**Is your feature request related to a problem? Please describe.**
It is quite confusing to understand what's the difference between PiKVMv3, PiKVMv4, PiKVMV4 Plus, PiKVMv4 Mini.

**Describe the solution you'd like**
Please consider adding a product comparison matrix with products along the horizontal axis, features along the vertical axis, and checks where features available for products.

**Describe alternatives you've considered**
The textual description present on the website is not easy to read.

**Additional context**
It isn't clear at all what the differences are. Is PiKVMv4 Plus the most feature full version?

**Comment by mdevaev** [comment]
I'm working on it :)

> Is PiKVMv4 Plus the most feature full version?

Yes.

**Comment by arch1mede** [comment]
> USB host support (external USB device ports)

KVM Switches for example

> Additional USB storage support (internal USB port)

USB flash drive can be inserted, along with a ssd/nvme 

> RJ-45 console port (this appears to mean the second Ethernet port, but it isn't clear why is it needed)

This is a console port much like what Cisco uses, you can either use this port or the usbc port for console access

**Comment by mdevaev** [comment]
It's done.

**Comment by anssih** [comment]
It is not discoverable from the website (www.pikvm.org), though.

I spent quite a long time going through the various pages there trying to find a feature comparison, before resorting to google and finding this bug which pointed me to README of this repo :)

**Comment by mdevaev** [comment]
Our website is a fossil, we will update it soon.

**Comment by mikulik86** [comment]
Still nothing on the website. Google search doesn't bring up the readme table.
