### ISSUE TITLE
setting 2 GPIO's in 1 button

### ISSUE THREAD

**Issue by phiser678** [pikvm/pikvm#118]
Hi
Great work guys! 
I just have a question on setting 2 GPIO's with 1 button. Is it possible?
e.g. GPIO1 goes on and at the same time GPIO2 delays 1 second, gives a pulse 1 sec and both goes down again.

Thanks

**Comment by mdevaev** [comment]
Hi. This function is not provided by the interface, as it is too custom behavior. You can make a JavaScript patch for the web interface that implements your algorithm. This is the easiest way.

**Comment by phiser678** [comment]
And a more simple one: 
GPIO1 & GPIO2 -> button1
GPIO1 & GPIO3 -> button2

**Comment by mdevaev** [comment]
Well, the same thing. The configuration does not provide the ability to manage multiple ports with a single button.
