### ISSUE TITLE
disabling https redirect cause 404 not found error.

### ISSUE THREAD

**Issue by dowonim323** [pikvm/pikvm#1182]
![image](https://github.com/pikvm/pikvm/assets/78487948/c77705b1-076d-4016-a0a8-7a2f1c9f569a)

Like above, I commented "include /etc/kvmd/nginx/redirect-to-https.conf;" this part, but i get 404 not found error.

I have read pikvm handbook about same problem, but i could not get the point.

Disable HTTPS at all in /etc/kvmd/nginx/nginx.conf. To do this, comment some lines [like in this file](https://github.com/pikvm/kvmd/blob/master/configs/nginx/nginx.conf#L39) and restart web server: systemctl restart kvmd-nginx.

This is what handbook says, but there was no clue about lines to comment on link "this file"

I think the conf file is updated after the handbook is written.

**Comment by mdevaev** [comment]
Hello. You need to keep only one server section with following content:
```nginx
    server {
        include /etc/kvmd/nginx/listen-http.conf;
        include /etc/kvmd/nginx/certbot.ctx-server.conf;
        include /etc/kvmd/nginx/kvmd.ctx-server.conf;
        include /usr/share/kvmd/extras/*/nginx.ctx-server.conf;
    }
```

**Comment by dowonim323** [comment]
> Hello. You need to keep only one server section with following content:
> 
> ```nginx
>     server {
>         include /etc/kvmd/nginx/listen-http.conf;
>         include /etc/kvmd/nginx/certbot.ctx-server.conf;
>         include /etc/kvmd/nginx/kvmd.ctx-server.conf;
>         include /usr/share/kvmd/extras/*/nginx.ctx-server.conf;
>     }
> ```

I fixed it. Thank you!

**Comment by mdevaev** [comment]
:ok_hand:
