### ISSUE TITLE
GPIO WOL

### ISSUE THREAD

**Issue by xtreegpt** [pikvm/pikvm#1187]
**Describe the bug**
When using WOL with GPIO it fails. Doing a packet trace, GPIO is sending a discard packet instead of a wol packet

**To Reproduce**
Steps to reproduce the behavior, like:
1. Setup WOL in GPIO
2. On a system you want to wake up, click on the associated GPIO menu item
3. System does not wake up

**Expected behavior**
When clicking on GPIO a system wakes up

**Screenshots**
![image](https://github.com/pikvm/pikvm/assets/16510644/69ffa0c3-4884-48ff-a2b1-f7d5dc1793d7)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser NA
 - Version NA
 - VNC client NA

**PiKVM info:**
  - [root@monpilan ~]# pistat
# Raspberry Pi 4 Model B Rev 1.2
  - PiKVM platform CSi V3
  - Video capture type CSI Bridge
  - KVMD version: [root@monpilan ~]# pacman -Q |grep kvmd
kvmd 3.257-2
kvmd-cloud 1.9-1
kvmd-fan 0.26-1
kvmd-oled 0.25-1
kvmd-platform-v3-hdmi-rpi4 3.257-2
kvmd-webterm 0.43-1
  - uStreamer version: [root@monpilan ~]# pacman -Q | grep ustreamer
ustreamer 5.42-1
  - Linux kernel:[root@monpilan ~]# uname -a
Linux monpilan 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux

**Additional context**
The image shows the comparison of the GPIO WOL on the left with the Command line WOL on the right. I have the txt files if you want them. 
![pikvm_wol_compare](https://github.com/pikvm/pikvm/assets/16510644/36d0d172-d9b3-4fa8-90c7-c55127c47cc3)

**Comment by mdevaev** [comment]
The observer effect :)
