### ISSUE TITLE
Use global Arch mirror instead of `de3.mirror.archlinuxarm.org`

### ISSUE THREAD

**Issue by thesuperzapper** [pikvm/pikvm#1192]
## Describe the bug

Currently, some users are unable to update because the default Arch mirror is set to `de3.mirror.archlinuxarm.org`, and this will often give <1kbps of speed to locations like west-coast USA.

Users can fix this by changing their `/etc/pacman.d/mirrorlist` to use `mirror.archlinuxarm.org`, but we should probably do this by default. For reference, `mirror.archlinuxarm.org` is the most equitable solution, and is the [recommended default](https://archlinuxarm.org/about/mirrors) by Arch themselves, as it uses IP-based routing to send you to the closest mirror for your location.

## What needs to change

Here are the locations which `de3.mirror.archlinuxarm.org` is being set:
- https://github.com/pikvm/os/blob/287a092f69655299cc20e477dec936df8ff168ee/Makefile#L13
- https://github.com/pikvm/pi-builder/blob/ffd2c20d6cc052d3c60be7ba923980ab1400e653/Makefile#L46

**Comment by mdevaev** [comment]
Hello. It's already done in new os images.

**Comment by anthonypants** [comment]
I'm using this version of PiKVM:
```
# pacman -Q | grep kvmd
kvmd 4.190-1
kvmd-fan 0.32-1
kvmd-platform-v4plus-hdmi-rpi4 4.190-1
kvmd-webterm 0.50-1
```

and I live in the western US, and `/etc/pacman.d/mirrorlist` is hardcoded to use `de3.mirror.archlinuxarm.org `:
```
# cat /etc/pacman.d/mirrorlist
Server = http://de3.mirror.archlinuxarm.org/$arch/$repo
```

and this server is currently timing out:
```
# ping de3.mirror.archlinuxarm.org
PING de3.mirror.archlinuxarm.org (137.226.34.46) 56(84) bytes of data.
64 bytes from ftp.halifax.rwth-aachen.de (137.226.34.46): icmp_seq=1 ttl=50 time=171 ms
64 bytes from ftp.halifax.rwth-aachen.de (137.226.34.46): icmp_seq=2 ttl=50 time=174 ms
64 bytes from ftp.halifax.rwth-aachen.de (137.226.34.46): icmp_seq=3 ttl=50 time=175 ms
64 bytes from ftp.halifax.rwth-aachen.de (137.226.34.46): icmp_seq=4 ttl=50 time=173 ms
^C
--- de3.mirror.archlinuxarm.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3137ms
rtt min/avg/max/mdev = 170.618/173.095/175.427/1.758 ms
[root@pikvm ~]# pikvm-update 
+ trap on_error ERR
+ _yes='--noconfirm --ask=4 --overwrite \*'
+ _remove_yes='--noconfirm --ask=4'
+ rw
+ mount -o remount,rw /
+ mount -o remount,rw /boot
+ set +x
=== PiKVM is in Read-Write mode ===
+ pacman -Syy
:: Synchronizing package databases...
 core.db failed to download
error: failed retrieving file 'core.db' from de3.mirror.archlinuxarm.org : Connection timed out after 10003 milliseconds
error: failed to synchronize all databases (download library error)
++ on_error
++ set +x
==============================================================
      An unexpected error occurred during the update.
==============================================================

==============================================================
Please note that the filesystem now remain in Read-Write mode.
       A reboot is necessary to make it Read-Only again.
The reboot can be performed later using the 'reboot' command.
==============================================================
++ set -x
```

**Comment by mdevaev** [comment]
Hello. Just edit the mirror URL end remove `de3.` prefix to use a global reflector.
