### ISSUE TITLE
Audio not working using HDMI-CSI bridge

### ISSUE THREAD

**Issue by sreedharch** [pikvm/pikvm#1193]
Hi,
I'm streaming using HDMI-CSI bridge connection on rpi4. I notice that the stream is working fine and able to detect the audio device. 
But I see below error from ustreamer:
INFO --- => == ustreamer/audio     -- Detected host audio
INFO --- => == ustreamer/audio     -- Pipeline configured on 48000Hz; capturing ...
INFO --- => [WARN] [5558898831029643] Failed to add some remote candidates (added 0, expected 1)
INFO --- => [5558898831029643] The DTLS handshake has been completed
INFO --- => [WARN] [5558898831029643] Error resolving mDNS address (f8b55cde-4d7a-413e-a73a-229467851bdb.local): Error resolving “f8b55cde-4d7a-413e-a73a-229467851bdb.local”: Name or service not known
INFO --- => [WARN] [5558898831029643] Error resolving mDNS address (f8b55cde-4d7a-413e-a73a-229467851bdb.local): Error resolving “f8b55cde-4d7a-413e-a73a-229467851bdb.local”: Name or service not known
INFO --- => [ERR] [src/audio.c:_pcm_thread:190] == ustreamer/audio     -- Fatal: Can't capture PCM frames: Input/output error
INFO --- => == ustreamer/audio     -- Pipeline closed
INFO --- => == ustreamer/audio     -- Detected host audio
INFO --- => == ustreamer/audio     -- Pipeline configured on 48000Hz; capturing ...
INFO --- => [ERR] [src/audio.c:_pcm_thread:190] == ustreamer/audio     -- Fatal: Can't capture PCM frames: Input/output error
INFO --- => == ustreamer/audio     -- Pipeline closed
INFO --- => == ustreamer/audio     -- Detected host audio
INFO --- => == ustreamer/audio     -- Pipeline configured on 48000Hz; capturing ...
INFO --- => [ERR] [src/audio.c:_pcm_thread:190] == ustreamer/audio     -- Fatal: Can't capture PCM frames: Input/output error
 
Not sure what's missing. Any help on this part please.

**Comment by mdevaev** [comment]
This is indicated in the audio documentation. The sound works only on our own hardware PiKVM V3 and V4.

**Comment by sreedharch** [comment]
Ooh ok, thanks for the info @mdevaev

**Comment by mdevaev** [comment]
Ur welcome.
