### ISSUE TITLE
Support for HDMI capture USB dongle (534d:2109 MacroSilicon)

### ISSUE THREAD

**Issue by alexisfrjp** [pikvm/pikvm#1195]
Is the cheap HDMI capture USB dongle supported?

* lsusb
```
Bus 001 Device 004: ID 534d:2109 MacroSilicon USB3. 0 capture
```

I also have the X630 HDMI2CSI plugged in and this one works.

When I have 2 capture devices, how to select which one to use?

**Comment by arch1mede** [comment]
**Is the cheap HDMI capture USB dongle supported?**
Yes, per [this page](https://docs.pikvm.org/v2/#required-parts) under the Video Capture Device section.

**When I have 2 capture devices, how to select which one to use?**
This configuration is not officially supported, you will need to use an image for 1 or the other.

Please consider joining [Discord]( https://discord.gg/bpmXfz5) as we have an active community that could also answer these questions live.

**Comment by alexisfrjp** [comment]
Thanks!
