### ISSUE TITLE
I tried to control my Android phone, but nothing happened.

### ISSUE THREAD

**Issue by happymy** [pikvm/pikvm#1196]
I control the PC and everything is fine.
I try use USB OTG Cable to control the Android phone and there is no feedback.

**Comment by mdevaev** [comment]
Try the relative mouse mode: https://docs.pikvm.org/mouse

**Comment by happymy** [comment]
I tried. Still not working. Can't control my android phone. Keyboard and mouse don't work.
I observed that when I connected the USB cable, the phone could not turn on or off the USB OTG mode.

Can I set pikvm to turn off USB HOST mode? Let PIKVM emulate HID device?

**Comment by mdevaev** [comment]
PiKVM is emulating HID device by default. Presumably there are problems in Android.

**Comment by happymy** [comment]
I cut the red power wire inside the USB cable.
Nothing has changed.

I guess the both USB work in HOST mode. Need disable pikvm USB host mode？

**Comment by mdevaev** [comment]
PiKVM never works in the host mode, only in the device mode. Probably your phone is a device too.

**Comment by mdevaev** [comment]
Which connector do you have on the phone? Micro USB or Type C?

**Comment by happymy** [comment]
Type-C.
That's weird. The mobile phone can turn on and off USB OTG.

**Comment by happymy** [comment]
That is work！ I try add a usb HUB to usb otg cable.

**Comment by mdevaev** [comment]
So, the problem solved?

**Comment by happymy** [comment]
yes. But why?

**Comment by happymy** [comment]
Why add a usb HUB to usb otg cable first?

**Comment by mdevaev** [comment]
I suppose this helped the phone determine the type of connection (host/device).
