### ISSUE TITLE
Keyboard not working in Web Terminal since update

### ISSUE THREAD

**Issue by Leseratte10** [pikvm/pikvm#1198]
**Describe the bug**

Flashed PiKVM image `v3-hdmi-rpi4-latest.img.xz` downloaded today, file timestamp from December 6th. Web terminal works. Updated OS, web terminal no longer works. It opens and I can see the text, but all keyboard input is ignored. 

**To Reproduce**
Steps to reproduce the behavior, like:
1. Flash image from December 6th
2. Open Web Terminal, check that it works
3. run `rw`, then `pacman -Syu`, then `reboot`
4. Web Terminal broken

**Expected behavior**
Expect web terminal to work.

**Desktop:**
 - OS: Ubuntu 20.04
 - Browser: Tested Chrome 116.0.5845.140 and Firefox 117.0

**PiKVM info:**
  - Raspberry Pi board version: CM4
  - PiKVM platform: v3-hdmi-rpi4
  - Video capture type: CSI bridge
  - KVMD version before update (working):

```
kvmd 3.284-1
kvmd-fan 0.26-1
kvmd-oled 0.26-1
kvmd-platform-v3-hdmi-rpi4 3.284-1
kvmd-webterm 0.44-1
```  

  - KVMD version after update (broken):
 
```
kvmd 3.288-1
kvmd-fan 0.26-1
kvmd-oled 0.26-1
kvmd-platform-v3-hdmi-rpi4 3.288-1
kvmd-webterm 0.47-1
```
  - uStreamer version: ustreamer 5.46-1
  - Linux kernel: `Linux pikvm 6.1.61-1-rpi-ARCH #1 SMP Fri Nov  3 20:48:52 MSK 2023 armv7l GNU/Linux` (didn't change during update)
  - The update installed the following packages: 
```
Installs:
              archlinux-keyring-20231222-1  ca-certificates-mozilla-3.96.1-1  curl-8.5.0-1  dhcpcd-10.0.6-1  geoip-database-20231213-1  glib2-2.78.3-1  harfbuzz-8.3.0-2
              hwdata-0.377-1  icu-74.2-1  iputils-20231222-1  iw-6.7-1  janus-gateway-pikvm-0.14.2-1  kbd-2.6.4-1  krb5-1.21.2-2  kvmd-3.288-1  kvmd-platform-v3-hdmi-rpi4-3.288-1
              kvmd-webterm-0.47-1  libbpf-1.3.0-1  libnl-3.9.0-1  libseccomp-2.5.5-1  libsecret-0.21.2-1  libssh-0.10.6-1  libxml2-2.12.3-1  licenses-20231215-1  lua-5.4.6-3
              mkinitcpio-37.1-2  nspr-4.35-2  nss-3.96.1-1  openresolv-3.13.2-2  openssh-9.6p1-1  openssl-3.2.0-1  pkgconf-2.1.0-2  python-aiosignal-1.3.1-5
              python-dateutil-2.8.2-6  python-frozenlist-1.4.0-2  python-idna-3.5-1  python-ldap-3.4.4-1  python-platformdirs-4.1.0-1  python-pygments-2.17.2-1
              python-pyotp-2.9.0-1  python-setuptools-1:69.0.3-1  python-typing_extensions-4.9.0-1  python-yarl-1.9.4-1  raspberrypi-utils-20231221-1  rtl-sdr-1:2.0.1-3
              sudo-1.9.15.p4-1  systemd-255.2-1  systemd-libs-255.2-1  systemd-sysvcompat-255.2-1  tesseract-5.3.3-2  ttyd-1.7.4-1  tzdata-2023d-1  ustreamer-5.46-1
              util-linux-2.39.3-1  util-linux-libs-2.39.3-1  v4l-utils-1.26.1-1  vim-9.0.2167-1  vim-runtime-9.0.2167-1
```

If you need any additional information let me know.

**Comment by Cebrain** [comment]
Can confirm the problem.

I flashed the "v2-hdmiusb-rpi4-latest.img" from today. 
After the update AND reboot, i cant type in the terminal anymore.

SSH and WebGUI works fine.

**Comment by Leseratte10** [comment]
Looks like the update to ttyd 1.7.4 broke it - the [upstream changelog](https://github.com/tsl0922/ttyd/releases/tag/1.7.4) says:

    Breaking Changes
    The web terminal is readonly by default now, to make it writable, use -W option.

So I guess some PiKVM code needs to be updated to include that switch.

**Comment by mdevaev** [comment]
I'll build the new package with fix, thank you.

**Comment by mdevaev** [comment]
Fixed in new kvmd-webterm
