### ISSUE TITLE
When VNC keymap /usr/share/kvmd/keymaps/en-us is used - the ':' key is translated to '^'

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1208]
**Describe the bug**
Shift-; should enter the ':' character, but instead it enters the '^' character.

/usr/share/kvmd/keymaps/en-gb doesn't have such problem.

**Comment by mdevaev** [comment]
Which layout do you have on client and dest PCs?

**Comment by yurivict** [comment]
It's US English on Windows 11 Enterprise.

**Comment by yurivict** [comment]
I changed to the en-gb keymap. But with this keymap there is also a problem: the ~ key (Shift-`) is entered as ^ from the VNC client.

Web interface is ok.

**Comment by mdevaev** [comment]
You use Remmina, right? Using keymaps is actually a deprecated feature.

The fact is that VNC is fundamentally incompatible with hardware keyboard emulation: it transmits keys in the form of X11 codes. The reverse conversion from X11 to physical codes is inaccurate.

In order for VNC to be used with hardware keys, QEMU has developed a [protocol extension](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#qemu-extended-key-event-message) that allows physical keys to be transferred. Almost all modern clients support this, except Remmina. If you have the time and skill, you can make them a patch, they are willing to accept the changes. A couple of years ago I wanted to do this, the implementation is not too complicated, but I did not have time to do it.

**Comment by yurivict** [comment]
Yes, I use Remmina.

**Comment by mdevaev** [comment]
What about patching?

Btw try `ru` keymap.

**Comment by yurivict** [comment]
Yes, I will prepare the PR for Remmina.

**Comment by mdevaev** [comment]
Got it. Thank you.

**Comment by mdevaev** [comment]
Okay, I'm closing this as you're solving this on the client side. Let me know about the progress, please.
