### ISSUE TITLE
OCR not working when using http

### ISSUE THREAD

**Issue by ich777** [pikvm/pikvm#1228]
**Describe the bug**
I've configured PiKVM for http only and OCR is missing:

**To Reproduce**
I disabled https like described [here](https://docs.pikvm.org/faq/#usb-problems-keyboard-mouse-mass-storage-etc) at the section `I can't use the PiKVM web interface on iOS: the Web UI network indicator flashes yellow` <- Yes I know the security implications but I'm only using it on my local network or through a VPN.

**Expected behavior**
OCR working with http only

**Screenshots**
![grafik](https://github.com/pikvm/pikvm/assets/28066518/d05e380e-4aa9-40ce-83a3-bbe50645951d)

**Desktop:**
 - OS: Debian Bullseye/Windows 11
 - Browser Firefox/Edge/Chrome
 - Version: latest version for all three listed above as time of writing
 - VNC client (if used) <- not used

**PiKVM info:**
  - Raspberry Pi board version RPi 4
  - PiKVM platform v2-hdmi
  - Video capture type USB adapter
  - KVMD version: 3.288
  - uStreamer version: 4.9

**Additional context**
Is this a technical limitation or just a bug? Fell free to close that issue if it's a bug.

**Comment by mdevaev** [comment]
Hello. It should be fixed now. Please update and test:
```
curl https://files.pikvm.org/update-os.sh | bash
```

**Comment by ich777** [comment]
Thank you! Working perfectly fine!

**Comment by mdevaev** [comment]
:ok:

**Comment by ich777** [comment]
Sorry, I have to reopen the issue... I have not actually tried OCR just checked if I can see it... 

I now see the OCR feature through http but it actually doesn't work, you'll see in this gif that the gear never stops turning:
![Peek 2024-01-27 10-40](https://github.com/pikvm/pikvm/assets/28066518/14dc8028-edbb-401f-b6a9-34f2b4766962)

When I connect through https it is working just fine:
![Peek 2024-01-27 10-42](https://github.com/pikvm/pikvm/assets/28066518/04a051f1-b33b-4d9a-987c-97437feb910d)

**Comment by mdevaev** [comment]
Please open developer tools and take a screenshot of JS console and requests list

**Comment by ich777** [comment]
I think this is what you where after:
![grafik](https://github.com/pikvm/pikvm/assets/28066518/a766f586-9857-4ae1-87fc-f8b830fc0aa6)

**Comment by mdevaev** [comment]
Try again with 3.296

**Comment by ich777** [comment]
Thank you, now it's working!
