### ISSUE TITLE
[question] Is there a way to disable https and to switch to http?

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1233]
**Describe the bug**
I run PiKVM w/in LAN between hosts that aren't exposed through the router, so https isn't really needed.
Performance might improve if encryption/decryption wouldn't occur.
Is there an easy way to disable https, and to switch to http?

The [first steps](https://docs.pikvm.org/first_steps/) guide doesn't talk about this.

**Comment by mdevaev** [comment]
In my experience, this does not provide any performance benefits.

You can edit `/etc/kvmd/nginx.conf` if you want get rid of https.

**Comment by mdevaev** [comment]
Since 3.301 you can simply disable HTTPS using the override.yaml: https://www.reddit.com/r/pikvm/comments/1ahxvhh/kvmd_3301_generated_nginx_configs/
