### ISSUE TITLE
Add support to dock some virtual keyboard buttons and keyboard shortcuts

### ISSUE THREAD

**Issue by plia7** [pikvm/pikvm#1234]
**Is your feature request related to a problem? Please describe.**
Sometimes when accessing the pikvm web ui desktop version from a touch based mobile device setting where connecting app/mobile virtual keyboard layout is quite limited in terms of pc based keyboard buttons, it will be beneficial to have several common pc keyboard buttons and shortcuts docked on the screen so you could use it in conjunction with the existing mobile virtual keyboard. 

**Describe the solution you'd like**
Provide an ability to dock buttons from virtual keyboard panel as well as the keyboard shortcuts menu. Similar to the options provided by Jump Desktop iOS app where you can have multiple pre-fixed sets you can quickly swipe on for pc based buttons to click on, i.e. one set: F1 F2 F3 F4 F5 F6 F7 F8 F9, second set: ALT SHIFT CTRL WINDOWS KEY, third set: common keyboard shortcuts, etc.

Some possible usage example for illustration:

![image](https://github.com/pikvm/pikvm/assets/134864072/961a1951-f8dd-4cc9-bbb0-5ddf97d8eb3a)

**Describe alternatives you've considered**
I tried to open the virtual keyboard to click on the pc based keyboard button(s) that I need to use, but the experience is a little frustrating as you need to do too many clicks: system -> show keyboard -> then click on the button that you want. The virtual keyboard panel is too big, taking too much screen real estate and if you click with the mouse somewhere on the screen behind the virtual keyboard, the virtual keyboard disappears and you need to start the whole process again.

![image](https://github.com/pikvm/pikvm/assets/134864072/18495396-3588-4068-b3e1-fa5ee1a2f4ba)

**Additional context**
You could enter edit mode where you can drag and drop/float/dock all the buttons and keyboard shortcuts that you want to the possible dock/float areas and save. Then, clicking with the mouse on the screen behind it should not cause the docked/floating areas buttons to disappear.

This probably could be useful also for other use cases even when not accessing from a mobile based device to the pikvm web desktop ui, as I'm sure many will want the print screen button to be docked as it would be useful so it understands you want print screen of the target not the client. Caps Lock button will be useful too as some connecting apps that use the mobile keyboard layout don't really know to send the pc Caps Lock when you press the "up arrow" button that usually indicates you want an upper case letter.

Thanks.

**Comment by mdevaev** [comment]
We have this task already: #207

I'll just keep in mind that we also need docking.
