### ISSUE TITLE
Dynamic usb configuration is not working

### ISSUE THREAD

**Issue by danacr** [pikvm/pikvm#1235]
**Describe the bug**
After changing kvmd on the pikvm v4 mini using the https://docs.pikvm.org/usb_dynamic/ keyboard fails to work.

**To Reproduce**
Steps to reproduce the behavior, like:
1.`kvmd-otgconf --disable-function mass_storage.usb0`
2. `kvmd-otgconf --enable-function hid.usb0`
3. Neither webui nor API can send keypresses anymore

**Expected behavior**
Using dynamic USB configuration works.

**PiKVM info:**
  - Raspberry Pi board version 4 compute module
  - PiKVM platform PiKVM v4 mini
  - Video capture type hdmi

**Additional context**
 When I was running this on the PiKVM V3 Pre-Assembled 3 months ago it was working. Since I no longer have access to the v3 and I saw there was a large OS update, I'm not sure if it's due to the hardware or the OS change.

**Comment by mdevaev** [comment]
Hello. Check `dmesg` and `journalctl -u kvmd`

**Comment by danacr** [comment]
when running `kvmd-otgconf --disable-function mass_storage.usb0` I get:
```
Feb 05 09:15:58 pikvm kvmd[527]: kvmd.plugins.hid.otg.device      ERROR --- Missing HID-mouse device: /dev/kvmd-hid-mouse
Feb 05 09:15:58 pikvm kvmd[526]: kvmd.plugins.hid.otg.device      ERROR --- Missing HID-keyboard device: /dev/kvmd-hid-keyboard
Feb 05 09:15:58 pikvm kvmd[528]: kvmd.plugins.hid.otg.device      ERROR --- Missing HID-mouse device: /dev/kvmd-hid-mouse-alt
```

**Comment by mdevaev** [comment]
This is normal for the switching period. But I think I see a problem. Okay, I'll try to figure out what's going on.

**Comment by mdevaev** [comment]
Fixed in KVMD 3.302. This is some kind of bug in the kernel, I made a workaround.

**Comment by danacr** [comment]
thank you very much!

**Comment by mdevaev** [comment]
:ok_hand:
