### ISSUE TITLE
CH340 serial

### ISSUE THREAD

**Issue by iLLiac4** [pikvm/pikvm#1239]
Will an Serial adapter like this work for Multiport KVM over IP?

https://www.aliexpress.com/item/32964541650.html

**Comment by mdevaev** [comment]
How you want to use it, I don't understand.

**Comment by iLLiac4** [comment]
Hi. To control KVM over Serial. Here it describes only the chip FTDI that is hard to find none cloned one.
CH340 is easy to get.
https://docs.pikvm.org/xh_hk4401/

**Comment by mdevaev** [comment]
Probably yes.
