### ISSUE TITLE
HP Z2 doesn't show Boot Menu

### ISSUE THREAD

**Issue by andybowser** [pikvm/pikvm#1242]
**Describe the bug**
PiKVM connected via HDMI to Mini Displayport cable to HP. 
On boot I push F9 to go to Boot Menu, which works, but then I can't see the boot menu. It shows the black HP screen. Taking HDMI out of PiKVM into a monitor, shows the menu fine.

**To Reproduce**
1. Reboot or turn on PC
2. Press F9
3. No Boot Menu

**Expected behavior**
Showing the boot menu as per this screenshot.
![image](https://github.com/pikvm/pikvm/assets/485249/7600be2c-b8b7-43d8-a908-587a61195717)

**Screenshots**
I just see the following
![image](https://github.com/pikvm/pikvm/assets/485249/ca373185-c409-4505-b9ee-e10adfaeaed8)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Firefox
 - Version 122.0

**PiKVM info:**
  - Raspberry Pi board version RPi 4
  - kvmd 3.173-1
kvmd-fan 0.22-1
kvmd-oled 0.13-1
kvmd-platform-v3-hdmi-rpi4 3.173-1
kvmd-webterm 0.42-1

**Comment by mdevaev** [comment]
Which pikvm device do you use?

**Comment by andybowser** [comment]
Pikvm v3

**Comment by mdevaev** [comment]
Please try some alternative EDIDs: https://docs.pikvm.org/edid

**Comment by andybowser** [comment]
Thank you. The Intel NUC EDID worked.

**Comment by mdevaev** [comment]
@andybowser Could you also check the new official EDID? https://www.reddit.com/r/pikvm/comments/1ars4lx/kvmd_3304_video_quality_and_compatibility/

**Comment by andybowser** [comment]
> @andybowser Could you also check the new official EDID? https://www.reddit.com/r/pikvm/comments/1ars4lx/kvmd_3304_video_quality_and_compatibility/

Yes. The new EDID works. 
I also bought the V4 for a project and that works fine with default config.
Thanks

**Comment by mdevaev** [comment]
Great!
