### ISSUE TITLE
Be able to adjust the mouse jiggler parameters...

### ISSUE THREAD

**Issue by Majestic7979** [pikvm/pikvm#1247]
Maxim I just noticed you managed to implement the jiggler, can I ask if this works even when the browser is closed? And is there a way to personalize it?

I currently have to use a macro... the macro presses a couple of keys even few minutes, as well as moves the mouse. This is necessary because the keys control a webpage which to remain live needs keyboard input as well as mouse movement.

So I assume if the Jiggler function from the system menu is based on the Macro engine this could be possible?

Here's my script (I'll remove later for privacy after you reply), essentially I want to get the convenience of the jiggler but with added parameters (keypress, wider movement variation of the mouse cursor, and I also want to adjust the timeout to be variable. (The jiggler watches for user input and doesn't do anything until there is a 60 second inactivity, I want to vary this timeout, with Macros I cannot do this as far as I'm aware?)

```
[
    {
        "event_type": "mouse_move_random",
        "event": {
            "range": {
                "min": -30000,
                "max": 30000
            }
        }
    },
    {
        "event_type": "delay_random",
        "event": {
            "range": {
                "min": 100,
                "max": 1000
            }
        }
    },
    {
        "event_type": "mouse_move_random",
        "event": {
            "range": {
                "min": -30000,
                "max": 30000
            }
        }
    },
    {
        "event_type": "key",
        "event": {
            "key": "F5",
            "state": true
        }
    },
    {
        "event_type": "delay_random",
        "event": {
            "range": {
                "min": 300,
                "max": 600
            }
        }
    },
    {
        "event_type": "key",
        "event": {
            "key": "F5",
            "state": false
        }
    },
    {
        "event_type": "delay_random",
        "event": {
            "range": {
                "min": 480000,
                "max": 540000
            }
        }
    }
   ]
```

**Comment by mdevaev** [comment]
> can I ask if this works even when the browser is closed? 

Yes, it is.

> And is there a way to personalize it?

Unfortunately no, this is a pretty deterministic function, and I don't think it will be done. Maybe in the future when we will support server-side macros, but jiggler should remain simple and oaky.

**Comment by Majestic7979** [comment]
Thanks for confirming Maxim :) Hopefully we get something like that in the future then.

**Comment by mdevaev** [comment]
:ok_hand:
