### ISSUE TITLE
toggle reset to cmos reset button label in gui

### ISSUE THREAD

**Issue by realies** [pikvm/pikvm#1252]
found this pretty useful when having fun with overclocking, guess it could be useful for other applications
![image](https://github.com/pikvm/pikvm/assets/5107843/b38d1f79-71c3-4221-8c9d-2568b37f1a28)

**Comment by mdevaev** [comment]
You can use [gpio menu functions](https://docs.pikvm.org/gpio/) for this.

**Comment by akhamar** [comment]
Could you provide a bit more context and explanation on how one could use gpio menu for doing a physical clear CMOS jumper on a motherboard ?
That would be greatly appreciated.

Do you need extra hardware ? Can you just plug 2 wires from the clear CMOS to rpi gpio pin ?

**Comment by realies** [comment]
I connect the jumper wires that usually go to the system reset header to the CMOS reset header.

**Comment by akhamar** [comment]
> I connect the jumper wires that usually go to the system reset header to the CMOS reset header.

Usually clear CMOS need 5-10sec of long press, how do you achieve that with reset ?

**Comment by realies** [comment]
> > I connect the jumper wires that usually go to the system reset header to the CMOS reset header.
> 
> Usually clear CMOS need 5-10sec of long press, how do you achieve that with reset ? As reset is just a short toggle.

The mobos I use it on don't require this.
