### ISSUE TITLE
Keyboard+mouse doesn't work in UEFI on HP EliteBook

### ISSUE THREAD

**Issue by Sislik42** [pikvm/pikvm#1261]
Keyboard and mouse doesn't work in UEFI on HP EliteBook 840 14" G10 (Product number: 818Q7EA#UUZ).
When Windows boots, there is no issue, and keyboard and mouse is working properly.

We tried all USB A ports on mentioned NB as described in FAQ.
(We even tried USB on docking station, but we were expecting it will probably not work too.)

<img width="2560" alt="Screenshot 2024-02-23 at 16 04 13" src="https://github.com/pikvm/pikvm/assets/95551653/89a68f40-15af-4604-a9df-35c87b6fe994">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: 17.3.1 (19617.2.4.11.12)
 - VNC client: no

**PiKVM info:**
PiKVM V4 Plus, bought here https://www.pi-shop.ch/pikvm-v4-plus
PiKVM was just bought and updated to the latest version today
 - Raspberry Pi board version: ???
 - PiKVM platform: ???
 - Video capture type: ???
 - KVMD version:
kvmd 3.306-1
kvmd-fan 0.30-1
kvmd-oled 0.26-1
kvmd-platform-v4plus-hdmi-rpi4 3.306-1
kvmd-webterm 0.48-1
 - uStreamer version: ustreamer 5.51-1
 - Linux kernel: Linux pikvm 6.1.61-1-rpi-ARCH #1 SMP Fri Nov  3 20:48:52 MSK 2023 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Hello. For the first action, please try to disable mass storage drive: https://docs.pikvm.org/msd/#disabling-mass-storage

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by jnstockley** [comment]
I am also having issues with my host device responding to input from my keyboard and/or mouse. I tried disabling the USB mass storage device, but that hasn't resolved the issue. Currently, TrueNAS Scale is installed, but also had an issue with the same device running Windows 10. When I unplug and re-plug the USB cable connected to the PiKVM I can see it's recognized. I am using a prebuilt PiKVM V3. I've also tried to re-install the OS which also didn't fix the issue.
<img width="767" alt="Screenshot 2024-03-02 at 2 10 52 PM" src="https://github.com/pikvm/pikvm/assets/34308937/1552b7a0-9f82-4560-b41a-aed4bfa750de">

**Comment by mdevaev** [comment]
@jnstockley For the replugging case we have a special option. Switch it to OFF and back to ON. This is equivalent to reconnecting the cable, but can be done remotely in case of problems like yours.
![image](https://github.com/pikvm/pikvm/assets/416259/77b514ef-be4c-492d-8521-8abc1bcd46e2)

**Comment by jnstockley** [comment]
Thanks that is useful to know, but that doesn't seem to resolve the issue with the host not responding to keyboard and mouse interactions made through PiKVM. I'm assuming my issue is related to the original poster issue, but I could be wrong.

**Comment by mdevaev** [comment]
@jnstockley What you see in dmesg when you're using usb switch in the menu?

**Comment by mdevaev** [comment]
@Sislik42 You're welcome!
