### ISSUE TITLE
Building PiKVM OS not possible due to crosscompiling error

### ISSUE THREAD

**Issue by wsxws** [pikvm/pikvm#1264]
https://docs.pikvm.org/building_os/ explains how to build an os and example uses apt-get like working on debian BUT
after installing all dependencies and creating config.mk and executing make os it leads to:

Makefile:64: *** Cross-arch ARM building like aarch64<->arm is not supported.  Stop.

but an PI 4 even using a 32bit RaspiOS (bullseye or bookworm doesnt matter) is on aarch64, how to solve that ?

**Comment by mdevaev** [comment]
Hello. Probably you have 64 bit OS. Run `arch` and `uname -a` commands on it.

**Comment by wsxws** [comment]
if i'd see such a silly question i would think the same.
i already checked it 2 times, but i just did it a thir time.
![card](https://github.com/pikvm/pikvm/assets/4209111/8b8bba4c-acfc-4c96-994e-8e7176055847)
and when i log in it says:
![ssh](https://github.com/pikvm/pikvm/assets/4209111/46d5c152-73dd-46c9-9f13-f792febcae1a)
any other idea ?

**Comment by mdevaev** [comment]
Well, it clearly states here that your OS is aarch64. Maybe there is something wrong with the links in the Imager. Download the OS directly from the Raspberry website. If the Imager is really pumping 64 bits to a 32-bit request, you should let them know about this bug.

**Comment by wsxws** [comment]
hm
some funny facts
i also tried out tinypilot. and as curious as i am i first tried to install it on 64bit, what did not work out. so i installed the 32bit version and installation of tinypilot ran throught and is working. when i log in on this system uname also shows arch64. (whysoever)

anyway i meanwhile managed to install pikvm v3 with hat on pi 4 using raspi os bookworm 64bit and also installed v2 with usb dongle on pi5 using bookworm 64bit as well. just display-services are missing atm, ill add them lateron

thanks for your great project over here
