### ISSUE TITLE
Support for HDPI Displays

### ISSUE THREAD

**Issue by makuru-dd** [pikvm/pikvm#1266]
**Is your feature request related to a problem? Please describe.**
I Have a new laptop and that has a 2k display and it is almost impossible to read the text in the terminal of the web interface.

**Describe the solution you'd like**
A button or scroll wheel to designate a text size for the terminal to use.

**Describe alternatives you've considered**
I tried to zoom in with the Browser but that did very little but make all the borders bigger.

![image](https://github.com/pikvm/pikvm/assets/58048293/419e96fc-75b3-48ca-9411-6f44e67aa13d)

**Comment by mdevaev** [comment]
Hello. Which browser do you use?

**Comment by mdevaev** [comment]
Sup?

**Comment by makuru-dd** [comment]
Hi I tried it with Librewolf (firefox fork based on web privacy, with a focus against fingerprinting) and ungoogled chromium.

**Comment by makuru-dd** [comment]
Seems like a update fixed it, I updated the PIKVM to the second last version and it seems to have fixed it.

**Comment by mdevaev** [comment]
Okay, then I'm closing it :ok_hand:
