### ISSUE TITLE
Can't access hidden SSID on first boot + doc ambiguity

### ISSUE THREAD

**Issue by Sazerak** [pikvm/pikvm#1267]
**Describe the bug**
This morning I tried getting PiKVM setup on a WiFi network (fresh install) but could not get it to work. While I didn't have the means to connect to the console to troubleshoot more, I'm thinking the issue is likely that the SSID is hidden. According to the docs [HERE](https://docs.pikvm.org/wifi/#setting-up-wi-fi-manually), there needs to be an option added to connect to a hidden SSID. However, there is no mention of if/how this can be done on first boot through the pikvm.txt file. Has anyone tried connecting to a hidden SSID on first boot and had success?

Also, on the note of WiFi settings for first boot, I feel that the docs are a bit ambiguous. The docs [HERE](https://docs.pikvm.org/on_boot_config/#other-available-options) mention that **The parameters must be specified strictly each on a separate line.** However, some parameters in the docs have been grouped together in a single line (for example **ETH_ADDR=192.168.0.100/24, ETH_DNS=8.8.8.8, ETH_GW=192.168.0.1**). It's unclear whether these should be kept together in a single line and considered a single parameter, or whether they should be divided into separate lines. My understanding is that they should be separated, but I believe it could be good to make this more clear in the docs.

**Comment by tvories** [comment]
I'm trying to figure out this exact solution. Have you had any luck?

**Comment by mdevaev** [comment]
I've added option WIFI_HIDDEN=1 for this. But to use it you will need to reflash the image. Images will be ready after ~2 hours.

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by tvories** [comment]
> I've added option WIFI_HIDDEN=1 for this. But to use it you will need to reflash the image. Images will be ready after ~2 hours. Also fixed the doc.

Wow, thank you for adding that! I really appreciate your quick turn around time.
