### ISSUE TITLE
Is the DIY PiKVM V2 build compatible with a raspberry pi 5 ?

### ISSUE THREAD

**Issue by melek-charfi** [pikvm/pikvm#1271]
Is the DIY PiKVM V2 build compatible with a raspberry pi 5 ?
Thanks.

**Comment by mdevaev** [comment]
No, and no any points to use it for PiKVM. Pi 5 doesn't have hardware video encoders, so you can't get any performance improvements over Pi 4.

**Comment by melek-charfi** [comment]
Thanks for the answer !

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by MarkusLange** [comment]
> No, and no any points to use it for PiKVM. Pi 5 doesn't have hardware video encoders, so you can't get any performance improvements over Pi 4.

Beside this that there is no performace improvements can I run it on a PI 5 anyway? And btw. in small config like only the HDMI-CSI bridge?

**Comment by mdevaev** [comment]
> Beside this that there is no performace improvements can I run it on a PI 5 anyway?

Nop.
