### ISSUE TITLE
Mouse and keyboard do not connect when windows restarts

### ISSUE THREAD

**Issue by Deefury13** [pikvm/pikvm#1279]
When you restart windows both the mouse and keyboard turn orange and cease to function unless the PiKvm is rebooted

**To Reproduce**

1. restart windows

**Expected behavior**
Should reconnect when windows restarts

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11

**PiKVM info:**
  - Raspberry Pi board version RPi 4 B 8GB
  - PiKVM platform V3 pice version

**Additional context**

**Comment by mdevaev** [comment]
Hello.

> PiKVM platform V3 pice version

What device do you mean? Please take a photo or give a link.

**Comment by Deefury13** [comment]
Geekworm KVM-A8 PCIe Version for... https://www.amazon.com/dp/B0BN1MFHMW?ref=ppx_pop_mob_ap_share
![IMG_3522](https://github.com/pikvm/pikvm/assets/71853277/fb9c8a50-9513-44e4-b172-0458c3d87763)
![IMG_3523](https://github.com/pikvm/pikvm/assets/71853277/e86b5b06-8fc1-40d6-a95f-fcdf2062b67b)

**Comment by mdevaev** [comment]
This is not PiKVM device. We only support our own devices and DIY builds. If you have problems with third-party devices, contact their manufacturer.
