### ISSUE TITLE
The "Exit Full Screen" button doesn't appear on MacOS

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1283]
**Describe the bug**
The "Exit Full Screen" button usually appears when the mouse is moved to the top of the screen.
This works on Linux and BSD.
But this doesn't work on MacOS, because MacOS has the top panel that becomes visible before the "Exit Full Screen" button appears.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Possible resolution**
Maybe an additional margin space at the top of the screen needs to be added on MacOS so that the PiKVM button would have a chance to appear before the MacOS standard top panel appears.

**Comment by mdevaev** [comment]
The button to exit full screen mode is part of the browser. I can't change it.

**Comment by yurivict** [comment]
I didn't know this.
Thank you.
