### ISSUE TITLE
v4 DIY instructions

### ISSUE THREAD

**Issue by hryamzik** [pikvm/pikvm#1285]
Is there a way to build v4 mini yourself? v3 works fine but does miss passive cooling.

**Comment by mdevaev** [comment]
Hello. The V4 is sold as a ready-to-use device complete with CM4 and case. There are no DIY options for this.

**Comment by hryamzik** [comment]
Does this mean hardware is not open sourced?

**Comment by mdevaev** [comment]
The software is open, the hardware is not. It's our way of monetization, since PiKVM is our full time work. Thanks to the closed hardware, the software remains open and high quality.

**Comment by hryamzik** [comment]
I totally get your points, was mostly interested in DYIing to make a silent unit but otherwise older versions are fine. Thanks for keeping software code open!

**Comment by mdevaev** [comment]
Well, V4 Mini is already silent unit with passive cooling. We have selected and tested the most suitable parts for this.
