### ISSUE TITLE
MSD Related Features

### ISSUE THREAD

**Issue by wohenipinle** [pikvm/pikvm#1292]
Hi Maxim Devaev,

Sorry to bother.
I wonder how to realize a structure like MSD to upload/download/remove/read write files.

For example :
1.Create a folder `msd2` just like  `/var/lib/kvmd/msd` for other ways to use.
2.How the code flow runs like MSD uses python files to read/write/remove/... in the folder `/var/lib/kvmd/msd`.

Could you show me the code location that msd used for the structure.

Really thanks for your help.

**Comment by mdevaev** [comment]
Hello. It's all here: https://github.com/pikvm/kvmd/tree/master/kvmd/plugins/msd
