### ISSUE TITLE
Sleep and wakeup button on web interface

### ISSUE THREAD

**Issue by sharicov** [pikvm/pikvm#1295]
Could you please impalement sleep and wake up buttons in the web interface to put host PC to sleep and to wake it up?
Thanks in advance.

**Comment by mdevaev** [comment]
The only thing that I give you is a quick access to the "Power" key. It will be available in the next release. But you should understand that there is no default standard behaviour for this key.

![image](https://github.com/user-attachments/assets/927881b9-c55c-40ac-a396-52561e930355)

**Comment by QkiZMR** [comment]
A sleep button like on a laptop keyboard would be nice.
