### ISSUE TITLE
I got a issue "Mouse and keyboard not have click response"

### ISSUE THREAD

**Issue by bi7jta** [pikvm/pikvm#1296]
**Describe the bug**
After boot use the Web Power menu , if I not have click activity long time since bootup, the mouse and keyboard will not accept my click request , till I disconnect and connect USB line between Raspberry Pi TypeC and PC USB.

My problem is : why will cause this ? Can I do some operation to activity piKVM mouse and keyboard again, use software?

Not one time , all bootup if I not wait the Windows 10 UI appear , will cause this .

Thank you very much! 

**Screenshots**
 
![Xnip2024-04-01_14-39-58](https://github.com/pikvm/pikvm/assets/22002824/feb16119-f829-4627-be23-60924042edb9)

![Xnip2024-04-01_14-40-48](https://github.com/pikvm/pikvm/assets/22002824/432c7a62-7ba6-4871-a6bd-5e1278cbd150)

**Comment by mdevaev** [comment]
Hello. Cursor is working?

**Comment by mdevaev** [comment]
No feedback, closing.
