### ISSUE TITLE
Paste Text or sending keypress sequence is not pasting/sending the white space correctly

### ISSUE THREAD

**Issue by plia7** [pikvm/pikvm#1298]
**Describe the bug**
Using the Paste Text function or sending keypress sequence is not pasting/sending the white space correctly.

**To Reproduce**
1. Try to paste or send the following text to the host while inside a new notepad or any other text editor program (make sure the text cursor is at the beginning of the new text file):

```
hello world12 3
  hellwoworld 45 6
    42 test one two three four
  23 54 test this 1234

  testing 5
    23 553 125 631 testing
  21
8
```

**Actual behavior**
It ends up being pasted like this:

```
hello world12 3
  hellwoworld 45 6
        42 test one two three four
           23 54 test this 1234

              testing 5
                   23 553 125 631 testing
                      21
                      8
```

**Expected behavior**
White space is preserved and should be pasted like this:

```
hello world12 3
  hellwoworld 45 6
    42 test one two three four
  23 54 test this 1234

  testing 5
    23 553 125 631 testing
  21
8
```

**Desktop (please complete the following information):**
Windows 11
Google Chrome Version 123.0.6312.58 (Official Build) (64-bit)
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4]
PiKVM v3 Pre-Assembled
  - PiKVM platform [e.g. v2-hdmi]
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `pacman -Q | grep kvmd`
kvmd 3.321-1
kvmd-fan 0.30-1
kvmd-oled 0.26-1
kvmd-platform-v3-hdmi-rpi4 3.321-1
kvmd-webterm 0.48-1
  - uStreamer version: `pacman -Q | grep ustreamer`
ustreamer 6.4-1
  - Linux kernel: `uname -a`
Linux pikvm 6.6.21-4-rpi # 1 SMP Wed Mar 13 20:36:42 UTC 2024 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Check if your have auto indentation in the text editor in the host

Пн, 8 апр. 2024 г. в 08:12, plia7 ***@***.***>:
