### ISSUE TITLE
[question] Will the v3 device also require purchase of a TC358743 based bridge?

### ISSUE THREAD

**Issue by jshridha** [pikvm/pikvm#130]
I'd like to build one of these devices right now and I know that v3 is in active development. I'm curious if I plan on buying one of the v3 boards, will it come with a TC358743 chip on board or will I need to purchase one of the boards like is linked on the front page? If I'll need to buy one anyway, I'll go ahead and build a v2 now and then just upgrade it to v3. Hope that makes sense.

Thanks for the help.

**Comment by mdevaev** [comment]
You won't need to buy a bridge since everything will already be on the v3 board.

**Comment by jshridha** [comment]
That's what I need to know. Thanks for the help!
