### ISSUE TITLE
Video is not streaming to browser from remote network

### ISSUE THREAD

**Issue by rgov** [pikvm/pikvm#1305]
**Describe the bug**
Streaming video across Tailscale and the Internet to my browser is not working. Streaming video to another system on the PiKVM's local network is working.

I have a PiKVM attached to a system in a remote location. The PiKVM is connected to the Internet and is running Tailscale.

When I try to access to PiKVM stream over Tailscale, I get no video output in either WebRTC or HTTP streaming modes. I *do* get a single frame if I use the "Screenshot" function.

If I access a second system on the same network as the PiKVM, and pull open the PiKVM web UI on that system, I *do* see the target system's video output. (Note in this case I am bypassing Tailscale and use TeamViewer.)

So it seems to be some issue either with the latency of streaming over the Internet, or the use of Tailscale, or both.

I see no errors in my browser console. I do see in the websocket history that there are only a few "binary frames" (presumably video frames) being sent, but the rest of the traffic is just `streamer_state` packets -- the server seems to stop sending video frames.

**Desktop:**
 - OS: macOS
 - Browser: Safari
 - Version: 14.4
 - VNC client: None

**PiKVM info:**
  - Raspberry Pi board version: RPi CM 4
  - PiKVM platform: V4 Mini
  - Video capture type: (as above)
  - KVMD version:
    ```
    kvmd 3.329-1
    kvmd-fan 0.30-1
    kvmd-oled 0.27-1
    kvmd-platform-v4mini-hdmi-rpi4 3.333-1
    kvmd-webterm 0.48-1
    ```
  - uStreamer version: `ustreamer 6.11-1`
  - Linux kernel: `Linux pikvm 6.6.21-4-rpi #1 SMP Wed Mar 13 20:36:42 UTC 2024 armv7l GNU/Linux`

**Comment by rgov** [comment]
I am able to access the video stream over TigerVNC.

**Comment by arch1mede** [comment]
Hi, please join [Discord](https://discord.gg/bpmXfz5) to discuss further, please mention this issue when you join.

**Comment by mdevaev** [comment]
This is clearly not a bug, but an installation problem, please use discord for support (if you haven't done it yet)
