### ISSUE TITLE
PiKVM for Intel NUC NUC11PAHI7

### ISSUE THREAD

**Issue by johnlockejrr** [pikvm/pikvm#1314]
Hi!

I want to order a PiKVM kit to manage my Intel NUC NUC11PAHI7. Anybody has tried and knows a success story? I can't seem to find the ATX pins on the NUC motherboard..., never had one before and I'm used to "normal" motherboards.

Thanks for your help! As sorry if I bother...

**Comment by mdevaev** [comment]
Hello! NUC does not have a standard ATX and for control you will have to figure out the pinout and connection of LEDs and buttons. But otherwise everything should work.

**Comment by johnlockejrr** [comment]
Thanks for your reply. I kind of figured it out.
From NUC's manual:

```
5.1.1.1 Front Panel Header (2.0 mm Pitch)
This section describes the functions of the front panel header. Table 14 lists the signal
names of the front panel header. Front Panel Header (2.0 mm Pitch) is a connection
diagram for the front panel header.
Table 14. Front Panel Header (2.0 mm Pitch)
Pin	Signal Name		Description		Pin	Signal Name	Description
1	HDD_POWER_LED		Pull-up 750Ω to +5V	2	POWER_LED_MAIN	[Out] Front panel LED (main color) Pull-up 300Ω to +5V
3	HDD_LED#		[Out] HDD activity LED	4	POWER_LED_ALT	[Out] Front panel LED (alt color)
5	GROUND			Ground			6	POWER_SWITCH#	[In] Power switch
7	RESET_SWITCH#		[In] Reset switch	8	GROUND		Ground
9	+5V_DC (1A) (Vcc)	Power			10	Key		No pin
```
As fas as I understand it, I must find some connector cables from 2,54 mm female to 2.0 mm female. I'll give it a try.

**Comment by mdevaev** [comment]
:ok_hand: If you have any problems, please contact our discord chat, it will be faster.

**Comment by scyto** [comment]
@johnlockejrr did you get it working?

**Comment by Austin519** [comment]
Look here: https://www.amazon.com/gp/product/B00LSW184G/ref=ox_sc_saved_image_1?smid=A1UCLUF7KW7AYG&psc=1

You may need to move pins around on the cable though.

**Comment by johnlockejrr** [comment]
I gave up, I use it without ATX and works well
