### ISSUE TITLE
Compiling fails / problem wit pacman

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#1315]
When I try to compile PiKVM (v2-hdmi for RPI4) on Debian 11.8 Bullseye and Debian 12.5 Bookworm with `make os`, I get:

```
:: File /var/cache/pacman/pkg/glibc-2.39-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: glibc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust
error: failed to commit transaction (invalid or corrupted package)

Errors occurred, no packages were upgraded.
```

**Comment by mdevaev** [comment]
Please use a ready-made image for this case: https://docs.pikvm.org/flashing_os/

Sometimes the features of the host system fail during assembly.

**Comment by etkaar** [comment]
Thanks. I tried it later with a new Ubuntu VPS and then it worked.
