### ISSUE TITLE
ATX Breadboard Scheme (only power SW)

### ISSUE THREAD

**Issue by ArtichautDev** [pikvm/pikvm#1318]
hi, I only need power SW for my DIY PIKVMV2 it is possible to only make the power SW on the breadboard ?

like this:
![Capture d’écran 2024-05-03 à 15 54 34](https://github.com/pikvm/pikvm/assets/91349238/7bf49384-6f12-4275-bb59-f3a2cb54e38f)

And, it is possible to simplify the scheme and remove the mosfet ?
Thanks !

**Comment by mdevaev** [comment]
Hello. Yes, you can only make the power SW. But mosfet is required, you can't remove it.

This is a support issue, so I ask you to follow on to [Discord](https://discord.gg/bpmXfz5) if you have any more questions.
