### ISSUE TITLE
Cannot access pikvm Ethernet Connection failed Linux Mint 20.3

### ISSUE THREAD

**Issue by greereer** [pikvm/pikvm#1319]
I follow the guidance in the first steps using a proven ethernet cable and outlet, pikvm powers on and ethernet shows connection.

On my computer I get wired connection failed, cannot find pikvm on arp scan, no connection to IP address on browser nor SSH.

System details:
Linux Mint 20.3
Kernel: 5.15.0-105-generic

Desired output: I can access pikvm by web browser via IP address or pikvm

I have try reinstall pikvm image, verified at all times OLED comes on as well and shows interface eth0

Thank you in advance for the help.

**Comment by arch1mede** [comment]
Hi, since you are having connection issues, I would ask that you please join [Discord](https://discord.gg/bpmXfz5) and show screen shots on how you have this all wired up.
