### ISSUE TITLE
Cannot Disable https

### ISSUE THREAD

**Issue by ItAdmin712** [pikvm/pikvm#1331]
I added the following code to: /etc/kvmd/override.yaml
nginx:
      https:
           enabled: false
I then restarted pikvmd

When attempting to go to http://<ip> it still redirects to https

Is there a way to disable this redirection and the requirement for https?

**Comment by mdevaev** [comment]
You should restart `kvmd-nginx`.

**Comment by mdevaev** [comment]
Solved I guess.
