### ISSUE TITLE
The RealVNC (was mistakenly listed as Microsoft VNC) client on MacOS doesn't allow to enter admin/admin credentials for PiKVM

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1332]
**Describe the bug**
Remmina is able to connect to PiKVM fine from FreeBSD using admin/admin credentials.
However, the same fails from the RealVNC client on MacOS.
It displays the login screen, but login name is grayed out, and only password can be entered.
This prevents connection from MacOS.

Is there a workaround for this problem?

**Comment by mdevaev** [comment]
I believe this client is somehow incorrectly or not fully implementing [password authorization](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#vencrypt). I usually recommend using TigerVNC in such cases.

**Comment by mdevaev** [comment]
Is it? https://apps.microsoft.com/detail/9pj2zqlfkwws?hl=en-mm&gl=MM

**Comment by yurivict** [comment]
* Correction:
It is RealVNC for MacOS (not MS VNC)

Sorry for the confusion.

**Comment by mdevaev** [comment]
Ah, RealVNC. Paradoxically, RealVNC is very far from open VNCs and for the most part implements its own proprietary protocols. It has never worked at all and I doubt it will.

**Comment by yurivict** [comment]
Ok, thank you.
