### ISSUE TITLE
Please add support of MS2130 Chip

### ISSUE THREAD

**Issue by vmvwv** [pikvm/pikvm#1336]
I love pikvm, it solves my home lab monitoring problem from raspberry pi4 ethernet. Recently, I purchase a USB 3.0 Video Capture Card HDMI to USB, which employing the MS2130 chipset solution, it offers great image quality and usability. 

So I hope pikvm can add the support of MS2130 chip as a new feature.

**Comment by mdevaev** [comment]
Hello. We support those devices for which there is a V4L2 driver in the kernel. If the device is supported by Linux, no additional actions are required on our part.
