### ISSUE TITLE
NO SIGNAL after upgrade 4.2-1

### ISSUE THREAD

**Issue by gonzalo-** [pikvm/pikvm#1337]
**Describe the bug**
Everything was working fine, I did the upgrade to 4.2-1 (on my rpi2w) and now I got "NO SIGNAL" on my 2 pikvm.

**To Reproduce**
I believe just to upgrade to 4.2-1 with the same hw.

**Expected behavior**
See the screen of the connected machine (it worked just fine before the upgrade)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OpenBSD
 - Browser: FF, Chrome.
 - Version 126.0
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version RPI2 Zero w
  - PiKVM platform v2-hdmi
  - Video capture type [e.g. CSI bridge]
 dmesg | grep tc3
[ 0.047398] platform 3f801000.csi: Fixed dependency cycle(s) with /soc/i2c0mux/i2c@1/tc358743@f
[ 10.168933] tc358743 10-000f: tc358743 found @ 0x1e (i2c-11-mux (chan_id 1))
  - KVMD version: `pacman -Q | grep kvmd`
kvmd 4.2-1
kvmd-fan 0.31-1
kvmd-oled 0.27-1
kvmd-platform-v2-hdmi-zero2w 4.2-1
kvmd-webterm 0.50-1
  - uStreamer version: `pacman -Q | grep ustreamer`
ustreamer 6.12-1
  - Linux kernel: `uname -a`
Linux [pikvm01.lab](https://pikvm01.lab/) 6.6.21-4-rpi #1 SMP Wed Mar 13 20:36:42 UTC 2024 armv7l GNU/Linux

**Additional context**

**Comment by gonzalo-** [comment]
Well, I just realized that I got some updates missing, running `pikvm-update` again just fixed the issue.

Sorry for the noise.

**Comment by return2alfred** [comment]
@gonzalo- , Hi gonzalo, I've met exactly the same issue on pi zero 2w, my pikvm update done, and info shows exactly same like yours. What is the missing updates you run and resolve this issue?

**Comment by springeye** [comment]
I encountered the same problem after running pikvm-update yesterday (but my computer system has already recognized the 'display')."

**Comment by mdevaev** [comment]
Please join discord chat to resolve support issues.
