### ISSUE TITLE
Add Model Name to /api/info

### ISSUE THREAD

**Issue by adamoutler** [pikvm/pikvm#1342]
**Is your feature request related to a problem? Please describe.**
I'm creating a Home Assistant integration and I can't get a proper name of the device. All I can see is the raspberry pi model.  It seems like there should be some way to get an official model/marketing name from API.

**Describe the solution you'd like**
I'd like PiKVM V3/V4 Mini/V4 Plus somewhere in the /api/info. 

**Describe alternatives you've considered**
I guess I could do something like:
* RPI 4 = V3
* Compute Module = v4
    * Fan = plus
    * No fan = mini

But this will incorrectly identify custom builds as official hardware and if someone removes the fan or adds one then it's possible to be incorrectly identified.

**Additional context**

I'd like to add an official model name to this page.
![image](https://github.com/pikvm/pikvm/assets/527919/f5453101-fbdd-4956-9d6d-7754bb802ff5)

**Comment by mdevaev** [comment]
Will be available in the next release.
