### ISSUE TITLE
CPU load via API

### ISSUE THREAD

**Issue by to4ko** [pikvm/pikvm#1347]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great to have CPU load available via API

**Describe alternatives you've considered**
cron job every minute or so

**Additional context**
-

**Comment by mdevaev** [comment]
Hello. It will be available in the next release.

![image](https://github.com/pikvm/pikvm/assets/416259/6e93fe11-80c7-4a73-bebf-578b859df66d)
