### ISSUE TITLE
kvmd vnc server is not compatible with client talking RFB Protocol 3.3

### ISSUE THREAD

**Issue by zhangyoufu** [pikvm/pikvm#1349]
**Describe the bug**
RFB Protocol 3.7/3.8 negotiate security types. Server sends an array and client choose one. Security type is encoded as u8.  
RFB Protocol 3.3 does not negotiate security types. Server decides the security type and sends a single u32.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Capture VNC packet between client and server
2. Connect to kvmd vnc server using a VNC client that only supports RFB Protocol 3.3
3. Wireshark dissector shows that server sent a malformed `Security types supported`

**Expected behavior**
kvmc vnc server is expected to downgrade protocol version to RFB Protocol 3.3

**Screenshots**
<img width="1364" alt="RFB-malformed" src="https://github.com/pikvm/pikvm/assets/1315097/a2db60b7-c87a-4abf-8fee-a92b1d7bac09">

**Desktop (please complete the following information):**
- OS: macOS
- Version: Sonoma 14.5 (23F79)
- VNC client: Screen Sharing

**PiKVM info:**
- PiKVM platform: v3-hdmi
- KVMD version: `4.2-1`

**Comment by zhangyoufu** [comment]
I understand that PiKVM requires a VNC client that supports either Tight(JPEG) or H.264. Both encoding are not available for RFB Protocol 3.3 clients.

Please simply drop support for RFB protocol < 3.7 and reject connection earlier.

**Comment by zhangyoufu** [comment]
3.3 spec defined raw(0), copy rectangle(1), RRE(2), CoRRE(4), hextile(5) without mentioning Tight though.

**Comment by zhangyoufu** [comment]
I opened a pull request for this issue, please checkout. I don't have a working RFB 3.3 client to test everything. But my client passed security type handshake and shows PiKVM.

**Comment by mdevaev** [comment]
Merged, thank you.
