### ISSUE TITLE
Paste fails sometimes: "HID paste error:"

### ISSUE THREAD

**Issue by yurivict** [pikvm/pikvm#1352]
**Describe the bug**
![image](https://github.com/pikvm/pikvm/assets/271906/6f50c690-f6e0-4a18-b3fb-a03814addb87)

The text is very regular, just ASCII characters.

**Comment by mdevaev** [comment]
Please check the browser console & network connections.

**Comment by arch1mede** [comment]
Hi, can you provide details so we can try and reproduce this? I am unable to repo this issue. No need to provide anything sensitive, you can make this similar.

**Comment by yurivict** [comment]
I can't reproduce this on purpose now.
But this happened to me twice in the last month.
I will look at the browser console next time when I see it.

**Comment by mdevaev** [comment]
Okay.

**Comment by yurivict** [comment]
The browser console gets an error like these every time:
![image](https://github.com/user-attachments/assets/17e19029-5064-4eb7-b40f-fed9245d02c6)

**Comment by yurivict** [comment]
The Network connections window gets one message like these every time:
![image](https://github.com/user-attachments/assets/f69fbad4-4e52-442b-b4d7-35ae43071120)

**Comment by mdevaev** [comment]
I don't understand why an SSL error occurs if the rest of the interface is working. Do you have any ideas?

**Comment by mdevaev** [comment]
Do you still have this problem after all updates?

**Comment by yurivict** [comment]
I will update, test, and will reopen this issue if it would come up again.

**Comment by mdevaev** [comment]
Okay.
