### ISSUE TITLE
Asrock BIOS is zoomed in on V3

### ISSUE THREAD

**Issue by chriexpe** [pikvm/pikvm#1355]
**Describe the bug**
This only happens when I access the BIOS, otherwise the video size is just fine.
Also you can note that the mouse  cursor isn't over mine, always quite a bit to the side.

**GIF**
![8mb video-1Eu-FRxIAwiI-ezgif com-video-to-gif-converter](https://github.com/pikvm/pikvm/assets/16724821/d317fe52-931b-4206-9890-f0ab024e1989)

**Desktop (please complete the following information):**
 - MOBO: Z690 Phantom Gaming 4/D5
 - BIOS: 16.03 (latest)
 - Firefox
 - Version 127.0.1

**PiKVM info:**
  - Raspberry Pi 4b 8GB
  - PiKVM platform: Geekworm-open source kvm-a3
  - KVMD version: kvmd 3.284-1 | kvmd-fan 0.26-1 | kvmd-oled 0.26-1 | kvmd-platform-v3-hdmi-rpi4 3.284-1 | kvmd-webterm 0.44-1
  - uStreamer version: 5.45-1
  - Linux kernel: Linux pikvm 6.1.61-1-rpi-ARCH #1 SMP Fri Nov  3 20:48:52 MSK 2023 armv7l GNU/Linux

**Additional context**
Couldn't change EDID `error: unrecognized arguments: --import-preset=v3.1080p-by-default`

**Comment by mdevaev** [comment]
> PiKVM platform: Geekworm-open source kvm-a3

This is not PiKVM V3. We don't support third-party hardware. Please contact the manufacturer.

**Comment by sqanch** [comment]
I have the exact same issue with the official PiKVM v3 hat. The described behavior occurs only in the BIOS, once the OS is booted everything works fine. Any suggestions on how to fix it?

**Comment by mdevaev** [comment]
Hello. Please try this: https://docs.pikvm.org/edid/#force-1080p-by-default-on-pikvm-v0

**Comment by chriexpe** [comment]
> Hello. Please try this: https://docs.pikvm.org/edid/#force-1080p-by-default-on-pikvm-v0

Yup, now it's working perfectly, thank you! @sqanch thank you too for bringing this up

![Image](https://github.com/user-attachments/assets/ee9ad02c-3f17-495c-b9a6-d43a1a45cd2d)

**Comment by sqanch** [comment]
Works for me as well, thank you very much!
