### ISSUE TITLE
Adding monitor/audio vendors/SN/model/product id to override.yaml

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1357]
**Is your feature request related to a problem? Please describe.**
Using the kvmd-edidconf is not very comfortable if you need to manage multiple devices. It would be much easier to share the same override.yaml file and have the ability to set the settings there. I don't need a specific EDID setting, vendor/serial number/model/product id should be displayed in the Device Manager and settings.
![edid1](https://github.com/pikvm/pikvm/assets/17403762/af5affa8-dd57-4ef2-8ad4-96a55ee0914b)
![edid2](https://github.com/pikvm/pikvm/assets/17403762/6df06e80-f857-468d-b2f4-bf9418b123ac)

**Describe the solution you'd like**
Please add this customization from kvmd-edidconf to override.yaml:
![edid3](https://github.com/pikvm/pikvm/assets/17403762/df177981-1287-44f1-b79a-4125945834ec)
In a manner similar to this one:
![edid4](https://github.com/pikvm/pikvm/assets/17403762/5a70744d-b152-446e-a234-6e2f12419227)

**Describe alternatives you've considered**
None, it's simple enough, I think.

**Additional context**
Thank you for your help.

**Comment by mdevaev** [comment]
Hello. Why you can't just copy /etc/kvmd/tc358743-edid.hex after all changes made by kvmd-edidconf?

**Comment by mareksagan** [comment]
Because then I have to copy two files and it's less convenient. As I mentioned, you're probably right that it's not a problem if you have one device. I have many.

**Comment by mdevaev** [comment]
I'll think about whether it's possible to do it the way you want. The fact is that EDID is a fairly low-level thing that is used in V4L2 even before KVMD starts working.

**Comment by mareksagan** [comment]
Ok, I understand. Maybe in the meantime you could guide me through the standard EDIDs please? I mean, what resolution, refresh frequency and monitor make/model do they set when I use them? I couldn't find the exact description for them.
![edid5](https://github.com/pikvm/pikvm/assets/17403762/f070a881-1761-4763-ac3f-6c17b83f9165)

**Comment by mdevaev** [comment]
V4 uses default 1080p resolution and supports 60Hz, also supports 1920x1200. V0-V3 uses default 720p, but supports 1080p at 50Hz.

**Comment by mdevaev** [comment]
Given the other features we have planned, this will not be implemented because we need flexible configuration of EDID data. I would recommend rolling out configs using tar archives.
