### ISSUE TITLE
Multi-device mouse jiggler (ezCoo switch)

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1359]
**Is your feature request related to a problem? Please describe.**
A multi device mouse jiggler, (hopefully) enabling the user to switch between devices and they all would be on all the time. I am thinking about the ezCoo EZ-SW41HA-KVMU3L that your project recommends but it can be any of the compatible switches.

**Describe the solution you'd like**
I found this document (excoo1.docx) describing a flashing/upgrade process of ezcoo switch:
![ezcoo1](https://github.com/pikvm/pikvm/assets/17403762/7101c904-b173-42ae-8a29-32b436f186c3)
![ezcoo2](https://github.com/pikvm/pikvm/assets/17403762/afdab40d-2502-4203-a94b-a49f165461c3)
![ezcoo3](https://github.com/pikvm/pikvm/assets/17403762/d64fb86b-5b00-41d9-a1ba-3bd019c68eeb)
![ezcoo4](https://github.com/pikvm/pikvm/assets/17403762/b6669a4f-11ad-4cb6-8404-269bd61bab71)
![ezcoo5](https://github.com/pikvm/pikvm/assets/17403762/8ba61442-10aa-472a-9609-90063adfe4c6)
Theoretically speaking, it is possible to program/flash the switch itself.
Do you have low level experience with that switch? Would it be possible to implement a multi-device jiggler on the switch level?
I realise how the switch works and a solution like that on the PiKVM level would be impossible since only 1 device at the time can be operated.

**Describe alternatives you've considered**
There is always Wakeup on LAN. Maybe you have some other ideas that would be better? Maybe apart from buying more PiKVM devices, is that the best way?

**Additional context**
Thank you for your help.

**Comment by mdevaev** [comment]
I don't think it's possible. It will require a custom firmware for the switch and reverse engeneering. It is possible that this is not feasible in hardware.

So no, we can't do it. The best advice is to use a cheap hardware jiggler in usb ports.
