### ISSUE TITLE
Ability to disable the macro and system menu from override.yaml

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1360]
**Is your feature request related to a problem? Please describe.**
I want to to be able to disable the macro and system menus from override.yaml in a manner similar to the ATX menu:
![menu1](https://github.com/pikvm/pikvm/assets/17403762/cacd5d40-56d0-401a-9fed-99b09677f8ac)
![menu2](https://github.com/pikvm/pikvm/assets/17403762/2db0d362-9ae9-422d-a7c9-319a37a96e73)
I want to set the default values in override.yaml and don't allow users to change them at all.

**Describe the solution you'd like**
kvmd:
    system:
        type: disabled
    macro:
        type: disabled

**Describe alternatives you've considered**
None.

**Additional context**
Thank you for your help.

**Comment by mdevaev** [comment]
Macro is browser-side feature, you can't disable it.

System menu is also can't be limited.

You can use `/etc/kvmd/web.css` to change display attributes of these menues and hide them from users.
