### ISSUE TITLE
Browser tab name customization for the PiKVM session

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1361]
**Is your feature request related to a problem? Please describe.**
I want to be able to change the name that appears on the tab of the PiKVM session.
![tab_session_name1](https://github.com/pikvm/pikvm/assets/17403762/515f9a1e-16e2-476c-88ae-946e3dd61c4c)

**Describe the solution you'd like**
Just add a override.yaml field that corresponds to the tab session name:
kvmd:
    tab_name: 'Happy Session'

It would change the name 'PiKVM Session: localhost:localdomain' to "Happy Session'

**Describe alternatives you've considered**
None.

**Additional context**
Thank you.

**Comment by mdevaev** [comment]
Hello. You can change `localhost:localdomain` part in /etc/kvmd/meta.yaml

**Comment by mdevaev** [comment]
Solved, I guess.
