### ISSUE TITLE
Disabling the green LED on PiKVM v3 (Raspberry Pi 4B)

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1362]
**Is your feature request related to a problem? Please describe.**
I would like to disable the green LED (ACT? soundboard?) on my PiKVM v3 because it's a little bit annoying sometimes in a dark environment.

**Describe the solution you'd like**
Is there an option in override.yaml or config.txt that allows me to do that? That would be ideal.

**Describe alternatives you've considered**
None.

**Additional context**
Thank you for your help.

**Comment by mdevaev** [comment]
Just use black tape :)

**Comment by mdevaev** [comment]
Solved I guess.
