### ISSUE TITLE
Ezcoo GPIO switching disabled following pikvm-update to v4.2

### ISSUE THREAD

**Issue by DocWoodward** [pikvm/pikvm#1363]
I've had PiKVM working nicely with an Ezcoo EZ-SW41HA-KVMU3P but today I updated to ver 4.2 and the switching options on the GPIO menu no longer work. I've tried rebooting PiKVM with no effect.

**Comment by mdevaev** [comment]
Hello. Please check `dmesg`, do you have your tty device of switch?

**Comment by DocWoodward** [comment]
I see quite a lot of these lines in dmesg:

[250249.378756] ch341-uart ttyUSB0: ch341_open - failed to submit interrupt urb: -22

**Comment by DocWoodward** [comment]
Rebooted switch and it's all resolved now. Not sure why it stopped working after update.

**Comment by mdevaev** [comment]
I see. Ok then. Replace the USB cable, just in case.
