### ISSUE TITLE
Disabling audio to make the stream more fluent/faster

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1364]
**Is your feature request related to a problem? Please describe.**
Is there a better way to disable audio on PiKVMv3 than just turning it off in kvmd-edid? So all of the daemons don't run and take resources from PiKVM?

**Describe the solution you'd like**
Maybe an option in the override.yaml or a dedicated tool?

**Describe alternatives you've considered**
 Are there any other ways that you can think of to improve the stream fluency/speed? I'm open to every suggestion.

**Additional context**
Thank you for your help!

**Comment by mdevaev** [comment]
This is already implemented. The audio in the EDID does not affect the delay. On the web interface side, if you set the volume to zero, the audio stream is not sent to the browser and reduces the delay.
