### ISSUE TITLE
QR code support in Text menu

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1366]
**Is your feature request related to a problem? Please describe.**
The OCR sometimes has a lot of issues and the text copied needs to be corrected.

**Describe the solution you'd like**
Adding a submenu in Text menu would solve a lot of issues. QR code based solution would be more easy and faster to use, not to mention the amount of errors (virtually zero). You would select the screen fragment with the QR code (you can generated them easily with e.g. browser extensions, Chrome has it by default) and just let it be copied to the clipboard.

**Describe alternatives you've considered**
None, it's very simple.

**Additional context**
Thanks.

**Comment by mdevaev** [comment]
Duplicate: #1005
