### ISSUE TITLE
PiKVM Automatically Powers Server Back On After Shutdown

### ISSUE THREAD

**Issue by Robdemi** [pikvm/pikvm#1367]
**Describe the bug**
Whenever I shut down my server, PiKVM detects that the server is off and then presses the power button to turn it back on. This only happens when PiKVM is connected to the computer.

**To Reproduce**
1. Shutdown the server via the OS.
2. Observe that the server shuts down.
3. PiKVM automatically presses the power button to turn the server back on.

**Expected behavior**
The server should remain off after being shut down.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
- OS: Linux
- Browser: Not applicable
- Version: Not applicable
- VNC client: Not applicable

**PiKVM info:**
- Raspberry Pi board version: Raspberry Pi Compute Module 4 Rev 1.1
- PiKVM platform: v4 plus
- Video capture type: Not specified
- KVMD version: v4.2
- uStreamer version: v6.12
- Linux kernel: v6.6.21-4-RPI

**Additional context**
- The issue only occurs when the PiKVM is connected to the computer.
- Disconnecting the PiKVM allows the server to remain off.
- The server is a regular ATX tower with an ASUS Prime B760 Plus motherboard.
- The server immediately turns back on after shutting down, with a click sound from the PiKVM that resembles a relay switch.
- The issue was not present before updating the PiKVM software.
- Suspect that the PiKVM might have an Always-On configuration or a watchdog setting related to ATX controller.

System details:
- **Machine:** armv7l
- **Release:** 6.6.21-4-rpi
- **Version:** #_1 SMP Wed Mar 13 20:36:42 UTC 2024
- **Serial:** 10000000c372d339
- **Temperature:**
  - **CPU:** 43.816°C
- **Throttling:**
  - **Freq capped:** No
  - **Throttled:** No
  - **Undervoltage:** No
- **Fan:**
  - **Status:** Ok
  - **Desired speed:** 27%
  - **PWM:** 276
  - **RPM:** 2430

**Attempts to resolve:**
- Checked the `/etc/kvmd/main.yml` file but couldn't find relevant settings.
- Tried various combinations of disconnecting USB and ATX cables.

Any help would be appreciated. Thanks!

**Comment by mdevaev** [comment]
Solved by client.
