### ISSUE TITLE
PIKVM V4-Public net work

### ISSUE THREAD

**Issue by reddeppa-eddala** [pikvm/pikvm#1372]
Right now PIKVM is connected with local network which is my home internet and i could connect my laptop remotely and no issue.

when i want use different network which means different internet but it is not working and checked with google and confirmed that using tail scale VPN is possible and followed those steps and updated at os Level but no luck.

Please refer this link -https://tailscale.com/kb/1292/pikvm.

Now my question to you : Is it possible use PIKVM device with different network? if yes please share the steps and also i am ready for online support .

**Comment by mdevaev** [comment]
For support questions please use our discord: https://discord.gg/bpmXfz5

**Comment by reddeppa-eddala** [comment]
I have registered in this link -[ttps://discord.gg/bpmXfz5](https://discord.gg/bpmXfz5) and not sure how to access it . 

Could you please reply to my query 

Right now PIKVM is connected with local network which is my home internet and i could connect my laptop remotely and no issue.

when i want use different network which means different internet but it is not working and checked with google and looks like  using tail scale is possible and followed those steps as per the below link  and updated at os Level but no luck.

Please refer this link -https://tailscale.com/kb/1292/pikvm.

Now my question to you : Is it possible use PIKVM device with different network? if yes please share the steps and also i am ready for online support .

**Comment by arch1mede** [comment]
Hi, yes I can confirm that with a default image, this should work on any network that uses DHCP that you place this on, we would need to see more details as to why this isn't working which Discord would help us with.

**Comment by reddeppa-eddala** [comment]
Is it possible to give online support from your end and will play for that

**Comment by reddeppa-eddala** [comment]
HI, 

Any PIKVM device would suggest  where public net work should support without tail scale 

Regards, 
Reddeppa

**Comment by mdevaev** [comment]
Online support is provided in the chat, I gave you the link earlier (https://discord.gg/bpmXfz5). PLease use the web browser and ask a question there.

**Comment by reddeppa-eddala** [comment]
Thank you so much for your support. Now i am able to login with public network using tail scale. however  the tailscale is required to install in the laptop but my office laptop is not allowing to install the tail scale to due to some restrictions.

Instead of Tail scale, is it possible to use TeamViewer . Please confirm. if yes please share the steps 

Regards, 
Reddeppa

**Comment by mdevaev** [comment]
You can't use TeamViewer for this.

**Comment by reddeppa-eddala** [comment]
Other than Tailscale, Any other software will support ?

Whenever i want to connect with public IP, Is tail scale must be installed in the laptop?

**Comment by mdevaev** [comment]
Please, use the chat for support questions. Github is only for development and bug reports.

**Comment by reddeppa-eddala** [comment]
Please send the link for chat

**Comment by mdevaev** [comment]
I gave you the link twice, see above.
