### ISSUE TITLE
PIKVM support requested. In addition can't log to discord

### ISSUE THREAD

**Issue by frenchyinmunich** [pikvm/pikvm#1374]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by frenchyinmunich** [comment]
Hello,
I have bought a PiKVM kit V4. It is mounted and now, I would like to have some support to correctly flash etc...
I feel lost. In addition it is impossible to log on the Discord chat.
Could you please help me?
Thanks,
Francois

**Comment by mdevaev** [comment]
V4 is a ready-made device. What kit did you buy? Please take a photo.

**Comment by frenchyinmunich** [comment]
Could I call you please?Thel ist of component I bought is attached
    Am Donnerstag, 25. Juli 2024, 11:26:44 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


V4 is a ready-made device. What kit did you buy? Please take a photo.

**Comment by mdevaev** [comment]
Github doesn't handle attaches. Please copy here.

**Comment by frenchyinmunich** [comment]
Am Donnerstag, 25. Juli 2024, 11:48:27 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Github doesn't handle attaches. Please copy and paste here.

**Comment by frenchyinmunich** [comment]
can I call U?
    Am Donnerstag, 25. Juli 2024, 11:48:27 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Github doesn't handle attaches. Please copy and paste here.

**Comment by mdevaev** [comment]
We provide support only in the discord. At least in the github.

**Comment by frenchyinmunich** [comment]
But your invitation is refused
    Am Donnerstag, 25. Juli 2024, 12:17:53 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


We provide support only in the discord. At least in the github.

**Comment by frenchyinmunich** [comment]
It says the invitation can't be accepted.Why?
    Am Donnerstag, 25. Juli 2024, 12:17:53 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


We provide support only in the discord. At least in the github.

**Comment by frenchyinmunich** [comment]
Here is the reason I can't connect:Invalid Invite Links


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Invalid Invite Links

Let me innnnnnn! You finally got an invite to a server, but you’re getting hit with an error message and can’t j...
 |

 |

 |




    Am Donnerstag, 25. Juli 2024, 12:17:53 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


We provide support only in the discord. At least in the github.

**Comment by frenchyinmunich** [comment]
Please help me
    Am Donnerstag, 25. Juli 2024, 12:17:53 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


We provide support only in the discord. At least in the github.

**Comment by mdevaev** [comment]
Take a photo of your kit here. Please use github interface for attaching photos, don't use email client.

**Comment by frenchyinmunich** [comment]
Am Donnerstag, 25. Juli 2024, 12:30:54 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Take a photo of your kit here. Please use github interface for attaching photos, don't use email client.

**Comment by mdevaev** [comment]
Please use github interface for attaching photos, don't use email client. I don't see your photos.

**Comment by frenchyinmunich** [comment]
![Uploading Bildschirmfoto 2024-07-19 um 08.31.21.png…]()

**Comment by frenchyinmunich** [comment]
just sent on GitHub
    Am Donnerstag, 25. Juli 2024, 12:42:02 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Please use github interface for attaching photos, don't use email client. I don't see your photos.

**Comment by frenchyinmunich** [comment]
<img width="1086" alt="Bildschirmfoto 2024-07-25 um 12 37 10" src="https://github.com/user-attachments/assets/965c767c-0bb4-4d13-ac4e-39e8b6a0e487">

**Comment by frenchyinmunich** [comment]
<img width="1284" alt="Bildschirmfoto 2024-07-25 um 12 34 36" src="https://github.com/user-attachments/assets/9f525f56-1974-453c-9c20-c6378b9a8269">

**Comment by frenchyinmunich** [comment]
<img width="1084" alt="Bildschirmfoto 2024-07-25 um 12 19 05" src="https://github.com/user-attachments/assets/10bb29d9-3e36-4499-b781-e68f11aaf0d0">

**Comment by frenchyinmunich** [comment]
![Uploading Bildschirmfoto 2024-07-25 um 11.45.40.png…]()

**Comment by frenchyinmunich** [comment]
<img width="852" alt="Bildschirmfoto 2024-07-25 um 11 43 28" src="https://github.com/user-attachments/assets/ecd9815c-6677-406c-9393-7c68e9e357cd">

**Comment by frenchyinmunich** [comment]
<img width="571" alt="Bildschirmfoto 2024-07-24 um 21 09 33" src="https://github.com/user-attachments/assets/ec3e334c-0983-4deb-893d-59a009ce1c57">

**Comment by frenchyinmunich** [comment]
![Uploading Bildschirmfoto 2024-07-19 um 08.31.21.png…]()

**Comment by mdevaev** [comment]
I asked our support team to help you.

**Comment by frenchyinmunich** [comment]
Please, tell them to hurry up
    Am Donnerstag, 25. Juli 2024, 13:32:49 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


I asked our support team to help you.

**Comment by frenchyinmunich** [comment]
Hi, can the support team contact me please?
    Am Donnerstag, 25. Juli 2024, 13:32:49 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


I asked our support team to help you.

**Comment by mdevaev** [comment]
Please wait.

**Comment by frenchyinmunich** [comment]
I understand, but I need the device to work.

    Am Donnerstag, 25. Juli 2024, 14:15:32 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Please wait.

**Comment by frenchyinmunich** [comment]
for my job
    Am Donnerstag, 25. Juli 2024, 14:15:32 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Please wait.

**Comment by frenchyinmunich** [comment]
and why I can't use discord?what a stress!
    Am Donnerstag, 25. Juli 2024, 14:15:32 MESZ hat Maxim Devaev ***@***.***> Folgendes geschrieben:  
 
 


Please wait.

**Comment by mdevaev** [comment]
Until support has contacted you, you can try to follow the guide carefully: https://docs.pikvm.org/v3/

**Comment by arch1mede** [comment]
Hi, github is not used for support, please join discord for [live chat](https://discord.gg/bpmXfz5). What you bought and what you are describing is not the same so we need to clarification.

**Comment by arch1mede** [comment]
All of your discord pics are broken, so I cannot tell what the issue is.

**Comment by frenchyinmunich** [comment]
Please, consider what I have bought
    Am Donnerstag, 25. Juli 2024, 16:16:55 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


Hi, github is not used for support, please join discord for live chat. What you bought and what you are describing is not the same so we need to clarification.

**Comment by frenchyinmunich** [comment]
- UStId-Nr.: DE287421501 | WEEE-Reg.-Nr.: DE53739998    
Bundle bestehend aus Raspberry Pi 4 Modell B (4 GB), internationalemNetzteil (EU/UK/US/AU), PiKVM HAT und PiKVM Steel Case inkl.Montagematerial, OLED Display und Lüfter2409332-010Goobay Ethernet-Kabel 1m CAT610,92 €19%1,10 €CAT 6 Patchkabel, S/FTP (PiMF), schwarz, LSZH halogenfrei, Kupfer3409151Kühlkörpersatz11,09 €19%1,30 €Schwarz eloxierte Aluminium-Kühlkörper mit selbstklebendem Wärmeleitpadfür Raspberry Pi CPU und USB/LAN-IC4GB1-058572Goobay 58572 HDMI Kabel, HDMI 2.0 LC, 1,00m11,84 €19%2,19 €Series 2.0 LC High Speed HDMI Kabel mit Ethernet, 1 m, Schwarz -HDMI-Stecker (Typ A) > HDMI-Stecker (Typ A)5GB1-055468Goobay 55468 USB-C Kabel, USB 2.0, 1,80m13,02 €19%3,59 €USB 2.0 Kabel USB-C auf USB A, schwarz, 1.8 m - geeignet für Geräte mitUSB-C Anschluss6DHL Express DE116,72 €19%19,90 €7Voucher1-6,72 €19%-8,00 €Gesamtpreis netto241,24 €zzgl. 19% MwSt.45,84 €Gesamtpreis brutto287,08 €Zahlung PayPal Express, 17.07.2024-287,08 €offener Betrag0,00 €Fortsetzung auf Seite 2
   - Marco Wünschmann Haid-und-Neu-Str. 7 76131 Karlsruhe Germany fon +49 721 909819-90 mail ***@***.*** web www.welectron.com Haid-und-Neu-Str. 7  6131 Karlsruhe 

    Am Donnerstag, 25. Juli 2024, 16:19:46 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


All of your discord pics are broken, so I cannot tell what the issue is.

**Comment by frenchyinmunich** [comment]
What a nightmare, and I still can't connect to discord....
    Am Donnerstag, 25. Juli 2024, 16:19:46 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


All of your discord pics are broken, so I cannot tell what the issue is.

**Comment by arch1mede** [comment]
There is no other means of support for PiKVM other than Discord, I have considered what you have purchased but most would be cleared up over live chat.

**Comment by frenchyinmunich** [comment]
It is still impossible to connect to discord!!!!!
    Am Donnerstag, 25. Juli 2024, 16:46:10 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


There is no other means of support for PiKVM other than Discord, I have considered what you have purchased but most would be cleared up over live chat.

**Comment by arch1mede** [comment]
Please try on Chrome, incognito mode.

**Comment by arch1mede** [comment]
The only other option is to contact Welectron for support, they in turn can join Discord for assistance but most of what's needed should be in the [v3 document](https://docs.pikvm.org/v3/) and [First_steps document](https://docs.pikvm.org/first_steps/).

**Comment by frenchyinmunich** [comment]
I am connected to discordcould you please telle me now what should I do?
    Am Donnerstag, 25. Juli 2024, 16:57:52 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


The only other option is to contact Welectron for support, they in turn can join Discord for assistance but most of what's needed should be in the v3 document and First_steps document.

**Comment by arch1mede** [comment]
Please post your question in the #support channel.

**Comment by frenchyinmunich** [comment]
tell me your pseudo on discord please
    Am Donnerstag, 25. Juli 2024, 16:59:57 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


Please post your question in the #support channel.

**Comment by arch1mede** [comment]
To start off, post your question in the #support channel

**Comment by frenchyinmunich** [comment]
My account on Discord is: Polykobol
    Am Donnerstag, 25. Juli 2024, 17:02:24 MESZ hat arch1mede ***@***.***> Folgendes geschrieben:  
 
 


To start off, post your question in the #support channel

**Comment by arch1mede** [comment]
Seems you clicked on the wrong discord link, please use [this one](https://discord.gg/bpmXfz5).
