### ISSUE TITLE
DIY V2 should use cheaper "relay" / mosfet

### ISSUE THREAD

**Issue by kaitallaoua** [pikvm/pikvm#1376]
**Is your feature request related to a problem? Please describe.**
DIY V2 is my goto cost effective pikvm, since I source the parts myself. However the guide for atx control says to use G3VM-61AY1 which are 3.5 USD for quantity under 10 at digikey. If following the whole guide, that's ~$15 USD for what is a primative switch. Simply, these seem to be overkill. 

**Describe the solution you'd like**
The guide should replace them for whatever the in production variant of the 2n7000 series mosfet, at 1/5 the cost! For example, onsemi have a drain to source voltage of 60V max, same as the relays so it should be an effortless and safe switch. Also no resistors should be needed at all, since it's a mosfet. I can provide a diagram, it's even easier then the current, since there's no resistors. I've used this one 3 pikvms, various motherboards, works great. 

**Describe alternatives you've considered**
Im guessing the purpose of the relays was for simple, high compatibility, but I've yet to come across motherboards with the digital pin inputs being above 3.3v.

**Additional context**
In my builds I've only needed one mosfet, for power atx control, I don't specifically know about other pins, but they shouldnt be above 5v. Again, I only bothered making this since the DIY v2 is a great cost effective option that shouldn't be left in the dust!

**Comment by mdevaev** [comment]
Sup. We use relays for simplicity, so that users do not confuse the polarity of the buttons. Besides, the savings are not too significant. You can use any solution for yourself, but we prefer to have one way to make ATX because it makes it easier to support users.
