### ISSUE TITLE
Keyboard Lock isn't properly working on MacOS Host using either Chrome or Edge.

### ISSUE THREAD

**Issue by rudironsonijr** [pikvm/pikvm#1377]
**Describe the bug**
Keyboard Lock isn't properly working on MacOS Host using either Chrome or Edge.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Setup Keyboard Lock on Chrome or Edge flags
2. Install PiKVM as an App (Chrome or Edge)
3. Open the app
4. Put your KVM window in full screen
5. Test the Key Combos

**Expected behavior**
Key combinations like Cmd+Tab, Cmd+Space and other MacOS specific combos aren't being grabber by PiKVM Web Interface.

**Screenshots**
![CleanShot 2024-07-31 at 14 16 08@2x](https://github.com/user-attachments/assets/c099b7c7-d52d-4d96-a3b7-7e1ad84f09e5)

![CleanShot 2024-07-31 at 14 17 45@2x](https://github.com/user-attachments/assets/cc0509f9-7ed6-4721-8f56-66aa8286a6b9)

![CleanShot 2024-07-31 at 14 21 11@2x](https://github.com/user-attachments/assets/d7bef298-0611-4e74-9748-df93adb6215b)

![image](https://github.com/user-attachments/assets/71f2c3e4-493f-4333-bda1-514245e26f8b)

![image](https://github.com/user-attachments/assets/0e9bb508-578e-48c7-91ac-a068e459f391)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma and MacOS Sequoia
 - Browser: Chrome and Edge
 - Version 127.0.2651.74
 - ~VNC client (if used)~

**PiKVM info:**
  - Raspberry Pi 4 Model B Rev 1.5
  - PiKVM platform v3 (official)
  - kvmd 4.3-1
  - kvmd-fan 0.31-1
  - kvmd-oled 0.27-1
  - kvmd-platform-v3-hdmi-rpi4 4.3-1
  - kvmd-webterm 0.50-1
  - ustreamer 6.12-1
  - Linux kernel: Linux pikvm 6.6.21-4-rpi SMP Wed Mar 13 20:36:42 UTC 2024 armv7l GNU/Linux

**Additional context**
~Add any other context about the problem here.~

**Comment by rudironsonijr** [comment]
@mdevaev, may you please help with this?

**Comment by mdevaev** [comment]
Found a similar problem: https://github.com/novnc/noVNC/issues/1799

Yeah, it can't be fixed on our side properly, we will have to wait for the fix in the browsers.
