### ISSUE TITLE
Adding AI to PiKVM

### ISSUE THREAD

**Issue by mareksagan** [pikvm/pikvm#1379]
**Is your feature request related to a problem? Please describe.**
I am interested if hosting a small LLM such as LLama 3 8B that the user would be able to use from the context menu would work fast without affecting the performance of the video stream.

**Describe the solution you'd like**
An LLM chat available from the context menu to check something quickly without Googling... Maybe integration with ChatGPT API would be nice too.

**Describe alternatives you've considered**
None.

**Additional context**
Thank you for considering my request.

**Comment by mdevaev** [comment]
Nonono. ChatGPT can be opened in the next tab, and I don't think users will be happy with integration for everyone. Personally, I don't find it useful at all.
