### ISSUE TITLE
Tests fail if `/etc/kvmd/main.yaml` does not exist

### ISSUE THREAD

**Issue by rhoriguchi** [pikvm/pikvm#1382]
**Describe the bug**
I'm trying to package `kvmd` for nix but I'm facing the issue that tests cannot run if no `/etc/kvmd/main.yaml` exists even if the tests have nothing to do with that file.

<details>
    <summary>Example error</summary>

    ___________________________________ test_ok ____________________________________

    arg = '/etc/kvmd/main.yaml', type = 'reg'
    name = 'absolute path to existent file'

        def valid_abs_path(arg: Any, type: str="", name: str="") -> str:  # pylint: disable=redefined-builtin
            if type:
                if not name:
                    name = f"absolute path to existent {type}"
                type = {
                    "file": "reg",
                    "dir": "dir",
                    "link": "lnk",
                    "sock": "sock",
                    "fifo": "fifo",
                    "char": "chr",
                    "block": "blk",
                }[type]
            else:
                if not name:
                    name = "absolute path"
        
            arg = os.path.abspath(valid_stripped_string_not_empty(arg, name))
        
            if type:
                try:
    >               st = os.stat(arg)
    E               FileNotFoundError: [Errno 2] No such file or directory: '/etc/kvmd/main.yaml'

    kvmd/validators/os.py:57: FileNotFoundError

    During handling of the above exception, another exception occurred:

    self = ArgumentParser(prog='kvmd-cleanup', usage=None, description='Kill KVMD and clear resources', formatter_class=<class 'argparse.ArgumentDefaultsHelpFormatter'>, conflict_handler='error', add_help=True)
    action = _StoreAction(option_strings=['-c', '--config'], dest='config', nargs=None, const=None, default='/etc/kvmd/main.yaml', ...unction valid_abs_file at 0x7ffff54b2520>, choices=None, required=False, help='Set config file path', metavar='<file>')
    arg_string = '/etc/kvmd/main.yaml'

        def _get_value(self, action, arg_string):
            type_func = self._registry_get('type', action.type, action.type)
            if not callable(type_func):
                msg = _('%r is not callable')
                raise ArgumentError(action, msg % type_func)
        
            # convert the value to the appropriate type
            try:
    >           result = type_func(arg_string)

    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:2565: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    kvmd/validators/os.py:68: in valid_abs_file
        return valid_abs_path(arg, type="file", name=name)
    kvmd/validators/os.py:59: in valid_abs_path
        raise_error(arg, f"{name}: {err}")
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    arg = '/etc/kvmd/main.yaml'
    name = "absolute path to existent file: [Errno 2] No such file or directory: '/etc/kvmd/main.yaml'"
    hide = False

        def raise_error(arg: Any, name: str, hide: bool=False) -> NoReturn:
            arg_str = " "
            if not hide:
                arg_str = (f" {arg!r} " if isinstance(arg, (str, bytes)) else f" '{arg}' ")
    >       raise ValidatorError(f"The argument{arg_str}is not a valid {name}")
    E       kvmd.validators.ValidatorError: The argument '/etc/kvmd/main.yaml' is not a valid absolute path to existent file: [Errno 2] No such file or directory: '/etc/kvmd/main.yaml'

    kvmd/validators/__init__.py:47: ValidatorError

    During handling of the above exception, another exception occurred:

    self = ArgumentParser(prog='kvmd-cleanup', usage=None, description='Kill KVMD and clear resources', formatter_class=<class 'argparse.ArgumentDefaultsHelpFormatter'>, conflict_handler='error', add_help=True)
    args = ['kvmd-cleanup', '--run']
    namespace = Namespace(config='/etc/kvmd/main.yaml', set_options=[], dump_config=False, run=True)

        def parse_known_args(self, args=None, namespace=None):
            if args is None:
                # args default to the system args
                args = _sys.argv[1:]
            else:
                # make sure that args are mutable
                args = list(args)
        
            # default Namespace built from parser defaults
            if namespace is None:
                namespace = Namespace()
        
            # add any action defaults that aren't present
            for action in self._actions:
                if action.dest is not SUPPRESS:
                    if not hasattr(namespace, action.dest):
                        if action.default is not SUPPRESS:
                            setattr(namespace, action.dest, action.default)
        
            # add any parser defaults that aren't present
            for dest in self._defaults:
                if not hasattr(namespace, dest):
                    setattr(namespace, dest, self._defaults[dest])
        
            # parse the arguments and exit if there are any errors
            if self.exit_on_error:
                try:
    >               namespace, args = self._parse_known_args(args, namespace)

    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:1929: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:2175: in _parse_known_args
        self._get_value(action, action.default))
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = ArgumentParser(prog='kvmd-cleanup', usage=None, description='Kill KVMD and clear resources', formatter_class=<class 'argparse.ArgumentDefaultsHelpFormatter'>, conflict_handler='error', add_help=True)
    action = _StoreAction(option_strings=['-c', '--config'], dest='config', nargs=None, const=None, default='/etc/kvmd/main.yaml', ...unction valid_abs_file at 0x7ffff54b2520>, choices=None, required=False, help='Set config file path', metavar='<file>')
    arg_string = '/etc/kvmd/main.yaml'

        def _get_value(self, action, arg_string):
            type_func = self._registry_get('type', action.type, action.type)
            if not callable(type_func):
                msg = _('%r is not callable')
                raise ArgumentError(action, msg % type_func)
        
            # convert the value to the appropriate type
            try:
                result = type_func(arg_string)
        
            # ArgumentTypeErrors indicate errors
            except ArgumentTypeError as err:
                msg = str(err)
                raise ArgumentError(action, msg)
        
            # TypeErrors or ValueErrors also indicate errors
            except (TypeError, ValueError):
                name = getattr(action.type, '__name__', repr(action.type))
                args = {'type': name, 'value': arg_string}
                msg = _('invalid %(type)s value: %(value)r')
    >           raise ArgumentError(action, msg % args)
    E           argparse.ArgumentError: argument -c/--config: invalid valid_abs_file value: '/etc/kvmd/main.yaml'

    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:2577: ArgumentError

    During handling of the above exception, another exception occurred:

        def test_ok() -> None:
            _ = Literal  # Makes liters happy
            queue: "multiprocessing.Queue[Literal[True]]" = multiprocessing.Queue()
        
            def ustreamer_fake() -> None:
                setproctitle.setproctitle("kvmd/streamer: /usr/bin/ustreamer")
                queue.put(True)
                while True:
                    time.sleep(1)
        
            proc = multiprocessing.Process(target=ustreamer_fake, daemon=True)
            proc.start()
            assert queue.get(timeout=5)
        
            assert proc.is_alive()
    >       main(["kvmd-cleanup", "--run"])

    testenv/tests/apps/cleanup/test_main.py:49: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    kvmd/apps/cleanup/__init__.py:60: in main
        config = init(
    kvmd/apps/__init__.py:136: in init
        (options, remaining) = parser.parse_known_args(argv)
    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:1931: in parse_known_args
        self.error(str(err))
    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:2665: in error
        self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    self = ArgumentParser(prog='kvmd-cleanup', usage=None, description='Kill KVMD and clear resources', formatter_class=<class 'argparse.ArgumentDefaultsHelpFormatter'>, conflict_handler='error', add_help=True)
    status = 2
    message = "kvmd-cleanup: error: argument -c/--config: invalid valid_abs_file value: '/etc/kvmd/main.yaml'\n"

        def exit(self, status=0, message=None):
            if message:
                self._print_message(message, _sys.stderr)
    >       _sys.exit(status)
    E       SystemExit: 2

    /nix/store/l014xp1qxdl6gim3zc0jv3mpxhbp346s-python3-3.12.4/lib/python3.12/argparse.py:2652: SystemExit
    ----------------------------- Captured stderr call -----------------------------
    usage: kvmd-cleanup [-h] [-c <file>] [-o <k=v> [<k=v> ...]] [-m] [--run]
    kvmd-cleanup: error: argument -c/--config: invalid valid_abs_file value: '/etc/kvmd/main.yaml'
</details>

<details>
    <summary>Side note, one test also fails if there's no `/root` dir</summary>

    __________________ test_ok__valid_abs_path__dir[/root-/root] ___________________

    arg = '/root', type = 'dir', name = 'absolute path to existent dir'

        def valid_abs_path(arg: Any, type: str="", name: str="") -> str:  # pylint: disable=redefined-builtin
            if type:
                if not name:
                    name = f"absolute path to existent {type}"
                type = {
                    "file": "reg",
                    "dir": "dir",
                    "link": "lnk",
                    "sock": "sock",
                    "fifo": "fifo",
                    "char": "chr",
                    "block": "blk",
                }[type]
            else:
                if not name:
                    name = "absolute path"
        
            arg = os.path.abspath(valid_stripped_string_not_empty(arg, name))
        
            if type:
                try:
    >               st = os.stat(arg)
    E               FileNotFoundError: [Errno 2] No such file or directory: '/root'

    kvmd/validators/os.py:57: FileNotFoundError

    During handling of the above exception, another exception occurred:

    arg = '/root', retval = '/root'

        @pytest.mark.parametrize("arg, retval", [
            ("/..",          "/"),
            ("/root/..",     "/"),
            ("/root",        "/root"),
            (".",            os.path.abspath(".")),
        ])
        def test_ok__valid_abs_path__dir(arg: Any, retval: str) -> None:
    >       assert valid_abs_path(arg, type="dir") == retval

    testenv/tests/validators/test_os.py:65: 
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    kvmd/validators/os.py:59: in valid_abs_path
        raise_error(arg, f"{name}: {err}")
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    arg = '/root'
    name = "absolute path to existent dir: [Errno 2] No such file or directory: '/root'"
    hide = False

        def raise_error(arg: Any, name: str, hide: bool=False) -> NoReturn:
            arg_str = " "
            if not hide:
                arg_str = (f" {arg!r} " if isinstance(arg, (str, bytes)) else f" '{arg}' ")
    >       raise ValidatorError(f"The argument{arg_str}is not a valid {name}")
    E       kvmd.validators.ValidatorError: The argument '/root' is not a valid absolute path to existent dir: [Errno 2] No such file or directory: '/root'

    kvmd/validators/__init__.py:47: ValidatorError
</details>

**To Reproduce**
Steps to reproduce the behavior, like:
1. checkout https://github.com/rhoriguchi/nixpkgs/commit/8f099ebac3cb61287cd4239638d3b580b5b962d5
2. cd in to `nixpkgs` dir
3. run `nix-build -A python312Packages.kvmd`
4. find line with `For full logs, run 'nix log /nix/store/0r4a48527pp10x85jrdzga6grx2pbnq1-python3.12-kvmd-4.2.drv'.`
5. [log output](https://github.com/user-attachments/files/16576676/logs.txt)

**Expected behavior**
Tests should run without `/etc/kvmd/main.yaml`.

**Desktop (please complete the following information):**
 - OS: NixOS

**PiKVM info:**
  - KVMD version: 4.2
  - uStreamer version: 6.12
  - Linux kernel: 6.10.2

**Additional context**
Tests should not depend on files in the environment.

**Comment by mdevaev** [comment]
Hello. Tests can only work inside the container because many involve changes to the OS. They are not supposed to be launched when creating a package. So the main.yaml is not the only thing you will encounter if you try to do this. I recommend skipping the tests.

**Comment by rhoriguchi** [comment]
Hi @mdevaev, thx for the reply. I try to get as many tests to run as possible to give me more confidence that an update won't break anything. Pytest does offer a fixture to test stuff that requires paths <https://docs.pytest.org/en/stable/how-to/tmp_path.html>. If you don't wish to address this, please close the issue and I'll just exclude all tests that fail.

I've already excluded this test since it calls `chpasswd` and `chpasswd`.
```
  disabledTestPaths = [
    # uses fixture that calls `chpasswd` and `useradd`
    "testenv/tests/plugins/auth/test_pam.py"
  ];
  ```

**Comment by mdevaev** [comment]
I checked it again. This file is required for some integration tests, as well as the rest of the configuration in testenv, so the fixture will not help here.
