### ISSUE TITLE
Mass Storage not working on HP ProDesk 600 G3 DM

### ISSUE THREAD

**Issue by Mastersomy** [pikvm/pikvm#1387]
**Describe the bug**
I have 3 HP ProDesk 600 G3 DM in a rack where a PiKVM with a raspbery pi 4 and the kit from geekworm that tey call KVM-A3 witch is to my understanding based on the pikvm v3.

this is a Test lab for me to lern on so i want to use the pikvm to install new OS reletivly often. 
i now have the problem, that i cannot use the keyboard in the bios.
i found the issue https://github.com/pikvm/pikvm/issues/410 where it was said to disable mass storage via the /etc/kvmd/override.yaml file. 
after i did that i could use the keyboard in the bios. 
but i need the mass storage to reinstall the OS in the test lab. so i would need the mass storage support working. 

I installed pikvmm with the PiKVM V3 HAT BOX Image, OLED/FAN preactivated immage from your wiki and used the updater to update evrything and i activated the hdmi audio support using your guide.
i have tested on another system that uses a gigabyte mainboard and that is working without issues.

**Comment by mdevaev** [comment]
Hello. We support only DIY devices and our official V3 and V4 hardware. You should contact the seller for technical support.
