### ISSUE TITLE
ssh_dispatch_run_fatal during pikvm-update & inaccessible after update via ssh

### ISSUE THREAD

**Issue by uforek** [pikvm/pikvm#1396]
Fresh PiKVM on a RPi Zero 2W, during pikvm-update, intermittent "ssh_dispatch_run_fatal" resulting in a disconnect. Solved this by running pikvm-update with screen.

After update is complete, the device becomes unreachable. Does not reestablished wifi connection - confirmed by pinging ip, checking DHCP leases. Haven't tried serial or USB comms. Halp.

**Comment by mdevaev** [comment]
I've updated images on the site, please try the new image.
