### ISSUE TITLE
Shadowcast 2 Support

### ISSUE THREAD

**Issue by eychei** [pikvm/pikvm#1399]
**Describe the solution you'd like**
The new Shadowcast 2 has a USB3 interface and very low latency. Supporting this would maybe reduce overall latency.

**Comment by mdevaev** [comment]
This is a similar UVC capture with JPEG compression and same latency: https://www.youtube.com/watch?v=NXRSxDYyhoI

If you plan to use it, you can contact us at Discord and I will help you set it up (if it is supported) and make patches. Otherwise, I don't see the point in supporting it.

**Comment by mdevaev** [comment]
The user reports that `v2-hdmiusb-rpi4` works here. Nothing to do then.
