### ISSUE TITLE
LED state reported only one time

### ISSUE THREAD

**Issue by tomiko23lol** [pikvm/pikvm#1405]
Hello I configured view that way that my header contains LEDs and when I click on this header it should be expanded with the same LED states, just with buttons to control it next to it.
Problem is that LED state is displayed only once. When I have it in Header, it is not reported in table. As both LED displays are the same thing, I would suspect that both should show the same thing at the same time ...

![image](https://github.com/user-attachments/assets/3e6b9051-18f2-44e3-9af0-c79b8590eae6)

Here is my configuration:

![image](https://github.com/user-attachments/assets/99ed5b45-8119-4340-922b-06f14d857273)

**Expected behavior**
I would expect that if I put in status of the same led 10 times, it will works 10 times the same way.

**PiKVM info:**
  - Raspberry Pi zero 2 w
  - 8 GPIO inputs (for LEDs) + 8 GPIO outputs (as button controls)
  - Video capture CSI bridge C790

**Comment by mdevaev** [comment]
Confirmed. I'll fix it soon.

**Comment by mdevaev** [comment]
Fixed. Please update OS.

**Comment by tomiko23lol** [comment]
It works now, thank You very much :) 

![image](https://github.com/user-attachments/assets/1aa55044-6f5a-445c-aafe-82311280c11f)

**Comment by mdevaev** [comment]
:ok_hand:
