### ISSUE TITLE
Macro Recorder: Pasting a text with german keymap setting in the pasting window is recorded with a different encoded characters

### ISSUE THREAD

**Issue by devz3r0** [pikvm/pikvm#1407]
**Describe the bug**

if you record the macro and paste a text with german keymap (and the according setting in the pasting tool), then replay the macro, the characters are swapped to different variants at the place where the german ones are.
Manually typing the wanted character on the same space at the keyboard works fine.
The pasting tool itself works fine too.

**To Reproduce**
Steps to reproduce the behavior, like:
1. start record a macro
2. paste a text in de keymap mode with a character f.e.  &&  and Y and run it
3. stop the macro
4. replay the macro
5. && gets changed to // and Y to Z 

**Expected behavior**
&& stays && and Y stay as Y

**Screenshots**

(https://s3.amazonaws.com/i.snag.gy/14InK9.jpg)
**Desktop (please complete the following information):**
 - OS: Linux 6.11.0-6-MANJARO  
 - Browser firefox
 - Version 130

**PiKVM info:**
  - Raspberry Pi board version 4
  - PiKVM platform v3
  - Video capture type : h264
  - KVMD version: 

 kvmd 4.16-1
kvmd-fan 0.31-1
kvmd-platform-v3-hdmi-rpi4 4.16-1
kvmd-webterm 0.50-1

  - uStreamer version: ustreamer 6.16-1 
  - Linux kernel: Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Fixed. Please update OS.
