### ISSUE TITLE
Custom Resolution

### ISSUE THREAD

**Issue by chchia** [pikvm/pikvm#1409]
**Is your feature request related to a problem? Please describe.**
I have a machine which running with non-standard custom resolution, at 1056x1116. i tried to change it in main.yaml but it doesnt seem to support it. i am using DIYv2 with USB capture dongle.

**Describe the solution you'd like**
supporting a custom resolution with correct display ratio will be appreciated.

![image](https://github.com/user-attachments/assets/a5188517-d6f9-49e8-8f56-e8d20ee71fef)

**Comment by chchia** [comment]
thank you, although i can now set custom resolution, however the aspect ratio still cant be changed.

![image](https://github.com/user-attachments/assets/bdc5c33d-ae0f-466a-821d-ac13df5f5a38)

**Comment by mdevaev** [comment]
Try to calculate the correct screen ratio and use it as a fake resolution.

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
Closing due no feedback.
