### ISSUE TITLE
Error after updating - "Can't find CEA extension" - no video capture

### ISSUE THREAD

**Issue by sgtwtf** [pikvm/pikvm#1410]
**Describe the bug**
Updated the PiKVM-v4Plus and after im getting no video capture.
Moved to terminal to try and reset video using kvmd-edidconf --import-preset=v4plus results in an error message 
`Traceback (most recent call last):
  File "/usr/bin/kvmd-edidconf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/kvmd/apps/edidconf/__init__.py", line 128, in main
    edid = Edid.from_file(options.edid_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/kvmd/edid.py", line 96, in from_file
    assert (data[_CEA + 0], [_CEA + 1]) == (0x02, 0x03), "Can't find CEA extension"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Can't find CEA extension`

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to terminal
2. Run **any** kvmd-edidconf command (including just the command itself)
3. See error

**Expected behavior**
If I run kvmd-edidconf I expect to see no errors 

**Screenshots**
![image](https://github.com/user-attachments/assets/1ad00540-c38c-4b58-940f-d9001285ab41)

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: Edge
 - Version 10.0.22631.4169
 -  - VNC client NA

**PiKVM info:**
  - Raspberry Pi board version RPi 4
  - PiKVM platform v-4plus
  - Video capture type [e.g. CSI bridge]
  - KVMD version: `4.17-1`
  - uStreamer version: `6.16-1`
  - Linux kernel: `Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux`

**Additional context**
none

**Comment by mdevaev** [comment]
Fixed, please update OS.
