### ISSUE TITLE
Stream doesnt auto adapt on macbook air monitors

### ISSUE THREAD

**Issue by ta-yuhyeon** [pikvm/pikvm#1411]
**Describe the bug**
I tried to override the pikvm settings by using a specific override.yml file,
hdmi:
  resolutions:
    - 1470x956

**To Reproduce**
Steps to reproduce the behavior, like:
1. Connect to your raspberry
2. Type rw then go to folder /etc/kvmd/
3. Put the yaml shown above
4. Restart kvmd service with systemctl restart kvmd

**Expected behavior**

I was expecting that ones pressed the full screen options on both chrome and the pikvm gui it would expand to fit the entire screen but that didnt happen.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: Chrome
 - Version: 129.0.06668.71

**PiKVM info:**
  - Raspberry Pi board version: RPi 4
  - PiKVM platform: v4
  - KVMD version:
kvmd 4.10-1
kvmd-fan 0.31-1
kvmd-oled 0.27-1
kvmd-platform-v3-hdmi-rpi4 4.10-1
kvmd-webterm 0.50-1

  - uStreamer version: ustreamer 6.14-1
  - Linux kernel: Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux

**Additional context**

**Comment by mdevaev** [comment]
Sorry, I don't understand anything. If you're using V4, the resolution settings is not applieble. Are you sure that you using V4? Also please attach some screenshots and take a photo of your device.

**Comment by mdevaev** [comment]
Sup?

**Comment by ta-yuhyeon** [comment]
sorry for late reply,

this is what i mean:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/58f217ba-cb4c-48ad-b2fa-3ee9e52ca1c6">

when going full screen mode thisi s what happens:

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/af4c7f86-f6bf-4fb9-8812-61e52757dba4">

see the black margin? is there any way to stretch the stream to fit the whole screen without those black margin?

<img width="1466" alt="image" src="https://github.com/user-attachments/assets/9c971b2d-d1a4-478d-adcd-bacbd0589633">

**Comment by mdevaev** [comment]
Click the dot button
![image](https://github.com/user-attachments/assets/e1d6b05f-de71-434a-a1aa-17500de6c0a7)

**Comment by ta-yuhyeon** [comment]
yes sir, i already tried the dot button but that's not what im looking for i was hoping to somehow change the settings to make the stream fit the whole screen of my macbook air with the button "go to full-screen mode" :
<img width="279" alt="image" src="https://github.com/user-attachments/assets/1e2be995-d5fc-468f-96bf-c010c1f4b89c">
i even tried to change the fake resolution by setting this configuration:
vmd:
    streamer:
        cmd_append: [--fake-resolution=1920x1080]

**Comment by mdevaev** [comment]
Ah. I think I know what the problem is. Take a screenshot of the monitor settings in macOS

**Comment by ta-yuhyeon** [comment]
here is the monitor settings:
<img width="464" alt="image" src="https://github.com/user-attachments/assets/291b1c8b-6dc1-4ab1-aebc-63318b969459">

**Comment by mdevaev** [comment]
What about PiKVM display?

**Comment by ta-yuhyeon** [comment]
here's the pikvm display settings on the laptop connected to the pikvm:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/161e2030-a7a0-479b-a196-e96b7b0ee0ee">

**Comment by mdevaev** [comment]
I don't understand again. Why you have 1470x956, why you have desktop resolutions 1920x1080? Which KVM device exactly do you use? Please take a photo.

**Comment by ta-yuhyeon** [comment]
This is my pikvm device:
![image](https://github.com/user-attachments/assets/d11f91ab-1271-41b8-9fa9-543b8dbb9357)

**Comment by mdevaev** [comment]
That is, you said that it was an V4 (with v3 image)-hdmi) and I tried to help you, but it turned out that it was not only not V3 and V4, but not PiKVM hardware at all. We don't support clones.

**Comment by mdevaev** [comment]
My only advice is set up desired resolution without scaling on the source host. You can't change it on the client side. This is not a bug.
