### ISSUE TITLE
PiKVM v4 show No Video Signal on BIOS menu for Dell Latitude 5330 and Dell latitude 5320 

### ISSUE THREAD

**Issue by Phoenix103105** [pikvm/pikvm#1412]
**Describe the bug**
PiKVM v4 show No Video Signal on BIOS menu for Dell Latitude 5330 and Dell latitude 5320 . Display is visible on KVM from the windows logo bootup but not able to see any bios option. Any suggestion will be greatly appreciated. Thanks

**Comment by mdevaev** [comment]
Check the behavior with the external display. Some laptops simply do not give the BIOS to another screen other than the built-in one.

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
Closing due no feedback.
