### ISSUE TITLE
Discord Invite Link Expired

### ISSUE THREAD

**Issue by gabefair** [pikvm/pikvm#1414]
**Describe the bug**
When using github issues and submitting a new issue, the user is taken to a screen to navigate to the correct place to seek help. The discord link to ask a question is expired.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to 'https://github.com/pikvm/pikvm/issues/new/choose'
2. Click on 'Open'

**Screenshots**
![Screenshot 2024-10-11 at 17 58 08](https://github.com/user-attachments/assets/450af8c2-f0e0-4a9d-9e12-197e7b2c29d8)
![image](https://github.com/user-attachments/assets/34eed097-0308-4d66-9502-66132a7ddd7c)

**Additional context**

I wanted to know why the `rtl-sdr` package is needed in the default pikvm image.

**Comment by mdevaev** [comment]
Hi. The link is working. The reason is that sometimes discord has glitches locally. You can use the temporary link: https://discord.gg/HG4djY3a

About your question:

```
[root@pikvm ~]# pacman -Qi rtl-sdr
Name            : rtl-sdr
Version         : 1:2.0.2-1
Description     : Driver for Realtek RTL2832U, allowing general purpose software defined radio (SDR)
Architecture    : armv7h
URL             : https://osmocom.org/projects/rtl-sdr/wiki
Licenses        : GPL-2.0-only
Groups          : None
Provides        : None
Depends On      : glibc  libusb
Optional Deps   : None
Required By     : rng-tools
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 284.65 KiB
Packager        : Arch Linux ARM Build System <builder+xu2@archlinuxarm.org>
Build Date      : Mon Oct 7 09:23:36 2024
Install Date    : Fri Oct 11 15:52:33 2024
Install Reason  : Installed as a dependency for another package
Install Script  : Yes
Validated By    : Signature
```

> Required By     : rng-tools

It's for random number generator for cryptography.
