### ISSUE TITLE
pikvm-update powers off when --no-reboot flag is passed

### ISSUE THREAD

**Issue by afunix** [pikvm/pikvm#1421]
**Describe the bug**
pikvm-update powers off when --no-reboot flag is passed

**To Reproduce**
Steps to reproduce the behavior, like:
1. Execute `pikvm-update --no-reboot`

**Expected behavior**
PiKVM software is updated, PiKVM keeps running until manually rebooted.

**Screenshots**
```
# pikvm-update --no-reboot
...
==============================================================
      Power off requested. We will make it after 30 seconds.
            Press Ctrl+C if you don't want this.
==============================================================
```

**PiKVM info:**
  - RPi 4b
  - v3
  - KVMD version: kvmd 4.20-1
  - Linux kernel: Linux pikvm0 6.6.45-8-rpi #1 SMP Wed Oct  2 19:56:38 UTC 2024 armv7l GNU/Linux

**Additional context**
There is an incorrect check for `_opt_power_off` in the script, should be checked for `-n`:
```
while test "$#" != 0; do
    case "$1" in
...
        --no-reboot) _opt_no_reboot=1;;
        --power-off) _opt_power_off=1;;
        *) echo "Usage: pikvm-update [--no-reboot] [--power-off]"; exit 1;;
    esac
    shift
done

...


if [ -z "$_opt_no_reboot" ]; then
...
    sleep 30
    reboot
elif [ -z "$_opt_power_off" ]; then
...
    sleep 30
    poweroff
else

```

**Comment by mdevaev** [comment]
Should be fixed now.
