### ISSUE TITLE
Error Connecting to Janus Websocket

### ISSUE THREAD

**Issue by pjeugster** [pikvm/pikvm#1423]
**Describe the bug**
I am seeing an intermittent error in which the KVM terminal window displays an error message "Error Connecting to the Janus Websockets Server.  Is the Server Down?".

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to the IP address of my PiKVM
2. Log in with admin credentials
3. Click on "KVM"
4. See error message at top of screen

**Expected behavior**
If the host PC is off, I usually see "H.264 - Inactive"  message

**Screenshots**
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/fdd8b98a-ba88-4413-b767-01fc829079a2">

**Desktop (please complete the following information):**
 - OS: MacOS 14.7 (23H124)
 - Browser Chrome
 - Version  30.0.6723.117 (Official Build) (arm64)
 - VNC client (if used): n/a

**PiKVM info:**
  - Raspberry Pi board version  RPi 4
  - PiKVM platform v2-hdmi
  - Video capture type CSI bridge
  - KVMD version: 

kvmd 4.10-1
kvmd-fan 0.31-1
kvmd-oled 0.27-1
kvmd-platform-v2-hdmi-rpi4 4.10-1
kvmd-webterm 0.50-1

  - uStreamer version: ustreamer 6.14-1
  - Linux kernel: Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux

**Additional context**

**Comment by jesseadams** [comment]
Seriously?
