### ISSUE TITLE
PiKVM resolution error

### ISSUE THREAD

**Issue by asterissco** [pikvm/pikvm#1424]
**Describe the bug**
pikvm only see noise, or you don't see anything. Sometimes it works. others don't

**To Reproduce**
Start up

**Expected behavior**
show computer image
**Screenshots**

![pikvm_error_imagen](https://github.com/user-attachments/assets/077db39a-3e0e-4480-ba79-dd5924d5aa60)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser Chrome
 - Version 128.0.6613.137
 - VNC client (if used)

**PiKVM info:**
  - Raspberry RPi 4]
  - PiKVM platform v4mini
  - Video capture type [e.g. CSI bridge]
  - KVMD version: kvmd 4.20-1
  - uStreamer version: ustreamer 6.17-1
  - Linux kernel: Linux pikvm 6.6.45-8-rpi #1 SMP Wed Oct  2 19:56:38 UTC 2024 armv7l GNU/Linux

**Additional context**

**Comment by mdevaev** [comment]
Hello. This is a support question, please follow to discord: https://discord.gg/bpmXfz5
