### ISSUE TITLE
Set MSD writable from REST API

### ISSUE THREAD

**Issue by bjackman** [pikvm/pikvm#1428]
**Is your feature request related to a problem? Please describe.**

When it's emulated flash storage the MSD can be writable on read-only. This can be flipped in the UI. But I can't see a [documented](https://docs.pikvm.org/api/#set-msd-parameters) way to do that via REST. 

**Describe the solution you'd like**

Seems likely this is just a documentation gap. But if not I guess we just need a param like `read_only=0` or `writable=1`.

**Comment by bjackman** [comment]
Oh - https://github.com/pikvm/kvmd/blob/7394588279129bba8942323867a65bbc950d1396/kvmd/apps/kvmd/api/msd.py#L79

I think it's probably `rw=1`. Can try this later.

**Comment by bjackman** [comment]
Even better, I can try it right now. 

Raised this issue then figured it out within 3 minutes, maybe I should have just tried to figure it out first :laughing:

**Comment by mdevaev** [comment]
Thanks!
