### ISSUE TITLE
Does gpiozero work in pikvm?

### ISSUE THREAD

**Issue by libram11** [pikvm/pikvm#143]
I have python installed but none of the commands I'm aware of work to install gpiozero. I'm trying to add a simple safe shutdown button since im getting corruption on the fat portion of the sd card. Am I just missing something or is it not supported?

**Comment by mdevaev** [comment]
I don't understand, you can't install a library or so?

**Comment by libram11** [comment]
yes cant get gpiozero to even run, i dont have to use that library if there is already any support in the build for a shutdown button though. I tried apt-get, pacman, direct library download, none worked at all. It could also be my inexperience with arch linux. So if it should work thats all I need to know to keep trying :)

**Comment by mdevaev** [comment]
Gpiozero uses the deprecated kernel interface to gpio. I recommend you to use [libgpiod](https://git.kernel.org/pub/scm/libs/libgpiod/libgpiod.git/). Pi-KVM uses it for own purposes (ATX and other things). libgpiod has official python binding.

**Comment by libram11** [comment]
awesome ty
