### ISSUE TITLE
Fails to Display Startup Sequence GPU DVI Monitor is Connected

### ISSUE THREAD

**Issue by rman215** [pikvm/pikvm#1430]
Bug:
When using a PiKVM V3 connected via HDMI to a GPU that also has a monitor connected via DVI, the BIOS and startup screen default to the DVI output, and the PiKVM does not display anything. Disconnecting the DVI monitor allows the PiKVM to display properly. This suggests a conflict in output prioritization or EDID detection by the GPU during boot.

Reproduce:

1. Connect a monitor to the DVI port of a GPU and the PiKVM to the HDMI port of the same GPU.
2. Power on the system and attempt to access the BIOS/startup screen via the PiKVM.
3. Observe that the BIOS/startup screen is displayed on the DVI monitor, not on the PiKVM.
4. Disconnect the DVI monitor and restart the system.
5. Observe that the BIOS/startup screen now displays correctly on the PiKVM.

Expected behavior:
The PiKVM should display the BIOS and startup screen via HDMI, regardless of whether a monitor is connected to the DVI port. Both outputs should either mirror the display or prioritize the HDMI output where the PiKVM is connected.

Desktop:
 - Windows 10 pro 22HD
 - Chrome Browser Version 131.0.6778.86

PiKVM info:
   -PiKVM V3 HAT
   -Raspberry Pi 4 Model B 2019 Quad Core 64 Bit WiFi Bluetooth (4GB)
   -Running with the default settings, except for changing the admin password for root and web.

**Comment by mdevaev** [comment]
Hello. Prioritization is performed in the BIOS. PiKVM or the physical display cannot affect this. You can use adapters to connect DVI if it has a higher priority.

For any support questions, please contact our discord.
