### ISSUE TITLE
Setting EDID disables display.

### ISSUE THREAD

**Issue by s-c-p** [pikvm/pikvm#1434]
**Describe the bug**
If I try to set any EDID (except the preset ones) I don't get display, only `< NO SIGNAL >`.  
Even real EDIDs (not hand made or copied from [linuxhw/EDID](https://github.com/linuxhw/EDID)) don't work.

**To Reproduce**
The device I'd like to remote control is ThinkCenter M770q and I am using the HDMI to CSI converter (from v3 docs) on  RPi 4B 4 GB.

1. connected Thinkcenter to physical monitor using HDMI cable
2. on Thinkcenter ran `sudo monitor-get-edid > realEDID.bin`
3. disconnected Thinkcenter from physical monitor and connected Pi-KVM to it
4. on Pi-KVM ran `rw` as root (via SSH)
5. on Thinkcenter ran `scp realEDID.bin root@192.168.1.19:/root/realEDID.bin` (via SSH)
6. on Pi-KVM ran `kvmd-edidconf --import=/root/realEDID.bin --edid=/root/realEDID.hex --apply`
7. display lost - even if I copy the hex to `/etc/kvmd/tc358743-edid.hex` and reboot both machines - I don't get video

**Expected behavior**
Screen should be visible for EDIDs other than the presets.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 41 on Thinkcenter and v3-OLED on PiKVM
 - Browser Chromium and Firefox
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board **RPi 4B**
  - PiKVM platform **v3 with OLED**
  - Video capture type **HDMI to CSI circuit**
  - KVMD version: **4.10-1**
  - uStreamer version: **6.14-1**
  - Linux kernel: `Linux pikvm 6.6.45-7-rpi #1 SMP Mon Sep  2 09:16:27 UTC 2024 armv7l GNU/Linux`

**Additional context**

**Comment by mdevaev** [comment]
Hello.

You can't just set a random EDID. It will include video modes that are not available for V3, and most likely it will be 1080p@60Hz. This is a V3 hardware limitation, only 1080p@50Hz maximum is supported.

Anyway, it's a matter of support, please use our Discord chat for instant help and such questions :)
