### ISSUE TITLE
Documentation page for ATX control board has a cybersquatted link

### ISSUE THREAD

**Issue by GCustom** [pikvm/pikvm#1435]
**Describe the bug**
on https://docs.pikvm.org/atx_board/ the link for "7 Connect the ATX board to PiKVM using a [straight Ethernet cable with 8 wires](https://www.home-network-help.com/straight.html)." the link is being cybersquatted instead leading to a dot kr page written in Thai, it appears to be a gambling site.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to 'https://docs.pikvm.org/atx_board/'
2. Click on 'straight Ethernet cable with 8 wires'
3. wrong page appears

**Expected behavior**
detailed instructions or technical information about straight Ethernet cables appears

**Screenshots**
![image](https://github.com/user-attachments/assets/b9f9c92b-d365-416c-a20a-55857ade004d)

**Desktop (please complete the following information):**
 - OS: [MacOS 15.1.1]
 - Browser [Edge]
 - Version [131.0.2903.70 (Official build) (arm64)]
 - VNC client (N/A)

**PiKVM info:**
  - Raspberry Pi board version [PiKVM v4 Mini]
  - PiKVM platform [N/A]
  - Video capture type [N/A]
  - KVMD version: `pacman -Q | grep kvmd` N/A
  - uStreamer version: `pacman -Q | grep ustreamer` N/A
  - Linux kernel: `uname -a` N/A

**Additional context**
None

**Comment by mdevaev** [comment]
Thank you for reporting. Fixed.

**Comment by GCustom** [comment]
looks great now
