### ISSUE TITLE
Build breaks if password/key with trailing $ used

### ISSUE THREAD

**Issue by mnotgninnep** [pikvm/pikvm#144]
Somewhere between make and docker something is getting mangled if you try to use a password or network key with a trailing $ symbol. Let's say my password is Password1$, it drops the $ from the end and the trailing ' resulting in either errors or weird behaviour. I've tried escaping it and quoting in vaious ways, none of which have allowed the build to proceed. I should mention that passwords without a $ work and build fine.

I've tried the following combinations in config.mk:
WIFI_PASSWD = Password1$
Password1$$
Password1$$$$
Password1\$
Password1\$\$
All the above surrounded by " "
All the above surrounded by ' '
All the above surrounded by (backslash)" (backslash)"
All the above surrounded by (backslash)' (backslash)'

Results range from the sublime to the ridiculous:

Here is the output of 3 of the examples in increasing weirdness. I won't post all as they didn't vary much beyond this. Any way around there doesn't seem to be a way of escaping the $ to allow it to build this wifi network password.

BOARD = rpi3
PLATFORM = v0-hdmi
HOSTNAME = pikvm
LOCALE = en_GB
TIMEZONE = Europe/London
ROOT_PASSWD = Password1$
WEBUI_ADMIN_PASSWD = Password1$
IPMI_ADMIN_PASSWD = Password1$
WIFI_ESSID = mpennington
WIFI_PASSWD = Password1$

Gives the following ouput for make and docker. Note the missing $ and ' in the docker command line.

make -C ./.pi-builder os \
	NC= \
	BUILD_OPTS="  \
		--build-arg PLATFORM=v0-hdmi \
		--build-arg USTREAMER_VERSION=2.2-1 \
		--build-arg KVMD_VERSION=2.10-1 \
		--build-arg KVMD_WEBTERM_VERSION=0.35-1 \
		--build-arg WIFI_ESSID='mywifi' \
		--build-arg WIFI_PASSWD='Password1$' \
		--build-arg WIFI_IFACE='wlan0' \
		--build-arg ROOT_PASSWD='Password1$' \
		--build-arg WEBUI_ADMIN_PASSWD='Password1$' \
		--build-arg IPMI_ADMIN_PASSWD='Password1$' \
		--build-arg NEW_HTTPS_CERT=d582024c-38a9-4569-8c20-1557ba7e01c1 \
	" \
	PROJECT=pikvm-os-v0-hdmi \
	BOARD=rpi3 \
	STAGES='__init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__' \
	HOSTNAME=pikvm \
	LOCALE=en_GB \
	TIMEZONE=Europe/London \
	REPO_URL=http://de3.mirror.archlinuxarm.org

docker build \
		--rm \
		--tag pikvm-os-v0-hdmi-pi-builder-arm-result-rpi3 \
		 \
		 \
		--build-arg "BOARD=rpi3" \
		--build-arg "ARCH=arm" \
		--build-arg "LOCALE=en_GB" \
		--build-arg "TIMEZONE=Europe/London" \
		--build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
		--build-arg "PIKVM_REPO_URL=https://pikvm.org/repos" \
		--build-arg "PIKVM_REPO_KEY=912C773ABBD1B584" \
		--build-arg "REBUILD=065cccc3-4972-4e20-bae1-f39e3489dcf2" \
		--build-arg PLATFORM=v0-hdmi 		--build-arg USTREAMER_VERSION=2.2-1 		--build-arg KVMD_VERSION=2.10-1 		--build-arg KVMD_WEBTERM_VERSION=0.35-1 		--build-arg WIFI_ESSID='mywifi' 		--build-arg WIFI_PASSWD='Password1 		--build-arg WIFI_IFACE='wlan0' 		--build-arg ROOT_PASSWD='Password1 		--build-arg WEBUI_ADMIN_PASSWD='Password1 		--build-arg IPMI_ADMIN_PASSWD='Password1 		--build-arg NEW_HTTPS_CERT=d582024c-38a9-4569-8c20-1557ba7e01c1 	 \
	./.build

#############

BOARD = zerow
PLATFORM = v2-hdmi
HOSTNAME = pikvm
LOCALE = en_GB
TIMEZONE = Europe/London
ROOT_PASSWD = "Password1$$"
WEBUI_ADMIN_PASSWD = "Password1$$"
IPMI_ADMIN_PASSWD = "Password1$$"
WIFI_ESSID = mywifi
WIFI_PASSWD = "Password1$$"

Gives the following ouput for make and docker. Note the missing $ but we keep the ' in the docker command line this time.

ake -C ./.pi-builder os \
                NC= \
                BUILD_OPTS="  \
                                --build-arg PLATFORM=v2-hdmi \
                                --build-arg USTREAMER_VERSION=2.2-1 \
                                --build-arg KVMD_VERSION=2.9-1 \
                                --build-arg KVMD_WEBTERM_VERSION=0.35-1 \
                                --build-arg WIFI_ESSID='mywifi' \
                                --build-arg WIFI_PASSWD='"Password1$"' \
                                --build-arg WIFI_IFACE='wlan0' \
                                --build-arg ROOT_PASSWD='"Password1$"' \
                                --build-arg WEBUI_ADMIN_PASSWD='"Password1$"' \
                                --build-arg IPMI_ADMIN_PASSWD='"Password1$"' \
                                --build-arg NEW_HTTPS_CERT=b5801c3a-9d7b-4fb3-9937-4e609f79a303 \
                " \
                PROJECT=pikvm-os-v2-hdmi \
                BOARD=zerow \
                STAGES='__init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__' \
                HOSTNAME=pikvm \
                LOCALE=en_GB \
                TIMEZONE=Europe/London \
                REPO_URL=http://de3.mirror.archlinuxarm.org

Which in turn gives

docker build \
                                --rm \
                                --tag pikvm-os-v2-hdmi-pi-builder-arm-result-zerow \
                                \
                                \
                                --build-arg "BOARD=zerow" \
                                --build-arg "ARCH=arm" \
                                --build-arg "LOCALE=en_GB" \
                                --build-arg "TIMEZONE=Europe/London" \
                                --build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
                                --build-arg "PIKVM_REPO_URL=https://pikvm.org/repos" \
                                --build-arg "PIKVM_REPO_KEY=912C773ABBD1B584" \
                                --build-arg "REBUILD=66ba9994-ad6e-4e85-b871-34c430b0a2fa" \
                                --build-arg PLATFORM=v2-hdmi                 --build-arg USTREAMER_VERSION=2.2-1                                --build-arg KVMD_VERSION=2.9-1                               --build-arg KVMD_WEBTERM_VERSION=0.35-1                   --build-arg WIFI_ESSID='mywifi'                         --build-arg WIFI_PASSWD='Password1'                   --build-arg WIFI_IFACE='wlan0'                        --build-arg ROOT_PASSWD='Password1'                                --build-arg WEBUI_ADMIN_PASSWD='Password1'                   --build-arg IPMI_ADMIN_PASSWD='Password1'                  --build-arg NEW_HTTPS_CERT=b5801c3a-9d7b-4fb3-9937-4e609f79a303      \
                ./.build

#############

BOARD = zerow
PLATFORM = v2-hdmi
HOSTNAME = pikvm
LOCALE = en_GB
TIMEZONE = Europe/London
ROOT_PASSWD = Password1$$$$ 
WEBUI_ADMIN_PASSWD = Password1$$$$
IPMI_ADMIN_PASSWD = Password1$$$$
WIFI_ESSID = mywifi
WIFI_PASSWD = Password1$$$$

Gives the following ouput for make and docker. What gives? The last 5 digits after Password1 are random each time.

make -C ./.pi-builder os \
                NC= \
                BUILD_OPTS="  \
                                --build-arg PLATFORM=v2-hdmi \
                                --build-arg USTREAMER_VERSION=2.2-1 \
                                --build-arg KVMD_VERSION=2.9-1 \
                                --build-arg KVMD_WEBTERM_VERSION=0.35-1 \
                                --build-arg WIFI_ESSID='mywifi' \
                                --build-arg WIFI_PASSWD='Password1$$' \
                                --build-arg WIFI_IFACE='wlan0' \
                                --build-arg ROOT_PASSWD='Password1$$' \
                                --build-arg WEBUI_ADMIN_PASSWD='Password1$$' \
                                --build-arg IPMI_ADMIN_PASSWD='Password1$$' \
                                --build-arg NEW_HTTPS_CERT=993fa06e-7a68-465e-b9d5-15637c1778d4 \
                " \
                PROJECT=pikvm-os-v2-hdmi \
                BOARD=zerow \
                STAGES='__init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__' \
                HOSTNAME=pikvm \
                LOCALE=en_GB \
                TIMEZONE=Europe/London \
                REPO_URL=http://de3.mirror.archlinuxarm.org

Which in turn gives

docker build \
                                --rm \
                                --tag pikvm-os-v2-hdmi-pi-builder-arm-result-zerow \
                                \
                                \
                                --build-arg "BOARD=zerow" \
                                --build-arg "ARCH=arm" \
                                --build-arg "LOCALE=en_GB" \
                                --build-arg "TIMEZONE=Europe/London" \
                                --build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
                                --build-arg "PIKVM_REPO_URL=https://pikvm.org/repos" \
                                --build-arg "PIKVM_REPO_KEY=912C773ABBD1B584" \
                                --build-arg "REBUILD=0748ef75-e2de-42f3-ae01-0f81277a5787" \
                                --build-arg PLATFORM=v2-hdmi                 --build-arg USTREAMER_VERSION=2.2-1                                --build-arg KVMD_VERSION=2.9-1                               --build-arg KVMD_WEBTERM_VERSION=0.35-1                   --build-arg WIFI_ESSID='mywifi'                         --build-arg WIFI_PASSWD='Password131897'                       --build-arg WIFI_IFACE='wlan0'                        --build-arg ROOT_PASSWD='Password131897'                    --build-arg WEBUI_ADMIN_PASSWD='Password131897' --build-arg IPMI_ADMIN_PASSWD='Password131897'                            --build-arg NEW_HTTPS_CERT=241c2e08-c6e4-4444-a847-05180cd36ffe    \
                ./.build

**Comment by mdevaev** [comment]
With [this](https://github.com/pikvm/os/pull/10) patch it can work properly. Use double quotes for your password like `WIFI_PASSWD="test test test"`.

Remove `os` dir and checkout it again.

**Comment by mnotgninnep** [comment]
Thanks for taking a look. It's still not working right.

BOARD = zerow
PLATFORM = v2-hdmi
HOSTNAME = pikvm
LOCALE = en_GB
TIMEZONE = Europe/London
ROOT_PASSWD = "Password1$"
WEBUI_ADMIN_PASSWD = "Password1$"
IPMI_ADMIN_PASSWD = "Password1$"
WIFI_ESSID = mywifi
WIFI_PASSWD = "Password1$"

make -C ./.pi-builder os \
	NC= \
	BUILD_OPTS='  \
		--build-arg PLATFORM=v2-hdmi \
		--build-arg USTREAMER_VERSION=2.2-1 \
		--build-arg KVMD_VERSION=2.10-1 \
		--build-arg KVMD_WEBTERM_VERSION=0.35-1 \
		--build-arg WIFI_ESSID=mywifi \
		--build-arg WIFI_PASSWD="Password1 \
		--build-arg WIFI_IFACE=wlan0 \
		--build-arg ROOT_PASSWD="Password1 \
		--build-arg WEBUI_ADMIN_PASSWD="Password1 \
		--build-arg IPMI_ADMIN_PASSWD="Password1 \
		--build-arg NEW_HTTPS_CERT=4a9f83b7-e403-466b-a847-cd9370490429 \
	' \
	PROJECT=pikvm-os-v2-hdmi \
	BOARD=zerow \
	STAGES='__init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__' \
	HOSTNAME=pikvm \
	LOCALE=en_GB \
	TIMEZONE=Europe/London \
	REPO_URL=http://de3.mirror.archlinuxarm.org

docker build \
		--rm \
		--tag pikvm-os-v2-hdmi-pi-builder-arm-result-zerow \
		 \
		 \
		--build-arg "BOARD=zerow" \
		--build-arg "ARCH=arm" \
		--build-arg "LOCALE=en_GB" \
		--build-arg "TIMEZONE=Europe/London" \
		--build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
		--build-arg "PIKVM_REPO_URL=https://pikvm.org/repos" \
		--build-arg "PIKVM_REPO_KEY=912C773ABBD1B584" \
		--build-arg "REBUILD=f061d221-b454-4371-947c-b9d567a80df5" \
		\
	--build-arg PLATFORM=v2-hdmi \
	--build-arg USTREAMER_VERSION=2.2-1 \
	--build-arg KVMD_VERSION=2.10-1 \
	--build-arg KVMD_WEBTERM_VERSION=0.35-1 \
	--build-arg WIFI_ESSID=mywifi \
	--build-arg WIFI_PASSWD="Password1 \
	--build-arg WIFI_IFACE=wlan0 \
	--build-arg ROOT_PASSWD="Password1 \
	--build-arg WEBUI_ADMIN_PASSWD="Password1 \
	--build-arg IPMI_ADMIN_PASSWD="Password1 \
	--build-arg NEW_HTTPS_CERT=4a9f83b7-e403-466b-a847-cd9370490429 \
 \
	./.build

**Comment by mdevaev** [comment]
Don't run `make -C ./.pi-builder os`. Use `make os` in the `os` directory.

**Comment by mnotgninnep** [comment]
That was make os. I was just trying to give you relevant snippets. Here's the full output:

make os
rm -rf ./.pi-builder/stages/{pikvm,pikvm-image,pikvm-otg-console}
cp -a pikvm pikvm-image pikvm-otg-console ./.pi-builder/stages
make -C ./.pi-builder os \
	NC= \
	BUILD_OPTS='  \
		--build-arg PLATFORM=v2-hdmi \
		--build-arg USTREAMER_VERSION=2.2-1 \
		--build-arg KVMD_VERSION=2.10-1 \
		--build-arg KVMD_WEBTERM_VERSION=0.35-1 \
		--build-arg WIFI_ESSID=mywifi \
		--build-arg WIFI_PASSWD="Password1 \
		--build-arg WIFI_IFACE=wlan0 \
		--build-arg ROOT_PASSWD="Password1 \
		--build-arg WEBUI_ADMIN_PASSWD="Password1 \
		--build-arg IPMI_ADMIN_PASSWD="Password1 \
		--build-arg NEW_HTTPS_CERT=fb2cbeaa-a924-450d-b534-09a5207965de \
	' \
	PROJECT=pikvm-os-v2-hdmi \
	BOARD=zerow \
	STAGES='__init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__' \
	HOSTNAME=pikvm \
	LOCALE=en_GB \
	TIMEZONE=Europe/London \
	REPO_URL=http://de3.mirror.archlinuxarm.org
make[1]: Entering directory '/home/michael/Desktop/pikvm/zerow/os/.pi-builder'
===== Ensuring toolbox image =====
docker build \
		--rm \
		--tag pi-builder-arm-toolbox \
		 \
		--file toolbox/Dockerfile.root \
	toolbox
Sending build context to Docker daemon  15.36kB
Step 1/5 : FROM archlinux/base
 ---> a79c9d41e4ac
Step 2/5 : RUN pacman --noconfirm -Syu 	&& pacman --needed --noconfirm -S 		base-devel 	arp-scan 		python 		parted 		dosfstools 		rsync 	&& (pacman --noconfirm -Sc || true)
 ---> Using cache
 ---> c2168eb235e7
Step 3/5 : RUN mkdir /tools
 ---> Using cache
 ---> 12815924a493
Step 4/5 : COPY install-binfmt /tools/
 ---> Using cache
 ---> c56d8e47e4d3
Step 5/5 : COPY docker-extract /tools/
 ---> Using cache
 ---> 98bebff3605a
Successfully built 98bebff3605a
Successfully tagged pi-builder-arm-toolbox:latest
===== Toolbox image is ready =====
===== Ensuring arm binfmt =====
docker run \
		--rm \
		--tty \
		--privileged \
	pi-builder-arm-toolbox /tools/install-binfmt \
		--mount \
		arm \
		/usr/bin/qemu-arm-static
:: Mounting binfmt_misc to '/proc/sys/fs/binfmt_misc' ...
:: Checking ARM binfmt configuration ...
:: Found existent ARM binfmt handler
:: ARM binfmt handler '/usr/bin/qemu-arm-static' is ready
===== Binfmt arm is ready =====
===== Ensuring base rootfs =====
if [ ! -e ./.tmp/base-rootfs-zerow.tar.gz ]; then \
	mkdir -p ./.tmp \
	&& curl -L -f http://de3.mirror.archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz -z ./.tmp/base-rootfs-zerow.tar.gz -o ./.tmp/base-rootfs-zerow.tar.gz \
; fi
===== Base rootfs is ready =====
===== Assembling main Dockerfile =====
rm -rf ./.build
mkdir -p ./.build
ln ./.tmp/base-rootfs-zerow.tar.gz ./.build/pikvm-os-v2-hdmi-pi-builder-arm-base-rootfs-zerow.tgz
cp qemu/qemu-arm-static ./.build
cp -r stages ./.build
sed -i \
		-e 's|%BASE_ROOTFS_TGZ%|pikvm-os-v2-hdmi-pi-builder-arm-base-rootfs-zerow.tgz|g' \
		-e 's|%QEMU_GUEST_ARCH%|arm|g' \
		-e 's|%QEMU_STATIC_GUEST_PATH%|/usr/bin/qemu-arm-static|g ' \
	./.build/stages/__init__/Dockerfile.part
echo -n > ./.build/Dockerfile
for stage in __init__ os pikvm-repo watchdog ro no-audit pikvm pikvm-image __cleanup__; do \
	cat ./.build/stages/$stage/Dockerfile.part >> ./.build/Dockerfile; \
done
===== Main Dockerfile is ready =====
===== Building OS =====
rm -f ./.builded.conf
docker build \
		--rm \
		--tag pikvm-os-v2-hdmi-pi-builder-arm-result-zerow \
		 \
		 \
		--build-arg "BOARD=zerow" \
		--build-arg "ARCH=arm" \
		--build-arg "LOCALE=en_GB" \
		--build-arg "TIMEZONE=Europe/London" \
		--build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
		--build-arg "PIKVM_REPO_URL=https://pikvm.org/repos" \
		--build-arg "PIKVM_REPO_KEY=912C773ABBD1B584" \
		--build-arg "REBUILD=1d82dd5e-9234-4dc2-8ec8-94889e700345" \
		\
	--build-arg PLATFORM=v2-hdmi \
	--build-arg USTREAMER_VERSION=2.2-1 \
	--build-arg KVMD_VERSION=2.10-1 \
	--build-arg KVMD_WEBTERM_VERSION=0.35-1 \
	--build-arg WIFI_ESSID=mywifi \
	--build-arg WIFI_PASSWD="Password1 \
	--build-arg WIFI_IFACE=wlan0 \
	--build-arg ROOT_PASSWD="Password1 \
	--build-arg WEBUI_ADMIN_PASSWD="Password1 \
	--build-arg IPMI_ADMIN_PASSWD="Password1 \
	--build-arg NEW_HTTPS_CERT=fb2cbeaa-a924-450d-b534-09a5207965de \
 \
	./.build
Sending build context to Docker daemon  506.6MB
Step 1/87 : FROM scratch
 ---> 
Step 2/87 : ADD "pikvm-os-v2-hdmi-pi-builder-arm-base-rootfs-zerow.tgz" /
 ---> Using cache
 ---> b3579add22fa
Step 3/87 : COPY "qemu-arm-static" "/usr/bin/qemu-arm-static"
 ---> Using cache
 ---> f4f975d7f3db
Step 4/87 : ARG BOARD
 ---> Using cache
 ---> e6fac53c1a96
Step 5/87 : ENV BOARD $BOARD
 ---> Using cache
 ---> b15a319fc4b0
Step 6/87 : ARG ARCH
 ---> Using cache
 ---> ed77cb118235
Step 7/87 : ENV ARCH $ARCH
 ---> Using cache
 ---> 0a0cf4e1dbc8
Step 8/87 : ARG LOCALE
 ---> Using cache
 ---> 1ca8005ef249
Step 9/87 : ENV LOCALE $LOCALE
 ---> Using cache
 ---> 23278c2203b2
Step 10/87 : ARG TIMEZONE
 ---> Using cache
 ---> d3a5178b4951
Step 11/87 : ENV TIMEZONE $TIMEZONE
 ---> Using cache
 ---> f4e3ca7ddaea
Step 12/87 : ARG REPO_URL
 ---> Using cache
 ---> 45acf63aac10
Step 13/87 : ENV REPO_URL $REPO_URL
 ---> Using cache
 ---> e14b795919e0
Step 14/87 : ARG PIKVM_REPO_URL
 ---> Using cache
 ---> 264d72addbec
Step 15/87 : ENV PIKVM_REPO_URL $PIKVM_REPO_URL
 ---> Using cache
 ---> 46e75b00668a
Step 16/87 : ARG PIKVM_REPO_KEY
 ---> Using cache
 ---> 04e09ded44bc
Step 17/87 : ENV PIKVM_REPO_KEY $PIKVM_REPO_KEY
 ---> Using cache
 ---> 7dd648301bee
Step 18/87 : RUN echo "$LOCALE.UTF-8 UTF-8" > /etc/locale.gen 	&& ([ "$LOCALE" == "en_US" ] || echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen) 	&& locale-gen
 ---> Using cache
 ---> 5e0c7010f3b0
Step 19/87 : ENV LC_ALL $LOCALE.UTF-8
 ---> Using cache
 ---> e6af1df06216
Step 20/87 : RUN rm -f /etc/localtime 	&& ln -s "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime
 ---> Using cache
 ---> 10a2a8e61f78
Step 21/87 : RUN echo "HOOKS=(base udev block filesystems)" >> /etc/mkinitcpio.conf
 ---> Using cache
 ---> 34e23283de4d
Step 22/87 : RUN echo "Server = $REPO_URL/\$arch/\$repo" > /etc/pacman.d/mirrorlist 	&& pacman-key --init 	&& pacman-key --populate archlinuxarm
 ---> Using cache
 ---> f3e2405d4c90
Step 23/87 : RUN sed -i -e "s/^CheckSpace/#!!!CheckSpace/g" /etc/pacman.conf
 ---> Using cache
 ---> 5a0892ad298e
Step 24/87 : RUN pacman --noconfirm -Syy 	&& pacman --needed --noconfirm -S 		glibc 	pacman 	&& pacman-db-upgrade 	&& pacman --noconfirm -Syu 	&& pacman --needed --noconfirm -S 	p11-kit 		archlinux-keyring 		ca-certificates 		ca-certificates-mozilla ca-certificates-utils 	&& pacman --needed --noconfirm -S 		base 		base-devel 	vim 		colordiff 		tree 		wget 		unzip 		unrar 		htop 		nmap 		iftop 		iotop 		strace 		lsof 		git 	jshon 		rng-tools 		bc 		ccache 	&& case "$ARCH" in         arm)             case "$BOARD" in                 rpi|rpi2|rpi3|zero|zerow) pacman --needed --noconfirm -S linux-raspberrypi linux-raspberrypi-headers;;                 rpi4) pacman --needed --noconfirm -S linux-raspberrypi4 linux-raspberrypi4-headers;;                 *) pacman --needed --noconfirm -S linux-armv7-headers;;             esac;;         aarch64) pacman --needed --noconfirm -S linux-aarch64-headers;;         *) echo "Unknown architecture: $ARCH"; exit 1;;     esac 	&& (pacman --noconfirm -Sc || true)
 ---> Using cache
 ---> f33ad26a248a
Step 25/87 : RUN echo 'RNGD_OPTS="-o /dev/random -r /dev/hwrng"' > /etc/conf.d/rngd 	&& systemctl disable haveged 	&& systemctl enable rngd
 ---> Using cache
 ---> d67b616298eb
Step 26/87 : COPY stages/os/semop-wrapper.c /tmp
 ---> Using cache
 ---> 2bd8c34915c6
Step 27/87 : RUN gcc -fPIC -shared -o /usr/local/lib/libpreload-semop.so /tmp/semop-wrapper.c
 ---> Using cache
 ---> 7f6cd6895af8
Step 28/87 : ENV LD_PRELOAD=/usr/local/lib/libpreload-semop.so
 ---> Using cache
 ---> 9d7194880a78
Step 29/87 : RUN sed -i -e "s/^#MAKEFLAGS=.*/MAKEFLAGS=-j5/g" /etc/makepkg.conf
 ---> Using cache
 ---> 4a7ab9e71236
Step 30/87 : RUN sed -i -e "s/ \!ccache / ccache /g" /etc/makepkg.conf
 ---> Using cache
 ---> 12c526964b99
Step 31/87 : ENV PATH="/usr/lib/ccache/bin/:${PATH}"
 ---> Using cache
 ---> 135cf8a7c7e3
Step 32/87 : RUN echo "DNSSEC=no" >> /etc/systemd/resolved.conf 	&& systemctl enable systemd-resolved
 ---> Using cache
 ---> 9ac959766c8a
Step 33/87 : COPY stages/os/gitconfig /etc/skel/.gitconfig
 ---> Using cache
 ---> f37250dca8a2
Step 34/87 : COPY stages/os/gitconfig /root/.gitconfig
 ---> Using cache
 ---> c36ae817a7be
Step 35/87 : COPY stages/os/gitconfig /home/alarm/.gitconfig
 ---> Using cache
 ---> 522eb5779840
Step 36/87 : RUN mkdir /tmp/linux-profile 	&& git clone https://github.com/mdevaev/linux-profile.git /tmp/linux-profile --depth=1 	&& cp -a /tmp/linux-profile/{.bash_profile,.bashrc,.vimrc,.vimpagerrc,.vim} /etc/skel 	&& cp -a /tmp/linux-profile/{.bash_profile,.bashrc,.vimrc,.vimpagerrc,.vim} /root 	&& cp -a /tmp/linux-profile/{.bash_profile,.bashrc,.vimrc,.vimpagerrc,.vim} /home/alarm 	&& chown -R alarm:alarm /home/alarm/{.bash_profile,.bashrc,.vimrc,.vimpagerrc,.vim,.gitconfig} 	&& rm -rf /tmp/linux-profile
 ---> Using cache
 ---> c955bbe05575
Step 37/87 : COPY stages/os/pistat /usr/local/bin/
 ---> Using cache
 ---> d3d500952c63
Step 38/87 : COPY stages/os/pkg-install /usr/local/bin/
 ---> Using cache
 ---> 24d5581efb33
Step 39/87 : RUN ( 		pacman-key --keyserver hkps://hkps.pool.sks-keyservers.net -r $PIKVM_REPO_KEY 		|| pacman-key --keyserver keyserver.ubuntu.com -r $PIKVM_REPO_KEY 	) 	&& pacman-key --lsign-key $PIKVM_REPO_KEY 	&& echo -e "\n[pikvm]" >> /etc/pacman.conf 	&& case "$BOARD" in 			zero|zerow) echo "Server = $PIKVM_REPO_URL/rpi-arm" >> /etc/pacman.conf;; 	*) echo "Server = $PIKVM_REPO_URL/$BOARD-$ARCH" >> /etc/pacman.conf;; 		esac 	&& echo "SigLevel = Required DatabaseOptional" >> /etc/pacman.conf
 ---> Using cache
 ---> 9ee0df0b827d
Step 40/87 : RUN pkg-install watchdog
 ---> Using cache
 ---> 21a73a970abc
Step 41/87 : COPY stages/watchdog/watchdog.conf /etc/watchdog.conf
 ---> Using cache
 ---> 69ddd1529f88
Step 42/87 : RUN systemctl enable watchdog
 ---> Using cache
 ---> 5bc48c10351f
Step 43/87 : RUN [ ! -f /boot/cmdline.txt ] || sed -i -e "s|\<rw\>|ro|g" /boot/cmdline.txt
 ---> Using cache
 ---> c653db86ff7b
Step 44/87 : RUN [ ! -f /boot/boot.txt ] || (         pacman --noconfirm --needed -S uboot-tools         && cd /boot         && sed -i -e "s|\<rw\>|ro|g" boot.txt         && ./mkscr     )
 ---> Using cache
 ---> e5321b45b81b
Step 45/87 : RUN mkdir -p /var/lib/private 	&& chmod 700 /var/lib/private
 ---> Using cache
 ---> 04cb1d918c7d
Step 46/87 : COPY stages/ro/fstab /etc/
 ---> Using cache
 ---> efd28dc10a18
Step 47/87 : COPY stages/ro/ro /usr/local/bin/
 ---> Using cache
 ---> e86619fd1a0b
Step 48/87 : COPY stages/ro/rw /usr/local/bin/
 ---> Using cache
 ---> 8b3704d38b4d
Step 49/87 : COPY stages/ro/journald.conf /etc/systemd/
 ---> Using cache
 ---> 2ffa713d8ab2
Step 50/87 : ADD stages/ro/logrotate.override /etc/systemd/system/logrotate.service.d/override.conf
 ---> Using cache
 ---> 873d02c42a14
Step 51/87 : RUN systemctl disable systemd-random-seed 	&& systemctl disable systemd-update-done 	&& systemctl mask man-db.service 	&& systemctl mask man-db.timer
 ---> Using cache
 ---> c8d94901ec91
Step 52/87 : RUN [ ! -f /boot/cmdline.txt ] || sed -i "1 s/\$/ audit=0/" /boot/cmdline.txt
 ---> Using cache
 ---> 537580e6c41a
Step 53/87 : ARG PLATFORM
 ---> Using cache
 ---> 86c86502477c
Step 54/87 : ARG USTREAMER_VERSION
 ---> Using cache
 ---> 8b66672a86c8
Step 55/87 : ARG KVMD_VERSION
 ---> Using cache
 ---> cfc64c83e853
Step 56/87 : ARG KVMD_WEBTERM_VERSION
 ---> Using cache
 ---> e52593a1ba84
Step 57/87 : ENV INSTALLATION $PLATFORM $USTREAMER_VERSION $KVMD_VERSION $KVMD_WEBTERM_VERSION
 ---> Using cache
 ---> 023fad9b750b
Step 58/87 : RUN echo $INSTALLATION
 ---> Using cache
 ---> c263814d2613
Step 59/87 : RUN pkg-install 	kvmd-platform-$PLATFORM-$BOARD 	kvmd-webterm 	netctl 	parted 	e2fsprogs
 ---> Using cache
 ---> 1cb636568767
Step 60/87 : RUN systemctl enable kvmd 	&& systemctl enable kvmd-nginx 	&& systemctl enable kvmd-webterm && ([[ ! $PLATFORM =~ ^.*-hdmi$ ]] || systemctl enable kvmd-tc358743) 	&& ([[ ! $PLATFORM =~ ^v[01]-.*$ ]] || systemctl mask serial-getty@ttyAMA0.service) 	&& ([[ ! $PLATFORM =~ ^v2-.*$ ]] || ( 		systemctl enable kvmd-otg 		&& echo "/dev/mmcblk0p3 /var/lib/kvmd/msd  ext4  nodev,nosuid,noexec,ro,errors=remount-ro,data=journal,X-kvmd.otgmsd-root=/var/lib/kvmd/msd,X-kvmd.otgmsd-user=kvmd  0 0" >> /etc/fstab 	))
 ---> Using cache
 ---> 324f2a5ce08d
Step 61/87 : COPY stages/pikvm/motd /etc/
 ---> Using cache
 ---> 31bd69c8f75d
Step 62/87 : RUN sed -i -f /usr/share/kvmd/configs.default/os/cmdline/$PLATFORM-$BOARD.sed /boot/cmdline.txt 	&& cp /usr/share/kvmd/configs.default/os/boot-config/$PLATFORM-$BOARD.txt /boot/config.txt
 ---> Using cache
 ---> 3fbe5a0a8780
Step 63/87 : RUN sed -i -e "s/-session   optional   pam_systemd.so/#-session   optional   pam_systemd.so/g" /etc/pam.d/system-login
 ---> Using cache
 ---> 9fb688b78e78
Step 64/87 : ARG WIFI_ESSID
 ---> Using cache
 ---> 691aa9792f1e
Step 65/87 : ARG WIFI_PASSWD
 ---> Using cache
 ---> a46feeae1c19
Step 66/87 : ARG WIFI_IFACE
 ---> Using cache
 ---> d7bfbc114ca1
Step 67/87 : RUN [ -z "$WIFI_ESSID" ] || ( 		export config="/etc/netctl/$WIFI_IFACE-${WIFI_ESSID/ /_}" 		&& echo "Description='Generated by Pi-KVM OS build system'" > $config 		&& echo "Interface='$WIFI_IFACE'" >> $config 		&& echo "Connection=wireless" >> $config 	&& echo "Security=wpa" >> $config 		&& echo "ESSID='$WIFI_ESSID'" >> $config 		&& echo "IP=dhcp" >> $config 		&& echo "Key='$WIFI_PASSWD'" >> $config 		&& systemctl enable netctl-auto@$WIFI_IFACE.service 	)
 ---> Using cache
 ---> 773be3edc309
Step 68/87 : ARG ROOT_PASSWD
 ---> Using cache
 ---> 49cd100f7550
Step 69/87 : ENV ROOT_PASSWD $ROOT_PASSWD
 ---> Using cache
 ---> 1210b747932a
Step 70/87 : RUN echo "root:$ROOT_PASSWD" | chpasswd 	&& echo "PermitRootLogin yes" >> /etc/ssh/sshd_config 	&& userdel -r -f alarm
 ---> Running in 368084a18bb9
No password has been supplied.
No password has been supplied.
No password has been supplied.
chpasswd: (user root) pam_chauthtok() failed, error:
Authentication token manipulation error
chpasswd: (line 1, user root) password not changed
The command '/bin/sh -c echo "root:$ROOT_PASSWD" | chpasswd 	&& echo "PermitRootLogin yes" >> /etc/ssh/sshd_config 	&& userdel -r -f alarm' returned a non-zero code: 1
make[1]: *** [Makefile:231: os] Error 1
make[1]: Leaving directory '/home/michael/Desktop/pikvm/zerow/os/.pi-builder'
make: *** [Makefile:54: os] Error 2

**Comment by mdevaev** [comment]
I'll check it today. Sorry for the long reply.

**Comment by mdevaev** [comment]
In the latest os/pi-builder: `WIFI_PASSWD = Password1$$$$` for `Password1$`. Remove old `os` environment, clone it again and retry.

**Comment by mnotgninnep** [comment]
Thank you. I think that is working now.
