### ISSUE TITLE
E2EE connection

### ISSUE THREAD

**Issue by trymeouteh** [pikvm/pikvm#1446]
**Is your feature request related to a problem? Please describe.**
Connection between PiKVM and remote computer is not encrypted. Especially when connecting to PiKVM using an IP address in the web interface which uses HTTP (not HTTPS)

**Describe the solution you'd like**
An E2EE solution which ensures video, audio, file transfer (for linux ISOs), keyboard and mouse packets are E2EE.

1. Creating a app (client). Would recommend forking RustDesk
2. Adding RustDesk support (Will need to add additional features in RustDesk such as sending linux ISOs)

**Describe alternatives you've considered**
SSH (This does not support video or audio)

**Additional context**
Will make remote connection secure

**Comment by mdevaev** [comment]
> Connection between PiKVM and remote computer is not encrypted. Especially when connecting to PiKVM using an IP address in the web interface which uses HTTP (not HTTPS)

That's not so. PiKVM always forces the use of HTTPS, even if the connection uses an IP address instead of a hostname. In both cases, a self-signed SSL certificate is used.

**Comment by mdevaev** [comment]
If you click on this icon, you will see that the browser complains that the certificate is self-signed. The connection is still encrypted. You can make your own root certificate and sign the certificate in PiKVM. In any case, the connection remains encrypted.
