### ISSUE TITLE
Please add Apache guacamole into pikvm for RDP/VNC access to hosts on same LAN as pikvm

### ISSUE THREAD

**Issue by mondipsen** [pikvm/pikvm#1447]
Please add Apache guacamole into pikvm for RDP/VNC access to hosts on same LAN as pikvm

This way, can RDP using the pikvm webUI into windows hosts from the GPIO menu

Thank you

**Comment by mdevaev** [comment]
Hello. There is VNC support: https://docs.pikvm.org/vnc

RDP will not be implemented because VNC works fine.
