### ISSUE TITLE
Add kernel config to support additional GPIOs over USB using a PI Pico

### ISSUE THREAD

**Issue by tinkeros** [pikvm/pikvm#1453]
It would be nice to be able to easily add external GPIO access via USB to the PiKVM v4 (for additional custom ATX or KVM controls).  There is a project that makes this easy to do using a PI Pico, but kernel support for the driver is needed.

Can you please add the following to the default kernel config to add support for this:

```
CONFIG_I2C_DLN2=m
CONFIG_SPI_DLN2=m
CONFIG_GPIO_DLN2=m
CONFIG_MFD_DLN2=m
CONFIG_DLN2_ADC=m
```

The project which allows using the GPIO pins of a PI Pico over USB is here:
https://github.com/notro/pico-usb-io-board/

These kernel config options are mentioned in the WIKI here:
https://github.com/notro/pico-usb-io-board/wiki

It also be nice to add the udev rules described in the WIKI, but that something users can do manually to easily:
```
ACTION=="add", SUBSYSTEM=="usb", \
        ATTR{idVendor}=="1d50", ATTR{idProduct}=="6170", \
        RUN+="/sbin/modprobe -b dln2"

ACTION=="add", SUBSYSTEM=="drivers", ENV{DEVPATH}=="/bus/usb/drivers/dln2", \
        ATTR{new_id}="1d50 6170 ff"
```

**Comment by mdevaev** [comment]
Released.
