### ISSUE TITLE
Direct download to Pi for mass storage

### ISSUE THREAD

**Issue by theLMGN** [pikvm/pikvm#148]
**Is your feature request related to a problem? Please describe.**
It's a waste of time and annoying when I want to use the mass storage feature as I have to download the iso to my local machine, then back up to the Pi

**Describe the solution you'd like**
Add a direct download box, like a more polished version of the follwing 
![image](https://user-images.githubusercontent.com/12257112/104109216-9f523f80-52c3-11eb-80c3-bc118c62fae6.png)

**Describe alternatives you've considered**
 - Downloading to my local host then to up to Pi-KVM, too slow, requires storage space on the local machine
 - Downloading to the Pi-KVM using wget in terminal, not immediately obvious, not user friendly.

**Comment by mdevaev** [comment]
This is a good idea, but I will consider its implementation a low priority, since there is now a documented way to load images directly to the Pi via the terminal: https://github.com/pikvm/pikvm/blob/master/pages/cookbook.md#upload-iso-images-manually

**Comment by mdevaev** [comment]
Working on it now.

**Comment by mdevaev** [comment]
Will be available in the next release, follow news.
