### ISSUE TITLE
VGA support ?

### ISSUE THREAD

**Issue by ketominer** [pikvm/pikvm#155]
Most rackmount servers have still/only VGA. Have you found any good VGA capture device that would work with this setup?

**Comment by mdevaev** [comment]
This one is ok: https://www.aliexpress.com/item/4000553298530.html

**Comment by mdevaev** [comment]
Feel free to reopen if you wnt to discuss something else.

**Comment by ketominer** [comment]
oh that's really cool, thank you

**Comment by omigeot** [comment]
The aliexpress link is dead, would any one have a named reference instead?

**Comment by mdevaev** [comment]
![image](https://user-images.githubusercontent.com/416259/205626161-500fcde2-b74b-4ac5-bb51-c00225b4e2cc.png)

**Comment by AkechiShiro** [comment]
The link in the README is dead to the converter

**Comment by AkechiShiro** [comment]
Could another trusted adapter be put in place/replace this older link ?
