### ISSUE TITLE
UART to USB HID device support?

### ISSUE THREAD

**Issue by chk-jxcn** [pikvm/pikvm#162]
I got a UART to USB HID(Keyboard/Mouse) convert device , and it's very cheap about $2~$3, which chip is CH9329.
How could I add it to Pi-KVM?

**Comment by mdevaev** [comment]
You need to write plugin for this hid. See here: https://github.com/pikvm/kvmd/tree/master/kvmd/plugins/hid

**Comment by xe5700** [comment]
I write a ch9329 plugin , but only support single key. And I don't know why mouse not support linux desktop, it works very well on windows 10. https://github.com/xe5700/kvmd @chk-jxcn
