### ISSUE TITLE
HDMI USB Dongle not working anymore with KVMD 2.15

### ISSUE THREAD

**Issue by y0hnn** [pikvm/pikvm#164]
Hello,

Following this thread : https://www.reddit.com/r/pikvm/comments/l6eomj/cant_get_a_macrosilicon_usbhdmi_dongle_working/

I confirm HDMI USB dongle (Macrosilicon) are not working with the latest release (on Rasp 4). We see the device plugged in with a dmesg, but the video interface is not created.

Do you have a solution?

Thanks!

**Comment by mdevaev** [comment]
The image build system assembled v2-hdmi under the instead of hdmiusb. Fixed.
