### ISSUE TITLE
Support for PoE

### ISSUE THREAD

**Issue by dkrutsko** [pikvm/pikvm#169]
I just found out about this project and I'm getting really excited about its potential uses. One consideration though is documenting and potentially creating a PoE variant of the top hat.

You see, in a rack-mounted environment, I could envision four or more of these Pi-KVMs being slotted and connected to their own machines. Ideally I would want the wiring to be as simple as possible. Having power be delivered alongside the ethernet cable would remove the need for a whole wire and power solution to be installed within the rack.

However, in the meantime, are you able to document the requirements for a third-party PoE solution which would be compatible with version 3 of the board. Specifically, power requirements and other considerations. It would also be nice to have some recommendations for existing PoE solutions which would be compatible.

**Comment by mdevaev** [comment]
Hi! We are creating v3 so that it can be used with PoE. It seems that all existing boards are compatible with this (except for the official RPi PoE, it requires turning off the fan since it conflicts with the HDMI chip, but this is not a big problem). My only advice is that you need an honest PoE with a transformer. This is more reliable.

**Comment by dkrutsko** [comment]
I've been seeing a lot of PoE hats which can deliver 15 watts of power. Is this going to be enough for the PiKVM, or does it require further testing?

**Comment by mdevaev** [comment]
I think yes

**Comment by cipy** [comment]
hi @mdevaev 

would (any of the) existing PoE HATs fit inside your custom PiKVM HAT v3 metal case? 🤔 

i.e. from https://thepihut.com/pages/search-results?q=power%20over%20ethernet, thanks

**Comment by mdevaev** [comment]
the existing ones won't fit, but we plan to release our poe module by the summer

**Comment by alichaudry** [comment]
> the existing ones won't fit, but we plan to release our poe module by the summer

Hi @mdevaev, are there any updates on the PoE module as we approach the end of summer? I require PoE for my needs and would like to go down the PiKVM route rather than the alternatives that provide PoE.

**Comment by mdevaev** [comment]
Hello. We are working on it. There are no updates right now.

**Comment by unknownusermello** [comment]
hey I know that you guys had the Kickstarter going on but I was wondering if there are any updates for the PiKVM V3 PoE addon that you mentioned back in February 2021?

**Comment by Gooberpatrol66** [comment]
does the v4 have PoE?

**Comment by alichaudry** [comment]
> does the v4 have PoE?

No, from what I read on [this thread](https://www.reddit.com/r/HomeServer/comments/znj4cm/pikvm_v4_nextgen_kvm_over_ip_on_kickstarter/) on reddit, pikvm v4 does _not_ have PoE. Pretty much the only reason I didn't pull the trigger and buy it (I absolutely love the new design of the PiKVM v4 mini otherwise).

**Comment by thomasdiemarbennedsen** [comment]
Im also waiting for PoE support for a version that fits a 1u installation for instance https://www.waveshare.com/pi4-1u-rack-kit.htm

What is the status for PoE support?

**Comment by mdevaev** [comment]
We have a prototype now, and just choosing a common chip for all V3 and V4 models.

**Comment by Gooberpatrol66** [comment]
> Im also waiting for PoE support for a version that fits a 1u installation for instance https://www.waveshare.com/pi4-1u-rack-kit.htm
> 
> What is the status for PoE support?

I've never seen a pi rackmount that actually looks like it'd fit a pikvm. It needs holes cut out for the ports on the hat. I'm hoping to just mount my pikvm's on a DIN rail.

**Comment by starsoccer** [comment]
Any update on this?
