### ISSUE TITLE
Build system other than Archlinux

### ISSUE THREAD

**Issue by db260179** [pikvm/pikvm#179]
**Is your feature request related to a problem? Please describe.**
Current build system using Arch linux is very problematic and breaks alot

**Describe the solution you'd like**
What steps or changes or limitations to use Debian as a base system?

**Describe alternatives you've considered**
Use a base build system on Ubuntu or Debian stable

Im happy to assist in getting this to work.

As you are using Docker to build the code, has there been any attempt to use Ubuntu or Debian as a base system.

**Comment by db260179** [comment]
Arch linux is a great next gen features OS, but its rapid pace means alot of random breakages and lots of bugs.

I can envisage the following is needed to be done:

1. Identify the packages and dependencies
2. Test build code
3. Identify issues based on versions of packages used

**Comment by mdevaev** [comment]
For the Debians, there will be too much to change. Many packages need to be packaged and tested. I'm not against the alternative, but right now I don't have the resources to do it.

**Comment by alexsalex** [comment]
Would like to help

**Comment by db260179** [comment]
I understand, im happy to make a start. If you are ok with that, can I ask questions later if I get stuck with your packaging?

The docker parts are straightforward, the packages and dependencies is the tricky bit.

I will update you on progress. This is my way of contributing.

**Comment by mdevaev** [comment]
Ofc you can contact me via discord or here.

**Comment by mdevaev** [comment]
Related: #245

**Comment by mdevaev** [comment]
I'm closing it since it seems that we have those who are going to do this in another issue.

**Comment by mdevaev** [comment]
See #374
