### ISSUE TITLE
Can this be used as a serial port IPKVM rather and HDMI?

### ISSUE THREAD

**Issue by MrClayPole** [pikvm/pikvm#18]

**Comment by MrClayPole** [comment]
I'm looking for power management over the network via IPMI and via the web interface. Is this currently supported?

The question around the serial console rather than HDMI is all the hosts I'll be managing are linux without desktops so was just wondering if I could get away with the cheaper Pi ZeroW and serial console rather than Pi 4 & HDMI?

**Comment by mdevaev** [comment]
Yes, you can control by IPMI. Power on, power off, and restart are supported. Ipmitool's requests will be translated into commands for the relay.

In fact, HDMI can be used even with Zero. But if you don't want to spend money on it, you can use the serial console without it. This will not be so convenient, because the project does not provide a special interface for the series console, except for the terminal emulator in the browser. But everything will work.

**Comment by stsirakidis** [comment]
Btw, what is the "logic" with IPMI regarding power on or off...since the relay for the ATX power acts only on "bridging" the two PINS on the motherboard?

**Comment by mdevaev** [comment]
Good question. To understand the current state, the server reads the power led. That is, you will need to connect it to the optocoupler (shown in the diagram). The off command will only be triggered when the led is on, and vice versa.

**Comment by stsirakidis** [comment]
Cool!

Btw, pls edit your documentation regarding the passwords...the should not contain the # sign...the rest of the password after the "hash" sign will be implemented as comment.... :-)

**Comment by mdevaev** [comment]
What file are you talking about?

**Comment by stsirakidis** [comment]
````
# For SSH root user
ROOT_PASSWD = root
````

e.g. setting the password to "root#blabla". The way that the scripts are building the docker images implement the # sign as comment, when the scripts run and substitute the password_variable with the passwords set in config.mk. If these passwords contain the # sign, then the passwords are not the same as when the SD card is build. Sorry...I should have open a new issue/thread therefore...

**Comment by mdevaev** [comment]
Don't worry. I will see how best to fix this or document this feature.

**Comment by MrClayPole** [comment]
I want to managed a number of "odroid H2" systems using a bare metal deployment tool "MAAS". In order to turn systems on and off as required by MAAS, I need to use one of the supported methods. IPMI is a supported method. 

Thanks for your help with this I'll have a play with a Pi Zero/Pi 4 and Serial/HDMI and see which route I like the best.

**Comment by mdevaev** [comment]
@stsirakidis try to use `ROOT_PASSWD = pass\#word`. It shoud works.
