### ISSUE TITLE
permission denied on /etc/kvmd/nginx/ssl/ when starting kvmd

### ISSUE THREAD

**Issue by thegogglesdonothing** [pikvm/pikvm#180]
I compiled the code in a clean Arch Linux vm build environment.

When booting up the pi, attempting to access the console via the browser returns a nginx 500 internal server error page.

The kvmd service fails to start with a permission denied on the ssl certificate file

/usr/lib/systemd/system/kvmd*.service files list kvmd:kvmd as the service user

but permissions on the ssl directory are root:kvmd-nginx and the kvmd user is not a member of the kvmd-nginx group so the nginx service fails to start.

chown kvmd on the ssl directory, or adding the kvmd user to the kvmd-nginx group fixes the problem.

**Comment by mdevaev** [comment]
Yes, my fault. It's already fixed. Just perform update: `rw; pacman -Syu; reboot`

**Comment by thegogglesdonothing** [comment]
Recompiled from start to finish, works perfectly now, thanks!
