### ISSUE TITLE
monit daemon doesn't work with ro file system

### ISSUE THREAD

**Issue by alexsalex** [pikvm/pikvm#183]
Is any reason to implement ro file system? Could you explain the purpose of this solution.

Do you have any solution to monitor the raspi health?

**Comment by mdevaev** [comment]
This is to protect against file system corruption in the event of a sudden power outage.

I think you can figure out what data monit wants to overwrite and mount it in tmpfs.

**Comment by alexsalex** [comment]
nano /etc/monitrc

Uncomment and change this line to:
`set statefile /var/tmp/.monit.state`

restart monit

**Comment by mdevaev** [comment]
Okay, apparently the problem is solved here.
