### ISSUE TITLE
Warning window with confirmation on remove image

### ISSUE THREAD

**Issue by sharicov** [pikvm/pikvm#189]
Please add warning window with confirmation on image remove.
Currently it removes it immediately, very inconvenient.
Thanks

**Comment by mdevaev** [comment]
This window has been there for a long time. Maybe I didn't understand you?

![image](https://user-images.githubusercontent.com/416259/107888669-db11a200-6f1e-11eb-9719-1bafd28e2797.png)

**Comment by sharicov** [comment]
> This window has been there for a long time. Maybe I didn't understand you?
> 
> ![image](https://user-images.githubusercontent.com/416259/107888669-db11a200-6f1e-11eb-9719-1bafd28e2797.png)

You are absolutely write, I suppose I didn't understand it correctly and pressed OK automatically. Was under impression it is removing it from the host computer, not deleting it from the pi-kvm. Maybe it worth to highlight it in the message. Something like: Are you sure ... Image will be deleted from the Pi-KVM.

**Comment by mdevaev** [comment]
Okay, fixed
