### ISSUE TITLE
unable to emulate USB device

### ISSUE THREAD

**Issue by alexsalex** [pikvm/pikvm#192]
I can see this error when I connect usb cable from the PiKVM to my server or after PiKVM rebooted:

![Screen Shot 2021-02-14 at 2 16 23 PM](https://user-images.githubusercontent.com/17325366/107890733-4764b500-6ecf-11eb-9283-2ceef502eda9.png)

**Comment by mdevaev** [comment]
Pi zero takes too long to load and a device timeout occurred because of this. This is one of the reasons why I recommend pi4.
