### ISSUE TITLE
Ethernet module with SPI interface

### ISSUE THREAD

**Issue by wnark** [pikvm/pikvm#193]
Can this support Ethernet module using SPI interface? This allows the Raspberry Pi ZEROW to have an RJ45 interface
like this

![TB224X0aL5TBuNjSspmXXaDRVXa_!!1070042715 jpg_430x430q90](https://user-images.githubusercontent.com/24355466/107899580-9e26c900-6f79-11eb-870c-4d54962e6446.jpg)

the blog:
https://shumeipai.nxez.com/2017/10/10/raspberry-pi-spi-netword-configuration-tutorial.html

**Comment by wnark** [comment]
Even, the Raspberry Pi can use the 4 / 5G module to access the Internet. Can the 4G-SPI module be used instead of wifi?

like this:https://blog.csdn.net/huayucong/article/details/51706307

You may need Google Translate, LOL，thanks

**Comment by mdevaev** [comment]
We have a regular Raspbian kernel. If this is supported, then everything will work. In extreme cases, you will have to compile the necessary module.

**Comment by wnark** [comment]
> We have a regular Raspbian kernel. If this is supported, then everything will work. In extreme cases, you will have to compile the necessary module.

I found another magic chip, ch9329, which can simulate spi as USB, which saves an arduino
I try to see if the Raspberry Pi can use it to communicate with the computer

**Comment by mdevaev** [comment]
I believe I have answered your question, so this issue will be closed. Write here or in the new issue if you want to discuss something else. I also recommend discord, as we have Zero users who use SPI Ethernet.
