### ISSUE TITLE
Please move "Paste your text here" out of Shortcuts

### ISSUE THREAD

**Issue by arch1mede** [pikvm/pikvm#198]
It doesn't make any sense that "Paste your text here" would be considered a shortcut, doesn't seem intuitive. It took me a while and had to ask in the channel if there was such a feature, I have also seen others ask the same.

Please move it to its own section and name it something like: "Paste to target" into a window like notepad so you can edit it before sending.

**Comment by mdevaev** [comment]
I've renamed "shortcuts" to "keyboard"
