### ISSUE TITLE
Implement a serial port on the OTG interface

### ISSUE THREAD

**Issue by agreen** [pikvm/pikvm#204]
Wondering if it would be possible to implement a serial port on the OTG interface that would allow you to connect to the Raspberry Pi from the host computer. This would allow configuration/reconfiguration of aspects of the system such as wifi, and especially useful on headless pikvm setups, like a zero w.

**Comment by mdevaev** [comment]
Already here: https://github.com/pikvm/pikvm/blob/master/pages/cookbook.md#enable-serial-over-usb-connection
