### ISSUE TITLE
Wake-lock type feature

### ISSUE THREAD

**Issue by bionemesis** [pikvm/pikvm#205]
This might take some trial-and-error in terms of the correct process, but a way to instruct pikvm to keep a connected device awake, by either pressing a key or moving the mouse every X minutes. Obviously, the best solution would be one that doesn't interfere with actual use (you wouldn't want a keypress while in the middle of typing something, for example). Perhaps there is a way to detect when a connected session is idle or disconnected and then work to keep the connected device alive? The use case here is for when we're setting up new equipment that by default may go into sleep mode before we've had a chance to change those settings.

**Comment by mdevaev** [comment]
We already have a task about this. Yes, it needs to be done.
#57
