### ISSUE TITLE
Phone web interface or application

### ISSUE THREAD

**Issue by sharicov** [pikvm/pikvm#210]
Could you please make web interface optimized for the phones, or phone app to control PI-KVM?
Would be a good use case to use a phone as mobile hotspot and control PI-KVM over the same phone.
Thanks

**Comment by mdevaev** [comment]
There are to possibilities:
* Use VNC with some mobile client (like bVNC): https://github.com/pikvm/pikvm/blob/master/pages/vnc.md
* Follow the issue #89. Your request actually duplicates it. The interface for phones is a low priority right now.

**Comment by adamoutler** [comment]
The provided VNC link is broken.
