### ISSUE TITLE
Feature Request - http only (no redirect to https) option for a happier iPad

### ISSUE THREAD

**Issue by aanon4** [pikvm/pikvm#215]
Would be nice to have an http-only (or also) mode rather than having it auto-redirect to https. The self-signed certificate doesn't work for websockets on the iPad so this would be a useful work around.

**Comment by mdevaev** [comment]
The problem seems to be solved. If not, I'm at your service.

**Comment by ewspikvm** [comment]
Another better alternative than removing security is to enable the TLS option of Tailscale for MagicDNS hosts, and install those certificates to the PIKVM and access it via the Tailnet address, this also allows it to work in "app" windows or pinned pages vs requiring only accessing via Safari.
