### ISSUE TITLE
Question about relays

### ISSUE THREAD

**Issue by Barborica-Alexandru** [pikvm/pikvm#218]
Hi, I hope i'm not a bother, I just have a quick question: the octocouplers suggested in the build guide I can't seem to find at my local retailer so I was curios if I could use this solid state relay I have on hand? I know I'm not supposed to use mechanical relays, but I never used a solid state one, maybe it's more reliable? I believe they are high activated vs low activated.
0V - 0.5V Low stage (SSR is OFF),
0.5V – 2.5V (unknown state).
2.5V - 20V High state (SSR is ON).
![image](https://user-images.githubusercontent.com/11920443/109462820-bc59f200-7a6c-11eb-8e9d-07f037c021dc.png)

**Comment by mdevaev** [comment]
Hi. You can use mechanical relays, but they must be activated by a high signal.

**Comment by Barborica-Alexandru** [comment]
> 
> 
> Hi. You can use mechanical or solid relays, but they must be activated by a high signal.

Oh wow thanks for the instant reply. Also thank you for your hard work!

**Comment by mdevaev** [comment]
ur welcome
