### ISSUE TITLE
Can I use only the web interface of the HTTP protocol?

### ISSUE THREAD

**Issue by wnark** [pikvm/pikvm#228]
How do I turn off https and only use http access, because when I use FRP intranet penetration, an error 502 will be reported when I use the https protocol。
At present, FRP is more compatible with HTTP, so I want to use HTTP only
Thank you

**Comment by wnark** [comment]
Sorry, I ignored this question that was asked before, sorry
[close https](https://github.com/pikvm/pikvm/issues/215)

**Comment by mdevaev** [comment]
It looks like the problem solved itself :)

**Comment by wnark** [comment]
> It looks like the problem solved itself :)

sorry,i still have trouble
i have deleted` return 301 https://$host$request_uri;`
but It reported an error
what should i do？
![image](https://user-images.githubusercontent.com/24355466/110318853-fe74cc00-8048-11eb-95b2-8848e716909b.png)

**Comment by mdevaev** [comment]
You probably missed a line. Look carefully at what exactly you should comment (not only 301): https://github.com/pikvm/kvmd/blob/master/configs/nginx/nginx.conf#L39

**Comment by wnark** [comment]
> You probably missed a line. Look carefully at what exactly you should comment (not only 301): https://github.com/pikvm/kvmd/blob/master/configs/nginx/nginx.conf#L39
![image](https://user-images.githubusercontent.com/24355466/110320350-1a796d00-804b-11eb-951c-46804faff924.png)

I changed it to this, it seems to be useful

**Comment by mdevaev** [comment]
Are you saying that it doesn't work like this? Weird. Maybe your browser has cached the 301 forwarding?

**Comment by wnark** [comment]
> Are you saying that it doesn't work like this? Weird. Maybe your browser has cached the 301 forwarding?

It should be a cache, http is now normal, thank you
