### ISSUE TITLE
PiKVM on RPi 4 1GB

### ISSUE THREAD

**Issue by yoGhurrt1** [pikvm/pikvm#23]
Hi,
In documentation there is a sentence about requirements "RPi4 with 2Gb RAM is pretty enough". "Pretty enogh" would suggest that this is even more then you need and possibly 1GB would fit here too. Is it that right or 2GB version should be secure minimum for this software?

Thanks in advance

**Comment by mdevaev** [comment]
I believe that 1Gb will also work fine, given that my software is currently running on ZeroW with 512Mb of memory.

**Comment by yoGhurrt1** [comment]
Right. I thought it can act differently because of differences between ZeroW and RPi4.
Thanks for answer, I'll go back to you if I'll find anything on it.
