### ISSUE TITLE
Paste-as-keys sending incorrect characters

### ISSUE THREAD

**Issue by longmover** [pikvm/pikvm#231]
I suspect this is something to do with my UK keyboard layout but using the paste-as-keys function results indifferent characters being pasted that those supplied.  Examples are:

~ becomes ¬
" becomes @

Is there a way to alter this and if not is it a feature which could be considered?

**Comment by mdevaev** [comment]
It's a bug, I'll fix it

**Comment by mdevaev** [comment]
In the new version, you will be able to select the keyboard layout of the target host, this will fix the problem

**Comment by longmover** [comment]
Fantastic, thank you, works perfectly!

**Comment by mdevaev** [comment]
Welcome!
