### ISSUE TITLE
No picture on PIKVM with Displayport to Triple Monitor Output

### ISSUE THREAD

**Issue by JsBergbau** [pikvm/pikvm#236]
**Describe the bug**
I don't know if this is really an issue, however perhaps you can help.
I bought this https://www.amazon.de/gp/product/B00V07XW3E device. It outputs from Displayport to VGA, DVI and HDMI. I use DVI for connection to monitor and want to use HDMI for connection to PI-KVM. However I always get "No signal" on PIKVM. If I plug this HDMI cable to another monitor I get the same picture on both monitors. If I plug a Displayport to HDMI adapter to PIKVM I get the signal on the PI-KVM.

Any idea whats going on here? 
**To Reproduce**
You need this special displayport adapter, see above.

**Expected behavior**
With that display port adapter I see the picture on the monitor and on PI KVM.
**Screenshots**

**Desktop (please complete the following information):**
 - VNC client (if used)

**Pi-KVM info:**
  - Raspberry Pi board version [e.g. RPi 4]: PI Zero
  - Pi-KVM platform [e.g. v2-hdmi] v2-hdmi
  - Video capture type [e.g. CSI bridge] CSI bridge
  - KVMD version: `pacman -Q | grep kvmd`
  - uStreamer version: `pacman -Q | grep ustreamer`
  - Linux kernel: `uname -a`

**Additional context**

**Comment by mdevaev** [comment]
To be honest I have no idea. Some adapters is working, and some not. I have one displayport adapter and I use it constantly with pikvm, everything works. But I think that this will not help you much.

**Comment by JsBergbau** [comment]
Which model do you use?

**Comment by mdevaev** [comment]
Noname. Looks like this:
![image](https://user-images.githubusercontent.com/416259/111876783-66b09f80-89b1-11eb-8a6b-9098e6e1bc30.png)

**Comment by JsBergbau** [comment]
Oh Ok. I've used different single Displayport to HDMI adapters. All these worked. It came only to problems with HDMI 1 to 2 Splitter or that above linked device.
Currently I use this one https://www.amazon.de/DeLock-87720-Displayport-Splitter-schwarz/dp/B079Z89CV6
This works fine. On Windows it enables me even to use 4 different displays with AMD Radeon Ryzen 3 Pro 4350GE with integrated Radeon Graphics and on Boot it shows the same image like the monitor which enables it to enter Bitlocker Password via PI-KVM. This is my only usecase for PIKVM because once I'm in Windows I can use RDP to connect. 
However this particular Delock device has one major disadvantage: It needs to be USB powered and there it consumes almost always 2 Watt, even when there is no monitor signal. I've ordered another Splitter and will report when I've tested it here.

**Comment by JsBergbau** [comment]
Now I've ordered https://www.amazon.de/PremiumCord-DisplayPort-Monitore-Extended-Duplicate/dp/B08438TV6G/
Needs to be connected via Micro-USB cable to get power, however there is no powerdraw. 
When monitor is off it still consumes 3W from DisplayPort.
In Bitlocker resolution is usually 1280x720. With that resolution images is blinking. So I can't recommend with PIKVM.
With AMD Radeon Ryzen 3 Pro 4350GE with integrated Radeon Graphics are 4 monitors possible. A 5th monitor is not supported. If I pull the plug of another monitor I can use all 3 HDMI outputs of the Displayport adapter.

**Comment by mdevaev** [comment]
I think there is nothing to do here now, but this information is valuable for other users. Thanks!

**Comment by ebarrere** [comment]
Hey all, I'm having a similar issue with the Microcenter DP-HDMI [here](https://www.microcenter.com/product/485114/inland-displayport-male-to-hdmi-female-adapter-black). Is there a list somewhere of working/non-working adaptors? I'm happy to add my findings for anyone who might come across this later!

**Comment by mdevaev** [comment]
@ebarrere There is no list now, but if you want to share something, you could create a new issue and we start such list.

PS: Happy New Year!

**Comment by ebarrere** [comment]
Sounds good! I'll list my findings in a new issue and we can go from there.
