### ISSUE TITLE
Delayed OTG Activation - Especially Useful for Pi Zero

### ISSUE THREAD

**Issue by dwhitt1962** [pikvm/pikvm#238]
Problem:  No Keyboard Access to OS

Once the Pi Zero is booted for the first time, the system configures itself for wifi and that is only way to access the OS.
If there is an error, the only easy option is to reflash the OS and reconfigure for the wifi present.

Solution:  Delayed OTG activation

If the OS detects a keyboard key like F2 or F11 "This status would be displayed in the local hdmi screen, then the keyboard would become active and the user could use that to reconfigure wifi or other maintenance items.  If no keyboard detected for 30 seconds (configurable), then the OTG function would be activated to relay keyboard and mouse to the targeted PC.

**Comment by mdevaev** [comment]
It can't be solved like you want. The kernel is not capable of this. I recommend using a USB UART adapter to configure Zero.
