### ISSUE TITLE
WebTerminal overlay Window

### ISSUE THREAD

**Issue by White-SAndS** [pikvm/pikvm#241]
Is it possible to put the webterminal as an overlay window on top of the hdmi output like the keyboard is? That would it make easyer to work with the pikvm, watch temperature, modify system and so one without open a new tab window.

**Comment by mdevaev** [comment]
Pikvm ui can't resize windows now, so even if you'll have a terminal, its size will be fixed

**Comment by mdevaev** [comment]
Will be available in KVMD 2.53.
