### ISSUE TITLE
folder {nginx,vnc} inside /etc/kvmd

### ISSUE THREAD

**Issue by vasyl83** [pikvm/pikvm#242]
Just wanted to know if that folder is supposed to be there or just an artifact of badly structured mkdir command somewhere?
It contains empty ssl folder.

I am using csi bridge image

**Comment by mdevaev** [comment]
This folder is filled after startup

**Comment by mdevaev** [comment]
It was necessary to opsat a little more detail. Found and fixed: https://github.com/pikvm/kvmd/pull/38
