### ISSUE TITLE
ENC28J60 Ethernet SPI Module with a Pi Zero

### ISSUE THREAD

**Issue by damo2929** [pikvm/pikvm#264]
Can anybody tell me if this project works with the PI zero with ENC28J60 Ethernet SPI Module connected for external connectivity ?

**Comment by mdevaev** [comment]
Yes, it will)

**Comment by woffko** [comment]
Does it mean that ENC28J60 works already? Any steps to configure? Connected some ENC28J60 to Pi ZeroW but interface is not listed
