### ISSUE TITLE
how to config wifi on Zero using pre-compiled image?

### ISSUE THREAD

**Issue by Zigngit** [pikvm/pikvm#271]
For zero only have ONE usb port which is used for OTG, I just cannot connect keyboard to it.
And because no wifi configuration in it , I cannot connect via SSH.
So I have no way to do the configuration ! What should I do?
I know I can make the OS myself, but I think it is just a little stuipd to just config a wifi to compile the whole OS!
Any help?

**Comment by mdevaev** [comment]
It described in the doc:
https://github.com/pikvm/pikvm/blob/master/pages/flashing_os.md#the-final-steps
