### ISSUE TITLE
relative mouse - scale sensitivity according to viewport

### ISSUE THREAD

**Issue by benbarkay** [pikvm/pikvm#281]
Using pikvm with relative mouse in a scaled viewport causes the mouse to move too fast if the viewport is bigger than the source, or too slow if the viewport is smaller than the source.

**Comment by mdevaev** [comment]
@benbarkay boop

**Comment by benbarkay** [comment]
@mdevaev Sorry, did not receive notification for your first reply.

I use Chromium. The viewport of the "server" is 720p (Android), and I run the browser in a 4k monitor.
Let me know if I can be of any more help

**Comment by mdevaev** [comment]
I'm just letting you know that I haven't forgotten about it. I'll get a high-resolution screen and try to figure it out. Or at least I will make a slider for the sensitivity of the mouse.

**Comment by benbarkay** [comment]
@mdevaev that would be really great.
Please let me know if I can be of any help.

**Comment by mdevaev** [comment]
Done. Will be available in the next release.
