### ISSUE TITLE
VNC logging to keyboard

### ISSUE THREAD

**Issue by june012006** [pikvm/pikvm#284]
When I attempt to connect using bVNC to the PI-KVM, the software immediately begins dumping what appears to be logs directly into the keyboard input, with no way to interrupt.

**Comment by mdevaev** [comment]
Sorry I don't understand this

**Comment by june012006** [comment]
Here is what gets typed to my server, captured after loading notepad.
![image](https://user-images.githubusercontent.com/74912214/115257046-5c3f0e00-a0f5-11eb-9783-efd8c91310df.png)

**Comment by mdevaev** [comment]
I believe this is a bVNC problem. Pi-KVM can't get this text in any way.

**Comment by mdevaev** [comment]
No anwer or not a bug.
