### ISSUE TITLE
I connected to a HDMI switch of aimos, but I couldn't find ttyusb in the /dev file

### ISSUE THREAD

**Issue by binbinshare** [pikvm/pikvm#287]
I connect a USB-A to Micro USB cable from the Raspberry Pi4B to the management port on the side of the aimos switch.But  I couldn't find ttyusb in the /dev file,need any operation？

**Comment by mdevaev** [comment]
AIMOS is not supported by the pikvm driver. We don't have a description of the protocol to do external management. Probably, AIMOS is not capable of this at all.

**Comment by binbinshare** [comment]
![image](https://user-images.githubusercontent.com/45224459/116497085-1e05d380-a8d9-11eb-9630-5a771ceecf62.png)
This page has been written to test aimos. In addition, I tried to connect the mouse and keyboard directly to raspberry 4b, and there was no ttyusb file.

**Comment by mdevaev** [comment]
This page does not say that there is a channel switching driver for aimos.

**Comment by binbinshare** [comment]
Raspberry pi 4B keyboard and mouse, dev folder does not appear ttyusb file, normal？On raspberry pi 4b, a USB keyboard and aimos are connected. Enter dmesg, and the following message will be displayed：
![image](https://user-images.githubusercontent.com/45224459/116497838-de3feb80-a8da-11eb-8e0d-41f903d96138.png)

**Comment by mdevaev** [comment]
I'm confused. Is this log on the pikvm when connecting the AIMOS control port? If so, then everything is clear: the device is not recognized by the kernel. If AIMOS works the same way as some other switches I've seen, then it's actually not USB (although it uses this connector), but UART. You can't manage it from Linux.

**Comment by binbinshare** [comment]
![image](https://user-images.githubusercontent.com/45224459/116499331-830ff800-a8de-11eb-8ba5-555f92c7d434.png)
AIMOS switch port is usb,this log on the pikvm is  connecting a USB-A to Micro USB cable from the Raspberry Pi4B to the management port on the side of the aimos switch.
![image](https://user-images.githubusercontent.com/45224459/116499479-d41fec00-a8de-11eb-9fbe-0c51cfc58f86.png)

**Comment by mdevaev** [comment]
Why do you think this is USB? Judging by what I see on the board, a button is connected to the lines on the "USB". It's definitely not USB.

Do you have this button? Disassemble it please:
![image](https://user-images.githubusercontent.com/416259/116499829-c73ad280-a8b5-11eb-834c-d50144496968.png)

**Comment by GrafDe** [comment]
I have the same device. This is not a usb device. it's just a micro-USB connector in which two wires lead to the button. For this device to switch (between hdmi ports), it must be connected to a relay that will close these two wires like this button (as button in pic).

**Comment by mdevaev** [comment]
Answered I guess
