### ISSUE TITLE
macOS 11.3 Recovery Mode stuck at "no mouse" screen

### ISSUE THREAD

**Issue by KarimGeiger** [pikvm/pikvm#289]
**Describe the bug**
With the latest version of macOS (11.3), the recovery mode cannot be used using PiKVM without an external mouse connected (on a Mac mini). When booting into recovery mode, the following screen appears, indicating that no mouse could be found.
![Screen Shot 2021-04-30 at 09 55 40](https://user-images.githubusercontent.com/2329930/116661515-39d2ad80-a99d-11eb-967b-169cc9ff146e.png)

This screen also appeared in the versions before, however, it could be dismissed by clicking the mouse/pressing a key. Now, there is no (known) way to work around this screen. Interestingly, the mouse cursor through PiKVM is begin shown and can be moved (i can even click the menu options on the top of the screen).

**To Reproduce**
Steps to reproduce the behavior, like:
1. Connect a Mac with macOS 11.3 to PiKVM (I'm using an M1 model) without a mouse attached
2. Boot into recovery mode (Command + R on Intel, hold power button on M1)
3. Try to get past the "no mouse" screen

**Expected behavior**
The "no mouse" screen should either not show or should be dismissable.

**Screenshots**
see above

**Desktop (please complete the following information):**
 - OS: mac
 - Browser firefox
 - Version 88
 - VNC client (if used): no

**Pi-KVM info:**
  - Raspberry Pi board version: RPi 4
  - Pi-KVM platform: kvmd-platform-v2-hdmi-rpi4 2.59-1
  - Video capture type: CSI bridge
  - KVMD version: kvmd 2.59-1
  - uStreamer version: ustreamer 3.27-1
  - Linux kernel:  5.10.32-2-ARCH #1

**Comment by mdevaev** [comment]
Hi. Do you use Arduino Hid?

Пт, 30 апр. 2021 г. в 10:23, Karim Geiger ***@***.***>:

**Comment by KarimGeiger** [comment]
Hi @mdevaev, thanks for your quick reply! No, I'm not using Arduino for HID. Just the split USB cable on the Raspberry Pi.

**Comment by mdevaev** [comment]
Try relative mouse mode: https://github.com/pikvm/pikvm/blob/master/pages/mouse.md

**Comment by KarimGeiger** [comment]
Thanks for the tip. I just tried it and it seems to make no difference. I can still move the mouse on the Mac but the screen won't go away. I tried both modes (with horizontal_wheel on and off) and rebooted both devices, but no luck 😞

**Comment by mdevaev** [comment]
Mac has some kind of generic mouse problem. I'm working with earlier macs and arduino hid (similar issue), but it looks like there's something very unusual there. Now I'm waiting for the USB protocol analyzer to figure this out.

**Comment by KarimGeiger** [comment]
Thank you for looking into it. If I can be of any help, please let me know.

**Comment by KarimGeiger** [comment]
Just had an idea: Since the mouse input seems to be working quite fine, I'm assuming that "no mouse" screen is an artificial lock put in place by Apple because they didn't recognize the USB device as a mouse. Therefore, would it be possible to just simulate a virtual mouse device that's connected via USB? (Similar to how you're simulating a USB stick?) I don't think it actually needs to do anything, I'm assuming it just needs to be there so macOS is happy.

Sorry if that makes no sense, though. I'm really not a hardware guy, otherwise I'd try verifying my idea myself.

**Comment by mdevaev** [comment]
We are already emulating a USB mouse. This is some kind of bug on the Apple side, now we are figuring out how to solve it.

**Comment by mdevaev** [comment]
I think I found out what the problem is. The fix for Arduino HID is already ready and will be available in the release soon, testing is needed for OTG and M1.

**Comment by mdevaev** [comment]
Fixed. See details here: https://www.reddit.com/r/pikvm/comments/ohmx8j/kvmd_38_the_epic_apple_fix/

**Comment by KarimGeiger** [comment]
Thank you very much for fixing this! Really appreciated!
