### ISSUE TITLE
Feedback on the use of raspberry 3a

### ISSUE THREAD

**Issue by wnark** [pikvm/pikvm#295]
I use the v0 solution, and the raspberrypi3B method is successful on raspberrypi3a.
![IMG_20210505_210910](https://user-images.githubusercontent.com/24355466/117145854-2f257780-ade6-11eb-92ce-1e2539297b02.jpg)
I found that when using a mobile power bank and the same power cord, raspberrypi3B will report that the voltage is insufficient, while raspberrypi3a is normal。
Now there is a question, how to manually add an emulated mass storage device to it on the web side?
![image](https://user-images.githubusercontent.com/24355466/117146395-becb2600-ade6-11eb-8694-ffcdbd0fb3be.png)

And I found that the v0 version does not seem to have automatic partition expansion.
![image](https://user-images.githubusercontent.com/24355466/117146258-99d6b300-ade6-11eb-8fb8-c1c3e2b0bc23.png)

——————————————————————————————————————————————

The usb-a of the Raspberry Pi 3A seems to be able to be simulated as a large-capacity device, although I am not sure how to implement it

https://hexdocs.pm/nerves_system_rpi3a/readme.html

https://gist.github.com/gbaman/50b6cca61dd1c3f88f41

——————————————————————————————————————————————
https://github.com/pikvm/pikvm/issues/158

If you need rj45, you can use this method
_______________________________________________________________________________________________________________

**Comment by wnark** [comment]
I was wondering, can I use raspberrypi4B mirroring directly on raspberrypi3A, and then modify a certain configuration file, modify the USB ID?, convert usbc into a large-capacity device, and convert usba into a large-capacity device.
Since Raspberry Pi 3a and 4a are both arm, although their architecture is different, they may be compatible. (It’s just that I don’t know which file to modify) lol

**Comment by wnark** [comment]
There is another question. Since the RAM of the Raspberry Pi 3a is only 512M, maybe I change the root directory to be writable, and then I can mount the swap partition in a normal Linux way? Or use the unallocated partition of the tf card as the swap partition?
Can this improve the problem of long-time use of the screen and operation freeze?

**Comment by wnark** [comment]
Very strange, it was very smooth at first, but it didn't take long for the keyboard and mouse to react very slowly, and the picture dropped from 30 to 2 frames.
At first I thought it was the reason for the lack of memory. It seems that compatibility is still not good somewhere?

**Comment by mdevaev** [comment]
Sorry, I understand nothing. What are you trying to do?

**Comment by wnark** [comment]
![image](https://user-images.githubusercontent.com/24355466/123093687-8d71ec80-d45e-11eb-8ce0-454bd63ffa47.png)
![image](https://user-images.githubusercontent.com/24355466/123093852-c14d1200-d45e-11eb-8be2-c3db3d4ef787.png)
It is not recommended to use Raspberry Pi 3A. The internal bus transmission speed of Raspberry Pi 3A may be only 14Mb, which will not fully utilize the performance of Raspberry Pi 3A.

**Comment by wnark** [comment]
I was planning to use the USB port of the Raspberry Pi 3A to simulate the device, so I did not use the USB network card. It seems that using w5500 or wifi is too slow and not suitable for use, so the plan to use Raspberry Pi 3A instead of Raspberry Pi 4B failed.

**Comment by wnark** [comment]
If the USB port is occupied in order to use the USB network card, it is better to use Raspberry Pi 2b, which costs less

**Comment by wnark** [comment]
```
[root@ipmi ~]# lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
emmm,The USB port of the Raspberry Pi 3A is not directly connected to the chip, and it cannot replace the Raspberry Pi 4B.

**Comment by mdevaev** [comment]
I have never held this device in my hands and I don't know what to tell you, sorry :(

**Comment by mdevaev** [comment]
I suppose I can close it. This is interesting information, but no work is expected here.
