### ISSUE TITLE
Cannot connect to host computer from RPI Zero W

### ISSUE THREAD

**Issue by scottnapleton** [pikvm/pikvm#298]
**Describe the bug**
I have RPI Zero W connected to Geekworm HDMI to CSI-2 (https://www.amazon.com/gp/products/B0899L6ZXZ/). I'm up to the step where I have connected to the Pi from a client computer and I get the following screen:
![IMG_0480](https://user-images.githubusercontent.com/83878409/117546921-d3800780-affa-11eb-86fd-4d4cace9cea6.jpg)

I have verified that the host computer is producing HDMI output and the Module recognizes that there is video attached. Also the device manager recognizes the the mouse and keyboard being emulated by the Pi Zero W.

Here is a picture of my setup:
![IMG_0479](https://user-images.githubusercontent.com/83878409/117546924-da0e7f00-affa-11eb-914c-48e2b21b9a12.jpg)

I've tried flashing and formatting the SD card multiple times. I have also swapped out numerous USB cables and tried adjusting the ribbon between the Pi and Geekworm module numerous times. I've run out of ideas at this point. Any help is greatly appreciated.

**Comment by mdevaev** [comment]
Which browser do you use?

**Comment by arch1mede** [comment]
I tried to assist this person and he logged off the server without a proper response, I would recommend this issue be closed as this appears to be due to something on the OS environment at play since he gets the same thing using Chrome/Incog and FF/Private window

**Comment by scottnapleton** [comment]
I just tried using a different client computer and was able to connect with no problem. I cannot figure out why the first client was unsuccessful but the issue must lie somewhere on my end.

**Comment by mdevaev** [comment]
Okay.
