### ISSUE TITLE
create permanent machine-id in _pikvm-bootconfig.sh

### ISSUE THREAD

**Issue by ComputerDoktor** [pikvm/pikvm#304]
/etc/machine-id size 0 in the distribution image should trigger systemd-machine-id-setup once in order to create a permanent machine-id. Because /etc is mounted read-only, /etc/machine-id is mapped to /run/machine-id, machine-id recreated at each boot. machine-id is used to build the DHCP client-id by the dhcp client integrated in systemd-networkd, so you get a new IP address at each reboot.

_systemctl start systemd-machine-id-commit.service_

**Comment by mdevaev** [comment]
Thanks! Will be available in the next os release.
