### ISSUE TITLE
ability to disable/enable HID on the fly

### ISSUE THREAD

**Issue by conix67** [pikvm/pikvm#307]
PIKVM session runs in a web browser which is just one of the apps running on a desktop. In some occasions, PIKVM session is used as virtual monitor to observe things happening on the target system but having mouse cursor over or across the PIKVM session window will inject mouse activities on the target system. This is fine in most cases but if the system is running something that uses mouse cursor control, either by someone or through scripted automation, the activity can be influenced by the mouse activities from the system where the PIKVM session is active. This can be better controlled if PIKVM provides user control over HID feature - disable/enable on the fly - and allow PIKVM to operate in pure virtual monitor mode when needed.

**Comment by mdevaev** [comment]
Will be available in the next release
