### ISSUE TITLE
Q. What program creates the virtual keyboard please?

### ISSUE THREAD

**Issue by CaptainMidnight** [pikvm/pikvm#310]
Can I simply ask, which program runs to create the virtual keyboard please?

**Comment by mdevaev** [comment]
You mean, how is the keyboard made in the web UI?

**Comment by CaptainMidnight** [comment]
Ah right, my mistake I thought the web UI was like a http vnc 'type' session with a keyboard overlay.

I see now it's more like a web page with the remote system screen as an in lay.

Sorry for my misunderstanding.

**Comment by CaptainMidnight** [comment]
Misunderstanding of system display format.
