### ISSUE TITLE
Terminal UI

### ISSUE THREAD

**Issue by harry2289** [pikvm/pikvm#311]
Hi, i want to add a message and a picture in the Terminal WEB UI. That is accessed from the terminal logo in the kvm. I can't find any html file for the terminal interface, can you tell me from where i can edit the content to add a picture or just plain text. I want to add some instructions on how to install my program with the use of some commands. Please respond as quick as possible because i want to use this in my school project and the deadline is near, any help is appreciated.

**Comment by srepac** [comment]
The file to modify is `/etc/motd`

**Comment by harry2289** [comment]
Thanks a lot, I was able to modify the file.
