### ISSUE TITLE
Which HDMI to CSI device choice?

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#312]
hi, i want to buy HDMI to CSI, but i found 2 different boards, which is the best?
[Link1](https://www.banggood.com/New-Version-HDMI-To-CSI-2-Adapter-1080p-25fps-For-Raspberry-Pi-Zero-PI-3B-4B-+-p-1748184.html?cur_warehouse=CN) [link2](https://www.banggood.com/HDMI-Adapter-Board-HDMI-to-CSI-2-TC358743XBG-for-Raspberry-Pi-3B-3B+-Zero-p-1748182.html?cur_warehouse=CN)

**Comment by mdevaev** [comment]
There is no difference
