### ISSUE TITLE
If piKVM is the second monitor with Debian host, mouse tracking is wrong

### ISSUE THREAD

**Issue by SimplicityGuy** [pikvm/pikvm#314]
If the piKVM is set as the second monitor extending to the right of the primary screen, mouse tracking in the web UI is incorrect. The host machine is Debian 10; piKVM is the latest version.

**Comment by joBr99** [comment]
Change your mouse mode from absolute to relative in override.yaml, that will solve your problem. (se absolute to false)

https://github.com/pikvm/pikvm/blob/master/pages/mouse.md

**Comment by mdevaev** [comment]
All as mentioned above. The absolute mouse cannot work in multi-screen mode, sorry.
