### ISSUE TITLE
Issue with progress bar of file uploading

### ISSUE THREAD

**Issue by al-pankov** [pikvm/pikvm#321]
**Describe the bug**
Progress bar not match file uploading process.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to 'KVM-mode'
2. Click on 'Drive - Select image to upload - Upload'
3. See error

**Expected behavior**
PiKVM is connected via WiFi. I tried to upload a 5GB ISO file. The file upload bar filled up after 5 seconds, but the upload process continued.

**Screenshots**
![2021-05-25 15_25_42-Window](https://user-images.githubusercontent.com/48507823/119499589-89738180-bd6f-11eb-801d-c84fb2e547fa.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Google Chrome
 - Version: 90
 - VNC client: not used

**Pi-KVM info:**
  - Raspberry Pi board version: RPi 4
  - Pi-KVM platform: v2-hdmi
  - Video capture type: CSI bridge
  - KVMD version: 2.72-1
  - uStreamer version: 3.27-1
  - Linux kernel: pikvm 5.10.23-2-ARCH #1 SMP Thu Mar 18 18:33:35 MSK 2021 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Is this problem reproducible or only occurred once?

**Comment by al-pankov** [comment]
It's occurs every time with big files, but if file is smaller then progress bar filling looks like normal.
I recorded a screencast that show the problem.
https://user-images.githubusercontent.com/48507823/119850984-b44c0a00-bf16-11eb-8bdd-e8e68518e5e9.mp4

PS. With latest kvmd 2.80 the problem persist.

**Comment by mdevaev** [comment]
Does this sound like your problem from the description? https://stackoverflow.com/questions/42516195/xmlhttprequest-wrong-progress

**Comment by mdevaev** [comment]
I can't reproduce it on my win10 machine and 6Gb image. Are there any additional conditions?

**Comment by mdevaev** [comment]
I've made a server-side download percentage calculation. I think it will solve the problem. It will be available in the next release.
