### ISSUE TITLE
Support "reduced motion"

### ISSUE THREAD

**Issue by abh** [pikvm/pikvm#324]
The "your mouse pointer is hidden" banner animation makes me nauseous. I tried figuring out where it comes from to help with a patch, but I couldn't find it in any of the pikvm code.

Please support "reduced motion" if the user has requested that: https://webkit.org/blog/7551/responsive-design-for-motion/

For example for this banner, just have it be an overlay that doesn't move the rest of the screen; or if it has to be put on top, then put it on top but don't animate moving the rest of the screen.

**Comment by abh** [comment]
<img width="1336" alt="Screen Shot 2021-05-28 at 23 11 11" src="https://user-images.githubusercontent.com/16861/120060098-99f35880-c00a-11eb-859c-ca6ba08fbcb5.png">

Highlighted it with a purple box. The banner is fine, but the animation that makes it fade up and down (and moves the content) makes me feel sick (from a vestibular disorder).

**Comment by mdevaev** [comment]
This banner is generated by the browser itself, I can't change it.

**Comment by abh** [comment]
> On May 28, 2021, at 23:20, Maxim Devaev ***@***.***> wrote:
> 
> This banner is generated by the browser itself, I can't change it.
> 
What's the API that makes the banner show? I can make a bug for that instead.

**Comment by mdevaev** [comment]
Is it Safari?

**Comment by mdevaev** [comment]
Sup?

**Comment by abh** [comment]
Yes, Safari!

**Comment by mdevaev** [comment]
I'll dust off the macbook and check it out

**Comment by mdevaev** [comment]
This API is `requestPointerLock()`. Each browser handles this in its own way and I really can't change this behavior. I think you should either use Chrome or ask Apple to fix it. I'm sorry, but it's impossible to do without this API for relative mouse mode.

**Comment by abh** [comment]
Brilliant — thank you. I will make an appropriate bit of feedback for that API.

**Comment by mdevaev** [comment]
Perfect
