### ISSUE TITLE
Pi0 W doesn't connect to WiFi channel 13

### ISSUE THREAD

**Issue by AndreaPro** [pikvm/pikvm#357]
**Describe the bug**
After the image is written on the Pi0 W and WiFi is configured the device doesn't connects to the WiFi network

**To Reproduce**
Steps to reproduce the behavior, like:
1. Download PiKVM image and write it to a micro SD
2. Configure WiFi following instructions on GitHub
3. The device is not recognised by the WiFi network even after multiple reboots if WiFi 2,4 GHz is on Channel 13

**Expected behavior**
The Pi0 W should be able to connect to the WiFi network

**Pi-KVM info:**
  - Raspberry Pi board version: Pi0 W
  - Pi-KVM platform: v2 CSI
  - Video capture type: CSI bridge
  - KVMD version: 
  kvmd 3.6-1
  kvmd-fan 0.1-1
  kvmd-oled 0.3-1
  kvmd-platform-v2-hdmi-zerow 3.6-1
  kvmd-webterm 0.39-1
  - uStreamer version: ustreamer 4.4-1
  - Linux kernel: Linux pikvm 5.10.23-2-ARCH #1 SMP Fri Mar 19 02:47:42 MSK 2021 armv6l GNU/Linux

**Additional context**
After various attempts I've been able to connect the Pi0 to my WiFi network but I needed to change the WiFi channel from 13 to 4. I have tried installing on the microSD Raspbian Lite and even this one was unable to connect to the network, but it worked if inside the WiFi configuration of the Pi0 if I removed the country code. By looking at the Pi forums it appears to be a common issue, so probably not something that can be solved by PiKVM, but maybe could be useful to note inside the installation instructions that if the device is unable to connect could be worth to change the 2,4 GHz WiFi channel

**Comment by arch1mede** [comment]
Please review https://wiki.archlinux.org/title/Network_configuration/Wireless, specifically this command:
```iw dev wlan0 connect your_essid 4```
You must be outside the US as we do not have a channel 13, looks like by default you already applied the firmware to allow to get to channel 13 as I have read here: https://tosbourn.com/get-channels-12-and-13-on-the-raspberry-pi-3/? I would ask in the arch linux discord or post something on the raspberry pi forums if this is something you really want to pursue. This is not a pikvm issue however you are more than welcome to join the discord to chat with us about it, maybe someone there "might" be able to assist but I haven't actually seen anyone ever ask for a specific channel in the 2.4 Ghz to be used over the default.

I am recommending this be closed.
