### ISSUE TITLE
Can't build for RPI2 (broken QEMU 5.1.0)

### ISSUE THREAD

**Issue by ech1965** [pikvm/pikvm#36]
Dear,

I'm trying to build an image for my RPI2 + HDMI CSI Hardware.
I followed instructions in building_os.md but build fails:

`Step 21/77 : RUN gcc -fPIC -shared -o /usr/local/lib/libpreload-semop.so /tmp/semop-wrapper.c
 ---> Running in 5cfe33b6374d

Allocating guest commpage: Operation not permitted

The command '/bin/sh -c gcc -fPIC -shared -o /usr/local/lib/libpreload-semop.so /tmp/semop-wrapper.c' returned a non-zero code: 1

make[1]: *** [Makefile:209 : os] Erreur 1
make[1] : on quitte le répertoire « /home/tsos/os/.pi-builder »
make: *** [Makefile:53 : os] Erreur 2
`

Freshly installed Ubuntu 20.04 server in a Virtualbox VM ( macos host)

Please help !
Etienne

**Comment by mdevaev** [comment]
For the protocol: the QEMU version is fixed for 5.0.0. Let's continue discussing the other issues in discord.

**Comment by ech1965** [comment]
Bug reported upstream: https://bugs.launchpad.net/qemu/+bug/1891748

@mdevaev : Thanks a lot for your help preparing the reproduction steps.

**Comment by mdevaev** [comment]
Related: https://bugs.launchpad.net/qemu/+bug/1880225

Still not fixed but at least we have workaround.

**Comment by mdevaev** [comment]
https://patchwork.ozlabs.org/project/qemu-devel/patch/1273756645-11149-1-git-send-email-Martin.Jansa@gmail.com/

**Comment by mdevaev** [comment]
TODO: report here: https://gitlab.com/qemu-project/qemu/-/issues

**Comment by mdevaev** [comment]
Fixed in dev branch, will be available in QEMU 7.0
