### ISSUE TITLE
Can't Input "IntelYen" key.

### ISSUE THREAD

**Issue by kumama** [pikvm/pikvm#373]
Hi,

The key "IntelYen" generate no input.

In my investigation, "Virtual Keyboard" has no data-code="IntelYen".
So webclient does not send IntelYen key event to server.

After adding the data-code="IntelYen" to "Virtual Keyboard",
Next time mappings.py is missing "IntelYen".
Adding KEYMAP to IntelYen, I can input IntelYen to host.

about "IntelYen"  see below.
https://www.w3.org/TR/uievents-code/#keyboard-101alt

Regards.

**Comment by mdevaev** [comment]
Hi! Will be available in the next release.
