### ISSUE TITLE
can't find iso image from BIOS boot menu

### ISSUE THREAD

**Issue by liyejun** [pikvm/pikvm#403]
I installed pikvm in a raspberry pi 4, keyboard/mouse is working,  can remote control the host in browser as well.

I uploaded a win10 iso via web UI, and status showed as "connected", but I can't find the os from bios boot menu after I reboot the host.

**Comment by mdevaev** [comment]
Sup. See here: https://github.com/pikvm/pikvm/blob/master/pages/msd.md#create-a-microsoft-windows-based-flash-disk-image

**Comment by mdevaev** [comment]
Solved I guess
