### ISSUE TITLE
Portal is not accessible if you disable ipv6

### ISSUE THREAD

**Issue by arch1mede** [pikvm/pikvm#409]
Per this [page](https://github.com/pikvm/pikvm/blob/master/pages/webrtc.md#troubleshooting), the portal is not accessible if you disable ipv6

```
Jul 20 17:10:30 epikvm nginx[614]: 2021/07/20 17:10:30 [emerg] 614#614: socket() [::]:80 failed (97: Address family not supported by protocol)
```

**Comment by mdevaev** [comment]
Replaced `ipv6.disable=1` to `ipv6.disable_ipv6=1` option.

https://wiki.archlinux.org/title/IPv6#Disable_IPv6
