### ISSUE TITLE
password for kvmd-webterm

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#415]
Hi, i want to install [duplicati](https://xo.tc/installing-duplicati-on-an-arch-linux-laptop.html) from this tutorial, but when i want to run `makepkg -si`, kvmd-webterm ask me a password, but "root" and "admin" not give me root access from web console:
![image](https://user-images.githubusercontent.com/20506433/126991071-09b55583-61df-4aa9-9f2d-f59e3d4b5c8c.png)

from ssh, i logging as root user by "root"username and password. When i want to run `makepkg -si` i receive this:

![image](https://user-images.githubusercontent.com/20506433/126991260-f60af63d-16b2-46a1-aca0-f60a630a6e5b.png)
i changed default password, but not helped.

**Comment by connected201** [comment]
i able ti install with these steps:
as root from ssh i installed dependencies for duplicati and git
pacman -Sy gtk-sharp-2 mono git
git clone https://aur.archlinux.org/duplicati-latest.git

as user from web interface:
cd duplicati-latest
makepkg # wait for installation complete

but i cannot run it because as root i receive
![image](https://user-images.githubusercontent.com/20506433/126993755-5d2c7451-a44d-43f3-b353-033f2c71c5b0.png)
as user, i need to enter password, but admin and root password not valid
![image](https://user-images.githubusercontent.com/20506433/126993269-c6351d69-5843-43e1-b2af-04c9e49d0a78.png)

**Comment by mdevaev** [comment]
kvmd-webterm does not have a password. To switch to root, use `su -`.
To build package switch to root then change directory (`cd`) and build packages using `sudo -u kvmd-webterm makepkg ...`.

**Comment by connected201** [comment]
thanks, i able to install with sudo -u kvmd-webterm makepkg
but i cannot run 
```
systemctl enable duplicati.service
systemctl start duplicati.service
```
also i tried with
`sudo -u kvmd-webterm` but no results, any idea?

![image](https://user-images.githubusercontent.com/20506433/127157058-2738e8af-3587-449d-bcba-6d222280910e.png)

**Comment by connected201** [comment]
also, i nstalled AUR package manager, but when i want to run `sudo -u kvmd-webterm yay`
i received
`[kvmd-webterm@pikvm(g:master) g:/]$ sudo -u kvmd-webterm yay
kvmd-webterm is not in the sudoers file.  This incident will be reported.`
i just want to install some additional tools, but i unable to run it!

**Comment by mdevaev** [comment]
under kvmd-webterm user you don't need to make sudo again

**Comment by connected201** [comment]
i had problem when i want to install something,
```
[root@pikvm(g:master) g:/]# sudo -u kvmd-webterm makepkg -si
==> ERROR: Failed to create the directory $BUILDDIR (/root/yay).
```
 but i resolve with folder rights
`chmod 777 /root/appfolder`

**Comment by connected201** [comment]
right now i have problem, i cannot use apps installed from other sources. only apps installed for pacman can work (`pacman -S appname`)
```
[kvmd-webterm@pikvm(g:master) g:/]$ yay
bash: yay: command not found
[kvmd-webterm@pikvm(g:master) g:/]$ su -
Password: 
[root@pikvm ~]# yay
-bash: yay: command not found
[root@pikvm ~]# 
```

**Comment by mdevaev** [comment]
makepkg does not install the package, use `pacman -U ...` on built package

**Comment by connected201** [comment]
All working great, thanks for help!

**Comment by mdevaev** [comment]
Welcome!
