### ISSUE TITLE
When you will start crowdfunding ?

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#423]
hi, i want to buy your shield, when it will be possible?

**Comment by mdevaev** [comment]
Hello. In a week or two. Subscribe here so you don't miss it: https://www.kickstarter.com/projects/mdevaev/pikvm-v3-hat

**Comment by connected201** [comment]
Subscribed, thanks, and best regards, pikvm is most advanced KVM ever.

**Comment by mdevaev** [comment]
:ok_hand:
