### ISSUE TITLE
Mobile Built-in Keyboard Support

### ISSUE THREAD

**Issue by joeljacobs** [pikvm/pikvm#426]
**Describe the bug**
On iOS at least, tapping inside the KVM stream window does NOT bring up the built-in keyboard. Instead, you need to use the Pikvm on-screen keyboard, which is far too large and doesn't fit on the screen with the kvm view. 

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to the KVM screen
2. Tap on the KVM stream
3. Nothing happens
4. Bring up PiKVM virtual keyboard
5. PiKVM virtual keyboard obstructs KVM stream

**Expected behavior**
Tap in the KVM stream window, and built-in iOS keyboard would come up to interact.

**Screenshots**
https://share.icloud.com/photos/0FY5cwVnaPLKKwBhk5KqTVy8Q

**Desktop:**
 - OS: iOS
 - Browser: both chrome and Safari
 - Version: iOS 13 lastest

**Pi-KVM info:**
  - RPi 4
  - Pi-KVM platform:  v2-hdmi
  - Video capture type: CSI bridge
  - KVMD version: 3.5-1
  - uStreamer version: 4.4-1
  - Linux kernel: Linux pikvm 5.10.23-2-ARCH #1 SMP Thu Mar 18 18:33:35 MSK 2021 armv7l GNU/Linux

**Additional context**
I would imagine (though I can't test) that this problem exists on Android as well

**Comment by mdevaev** [comment]
Hi! The built-in keyboard is useless and does not contain all the necessary keys. I will try to find out why this is not happening.

**Comment by mdevaev** [comment]
I've tested on iPad pro 2016 with iOS 14 and it's working fine. Please specify which device you use.

**Comment by mdevaev** [comment]
There is no necessary information.
