### ISSUE TITLE
Mount RW mass storage device?

### ISSUE THREAD

**Issue by SaulGoodman1337** [pikvm/pikvm#429]
Hi,
is it possible to mount an image as RW?

I have an old Macbook without screen in the living room closet running a Proxmox. First of all, thanks for the Apple UEFI Keyboard fix !
I also have a LIVE Macos USB stick for the EFI emergency. 
Now I think I could save the USB slot for the stick by simply emulating the stick with the Pi.

thank you and ... awesome project.

**Comment by mdevaev** [comment]
Hello. Take a look at this: https://github.com/pikvm/pikvm/blob/master/pages/msd.md#multiple-and-writable-drives

**Comment by mdevaev** [comment]
Also we have #21 as feature request.
