### ISSUE TITLE
WIFI_ESSID fails if the ESSID has spaces

### ISSUE THREAD

**Issue by bbeaudoin** [pikvm/pikvm#43]
My wireless network ESSID is "GET OFF MY LAN". When configuring Arch Linux wireless using wifi-menu in rw mode, it creates an interface that netctl can enable; when escaped by `systemd-escape` the output, and device-specific unit file, appears as

~~~
wlan0\x2dGET\x20OFF\x20MY\x20LAN
~~~

During the build process ("Building OS"), `make os` calls `docker build` with the `WIFI_ESSID='GET \` resulting in

~~~
/bin/sh: 12: Syntax error: Unterminated quoted string
~~~

Looks like `BUILD_OPTS` of `~/os/.pi-builder/Makefile` (line 35) may be splitting based on the IFS, ignoring the quotes around the variable name. Unfortunately, and admittedly, it's been a while since I've coded a Makefile, for now I've created an alternate ESSID without special characters or spaces and was able to complete the build successfully.

**Comment by nohajc** [comment]
@bbeaudoin I had a similar problem (wifi password containing spaces) and I've solved it by shell escaping (`\ `) in the Makefile.

**Comment by mdevaev** [comment]
Fixed here: https://github.com/pikvm/os/pull/10
