### ISSUE TITLE
pikvm password protect of access webinterface

### ISSUE THREAD

**Issue by Morta1985** [pikvm/pikvm#436]
When i add this two lines in /etc/kvmd/nginx/nginx.conf

server{
..
auth_basic "Administrator Login";
auth_basic_user_file /etc/kvmd/nginx/.htpasswd;
}

The password prompt is coming but after that the normal login of pikvm doesn't work.
Why?

**Comment by mdevaev** [comment]
Because pikvm has an alternative authorization method using http basic.

Why do you need this?

**Comment by Morta1985** [comment]
because i have a reverse proxy which is directly in the internet

Maxim Devaev ***@***.***> schrieb am Fr. 3. Sept. 2021 um
02:26:

**Comment by mdevaev** [comment]
forward pikvm backend without authorization, it has own

**Comment by mdevaev** [comment]
@hugomon noauth mode described in the faq

**Comment by adamoutler** [comment]
Can you post a link to noauth mode? 
This is literally the only result on google.  
![image](https://user-images.githubusercontent.com/527919/176286956-0b4aa6e0-54e3-4616-a431-ce354e421676.png)

**Comment by mdevaev** [comment]
> How do I completely disable authorization in PiKVM?

https://docs.pikvm.org/faq/#first-steps
