### ISSUE TITLE
Hdmi-to-CSI-2 Module with Toshiba TC358743XBG chip not working

### ISSUE THREAD

**Issue by antwal** [pikvm/pikvm#449]
Toshiba TC358743XBG chip not working

Attach log file: [dmesg log](https://pastebin.com/XUg0YrvL)

**Pi-KVM info:**
  - Raspberry Pi board version `RPi 4`
  - Pi-KVM platform `v2-hdmi`
  - Video capture type `CSI`
  - KVMD version: `kvmd 3.23-1
kvmd-oled 0.3-1
kvmd-platform-v2-hdmiusb-rpi4 3.23-1
kvmd-webterm 0.40-1`
  - uStreamer version: `ustreamer 4.5-1`
  - Linux kernel: `Linux pikvm 5.10.60-1-ARCH #1 SMP Sat Aug 21 14:56:39 UTC 2021 armv7l GNU/Linux`

**Comment by mdevaev** [comment]
You took the wrong OS image (v2-hdmiusb) judging by the list of packages. You need v2-hdmi. Please read the description of the downloads carefully.
https://pikvm.org/download.html
