### ISSUE TITLE
Login page inputs loose focus

### ISSUE THREAD

**Issue by tryallthethings** [pikvm/pikvm#45]
**DarkSide** on Discord reported the following issue with the login page on mobile phone / tablet:

> just upgraded and now it is not possible to type user or password from web browser on tablet/smartphone. It doesn't even open the soft keyboard. I didn't tried with last updates, so i cannot figure if is an issue from this last update or from any of the last ones.

I can reproduce this on my android smartphone, Windows 10 with Firefox and Windows 8.1 with Firefox / Chrome. 

If you load the login page and just type (on PC) you can login with no problems. If you happen to click on the username or password field it looses focus and you can't enter either of the fields again reliably. Did some digging (with my very limited Javascript skills) and saw that kvmd/web/share/js/wm.js line 260 seems to grab the focus immediately when you click into any of the fields.

![ezgif-1-2a1e66d5197f](https://user-images.githubusercontent.com/11146296/90695991-cb6d1580-e27b-11ea-8b0c-9798d6135035.gif)

**Comment by mdevaev** [comment]
Fixed.
