### ISSUE TITLE
Discord invitation doesn't seem to work

### ISSUE THREAD

**Issue by e-minguez** [pikvm/pikvm#451]
**Describe the bug**
Discord invitation doesn't seem to work

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to the README
2. Click on the discord invitation

**Expected behavior**
It doesn't work

**Screenshots**
![Screenshot from 2021-09-08 16-21-41](https://user-images.githubusercontent.com/346758/132527293-0250e273-52ca-4d1e-b720-0eda2bfa5bc2.png)

**Desktop (please complete the following information):**
Irrelevant I guess

**Pi-KVM info:**
N/A

**Additional context**

**Comment by mdevaev** [comment]
Just checked, everything works. Probably some kind of temporary glitch. Try again.

**Comment by e-minguez** [comment]
You are right, it works now, thanks!

**Comment by mdevaev** [comment]
Ur welcome
