### ISSUE TITLE
Emulate mouse and keyboard via Bluetooth

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#458]
hi, it's possible to connect on remote computer with Bluetooth and control them like mouse or keyboard via Bluetooth connection?

**Comment by mdevaev** [comment]
Hi. Yes. https://github.com/pikvm/pikvm/blob/master/pages/bluetooth_hid.md

**Comment by pancsta** [comment]
Would it be possible to pair with >1 device by adding another BT adapter? Im looking to replace BT-500, as it only connects to 1 BT downstream. thx
