### ISSUE TITLE
Insignia VGA to HDMI Adaptor Displays No Signal

### ISSUE THREAD

**Issue by ossiemoore** [pikvm/pikvm#459]
**Describe the bug**
When connecting a PiKVM to the HDMI output of the Insignia VGA to HDMI Adaptor, "No Signal" is displayed. (see attached screenshot)

Device:  Inignia - VGA to HDMI Adapter
Model: NS-PCAVH
Linke to Item on BestBuy: https://www.bestbuy.com/site/insignia-vga-to-hdmi-adapter-white/6418344.p?skuId=6418344

**To Reproduce**
Steps to reproduce the behavior, like:
1. Connect VGA to HDMI Adaptor to HDMI port of computer/laptop and Pi running PiKVM
2. Login to pikvm.
3. Observe No Display  video. (example screen shot attached)
4. SSH into pikvm and run `journalctl -u kvmd | tail -n 50` and observe output similar to the following:
```
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => ================================================================================
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.584    stream] -- Device fd=15 opened
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.584    stream] -- Using input channel: 0
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.590    stream] -- Got new DV timings: resolution=1920x1080, pixclk=148500000
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.610    stream] -- Using resolution: 1920x1080
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.610    stream] -- Using pixelformat: UYVY
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.610    stream] -- Querying HW FPS changing is not supported
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.610    stream] -- Using IO method: MMAP
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.623    stream] -- Requested 5 device buffers, got 5
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- ERROR [155188.624    stream] -- Unable to start capturing: Invalid argument
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.624    stream] -- Device fd=15 closed
Sep 09 13:42:27 pikvm kvmd[421]: kvmd.apps.kvmd.streamer           INFO --- => -- INFO  [155188.624    stream] -- Sleeping 1 seconds before new stream init ...
```

**Expected behavior**
Display to show normally.

**Screenshots**

Screenshot from HP ZBook:

<img width="952" alt="Screen Shot 2021-09-09 at 5 45 54 AM" src="https://user-images.githubusercontent.com/44754148/132673002-00ff7f3a-6191-42b6-9846-2703058257fe.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox , Safari
 - Version: 91.0.2, 14.1.2
 - VNC client (if used): None

**Pi-KVM info:**
  - Raspberry Pi board version: Pi4
  - Pi-KVM platform: v2 hdmi
  - Video capture type CSI bridge
  - KVMD version:
```
[root@pikvm ~]# pacman -Q | grep kvmd
kvmd 3.7-1
kvmd-fan 0.1-1
kvmd-oled 0.3-1
kvmd-platform-v2-hdmi-rpi4 3.7-1
kvmd-webterm 0.39-1
```
  - uStreamer version: `ustreamer 4.4-1`
  - Linux kernel: `Linux pikvm 5.10.23-2-ARCH #1 SMP Thu Mar 18 18:33:35 MSK 2021 armv7l GNU/Linux`

**Additional context**
Output from `journalctl -u kvmd` command appears above.

**Comment by arch1mede** [comment]
Please join the discord for troubleshooting this. Thanks.

**Comment by mdevaev** [comment]
Some VGA converters do not respect the EDID that the video capture device provides. I recommend using a different converter.

**Comment by mdevaev** [comment]
Also you can decrease resolution: https://github.com/pikvm/pikvm/blob/master/pages/edid.md

**Comment by wcck** [comment]
Hi @mdevaev 

Excuse me, Do you recommend VGA converters except https://www.aliexpress.com/item/4000553298530.html ?
Thank you.

**Comment by arch1mede** [comment]
> Hi @mdevaev
> 
> Excuse me, Do you recommend VGA converters except https://www.aliexpress.com/item/4000553298530.html ? Or others solution to solve this problem? Thank you.

Please join Discord and review the Discord pins, there are some vga adapters that have been vetted.

**Comment by wcck** [comment]
Hi @arch1mede 

Thank you for your response.
I had joined discord and search this solve I will try that.
Thank you.

**Comment by wnark** [comment]
![fbe6768257c902bea19fe13204b8843](https://user-images.githubusercontent.com/24355466/187131172-52cd1ee6-577c-4c8d-adfa-76074365dbac.jpg)
When your resolution is constantly changing, you can use this device, the Chinese name is "HDMI锁屏宝"：hdmi lock screen treasure
it can lock the resolution at a certain value, such as 1080P, so that VGA TO HDMI will not be unusable due to constant switching of resolutions.
@mdevaev

**Comment by shiroha777777** [comment]
@mdevaev  Hi, could you recommend a VGA-to-HDMI converter that works with this issue? My current converter always forces the resolution and frame rate to 1080p at 60Hz, which is causing problems.

**Comment by mdevaev** [comment]
I'm not sure for 100%, but this one should work: https://www.startech.com/en-us/audio-video-products/vga2hdu
