### ISSUE TITLE
Alternative for 390 Ohm resistors.

### ISSUE THREAD

**Issue by deepwather** [pikvm/pikvm#46]
Hello mdevaev,
I would like to build the v2 version of your project for my server. But I can't get 390 Ohm resistors in Switzerland.

I have already ordered: 10 Ohm, 100 Ohm, 220 Ohm, 330 Ohm, and 470 Ohm.

Can I use one or more of these instead of the 390 Ohm?

Friendly greetings
Michael Reber

**Comment by mdevaev** [comment]
Hi. You can use 470 or 330.

**Comment by deepwather** [comment]
Thanks for the quick response, so here's what I need:

For ATX control:
4x MOSFET relays OMRON G3VM-61A1.
4x 330 Ohm resistors.
2x 4.7k ohm resistors.

What are the advantages or disadvantages if I use the bigger resistor? or are there none?

Thanks

**Comment by mdevaev** [comment]
The difference can only be noticeable in certain specific conditions. I think everything should work fine.

**Comment by mdevaev** [comment]
Feel free to reopen if needed.
