### ISSUE TITLE
PS/2 passthrough support for Arduino HID firmware

### ISSUE THREAD

**Issue by mclei-asw** [pikvm/pikvm#476]
I would like to support local console. It means VGA monitor and real PS/2 keyboard locally installed in the rack for local access in parallel to pikvm.

VGA could be easily split by Y cable. But it does not work for PS/2. So I would like to connect the real PS/2 or USB keyboard to Arduino with HID/PS2 firmware and let the Arduino to pass every key pressed on this keyboard to PS/2 output port connected to controlled computer.

This way it will be possible to remotely control the computer using pikvm console, but also locally using keyboard and LCD when present in the server room.

**Comment by mdevaev** [comment]
It's a good idea, but I can't say that we will make it a priority.

**Comment by mclei-asw** [comment]
I can sponsor somebody who is able to modify the Arduino firmware.

**Comment by mdevaev** [comment]
Okay, I'll take that into account

**Comment by No0ne** [comment]
With these two PRs this issue should be fixed/closed now:
https://github.com/pikvm/kvmd/pull/171
https://github.com/pikvm/kvmd/pull/175

**Comment by mdevaev** [comment]
I'll write some docs and close this issue, yes.

**Comment by No0ne** [comment]
Please adopt for docs.pikvm.org: https://github.com/No0ne/ps2x2pico?tab=readme-ov-file#ps2-passthru

**Comment by mdevaev** [comment]
@No0ne Thank you! I will. I completely forgot about it :(

**Comment by mdevaev** [comment]
Done.
