### ISSUE TITLE
Advanced USB Module: Missing Details / Specs 

### ISSUE THREAD

**Issue by berlin4apk** [pikvm/pikvm#477]
**Describe the bug**
For the Advanced USB Module the Details / Specs
are Missing.

e.g.  
- can it used as USB DRD (USB Dual Role Device Controller)?
- supported USB Speed to the Host?

**Comment by mdevaev** [comment]
This is a dedicated USB HID controller. We will not produce it since all the functionality has already been transferred to the Linux kernel. So there is no need to publish specifications either.
