### ISSUE TITLE
v3 HAT: SuperSpeed+ supported form the OTG / DRD controller?

### ISSUE THREAD

**Issue by berlin4apk** [pikvm/pikvm#479]
When using the pikvm as install helper / iSCSI Server,
The important factor is the supported USB Speed of the OTG / DRD controller.

Does the v3 HAT Supports SuperSpeed+?

If not Please add a USB DRD controller like
Renesas USB3.0 Peripheral controller
https://github.com/torvalds/linux/blob/master/drivers/usb/gadget/udc/Kconfig

Maybe it's also possible with a microchip USB 3.1 SmartHub IC
https://www.microchip.com/en-us/products/interface-and-connectivity/usb/usb-hubs

**Comment by mdevaev** [comment]
No, since Raspberry does not support this (it implements USB 2.0). It can work only with max High-speed mode.
