### ISSUE TITLE
Does the driver support HDCP?

### ISSUE THREAD

**Issue by wnark** [pikvm/pikvm#483]
Now there is a new HDMI-CSI HC120 version that supports HDCP, but it needs to be driven to support hdcp

**Comment by arch1mede** [comment]
Please provide a link to the board.

**Comment by wnark** [comment]
> Please provide a link to the board.

This is a link to Taobao. I don't know if there is any sales on Alibaba. It's also from Dongchong Electronics
https://item.taobao.com/item.htm?spm=a230r.1.14.33.17d63b83LhUiM5&id=602390051699&ns=1&abbucket=5#detail

**Comment by mdevaev** [comment]
As far as I know, no video capture device supports HDCP.
