### ISSUE TITLE
How to turn off VNC JPEG compression without considering traffic?

### ISSUE THREAD

**Issue by TelDragon** [pikvm/pikvm#490]
How to turn off VNC JPEG compression without considering traffic?

Continuation of previous links #471 

I still want to try using guacamole connection

**Comment by mdevaev** [comment]
You can't. The requirement to support JPEG compression is mandatory. The requirement to support JPEG compression is mandatory. Firstly, our VNC server does not support the lack of compression. Secondly, without JPEG, the traffic would have been simply huge and with a high probability Raspberry would not have coped with it.
