### ISSUE TITLE
Support for YubiKey passthrough / generic USB device passthrough?

### ISSUE THREAD

**Issue by carfesh** [pikvm/pikvm#501]
**Is your feature request related to a problem? Please describe.**
For one of the machines I am using via pikvm, I have to use a YubiKey for authentication. Currently the YubiKey is connected to the device, so I have to go to the device and physically press a button (using a finger, I don't think it reacts to other ways of pressing it) on the YubiKey when I need to authenticate. This somewhat defeats the purpose of a KVM..

**Describe the solution you'd like**
It would be awesome if I could take the YubiKey with me and pass it through to the device somehow, be it via the browser, via VNC or some other addon that might be able to achieve this. My devices are all Windows devices.
What might also work is if there was some way to remotely trigger a button press on the YubiKey.

**Describe alternatives you've considered**
No alternatives come to mind right now.

**Additional context**
This is the key I am using: https://www.yubico.com/de/product/yubikey-5-nfc/

**Comment by mdevaev** [comment]
USB passthrough is a hard and complex task. I do not know if we will be able to do this in the very near future as it requires a revision of the entire USB gadget stack. Key emulation requires writing a separate driver specifically for this key, which seems to be too resource-intensive task with a small number of users. So it is more appropriate to solve the problem in a general way.

Considering that we already have a similar task, I will close this issue as a duplicate and suggest that you subscribe and follow the other one: #195.
