### ISSUE TITLE
Removing RPi specific dependencies from kvmd

### ISSUE THREAD

**Issue by shantur** [pikvm/pikvm#505]
Bringing this from the discussion over Discord and tracking the required tasks here.

The idea is to make kvmd platform independent, currently it is dependent on RPi specific stuff which gets installed with kvmd when trying to install it on another arm platform running arch linux ( like RockPro64 )

Below are the ones which are left from my findings.

- [x] raspberrypi-firmware
- [x] raspberrypi-io-access
- [x] ustreamer with OMX
- [x] https://github.com/pikvm/kvmd/blob/master/scripts/kvmd-udev-hdmiusb-check

**Comment by mdevaev** [comment]
Moved `kvmd-udev-hdmiusb-check` to `kvmd-platform`

**Comment by mdevaev** [comment]
`ustreamer` can't be removed from dependencies, but you can build your own package like `ustreamer-generic` with `provides` and `conflicts` for it. Example: https://github.com/pikvm/packages/blob/master/packages/linux-api-headers-pikvm/PKGBUILD#L20

**Comment by mdevaev** [comment]
UPD: OMX and MMAL will be removed from streamer altogether and replaced with a V4L2 driver.

**Comment by mdevaev** [comment]
raspberrypi-io-access has been replaced by abstract platform-io-access
