### ISSUE TITLE
Feature - maximizing window

### ISSUE THREAD

**Issue by arykov** [pikvm/pikvm#509]
As discussed [here](https://discord.com/channels/580094191938437144/580094193834131456/758069937112744136) I am looking for a way to maximize use of screen real estate by maximizing streaming window.

**Comment by jrkasu252** [comment]
Hello..I am not seeing any pikvm full screen option on iPad ?

**Comment by mdevaev** [comment]
The iPad interface is a little behind in features, we will fix it at some point.
