### ISSUE TITLE
EFI boot support

### ISSUE THREAD

**Issue by MarkProminic** [pikvm/pikvm#51]
Would it be possible to boot this using Network Boot?

https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md

I am not confident in my Arch expertise, mostly CentOS, OmniOS, and Windows here. I've setup EFI Boot before with those systems. I'm sure I could, but I was curios if there are any Arch specific instructions that you could guide me on, and if I had issues I could report back here to debug it with you.

**Comment by mdevaev** [comment]
Feel free to reopen this issue if you want to continue this discussion.
