### ISSUE TITLE
Hardware orders...

### ISSUE THREAD

**Issue by noci2012** [pikvm/pikvm#525]
How to Order a piKVM. (2 actually)

I am interested and only learned about it  Oct. 28th.
Kickstarter is closed....

So the requested feature: piKVM order form / piKVM shop,

**Comment by mdevaev** [comment]
Hello. Sales will have to start around November: https://www.pishop.us/product/pikvm-v3-hat-for-raspberry-pi-4/

**Comment by mohnish82** [comment]
Please keep an open issue where interested people can +1 to express intent to buy. It would help you gauge the demand and plan for production accordingly.

I'm interested in buying when available.

**Comment by mdevaev** [comment]
Please use reddit, discord or kickstarter for this. Github is a place for technical discussions.
