### ISSUE TITLE
error: failed retrieving file 'pikvm.db' from pikvm.org : The requested URL returned error: 404

### ISSUE THREAD

**Issue by ashmodai6** [pikvm/pikvm#539]
**Describe the bug**
Error: failed retrieving file 'pikvm.db' from pikvm.org : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)

**To Reproduce**
rw
pacman -Syu

**Expected behavior**
Update works ...

**Screenshots**
N/A

**PiKVM info:**
  - Raspberry Pi board version: RPI4
  - PiKVM platform [e.g. v2-hdmi]
  - Video capture type : CSI
  - KVMD version: `pacman -Q | grep kvmd`
kvmd 3.5-1
kvmd-platform-v2-hdmi-rpi4 3.5-1
kvmd-webterm 0.39-1

  - uStreamer version: `pacman -Q | grep ustreamer`
 ustreamer 4.4-1

  - Linux kernel: `uname -a`
Linux pikvm 5.10.79-1-raspberrypi4-ARCH #1 SMP Mon Nov 15 22:18:40 UTC 2021 armv7l GNU/Linu

**Additional context**

**Comment by mdevaev** [comment]
Hello. See here: https://www.reddit.com/r/pikvm/comments/qpcww6/pikvm_infrastructure_update/
