### ISSUE TITLE
Move environment from config.mk to environment file

### ISSUE THREAD

**Issue by bbeaudoin** [pikvm/pikvm#542]
At present, `config.mk` has options for setting the wireless password, among other environment variables passed to Docker via the commandline. The suggestion is to move these into a Docker environment file instead.

Both -e and --env-file can be passed in the same line: https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

This would simpliffy the `docker` commandline in the `Makefile` by reducing the number of `-e` or `--env` flags required eliminating any possibility special characters in passphrases would be interpolated by bash when `docker run` is invoked by `make` and descoping the `Makefile` and `config.mk` for troubleshooting variable interpolation issues.

**Comment by mdevaev** [comment]
Maybe it's worth doing

**Comment by mdevaev** [comment]
I just read about this feature. Environment variables cannot be used at the `docker build` stage. Sorry.

**Comment by bbeaudoin** [comment]
Technically true, it's still possible in a few ways (https://vsupalov.com/docker-build-pass-environment-variables/). It's also possible to source the environment variables using the Makefile itself (default is to use /bin/sh, that could be changed to /bin/bash to source the environment file) to avoid the extra `make` processing of variables:

```make
# Makefile

SHELL := /bin/bash

rule:
    source env.sh && YourCommand
```

Ultimately there are more configuration options (i.e. `pikvm.txt`) which means less need to rely on compile-time options for these settings so accepting things like wireless passwords at compile time is no longer a big issue.

**Comment by mdevaev** [comment]
I don't like the shell sourcing. I think we can add more options to pikvm.txt.
