### ISSUE TITLE
API access for macro

### ISSUE THREAD

**Issue by joukio** [pikvm/pikvm#543]
I would like to be able to execute all te functions in the macro menu from the API if possible?

For some setups I need to repeatedly do the same tasks over and over again and this is very easily done in a macro. However, there is a slight difference in buttons and locations between those systems. To automate this it would be necessary to have all the macro functions available via the API.

kind regards
Jouk Hettema

**Comment by mdevaev** [comment]
Hello. We already have an issue for this: #170
