### ISSUE TITLE
x86 alternative 

### ISSUE THREAD

**Issue by TheKoakuma** [pikvm/pikvm#544]
Hi everyone

I know that this is not the purpose of the project, but is it possible to adapt and compile the project to x86 platform or there are major incompatibilities that requires ARM?

I'm really interested on the project, but for $reasons (chip shortage, dollar, etc...) I can't actually afford the enough (500-700 BRL) for a Rpi 4 (or even 300-500 for a Rpi 2 or 3) but I have some x86 boards lying around that i could reuse while i can't build it properly on Pi 4

**Comment by mdevaev** [comment]
Hello. There is an abandoned x86 port of pikvm: https://github.com/purplepalmdash/pikvmx86

This is still possible now by changing a lot of configuration files, but it will be easier to buy raspberry pi zero 2 or something like that.

For similar questions, please contact the discord chat.
