### ISSUE TITLE
change mouse cursor from ring to any symbol with own bitmap?

### ISSUE THREAD

**Issue by dbase25** [pikvm/pikvm#548]
hi everbody,

its possible to implement a changeable mouse cursor when a webrtc is running.

i mean not the guest system ;-)

thanks and regards

dave

**Comment by mdevaev** [comment]
Hello. You can use `/etc/kvmd/web.css` to override cursor CSS.

https://github.com/pikvm/kvmd/tree/master/web/share/css

**Comment by dbase25** [comment]
perfect, thanks for your support

**Comment by mdevaev** [comment]
Welcome. Here the classes: https://github.com/pikvm/kvmd/blob/master/web/share/css/kvm/stream.css
