### ISSUE TITLE
500 Internal Server Error after pacman update 

### ISSUE THREAD

**Issue by pmagid** [pikvm/pikvm#551]
Almost Identical to Issue 280.  The solution in 280 does not work though...

**Describe the bug**
Fresh Install of PiKVM from Image. Then boot and ssh into. Then do an update as follows:
rw
pacman -Syy
pacman -Su
reboot
After the Reboot the Webinterface shows just 500 Internal Server Error
(I dont recall seeing an error about python.  Connection using ssh via terminal still works after the upgrade for troubleshooting.)

**Expected behavior**
A working webinterface.

**Desktop (please complete the following information):**
OS: MacOS Monterey
Browser: Chrome 95.0.4638

**Pi-KVM info:**
Raspberry Pi Zero W2
Pi-KVM platform [e.g. v2-hdmi]

**Comment by mdevaev** [comment]
Aiohttp was broken in the upstream. Fixed, update again.
