### ISSUE TITLE
Support for Wake Up On LAN (WOL) [Feature request]

### ISSUE THREAD

**Issue by roblatour** [pikvm/pikvm#565]
In the same way PiKVM provides for an ATX 'Power' button on the menu bar, it should also provide for a WOL button, or perhaps even better, when the user clicks on the current ATX power button an option to send a WOL Magic Packet to the target computer is also shown.

This for the benefit of users who are incapable of adding an atx board to their target computer, or just don't want to.

**Comment by mdevaev** [comment]
Hello. It's already implemented. See here: https://docs.pikvm.org/wol

**Comment by roblatour** [comment]
Perfect, and thank you so much for all your hard work on this.  Its amazing!
________________________________

**Comment by mdevaev** [comment]
Welcome!
