### ISSUE TITLE
support usb cameras 

### ISSUE THREAD

**Issue by linuxsky** [pikvm/pikvm#572]
At present, KVM web supports displaying HDMI input, but I often want to have a camera to see the surrounding environment. If I plug a USB camera into KVM, can I display the camera content on the web and switch freely with the desktop content. If yes, how should I set it?

**Comment by arch1mede** [comment]
Please use the USB image and follow the V2 USB setup using the lower left usb2.0 port per the instructions.

**Comment by linuxsky** [comment]
> Please use the USB image and follow the V2 USB setup using the lower left usb2.0 port per the instructions.

How can I set it so that the USB camera can also be displayed on the web, similar to the desktop.

**Comment by arch1mede** [comment]
Hi, I don't feel this is the correct forum for further troubleshooting, please join the Discord and you can get further assistance.

In a nut shell you are replacing the usb dongle with the usb webcam but you will not be able to view them the same as you can on the desktop.

**Comment by arch1mede** [comment]
While this is possible, it is not usable, others have tried it....this is also not something that we will support as it requires some advanced linux skills.

**Comment by mdevaev** [comment]
What you want is a special case of multimonitor support. We have a plan to do this in the future, but it's not a priority right now. I can suggest you to run another ustreamer with some scripts or through systemd, and then throw it through nginx.
