### ISSUE TITLE
documentation update - "Flashing the OS image"

### ISSUE THREAD

**Issue by vbooka1** [pikvm/pikvm#578]
I suggest updating this document: https://docs.pikvm.org/flashing_os/

This part:

```
> Using Linux CLI
> Decompress and flash the image. Be careful when choosing your device path:
> # dd if=v2-hdmi-rpi4-latest.img of=/dev/mmcblkX
```

Add:

```
> # # or, if using USB SD card reader:
> # dd if=v2-hdmi-rpi4-latest.img of=/dev/sdX 
> # # where X is the device letter, not the partition number -- use /dev/sdX, not /dev/sdX1
```

It took me a while to understand why rPI does not boot after I flashed the image to /dev/sdb1, twice 🤭

**Comment by arch1mede** [comment]
Thank you for the feedback - We will discuss if this would be worth adding in. The logic is that if you choose to do the dd route that you have the required linux skills to know about the lettering differences, hence the "Be careful when choosing your device path" verbiage.

**Comment by mdevaev** [comment]
Changed: `Be careful when choosing the device path, it may be different on your OS`

**Comment by vbooka1** [comment]
> Changed: Be careful when choosing the device path, it may be different on your OS

Still not clear I meant to add a comment about using the device name itself, without the partition number - e.g. "Use the device name itself, not the partition number -- like `/dev/sdx`, not `/dev/sdx1` "
