### ISSUE TITLE
Blurry Video

### ISSUE THREAD

**Issue by maxexcloo** [pikvm/pikvm#58]
I'm using a Raspberry Pi 4 with the USB HDMI dongle, my video is coming out quite blurry - is there any diagnostic work I can do to check this or scope out what exactly is causing it?

Example:
![Screenshot_2020-09-09 Pi-KVM Session localhost localdomain](https://user-images.githubusercontent.com/927210/92554330-6c158a80-f2a8-11ea-8a10-205b1256e00a.png)

**Comment by mdevaev** [comment]
This is one of the problems that I don't recommend using the dongle (as described in the documentation). This is a dongle hardware problem, it can't be fixed. If the resolution in the System menu in Pi-KVM is set correctly and corresponds to the system one on your workstation, then nothing else can be done. Sorry.

**Comment by mdevaev** [comment]
A little comparison to confirm my words.

Top: HDMI to CSI-2 Bridge (~$35 USD) / GPU comression
Middle: HDMI Game Capture (~$60 USD) / HW compression
Bottom: HDMI USB Dongle (~$20 USD) / HW compression

![image](https://user-images.githubusercontent.com/416259/92742752-9c345a80-f388-11ea-9111-9eedba8745d2.png)

**Comment by maxexcloo** [comment]
Great comparison 👍
I've ordered the CSI-2 bridge and a Pi Zero W for my use case :)
