### ISSUE TITLE
CD Read Fail when custom MECM task sequence media connected 

### ISSUE THREAD

**Issue by aggietallboy** [pikvm/pikvm#580]
**Describe the bug**
Booting to the Bootable task sequence ISO, system boots into main Microsoft Endpoint Configuration Manager screen, but returns "unable to read task sequence configuration disk. For more information contact your system administrator or helpdesk operator".

Same ISO used with Rufus, produces GPT bootable disk which works fine to run task sequences.

**To Reproduce**
1. Create bootable task sequence media in SCCM/MECM
2. Copy iso to pikvm (select image to upload...)
3. Connect drive to server
4. boot
5. fail

**Expected behavior**
Welcome to the Task Sequence Wizard

**Screenshots**
Failure:
![image](https://user-images.githubusercontent.com/10222174/146970481-c81abbf3-411f-467a-b975-811d5e1629e6.png)

Success/Normal:
![image](https://user-images.githubusercontent.com/10222174/146971210-0076a296-ec97-477b-8030-ff49aacf477a.png)

**Desktop (please complete the following information):**
Chrome browser running in app mode

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4] - Raspberry Pi 4 Model B Rev 1.4 - 8gb
  - PiKVM platform [e.g. v2-hdmi]  - v3-hdmi-rpi4-latest.img
  - Video capture type [e.g. CSI bridge] - PiKVM Hat from Kickstarter campaign
  - KVMD version: `pacman -Q | grep kvmd` - 3.48
  - uStreamer version: `pacman -Q | grep ustreamer` 4.9
  - Linux kernel: `uname -a` 5.10.52-13-ARCH

**Additional context**

**Comment by arch1mede** [comment]
While I do not use Windows PE, I believe it has the same limitations as the other windows installs: Please see [here](https://docs.pikvm.org/msd/#how-to-create-rw-flash-drive)

**Comment by arch1mede** [comment]
Ping, does this work for you?

**Comment by mdevaev** [comment]
No answer from user.
