### ISSUE TITLE
Set different interface metric for eth0 and wlan0

### ISSUE THREAD

**Issue by nvtkaszpir** [pikvm/pikvm#583]
**Is your feature request related to a problem? Please describe.**
Right now both interfaces get the same routing metric:
```text
[root@pikvm /]# ip r
default via 192.168.1.1 dev wlan0 proto dhcp src 192.168.1.37 metric 1024 
default via 192.168.1.1 dev eth0 proto dhcp src 192.168.1.38 metric 1024 
```
As a result packets may be routed by wlan0 even though on the same segment eth0 would be just faster.

So it would be better to favor cable interface for dynamic routing, this can be solved with static routes and metrics per interface. But for DHCP networks it is better to do it with RouteMetric in systemd.network, see below

**Describe the solution you'd like**
This can be solved by editing /etc/systemd/network/eth0.network and adding RouteMetric into DHCP section like below (last line):
```text
[Match]
Name=eth0

[Network]
DHCP=yes
DNSSEC=no

# Use same IP by forcing to use MAC address for clientID
[DHCP]
ClientIdentifier=mac
RouteMetric=10

```
and running `systemctl restart systemd-networkd` will automatically reconfigure interfaces:
```text
[root@pikvm /]# systemctl restart systemd-networkd
[root@pikvm /]# ip r
default via 192.168.1.1 dev eth0 proto dhcp src 192.168.1.38 metric 10 
default via 192.168.1.1 dev wlan0 proto dhcp src 192.168.1.37 metric 1024 
```
As a result we can test if it works as intended by pinging gateway (cut out sections for better visibility):
```text
64 bytes from 192.168.1.1: icmp_seq=1 ttl=64 time=0.503 ms
64 bytes from 192.168.1.1: icmp_seq=2 ttl=64 time=0.237 ms
64 bytes from 192.168.1.1: icmp_seq=3 ttl=64 time=0.247 ms
64 bytes from 192.168.1.1: icmp_seq=4 ttl=64 time=0.241 ms
...
64 bytes from 192.168.1.1: icmp_seq=6 ttl=64 time=7.68 ms
64 bytes from 192.168.1.1: icmp_seq=7 ttl=64 time=4.14 ms
64 bytes from 192.168.1.1: icmp_seq=8 ttl=64 time=4.12 ms
...
64 bytes from 192.168.1.1: icmp_seq=21 ttl=64 time=4.12 ms
64 bytes from 192.168.1.1: icmp_seq=22 ttl=64 time=6.21 ms
64 bytes from 192.168.1.1: icmp_seq=23 ttl=64 time=4.10 ms
64 bytes from 192.168.1.1: icmp_seq=24 ttl=64 time=0.257 ms
64 bytes from 192.168.1.1: icmp_seq=25 ttl=64 time=0.214 ms
64 bytes from 192.168.1.1: icmp_seq=26 ttl=64 time=0.244 ms
64 bytes from 192.168.1.1: icmp_seq=27 ttl=64 time=0.247 ms

32 packets transmitted, 31 received, 3.125% packet loss, time 31508ms
rtt min/avg/max/mdev = 0.214/2.746/7.676/2.265 ms
```
As we can see in case of disconnected cable on eth0 we just get higher response times but connectivity was kept, and later on pings response latency decreased in case of connectivity restoration.
With the same metric values we would probably end on using only wlan0 from the start.

For statically assigned addresses it will look a bit different, though, but that's another story. More on that in systemd.network.5 (link below)

**Describe alternatives you've considered**
None.

**Additional context**
https://man.archlinux.org/man/systemd.network.5

**Comment by mdevaev** [comment]
Perhaps we will change OLED script and Janus runner to get right default network interface. Hint for me: netifaces + /proc/net/route

**Comment by nvtkaszpir** [comment]
Right now if two interfaces are set as default gateway and they have the same metric then the first one registered in the system is returned.
If metric value is changed on the fly (as described in first comment of this github issue) then interface with lowest metric is returned, no need to restart kvmd-oled service.

**Comment by mdevaev** [comment]
Done. It will be available in the next OS release.
