### ISSUE TITLE
flip input screen

### ISSUE THREAD

**Issue by DBursch78** [pikvm/pikvm#585]
**Is your feature request related to a problem? Please describe.**
I am using a pikvm hat v3 and for some reasons my hdmi input is rotate to upside down

**Describe the solution you'd like**
I guess i need option like "rotate input video" or the output 

**Describe alternatives you've considered**
Any option to flip the output screen so the mouse works right but the screen as to flip

**Comment by arch1mede** [comment]
Please join Discord in #support channel, id like to discuss as I have never heard of this before.

**Comment by mdevaev** [comment]
@DBursch78 is it solved in the Discord or required my help?

**Comment by mdevaev** [comment]
Sup?

**Comment by DBursch78** [comment]
I go into it next week, I’m on vacation 

Von meinem iPhone gesendet

> Am 10.01.2022 um 16:18 schrieb Maxim Devaev ***@***.***>:
> 
> ﻿
> Sup?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.


--
This e-mail and any attached files are confidential and may be legally privileged. If you are not the addressee, any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication is strictly prohibited. If you have received this transmission in error please notify the sender immediately and then delete this mail.
E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission or changes to transmitted date not specifically approved by the sender.
If this e-mail or attached files contain information which do not relate to our professional activity we do not accept liability for such information.

**Comment by arch1mede** [comment]
@DBursch78 boop?

**Comment by arch1mede** [comment]
@DBursch78 boop, boop?

**Comment by mdevaev** [comment]
Apparently, this is no longer needed.

**Comment by DBursch78** [comment]
I post a vid with that issue?!

Von meinem iPhone gesendet

> Am 16.03.2022 um 19:29 schrieb Maxim Devaev ***@***.***>:
> 
> ﻿
> Closed #585.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.


--
This e-mail and any attached files are confidential and may be legally privileged. If you are not the addressee, any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication is strictly prohibited. If you have received this transmission in error please notify the sender immediately and then delete this mail.
E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission or changes to transmitted date not specifically approved by the sender.
If this e-mail or attached files contain information which do not relate to our professional activity we do not accept liability for such information.

**Comment by mdevaev** [comment]
What kind of signal source are you using?

**Comment by DBursch78** [comment]
Hdmi, it's  in the Settings from System, all Display’s are set to upside down. That’s the reason why I needed to rotate the stream.

Von meinem iPhone gesendet

> Am 16.03.2022 um 19:44 schrieb Maxim Devaev ***@***.***>:
> 
> ﻿
> What kind of signal source are you using?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you were mentioned.


--
This e-mail and any attached files are confidential and may be legally privileged. If you are not the addressee, any disclosure, reproduction, copying, distribution, or other dissemination or use of this communication is strictly prohibited. If you have received this transmission in error please notify the sender immediately and then delete this mail.
E-mail transmission cannot be guaranteed to be secure or error free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message which arise as a result of e-mail transmission or changes to transmitted date not specifically approved by the sender.
If this e-mail or attached files contain information which do not relate to our professional activity we do not accept liability for such information.

**Comment by mdevaev** [comment]
This is not a best solution, but anyway. Edit file `/etc/kvmd/web.css` and add:
```css
video#stream-video {
    transform: rotate(180deg);
}
img#stream-image {
    transform: rotate(180deg);
}
```

**Comment by DBursch78** [comment]
Works perfect, good work, thank you!

**Comment by mdevaev** [comment]
:ok_hand:

**Comment by BhupiMAD** [comment]
While this solution works, the mouse on the screen is still not inverted as per the screen resolution. You see mouse going in opposite direction. Any fix for this?

**Comment by mdevaev** [comment]
You can invert the mouse range. Run `kvmd -m` and find options tree with `mouse_x_range` and `mouse_y_range`.
