### ISSUE TITLE
Need RPi0W image

### ISSUE THREAD

**Issue by SozDM** [pikvm/pikvm#59]
I don't have oppotunity to prepare OS image, so could you please share it whith me?

**Comment by SozDM** [comment]
I'm going to use CSI-HDMI converter

**Comment by SozDM** [comment]
Now i'm trying to use Linux for Windows, Ubuntu 2004
Docker didn't start, so i found solution here: https://github.com/MicrosoftDocs/WSL/issues/457
Instead of using sudo systemctl start docker use: sudo /etc/init.d/docker start
Trying to build it again...

**Comment by mdevaev** [comment]
Contact me through discord, there is a link in on the home page in the README.
