### ISSUE TITLE
Paste: please add keymap for us-intl

### ISSUE THREAD

**Issue by j0xaf** [pikvm/pikvm#594]
**Is your feature request related to a problem? Please describe.**

I am using `setxkbmap us altgr-intl` as keymap on my target. When pasting text containing Umlauts (äöüß etc) using the paste popup, the umlauts are omitted.

**Describe the solution you'd like**

 Could you please add `us altgr-intl` as option in the paste popup? Or is there a way for myself to add it?

Btw, PiKVM with the Hatv3 is the best KVM solution I have used so far! Thank you for creating!

**Comment by mdevaev** [comment]
Sup. Where I can get this keymap?

**Comment by j0xaf** [comment]
Thank you! I couldn't find one online, so I generated it using `qemu-keymap` myself.

See https://github.com/j0xaf/keymap-us-altgr-intl/blob/main/keymap-us-altgr-intl for the generated file.

**Comment by mdevaev** [comment]
Added, will be available in the next release.
