### ISSUE TITLE
How to emulate mouse and keyboard via USB if don't use splitter (i.e. Y Cable) ?

### ISSUE THREAD

**Issue by wcck** [pikvm/pikvm#595]
I want to change data transfer method by USB. i.e. I don't use splitter.
Whether some method can workaround? In this case it can implement?
If it can what should i do something?
Thanks

**Comment by mdevaev** [comment]
Hello.

In any case, you need either a splitter or a USB cable without a power line (but in this case you will have to supply power in some other way, and this will also require manual work).

There is no alternative, this is a limitation of the Raspberry Pi design.
