### ISSUE TITLE
new DIY case on thingiverse

### ISSUE THREAD

**Issue by badsmoke** [pikvm/pikvm#597]
this ist also a very cool case for the zero w/zero 2   ;-)

https://www.thingiverse.com/thing:4754892

this could be added to the docs

https://docs.pikvm.org/3d_printing/

**Comment by mdevaev** [comment]
![image](https://user-images.githubusercontent.com/416259/148224230-d432eaa7-9df7-4844-b3b4-0c0e5fe77007.png)
dafaq

**Comment by mdevaev** [comment]
Sorry, I can't add a penis-shaped case to the official page. Take it away and I'll add the main case.
