### ISSUE TITLE
Whether support macro API on Web UI?

### ISSUE THREAD

**Issue by wcck** [pikvm/pikvm#598]
Dear Authors

If I want to auto upload next script can i through "macro API" to use it?
P.S. I didn't find it on https://docs.pikvm.org/api/

Thanks

**Comment by wcck** [comment]
[Update]
Using websocket and develop Python script can control remote PC.
Ref. https://docs.pikvm.org/api/#websocket-events
Maybe it can workaround "upload script" because we can develop others python scripts to control remote PC.

**Comment by mdevaev** [comment]
Macro has no a special API, it's just some JS code over HID API. You need to write something like this on Python: https://github.com/pikvm/kvmd/blob/master/web/share/js/kvm/recorder.js

**Comment by mdevaev** [comment]
Solved I guess.
