### ISSUE TITLE
Fan fails to spin on low levels after restart

### ISSUE THREAD

**Issue by Martin-HiPi** [pikvm/pikvm#603]
**Describe the bug**
After activating the fan as mentioned in the documentation, the fan fails to spin on low levels. Instead, it whines and will spin if helped. Once the inertia broken, it will run at PWM 256/1023.

**To Reproduce**
1. systemctl stop kvmd-fan.service
2. gpio -g mode 12 pwm && gpio -g pwm 12 0
3. gpio -g mode 12 pwm && gpio -g pwm 12 256

**Expected behavior**
The fan should spin, but it doesn't.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**PiKVM info:**
  - Raspberry Pi board version: RPi 4 rev 1.?
  - PiKVM platform: v3.3
  - KVMD version: 
```
kvmd 3.54-1
kvmd-fan 0.2-1
kvmd-oled 0.12-1
kvmd-platform-v3-hdmi-rpi4 3.54-1
kvmd-webterm 0.41-1
```
  - uStreamer version: n/a
  - Linux kernel: `Linux pikvm-hipi 5.10.52-14-ARCH #1 SMP Thu Dec 2 09:40:42 MSK 2021 armv7l GNU/Linux`

**Additional context**
This would be avoided by forcing a fan blip before setting the actual speed. The following works:
`gpio -g mode 12 pwm && gpio -g pwm 12 512 && gpio -g mode 12 pwm && gpio -g pwm 12 256`

**Comment by mdevaev** [comment]
Fixed
