### ISSUE TITLE
mouse/keyboard emulation not working with Raspbian OS buster/bullseye 

### ISSUE THREAD

**Issue by cipy** [pikvm/pikvm#613]
PiKVM doesn't seem to be able to control a Raspberry Pi computer

the video over HDMI is fine, but there's no interaction with the RPi OS

**To Reproduce**
1. install a fresh Raspbian OS on a RPi 4B
2. connect it to a working PiKVM HAT v3
3. try to interact using the mouse/keyboard
4. oops/fail

**Expected behavior**
Should work fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Raspbian OS Buster
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version RPi 4B
  - PiKVM platform v3
  - Video capture type CSI bridge
  - latest `pacman -Syu`
  - KVMD version: `pacman -Q | grep kvmd`
  - uStreamer version: `pacman -Q | grep ustreamer`
  - Linux kernel: `uname -a`

Thanks,

**Comment by arch1mede** [comment]
Hi, can you join discord so we can troubleshoot this, it seems like there is maybe an issue with the v3 usbc bridge or cable. I would rather not do troubleshooting in this space.

**Comment by mdevaev** [comment]
This is the same problem as #614
