### ISSUE TITLE
Feature Request: Hide Text option for Paste feature

### ISSUE THREAD

**Issue by kamotswind** [pikvm/pikvm#616]
On the KVM page, please add a "Hide" toggle option to the Paste feature that hides the text in the textbox. This would allow pasting sensitive information during a screen share or "over-the-shoulder" session, such as passwords or keys, without exposing them.

**Comment by mdevaev** [comment]
Hint: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security

**Comment by mdevaev** [comment]
Will be available for chrome, opera and safari.
