### ISSUE TITLE
Non-video instructions for assembling PIKVM HAT v3

### ISSUE THREAD

**Issue by abh** [pikvm/pikvm#625]
The video and weird music makes me dizzy (I have a vestibular disorder after a head injury). It'd be nice to have set of normal written / illustrated instructions instead of only the YouTube video.

**Comment by arch1mede** [comment]
Done, @mdevaev please close

**Comment by mdevaev** [comment]
https://docs.pikvm.org/v3_illustrated_install_instructions/

**Comment by abh** [comment]
Beautiful, thank you!
