### ISSUE TITLE
Allow hiding the navbar at the top

### ISSUE THREAD

**Issue by arielsalvo** [pikvm/pikvm#631]
**Is your feature request related to a problem? Please describe.**
The navbar, even though it houses some important controls, takes up a lot of screen space at the top that could be use for remote video instead.

**Describe the solution you'd like**
Auto hiding or minimizing to a smaller button or a floating toolbar.

**Describe alternatives you've considered**
I tried setting `display: none` in the dev console of the browser and that allowed me to use more screen for video.

**Additional context**
I use an ultra-wide screen so width is not an issue but height is. Full screen is not useful because it takes up all the monitor. Optionally, moving the bar to the left or right would also work.

**Comment by mdevaev** [comment]
Will be available in the next release
