### ISSUE TITLE
Source files for PiKVM v3 ATX mounting brackets for 3D printing

### ISSUE THREAD

**Issue by denschub** [pikvm/pikvm#638]
**Is your feature request related to a problem? Please describe.**
This is technically a "documentation feature request"?

I'd like to make some changes to the PCI mounts provided in https://docs.pikvm.org/stl/atx/ to make them easier to print and a bit less fragile. Unfortunately, working with the exported STL files is a bit hard, as it only contains some high-density mesh, but not the actual sources.

**Describe the solution you'd like**
If possible, I'd love to have the source files from whatever program this was created, or some neutral file formats like .step for example.

**Comment by benmprojects** [comment]
Please upload and people can test

**Comment by mdevaev** [comment]
There is a certain problem. We drew them in a hurry and now the sources of the 3D parts have been lost :/

**Comment by denschub** [comment]
Well, too bad. :) I'll design my own eventually, and I'll share the source files here. No time estimate, tho.

**Comment by mdevaev** [comment]
I'm closing it due inactivity (temporary), and will open it later if needed.

**Comment by fletchto99** [comment]
@denschub did you manage to design your own? I was facing the same issues when trying to print the STL files

**Comment by denschub** [comment]
I'm currently using some brackets I hacked together using stamped metal, since I wasn't yet able to spend the time to design a clean, printable, version.

**Comment by denschub** [comment]
As an official update since I opened this issue, and my previous message contained the word "yet": I have no plans of designing a more stable 3D-printable ATX mount in the future.

The reason here is simple: my v3 PiKVMs will "soon" be degraded into mobile use-cases where I don't need the ATX control, and for my two stationary machines that have the ATX board, they'll be replaced by PiKVM v4's, which come with PCI brackets that look like sheet metal.

If someone else wants to tackle this project in the future, note that this might not be feasible in the standard way. No matter how much you reinforce the "main part" of the bracket, there's always the lower lip where the bracket slides besides the mainboard into the case. This will always be the weak point, and if you print with PETG, it'll flex too much; and if you print with PLA, it'll shatter due to stress.

One might be able to get away with Carbon-reinforced PA11 or something, although I haven't tried. A more realistic workaround is probably to design some kind of external-bracket, where you have two clamps outside the case, that pull the mounting bracket outwards - ideally right next to the RJ45 socket. That way, when you push a cable into the board, it won't have a chance to deflect inwards. Good luck! :)
