### ISSUE TITLE
Is a USB Power Blocker a must for the Y OTG cable?

### ISSUE THREAD

**Issue by chenming6615** [pikvm/pikvm#646]
What is the consequence if I connect the target PC directly to the Y OTG cable without the power blocker?  
Will it burn down my Raspberry Pi 4? 

It's hard to find a Power Blocker in China. 
I don't know what the correct Chinese name of "Power Blocker" is.
So I failed to search it in Chinese online shopping site.

**Comment by arch1mede** [comment]
**_What is the consequence if I connect the target PC directly to the Y OTG cable without the power blocker?
Will it burn down my Raspberry Pi 4?_**

If you directly connect your RPi to your PC, it will do nothing HOWEVER most USB's have power limitations which wont provide enough power and some will reset when you reboot the PC so its advised to use an external power in which case you NEED to be sure you are not back powering, you can view how this is to be wired up looking at the wiring_examples doc from github.

**_It's hard to find a Power Blocker in China._**

I am positive that they make power blockers in China but you can always use label tape per the DIY instructions.
