### ISSUE TITLE
Feature Request: Integratea option to put Notes on Webui. 

### ISSUE THREAD

**Issue by soares23** [pikvm/pikvm#650]
Hi,

I will ask if is possible to add a Tab on Webui for Notes.
Why i'm asking for. It will help me to easier and faster put information for the other people that also working with the pikvm.

We use the Pikvm with a multiswitch and would to put in the Notes example: Channel 1 of the kvm PC of costumer xyz, Chanel 2 PC costumer abc or or other small notes. We wok with many PC's and Laptops and same time and it's easier to determinate what Device is connected to what Port of the multi Switch.

It would be nice if it's possible to integrate it but if not isn't a problem. 

Thank's for you great work. 
Have a nice day.

**Comment by mdevaev** [comment]
Sup. PiKVM is not a ticket system and should not deal with this task. Any functionality of the built-in notepad will always be insufficient for some users and threatens to turn into a text processor. So it seems to me that this is not the best way to solve your problem.
