### ISSUE TITLE
What will be the future of Pi Zero?

### ISSUE THREAD

**Issue by gabrielbelli** [pikvm/pikvm#656]
As said in Arch Linux ARM's forum, armv6 will no longer be supported.
scource: https://archlinuxarm.org/forum/viewtopic.php?f=3&t=15721

What will be the future of Pi Zero with pikvm? Will it receive further updates? Distro change? Any recommendations?

**Comment by mdevaev** [comment]
See here: https://www.reddit.com/r/pikvm/comments/sq6e63/zero_w_1_and_rpi_1_endoflife/
