### ISSUE TITLE
HDMI capture appears to be darkened

### ISSUE THREAD

**Issue by JoeMod2017** [pikvm/pikvm#663]
Hi there,

using the PiKVM v3 for a few days now and I am just blown away by its capabilities. This is just unbeaten at the price, great work!
There is just one thing that bothers me a bit. I am sometimes working half a day or more via KVM, now that it is eventually possible. But the picture is not same as it is shown on screen in the remote system.
To be exact, surfaces which are just plain white (#FFFFFF) are shown in the KVM remote view as #EBEBEB which is quite a bit darker. All colors appear to be darker than they actually are. It's same in Firefox and Chrome. It this a compression artifact? I am using MJPEG/HTTP as the other mode (H.264/WebRTC) just gives me a black view. The issue is not dependent on the selected FPS or quality index.

I would like to emphasize that I am fully content with the product and this is merely a question. I am aware that PiKVM is not made to provide the best video fidelity possible, but if there is a way to finetune, I would be very happy to learn how that is done.

Thank you so much!

Cheers,
Joe

**Comment by mdevaev** [comment]
Hello. What you describe is the features of the video capture chip/driver. There's nothing we can do about it yet.
