### ISSUE TITLE
Mic input

### ISSUE THREAD

**Issue by edescourtis** [pikvm/pikvm#665]
**Is your feature request related to a problem? Please describe.**
I have a locked-down machine from my employer that I would like to control from my laptop. I sometimes require two-way audio. That means I need my mic on my laptop to be captured and sent to the computer via its MIC input port.

**Describe the solution you'd like**
The quality of the audio is not a big issue for me. I want to be able to use MIC audio. That means we need a way to send sound to the MIC port.

**Describe alternatives you've considered**
No other options exist; I've looked everywhere.

**Additional context**
Maybe a way to turn on and off the MIC might be a good idea.

**Comment by arch1mede** [comment]
Hi, sound is not supported at this time, it is on the roadmap though. 

https://docs.pikvm.org/faq/

![image](https://user-images.githubusercontent.com/3489071/156888141-c8cad34e-505d-4ddc-9a22-a50f05a5853c.png)

**Comment by mdevaev** [comment]
Sup. Audio, including two-way, will be made in the future: #97
