### ISSUE TITLE
Waveshare CSI Adapter HDMI 1080p@30fps

### ISSUE THREAD

**Issue by Xev** [pikvm/pikvm#671]
Due to me being located near Germany - it is far more desirable for me to order csi adapter together with Splitter USB-C/PWR.

The CSI adapter in question is this:
https://www.ebay.pl/itm/124819583323?hash=item1d0fd3b15b:g:sMEAAOSw9-ZhimrN
https://botland.com.pl/tasmy-ffc-i-obudowy-do-kamer-do-raspberry-pi/19044-adapter-hdmi-csi-1080p-30fps-do-raspberry-pi-waveshare-19137-5904422364113.html

This is the splitter
https://www.ebay.pl/itm/115287609375?hash=item1ad7ad501f:g:LqsAAOSwgiJiKgLh#shpCntId

Would this work for pikvm? I don't want order from ebay, without being 100% sure it works.

**Comment by mdevaev** [comment]
Hello. Yes, both will work.
