### ISSUE TITLE
Cannot update installed pi zero w

### ISSUE THREAD

**Issue by sharicov** [pikvm/pikvm#674]
When running update command **pacman -Syy** getting following error:

```
:: Synchronizing package databases...
 core.db failed to download
error: failed retrieving file 'core.db' from de3.mirror.archlinuxarm.org : The requested URL returned error: 404
error: failed retrieving file 'core.db' from mirror.rackspace.com : The requested URL returned error: 404
error: failed retrieving file 'core.db' from mirror.rackspace.com : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
```

Didn't use this device for quite a long time.

DNS resolution works fine (ping google.com)
ipv6 enabled

**Comment by mdevaev** [comment]
Sup. Please read here: https://www.reddit.com/r/pikvm/comments/sq6e63/zero_w_1_and_rpi_1_endoflife/

**Comment by si458** [comment]
https://forums.raspberrypi.com/viewtopic.php?t=326235#p2005629
this will help with arch pacman packages but wont help with pikvm packages sadly
