### ISSUE TITLE
Syntax error happened when build PiKVM os

### ISSUE THREAD

**Issue by josh-otwise** [pikvm/pikvm#676]
# Syntax error happened when build PiKVM os

## Abstract

Got ``/bin/sh: 16: Syntax error: redirection unexpected`` error message when build PiKVM [os](https://github.com/pikvm/os).

## How to reproduct

1. Git clone [os](https://github.com/pikvm/os) repo
2. Install all required packages on my Ubuntu 20.04 machine
3. Add ``config.mk``
4. Build ``os`` as following instruction:

```shell
$ sudo make os
```

## The part of build failed messages

```shell
	--build-arg NEW_HTTPS_CERT=5d4c6533-ffa6-4ef5-b3ce-e839d71cf742 \
 \
	./.build
/bin/sh: 16: Syntax error: redirection unexpected
make[1]: *** [Makefile:232: os] Error 2
make[1]: Leaving directory '/home/user/workspace/os/.pi-builder'
make: *** [Makefile:54: os] Error 2
```

**Comment by arch1mede** [comment]
Please show us what you have in config.mk

**Comment by linahbei** [comment]
I copied example to ``config.mk`` from [building guide](https://github.com/pikvm/pikvm/blob/master/docs/building_os.md) as the following.

```mk
BOARD = rpi4

# Hardware configuration
PLATFORM = v2-hdmi

# Target hostname
HOSTNAME = pikvm

# ru_RU, etc. UTF-8 only
LOCALE = en_US

# See /usr/share/zoneinfo
TIMEZONE = Europe/Moscow

# For SSH root user
ROOT_PASSWD = root

# Web UI credentials: user=admin, password=<this>
WEBUI_ADMIN_PASSWD = admin

# IPMI credentials: user=admin, password=<this>
IPMI_ADMIN_PASSWD = admin

# SD card device
CARD = /dev/mmcblk0
```

**Comment by josh-otwise** [comment]
> Please show us what you have in config.mk

I copied example to ``config.mk`` from [building guide](https://github.com/pikvm/pikvm/blob/master/docs/building_os.md) as the following.

```mk
BOARD = rpi4

# Hardware configuration
PLATFORM = v2-hdmi

# Target hostname
HOSTNAME = pikvm

# ru_RU, etc. UTF-8 only
LOCALE = en_US

# See /usr/share/zoneinfo
TIMEZONE = Europe/Moscow

# For SSH root user
ROOT_PASSWD = root

# Web UI credentials: user=admin, password=<this>
WEBUI_ADMIN_PASSWD = admin

# IPMI credentials: user=admin, password=<this>
IPMI_ADMIN_PASSWD = admin

# SD card device
CARD = /dev/mmcblk0
```

**Comment by arch1mede** [comment]
Also, what step did this fail at?

**Comment by josh-otwise** [comment]
> Also, what step did this fail at?

In this step:

```shell
$ sudo make os
```
It's seems something wrong when build / make ".build" dir in ``.pi-builder`` sub process.

And the latest depended building / error messages are:

```shell
	--build-arg NEW_HTTPS_CERT=5d4c6533-ffa6-4ef5-b3ce-e839d71cf742 \
 \
	./.build
/bin/sh: 16: Syntax error: redirection unexpected
make[1]: *** [Makefile:232: os] Error 2
make[1]: Leaving directory '/home/user/workspace/os/.pi-builder'
make: *** [Makefile:54: os] Error 2
```

**Comment by josh-otwise** [comment]
> Just curious, why are you building the image for rpi4? Pre-made images are available.

I would like to add some runtime app as a daemon service with PiKVM image together.

i.e., Another Web UI based on Lua, an "echo My IP" UDP app.

**Comment by mdevaev** [comment]
Please use the ready-made image for v2. The build environment is now preparing for the transition to a new kernel and may not work. This will be resolved in a few days.

**Comment by mdevaev** [comment]
Fixed not. Clone this repo again.
