### ISSUE TITLE
Add 2FA authentication method

### ISSUE THREAD

**Issue by jobggun** [pikvm/pikvm#679]
**Is your feature request related to a problem? Please describe.**
When I use PIKVM outside, I am worried about the password being leaked. (unsafe network, cctv, etc.)

**Describe the solution you'd like**
Adding login method with password and [Time-based One-time Password Algorithm](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm) (TOTP; specified in RFC 6238)

**Comment by arch1mede** [comment]
I would install Tailscale if you are going to expose this on the inet.

**Comment by mdevaev** [comment]
https://www.geeksforgeeks.org/two-factor-authentication-using-google-authenticator-in-python/

**Comment by mdevaev** [comment]
Done: https://docs.pikvm.org/auth/#two-factor-authentication
