### ISSUE TITLE
Add timestamp to build images

### ISSUE THREAD

**Issue by tryallthethings** [pikvm/pikvm#68]
Currently, all images regardless of version are called **v2-hdmi-rpi4.img.bz2**. My suggestion is to add a timestamp to the image name for differentiation of versions. For example **v2-hdmi-rpi4.img-20201209.bz2**. 
Background: I already downloaded the image 3 times and in my downloads folder I have:
- v2-hdmi-rpi4.img.bz2
- v2-hdmi-rpi4 (1).img.bz2
- v2-hdmi-rpi4 (2).img.bz2

**Comment by mdevaev** [comment]
Done
