### ISSUE TITLE
Override.yaml - config.md not found

### ISSUE THREAD

**Issue by djarbz** [pikvm/pikvm#684]
**Describe the bug**
In the default override.yaml, the reference page is not available.
[config.md](https://github.com/pikvm/pikvm/blob/master/pages/config.md)

I would expect this link to open the correct reference documentation.

**PiKVM info:**
  - Raspberry Pi board version: RPi4
  - PiKVM platform: v3HAT
  - Video capture type v3HAT
  - KVMD version: 3.62-1
  - uStreamer version: 5.1-2
  - Linux kernel: 5.15.25-10-rpi-ARCH

**Comment by mdevaev** [comment]
Thanks, fixed.
