### ISSUE TITLE
Invalidate user sessions upon password change

### ISSUE THREAD

**Issue by tryallthethings** [pikvm/pikvm#69]
Security feature: If you change the password via `kvmd-htpasswd set admin` any active user session should be invalidated / logged out.

**Comment by mdevaev** [comment]
Invalidation of sessions will not result in closing connections. this is especially true for third-party applications such as ttyd. I suggest simply reflecting the current behavior in the documentation. Like, if you need to reset all sessions urgently restart kvmd and nginx.

**Comment by tryallthethings** [comment]
Hardly anyone would check the documentation for a password change. Especially since the command to use is listed upon SSH login.  IMHO it would be better to ask the user if they want to restart the services after the password change if that's the only way to "kick" them out.
```
[root@pikvm ~]# kvmd-htpasswd set admin
Password:
Repeat:
Note: Users logged in with the username "admin" will stay logged in. Do you want to restart KVMD and nginx to log them out? [y/N] y
Restarting kvmd ...
Restarting nginx ...
[root@pikvm ~]# 
```

I'll raise a documentation PR later including this information.

**Comment by mdevaev** [comment]
Good idea.

**Comment by mdevaev** [comment]
After discussion, we decided not to change the existing behavior and just add a warning.

![image](https://user-images.githubusercontent.com/416259/93139752-ff582100-f6e9-11ea-92b2-34ab64f47c9a.png)

**Comment by mdevaev** [comment]
Done
