### ISSUE TITLE
About arm64

### ISSUE THREAD

**Issue by wilinz** [pikvm/pikvm#711]
Is it possible to compile the arm64 version system image for the pi 4

**Comment by mdevaev** [comment]
Yes, but why you need it?

**Comment by wilinz** [comment]
> Yes, but why you need it?

I want to run some server apps on pkvm which only support arm64

**Comment by mdevaev** [comment]
Right now we have no plans to support arm64. Moreover, I don't recommend you to use pikvm as a server for any other purposes because pikvm is an emergency tool.

**Comment by wilinz** [comment]
How to compile a 64-bit system
