### ISSUE TITLE
USB emulated device install windows can not find the driver

### ISSUE THREAD

**Issue by wilinz** [pikvm/pikvm#713]
When installing windows 11 it shows:

A required media driver for your computer is missing. This could be a DVD, USB stick, or hard drive. If you have a CD, DVD or USB stick that contains the driver, insert it now.

Note: If the Windows installation media is in a DVD drive or a USB stick, you can safely remove it during this step.

Could not find any device drivers. Please make sure the installation media contains the correct drive and click OK.

![QQ截图20220419211051](https://user-images.githubusercontent.com/59408438/164013493-fa50dd32-5c52-4e83-81f6-315e20a5b291.png)
![QQ截图20220419211114](https://user-images.githubusercontent.com/59408438/164013502-73472e3e-bccb-44ed-b25f-cf377ce865d3.png)
"

**Comment by NiKiZe** [comment]
Does it find your harddrive that you want to install to? You can use shift+F10 to get CMD and use diskpart to view partitions.

**Comment by arch1mede** [comment]
Windows needs to be prepped and cannot be used natively, please review the MSD [document.](https://docs.pikvm.org/msd/#how-to-create-rw-flash-drive)

**Comment by arch1mede** [comment]
Hi, did you get this working? I think it would be easier if you joined on [Discord](https://discord.gg/bpmXfz5)

**Comment by mdevaev** [comment]
No answer.
