### ISSUE TITLE
[SOLVED] UEFI setup screen broken with ASRock H670 PG Riptide

### ISSUE THREAD

**Issue by syuu1228** [pikvm/pikvm#715]
**Describe the bug**

I found how to fix this issue but reporting anyway,

Similar with #4 or #78, UEFI setup screen broken on ASRock H670 PG Riptide (everything else is working fine, only UEFI setup screen).

Not only right side of the screen doesn't appear correctly, the video output is completely frozen.

**To Reproduce**
1. Enter UEFI setup.

**Screenshots**
![snapshot2](https://user-images.githubusercontent.com/183648/164344075-1c633d68-80b3-489e-9ea4-73be943132bf.jpeg)
![snapshot](https://user-images.githubusercontent.com/183648/164344132-5118b5a8-9514-4b8c-9285-138b348471c5.jpeg)

**Additional context**
GPU is MSI GeForce GTX 1050 2GT LP

**How to fix the issue**
Just like GA-H77-DS3H issue(#78) change EDID solved the issue.
After I applied ["1920x1080 as preferred. Useful for Gigabyte GA-H77-DS3H or Intel NUC"](https://docs.pikvm.org/edid/#default-edid) it works perfectly.

**Comment by arch1mede** [comment]
Hi! Thank you for reporting this, can you change the title to add in the [SOLVED]? This way we can reference this to others. You can also remove the PiKVM info and additional context verbiage, as its non relevant.

**Comment by mdevaev** [comment]
Edited.
@arch1mede could you document it on the edid page? Like Gigabyte motherboard

**Comment by mdevaev** [comment]
Documented

**Comment by korhojoa** [comment]
> This also fix the same issue on MSI motherboard. After I applied [1920x1080 as preferred](https://docs.pikvm.org/edid/#default-edid) it works perfectly for me.
> 
> motherboard model: MSI MAG B660M MORTAR WIFI DDR4 video out: iGPU

Quite similar, MSI PRO Z690-A WIFI DDR4 with iGPU also was helped by using the 1920x1080 EDID
