### ISSUE TITLE
Border around Web UI window when full screen

### ISSUE THREAD

**Issue by youcangetme** [pikvm/pikvm#731]
**Is your feature request related to a problem? Please describe.**
When in full screen there is a border around the screen. The value is in "vars.css" and is '--shadow-window-fullscreen-active: 0 0 0 2px #5b90bb inset;'

**Describe the solution you'd like**
--shadow-window-fullscreen-active: 0 0 0 0px;

**Describe alternatives you've considered**
I go in at the beginning of the session and change the CSS in the browser. I have also edited the file directly on my install. 

**Additional context**
I can understand highlighting the windows that have focus in the multiwindow setting. That provides context. But when you go full screen you know the window you are in and so the border is just annoying and can cause burn-in on OLEDs. Well, everything causes burn in on OLEDs but you know what I mean :|

**Comment by mdevaev** [comment]
This border indicates the focus of the screen, so it's not a bug. If you don't like it, you can override this CSS using `/etc/kvmd/web.css` file.
