### ISSUE TITLE
Feature request: "reverse_scroll_direction" toggle

### ISSUE THREAD

**Issue by arch1mede** [pikvm/pikvm#739]
in the web interface to translate mousewheel_down events to mousewheel_up and vice versa, and a corresponding "default_scroll_direction" yaml that would determine which state the web_ui toggle starts in and also which setting the vnc server uses

**Comment by mdevaev** [comment]
Will be available in the next release.

**Comment by rudironsonijr** [comment]
Hi, @mdevaev. How can I set this config for VNC?

**Comment by mdevaev** [comment]
Hello. This is a client-side feature. If your client doesn't have it, you need to ask client developers for implementation.
