### ISSUE TITLE
Annoying question when returning from KVM to menu

### ISSUE THREAD

**Issue by tryallthethings** [pikvm/pikvm#74]
Bug or feature?
When I'm returning from https://pikvm-1/kvm/ back to the menu (https://pikvm-1/) via the top left Pi-KVM logo / button I'm always greeted with a question:
* This page is asking you to confirm that you want to leave - data you have entered may not be saved. (Firefox)
* Changes you made may not be saved. (Chrome)

Is there a way around it or is it a necessary "feature" of the way keys are sent to the controlled computer?

**Comment by mdevaev** [comment]
Yes, this is a feature to avoid accidentally closing the session.

**Comment by mdevaev** [comment]
PS: This is not related to key transmit

**Comment by tryallthethings** [comment]
Okay. Let's assume I sometimes know what I'm doing and don't need this feature. Can I disable it (override.yaml or otherwise)?

**Comment by mdevaev** [comment]
This is not possible right now, but I will add.

**Comment by tryallthethings** [comment]
Thanks. Lower than low priority :smile:

**Comment by mdevaev** [comment]
Currently, the web interface does not have any mechanisms for saving settings, so I drop these parameters in meta.yaml. This may change in the future, but you can still use it.
`/etc/kvmd/meta.yaml`:
```yaml
web:
    confirm_session_exit: false
```
Will be available in the next release.
