### ISSUE TITLE
Question: Which board for PS/2 Keyboard (and question about mouse support?)

### ISSUE THREAD

**Issue by accessiblepixel** [pikvm/pikvm#744]
Hello!

I've just bought some hardware (the HDMI to CS2) and I'm trying to hobble something together to control a PS/2 Input KVM.

I was thinking of building it on a PiZeroW but considering I won't be able to use the USB OTG/Keyboard/Mounting features anyway, would it be better to build it on a 3B+ that I have?

I'm a little confused by the documentation for getting the Arduino AtMega32u4 working, does that not work with the ZeroW?

I also saw that mouse support for PS/2 is coming soon but I can't find out roughly when that would be... Kinda don't wanna make a single PS/2 connector when mouse support might be released next week or something :)

For my case what is the recommended hardware to use, the ZeroW or the 3B+? I think the 3B+ would support h264 but the zerow doesn't?

Sorry for some noobish questions. I've a fair bit of experience with arduino and linux but I'm missing some of the nuances so far with PiKVM :)

Thank you.
PS. If I've posted this wrong or in the wrong place - I'm still pretty new at github so please move it to where is appropriate if I've messed up :)

Kind regards,
Jessica

**Comment by arch1mede** [comment]
Just making a comment about "soon", soon is used in the industry for: it will be released when there is nothing else to do, as of now there are plenty to do, so rest assured, it will not be released next week "or something". 0w does not officially support h.264 as its too low powered and heats up alot, so remains unsupported along with arch linux dropping support for it. Your best bet is to get the 3B+ working with the arduino for ps/2 functionality.

**Comment by accessiblepixel** [comment]
Great! Thank you for the reply. When I've had a bit more of a play, I think I might be able to help with some documentation based on my experience since a couple of things weren't clear, so hopefully I can help with that when I've built mine and got my head around it a bit more :)

Hope you're having a good week :)

**Comment by arch1mede** [comment]
Great! We look forward to other community members participating in this project. Look forward to seeing what you will provide.

**Comment by mdevaev** [comment]
:ok_hand:

I'm closing this, because it looks like everyone has discussed everything :)
