### ISSUE TITLE
Asus notebook，Unable to enter BIOS,No image after the physical keyboard enters BIOS

### ISSUE THREAD

**Issue by TelDragon** [pikvm/pikvm#753]
**Describe the bug**
Asus notebook，Unable to enter BIOS,No image after the physical keyboard enters BIOS

1. the kvmd system cannot enter the BIOS by typing F2.

2.After entering BIOS by typing F2 with the physical keyboard, kvmd cannot display the image, but the keyboard is available and the mouse is not available. At this time, LCD displayed on BIOS interface is 1366*768 The USB port is hid keyboard. HID Mouse
**To Reproduce**
Steps to reproduce the behavior, like:

**Expected behavior**
It may be a compatibility problem. When I change to another PC, I can normally enter the BIOS and use the keyboard to operate. If the mouse is not available, I can ignore it.

**Screenshots**
Asus notebook
Model: s4100u
BIOS Version： 305
GOP Version： 9.0.1058
EC Version： F0KL0D02.00C
Type bios:f2

**Desktop (please complete the following information):**
 - OS: macos12.3.1、windows11、windows10
 - Browser google chrome,  firefox 、microsoft edge 、 。。。。。
 - Version V4 latest
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version Raspberry Pi 4
  - PiKVM platform For HDMI-to-CSI bridge: [v2-hdmi-rpi4-latest.img.xz](https://files.pikvm.org/images/v2-hdmi-rpi4-latest.img.xz)
  - Video capture type  CSI TC358743
  - KVMD version: `kvmd 3.106-1
kvmd-fan 0.22-1
kvmd-oled 0.12-1
kvmd-platform-v2-hdmi-rpi4 3.106-1
kvmd-webterm 0.42-1`
  - uStreamer version: `ustreamer 5.9-1`
  - Linux kernel: `Linux pikvm 5.15.34-2-rpi-ARCH #1 SMP Fri Jun 3 06:14:48 MSK 2022 armv7l GNU/Linux`

**Additional context**
1. I tried
https://docs.pikvm.org/faq/#video -problems
`BIOS/UEFI does not recognize USB of v2+, but computer does
If you are using a USB hub or USB PCI controller, this may not be handled by your BIOS. Try to use another USB port. Some ports may have a built-in hub on the motherboard and a buggy BIOS that can't handle it.
`
Still not resolved.

**Comment by arch1mede** [comment]
Hi, please use Discord to discuss this issue. This is not a real reportable issue.
