### ISSUE TITLE
ESP32-S2 HID

### ISSUE THREAD

**Issue by tomaszduda23** [pikvm/pikvm#771]
ESP32-S2 could be used as HID keyboard and mouse over WIFI.

https://www.wemos.cc/en/latest/s2/s2_mini.html?spm=a2g0o.detail.1000023.1.5ea857b17pvgNr

https://github.com/chegewara/EspTinyUSB

**Comment by mdevaev** [comment]
I thought about it and I don't see any point in doing that, especially considering that we still have wired HDMI. My AVR firmware and your STM32 covers absolutely all use cases. And if we are talking about the personal preference of end users, then they should not care which MCU is used for the HID.

For the rest of the cases, my policy is that if someone needs something strange, he does it himself, and if it doesn't break existing apis and does not require strange dependencies, I will accept it as PR.
