### ISSUE TITLE
Ultrawide resolution

### ISSUE THREAD

**Issue by ajknol** [pikvm/pikvm#774]
Currently I have pikvm as my primary monitor plugged into my desktop pc. I always work remote on this pc. Everything works fine after editing edid (https://docs.pikvm.org/edid/) - can see the bios remotely etc. The only thing is the maximum resolution is 1920x1080 in Win11. When I connect my monitor directly not working remote (without pikvm) higher resolutions are available.

Is it possible to enable 3440x1440 in pikvm to connect with my ultrawide monitor remotely?

**Comment by mdevaev** [comment]
The maximum resolution is 1920x1080. It is impossible to do bigger, this is a hardware limitation.
