### ISSUE TITLE
oled display not enabled by default

### ISSUE THREAD

**Issue by nona00** [pikvm/pikvm#779]
**Describe the bug**
I installed https://files.pikvm.org/images/v3-hdmi-rpi4-latest.img.xz on PI HAT v3.

At boot the oled display did not work. I had to manually enable it by:

rw; systemctl enable --now kvmd-oled; ro

**To Reproduce**
see above

**Expected behavior**
oled display usable out of the box

**PiKVM info:**
- Raspberry Pi board version: RPi 4
- PiKVM platform: PiKVM v3 HAT
- Video capture type: PiKVM v3 HAT (HDMI in)
- KVMD version: pacman -Q | grep kvmd
kvmd 3.117-1
kvmd-fan 0.22-1
kvmd-oled 0.12-1
kvmd-platform-v3-hdmi-rpi4 3.117-1
kvmd-webterm 0.42-1
- uStreamer version: pacman -Q | grep ustreamer
ustreamer 5.11-1
- Linux kernel: uname -a
Linux pikvm 5.15.34-2-rpi-ARCH
https://github.com/pikvm/pikvm/issues/1 SMP Fri Jun 3 06:14:48 MSK 2022 armv7l GNU/Linux

**Comment by mdevaev** [comment]
This behavior is described in the [documentation](https://docs.pikvm.org/v3/#basic-setup) and configured to work well with sets without a screen and fan. If you need an image where this is enabled by default, use this: https://files.pikvm.org/images/v3-hdmi-rpi4-box-latest.img.xz
