### ISSUE TITLE
Audio v2-hdmi-rpi4 How to support it?

### ISSUE THREAD

**Issue by TelDragon** [pikvm/pikvm#782]
[https://docs.pikvm.org/multiport/](https://docs.pikvm.org/multiport/)

Follow its process.

V2 HDMI also uses tc358743

**Comment by mdevaev** [comment]
On V2 it depends on the capture device. Most of them contain a hardware problem due to which the sound does not work. The list of working devices is unknown. In any case, this is not officially supported.

Please use Discord for support questions.
