### ISSUE TITLE
Aborting image upload does not delete partially uploaded file

### ISSUE THREAD

**Issue by asheroto** [pikvm/pikvm#783]
**Describe the bug**
If you upload an image, then decide to abort the upload, the partially uploaded image file remains which prevents you from re-uploading it. You must delete it from the images directory.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Select image to upload
2. Click Upload
3. Click Abort

File still exists `/var/lib/kvmd/msd/images`

**Expected behavior**
Temporary file should be deleted if upload is aborted.

**Screenshots**
N/A

**Info**
KVMD: 3.123
Streamer: 5.17 (ustreamer)
HAS_PDEATHSIG: Yes
WITH_GPIO: Yes
WITH_PTHREAD_NP: Yes
WITH_SETPROCTITLE: Yes
WITH_SYSTEMD: Yes
Linux kernel:
Machine: armv7l
Release: 5.15.34-4-rpi-ARCH
Version: 1 SMP Tue Jul 5 12:10:16 MSK 2022

**Comment by connected201** [comment]
I can confirm, problem exist!.

**Comment by mdevaev** [comment]
Will be fixed in the next release.
