### ISSUE TITLE
pacman update reports "/var/lib/kvmd/msd: Read-only file system"

### ISSUE THREAD

**Issue by marcelser** [pikvm/pikvm#785]
**Describe the bug**
during last pacman update with -Sya when it start applying the package changes I get:
```
(50/58) upgrading kvmd                                                                                                                                                           ==> Ensuring KVMD users and groups ...
chown: changing ownership of '/var/lib/kvmd/msd': Read-only file system

```

**To Reproduce**
Steps to reproduce the behavior, like:
1. rw
2. pacman update with -Sya

**Expected behavior**
no errors on chown

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox
 - Version 102.0.1

**PiKVM info:**
  - Raspberry Pi board version RPi 4
  - PiKVM platform v3-hdmi
  - KVMD version: 
        kvmd 3.127-1
        kvmd-fan 0.22-1
        kvmd-oled 0.12-1
        kvmd-platform-v3-hdmi-rpi4 3.127-1
        kvmd-webterm 0.42-1
  - uStreamer version: ustreamer 5.17-1
  - Linux kernel: Linux pikvm 5.15.34-4-rpi-ARCH #1 SMP Tue Jul 5 12:10:16 MSK 2022 armv7l GNU/Linux

**Additional context**
Would be nice to know if there's a manual fix

btw: the /etc/fstab looks like:
```
/dev/mmcblk0p1 /boot     vfat   ro,errors=remount-ro    0 0
tmpfs /var/lib/systemd   tmpfs  mode=0755               0 0
tmpfs /var/lib/private   tmpfs  mode=0700               0 0
tmpfs /var/lib/dhclient  tmpfs  mode=0755               0 0
tmpfs /var/lib/dhcpcd    tmpfs  mode=0750               0 0
tmpfs /var/log           tmpfs  nodev,nosuid            0 0
tmpfs /var/tmp           tmpfs  nodev,nosuid            0 0
tmpfs /tmp               tmpfs  nodev,nosuid,mode=1777  0 0
tmpfs /run               tmpfs  nodev,nosuid,mode=0755  0 0
/dev/mmcblk0p3 /var/lib/kvmd/msd  ext4  nodev,nosuid,noexec,ro,errors=remount-ro,data=journal,X-kvmd.otgmsd-root=/var/lib/kvmd/msd,X-kvmd.otgmsd-user=kvmd  0 0
```

**Comment by mdevaev** [comment]
It's not a problem, everything is fine. I'll mute this message.
