### ISSUE TITLE
API mouse_move not effetct

### ISSUE THREAD

**Issue by lxf920125** [pikvm/pikvm#786]
Hi,
I want to use script to control the remote PC,
I use mose_move like this:
ws.send('{"event_type": "mouse_move", "event": {"to": {"x":10000,"y":1000}}}')
however, the position of the mouse always to the top left corner, i don't know why. It seems that the API not really effected.

**Comment by mdevaev** [comment]
This cannot fail to work, this API is used by the web interface. I just tested it on my KVM with such a script. Everything is fine.
```python
import websocket, time
uri = "wss://pikvm/api/ws?stream=0"
headers = {"X-KVMD-User": "admin", "X-KVMD-Passwd": "admin"}
ws = websocket.WebSocket(sslopt={"cert_reqs": ssl.CERT_NONE})
ws.connect(uri, header=headers)
while 1:
    ws.send('{"event_type": "mouse_move", "event": {"to": {"x":10000,"y":1000}}}')
    time.sleep(1)
    ws.send('{"event_type": "mouse_move", "event": {"to": {"x":0,"y":0}}}')
    time.sleep(1)
ws.close()
```

**Comment by lxf920125** [comment]
Thanks, I understood, this really works well, In fact, the position not the real position like PC screen rate, If I want to use the position in the screen, should I must remap the position like the mouse.js?
![image](https://user-images.githubusercontent.com/28556522/181397672-745edd3d-1ecf-4fdc-948b-7c9f35b09842.png)
for example, the PC screen rate is 1920*1080,  I want to move to position (1200,800)

**Comment by lxf920125** [comment]
Hello,
In addition, while I move the position use API, the mouse not hold on this point
the case is I will use API to control the remote PC, move mouse and click mouse left,  so I use it like this, is there other better method to operate this?
ws.send('{"event_type": "mouse_move", "event": {"to": {"x":10000,"y":1000}}}')
 ws.send('{"event_type": "mouse_button", "event": {"button":"left","state":true}}')
time.sleep(0.01)
 ws.send('{"event_type": "mouse_button", "event": {"button":"left","state":false}}')

**Comment by mdevaev** [comment]
> If I want to use the position in the screen, should I must remap the position like the mouse.js?

Yes.

> while I move the position use API, the mouse not hold on this point

I don't understand. If you need something like "grab and move", you need to fire mouse_button event with true state, then move, then button again with false.

**Comment by lxf920125** [comment]
thanks, this already helped for my use scenario! I already remap the position.

**Comment by mdevaev** [comment]
:ok_hand:
