### ISSUE TITLE
Atx control power problem

### ISSUE THREAD

**Issue by kesp91** [pikvm/pikvm#796]
I connected a v3 atx to my supermicro server. The server doesn’t respond to short click power , but the long click starts to turn server on but lasts too long and shuts down system immediately.

Is there a way to increase the “duration” of the short click through software changes? 

On a side note I was thinking of attaching the atx to a simultaneous second system. Can the click reset be repurposed and only act as a power button too (by changing code?) if attached to power pins on second hard drive?

**Comment by mdevaev** [comment]
Sup. Yes, you can change the duration using `/etc/kvmd/override.yaml` like this:
```yaml
kvmd:
    atx:
        click_delay: 1
        long_click_delay: 3
```
Also you can use reset wipe as you like, but you can't change it's name.
