### ISSUE TITLE
Web browser access to iPad Pro 11" (3rd Gen) has screen flicker

### ISSUE THREAD

**Issue by fxbulldog** [pikvm/pikvm#801]
**Describe the bug**
Screen flickers to the point that it is not usable.  Flicker = screen is seen then not seen (No Signal) every 10 seconds. Occurs on both local connection and port forwarded connection.

**To Reproduce**
Both video (MJPEG/HTTP & H.264 / WebRTC) modes tried. 

Try 1 (Using Apple USB-C to Digital AV):
Connected to KVM switch select GPIO input (Screen Flicker)
Rebooted PiKVM and Switch (Screen Flicker)
Connected direct to PiKVM as a single source (Screen Flicker)

Try2 (Using Akhara USB-C to Digital AV):
Connected direct to PiKVM as a single source (Screen Flicker)

Try3 (Using Dell Thunderbolt Dock WD19TBS):
Connected direct to PiKVM as a single source (Screen Flicker)

**Expected behavior**
No screen flicker

**Desktop** 
macOS 12.5
Safari 15.6 / Firefox 103.0.1

win10 21H1
Firefox 103.0.1 / Edge 104.0.1293.47

**PiKVM info:**
PiKVM v3 Pre-Assemble
KVMD: 3.61
Streamer: 5.1 (ustreamer)
HAS_PDEATHSIG: Yes
WITH_GPIO: Yes
WITH_PTHREAD_NP: Yes
WITH_SETPROCTITLE: Yes
WITH_SYSTEMD: Yes
Linux kernel:
Machine: armv7l
Release: 5.15.25-10-rpi-ARCH
Version: #1 SMP Wed Mar 16 06:04:18 MSK 2022
ezcoo HDMI 2.0 KVM Switch 4x1
iPad Pro 11" (3rd Gen) IOS 15.5
Enabled Dual mouse mode - Had to select Relative to get the mouse to work.

**Comment by fxbulldog** [comment]
Updated to the following it is better in the MJPEG/HTTP video mode in that is does not go to no signal and just fades for 1sec instead. 

KVMD: 3.134
Streamer: 5.19 (ustreamer)
HAS_PDEATHSIG: Yes
WITH_GPIO: Yes
WITH_PTHREAD_NP: Yes
WITH_SETPROCTITLE: Yes
WITH_SYSTEMD: Yes
Linux kernel:
Machine: armv7l
Release: 5.15.34-4-rpi-ARCH
Version: #1 SMP Tue Jul 5 12:10:16 MSK 2022

**Comment by arch1mede** [comment]
Hi, the tablet experience still needs to be worked on, the dev is aware but is not a priority at the moment. I have found that activating VNC+using a VNC client is a much better experience. Please see this [page.](https://docs.pikvm.org/vnc/)

My VNC client of choice is Jump but its a little pricey.

**Comment by mdevaev** [comment]
Could you show `journalctl -u kvmd` on flickering?

**Comment by mdevaev** [comment]
I've tried iPad Pro 12.9 with the official Apple USB->HDMI converter and everything is working great.

+ no answer from the issue author, so I'm closing this.
