### ISSUE TITLE
How to change stream resolution ratio

### ISSUE THREAD

**Issue by lxf920125** [pikvm/pikvm#811]
Hello,
I want to change the resolution ratio of the streamer, for example I set it as 1920*1080 or other ratio I wanted,
is there API to help me?

**Comment by mdevaev** [comment]
Sup.

In case of V3/CSI bridge, the screen resolution depends entirely on the host, you can't change it from PiKVM side.

In case of USB capture: you can use `POST /api/streamer/set_params?resolution=NNNxNNN` to change the resolution, BUT it is not actual resolution changing, it does not change the host's resolution, it's kinda zooming.

**Comment by lxf920125** [comment]
Thanks, I find chaning EDID configuration could help me!
https://docs.pikvm.org/edid/?h=edid#custom-edids
