### ISSUE TITLE
Chrome on Mac keyboard code problem

### ISSUE THREAD

**Issue by visit1985** [pikvm/pikvm#819]
First, a big **Thank you for your awesome work!** I know you just closed an annoying ticket like this, so I sincerely apologize for this one.

I access a Windows 10 Host with US keyboard layout via PiKVM from Mac OS 12.5 with an Englisch International Magic Keyboard and U.S. layout.

In Safari the &#96;~ key (next to left shift) is correctly sent to the web interface.
In Chrome the &#96;~ key is interpreted as N/US.

It works properly in the web console, just not in KVM.

I have to use Chrome in app mode to avoid the Ctrl+T problem, but I need the &#96;~ key pretty often too.
Is there a way to work around this?

**Comment by mdevaev** [comment]
Hello. This one?

![image](https://user-images.githubusercontent.com/416259/190897861-2b51fe08-5fef-4d26-b653-5b67a8984b16.png)

I'll try to debug this.

**Comment by visit1985** [comment]
Yes, this one. If I can help you debug, just let me know how.

**Comment by mdevaev** [comment]
Yes, I need your help here :)

You need to open the JS console in chrome and use this url for KVM: `https://yourkvm/kvm/?debug=1` Press that keys and show me the JS console log.

**Comment by visit1985** [comment]
The &#96;~ key logs

```
Keyboard: key pressed: IntlBackslash
```

The \\| key produces the same chars, but logs

```
Keyboard: key released: Backslash
```

**Comment by visit1985** [comment]
Safari logs IntlBackslash on §± key and Backquote on &#96;~ key. So it seems this keys need to be swapped.

**Comment by mdevaev** [comment]
Okay, thank you. I'll think what I can do.

**Comment by mdevaev** [comment]
Is it reproducet if you will use the regular pc keyboard with mac?

**Comment by visit1985** [comment]
A regular pc keyboard does not have this key.

**Comment by visit1985** [comment]
And I'm still curious, why it works properly in the web console, just not in KVM.

**Comment by mdevaev** [comment]
The reason is that web console and KVM are using different ways to process keyboard.

**Comment by mdevaev** [comment]
Here the some explanation of the issue: https://github.com/microsoft/node-native-keymap/issues/15

I can add menu switch to swap two keys but I need idea how to name this option shortly. `Swap IntlBackslash/Backqoute keys is too long.

**Comment by visit1985** [comment]
You could just make it a config switch in override.yaml

**Comment by mdevaev** [comment]
This is a browser problem and should be solved in the browser, in override the option would work for everyone

**Comment by visit1985** [comment]
I did some further testing and found, that on a javascript keydown event the event.key attributes is always set correctly, while the event.code attribute is different between Chrome and Safari. Couldn't you implement a condition based on the detected browser, event.key and event.code then?

**Comment by mdevaev** [comment]
What happens if you use a regular pc keyboard on mac os? I checked on my mac and a similar fix for apple magic keyboard breaks pc keyboard because there is no way to distinguish different keyboards at the browser level.

**Comment by visit1985** [comment]
The only "regular keyboard" I own is [this](https://www.amazon.com/dp/B01DBVH16U). At least it has a &#96;~ key next to 1.
The key/code combinations to fix do not appear with that keyboard on my mac.

| Browser | Key pressed  | event.key | event.code | event.shift |
| --- | --- | --- | --- | --- |
| Chrome | `` `~ `` | ` | Backquote | false |
| Chrome | `Shift` + `` `~ `` | ~ | Backquote | true |
| Safari | `` `~ `` | ` | Backquote | false |
| Safari | `Shift` + `` `~ `` | ~ | Backquote | true |

**Comment by mdevaev** [comment]
If I just swap keys `Backquote` and `IntlBackslash` for non-Safari, your PC keyboard will stop working correctly and will generate IntlBackslash when you click on `~`. This setting should depend on the type of keyboard, but there is no way to know which keyboard you are currently using.

**Comment by visit1985** [comment]
Do you have access to event.key/code from your kvm code?

You could build something like:

if (event.key = "`" and event.code = "IntlBackslash") then event.code = "Backquote"

**Comment by mdevaev** [comment]
Good idea. I'll try

Ср, 21 сент. 2022 г. в 10:01, Michael Göhler ***@***.***>:

**Comment by visit1985** [comment]
Looks like `x in []` has to be replaced with `[].includes(x)` in javascript.

```
if (code == "IntlBackslash" && ["`", "~"].includes(event.key)) {
	code = "Backquote";
} else if (code == "Backquote" && ["§", "±"].includes(event.key)) {
	code = "IntlBackslash";
}
```

**Comment by mdevaev** [comment]
Oh crap. One moment.

**Comment by mdevaev** [comment]
3.147 released

**Comment by visit1985** [comment]
Now it works perfectly on magic and external pc keyboard. Thanks a lot!

**Comment by mdevaev** [comment]
Great! Thank you for your help.
