### ISSUE TITLE
assigning static IP

### ISSUE THREAD

**Issue by a-singer** [pikvm/pikvm#82]
Hello,
Hello,

For some reason, my iPhone is not recognising the hostname pikvm though my Windows machine does. If I may ask, how does one assign a static IP address to the pikvm? Thanks.

**Comment by mdevaev** [comment]
Try this: https://wiki.archlinux.org/index.php/Netctl#Wired_2

**Comment by mdevaev** [comment]
Okay, I guess I answered your question. Feel free to reopen if necessary.

**Comment by ozboss** [comment]
For others looking how to set a static IP for pikvm:

Networking seems to be handled by systemd-networkd now and not netctl.
Therefore edit `/etc/systemd/network/eth0.network` according to https://wiki.archlinux.org/index.php/Systemd-networkd#Wired_adapter_using_a_static_IP
