### ISSUE TITLE
Request: rsync on files.pikvm.org

### ISSUE THREAD

**Issue by singingtelegram** [pikvm/pikvm#824]
**Is your feature request related to a problem? Please describe.**
Download speeds from my ISP are low, in the 100KB/s range.

**Describe the solution you'd like**
I'd like to set up a mirror server for files.pikvm.org, so it would be great if you can set up rsync on the files server for mirroring.

**Describe alternatives you've considered**
Another solution would be using lftp to mirror the archive, however rsync is the standard practice for providing access to downstream mirrors.

**Additional context**
None.

**Comment by mdevaev** [comment]
Done, but I've exposed only packages because we have no cpu resources to expose OS images because of their size.

```
rsync://files.pikvm.org/repos
```
