### ISSUE TITLE
Question: Possibility to wake up machine on schedule through ATX?

### ISSUE THREAD

**Issue by imightbelosthere** [pikvm/pikvm#836]
Hi,

More of a question than anything else... Can one wake up the machine connected through ATX with a command on the CLI?
If so, can we schedule it with cron? Or is there an API that we can call to do this?

Thanks

**Comment by mdevaev** [comment]
Hello. You can use `curl` with ATX api + systemd timer: https://docs.pikvm.org/api/#set-atx-power
