### ISSUE TITLE
GPIO Input not working

### ISSUE THREAD

**Issue by andreaconfa** [pikvm/pikvm#840]
I all,
i'm testing pikvm on a Raspberry PI4B with an ezcoo 4hdmi switch.

I'm building a custom HAT PCC to handle my four server ATX control.

In my config ovverride i setted up and correctly tested the ezcoo switch and is working fine.
I also added some input / outputs to control and receive status of the servers ATX but i found that the input are not displayed. The led bouble stays always grey.

I'm testing it manually puytting the GPIO tu the 3.3v directly and i found that is not working. 

Here my config override: https://pastebin.com/DQvCrxJL

**Comment by mdevaev** [comment]
Hello. Are you sure that you're using corrent pin numbers? You need to use GPIO(X) values, not physical pin numbers: https://pinout.xyz

**Comment by mdevaev** [comment]
Sup?

**Comment by andreaconfa** [comment]
Issue resolved.
I’m the configuration I accidentally used a pin two times

Inviata da iPhone

Il giorno 6 nov 2022, alle ore 21:11, Maxim Devaev ***@***.***> ha scritto:

﻿

Sup?

**Comment by mdevaev** [comment]
Glad to hear it!
