### ISSUE TITLE
Add time/date stamp to drive -> image selection drop down menu

### ISSUE THREAD

**Issue by n3gwg** [pikvm/pikvm#842]
When one uses the Drive menu and wishes to mount an image they click the down arrow and are presented the image selection menu inclusive of the size of the image. How difficult would it be to also have the date/time stamp of ISO in that window too? This would allow the user to know if they needed to update the image perhaps in a very convenient manner.

**Comment by mdevaev** [comment]
It's not difficult but do you really need this? This is a rare case. Why just don't use date and time in the image name? like `foobar-20221104.iso`

**Comment by n3gwg** [comment]
I have a tendency to give the ISOs the same name I am familiar with seeing them have when I download them from their source website. Moreover, image names can be quite long to begin with (like: "debian-live-11.4.0-amd64-gnome+nonfree.iso" or that kind of thing).

It is surely not an urgent feature request, I can live without it. However, the next time you are in that section of the code and you can get to implementing it, I would surely like to see it added. I understand that there may be functional bugs taking priority over modest improvements. I also think it would not require very much more screen real estate to do so as well.

**Comment by mdevaev** [comment]
It takes too much space:

![image](https://user-images.githubusercontent.com/416259/200091564-6d9a3dc3-b279-4027-91c9-dd0e3597e804.png)

**Comment by mdevaev** [comment]
It takes too much space:

![image](https://user-images.githubusercontent.com/416259/200091592-6f3e63e0-8392-404c-99a4-b28c494bee5a.png)

**Comment by n3gwg** [comment]
Well I would suggest that of the entirety of the date/time group, the seconds and the portion thereafter could be disposed of. My reasoning is that most websites showing ISO downloads only depict the date and the time contains only hours and minutes anyway.

**Comment by mdevaev** [comment]
Will be available in the next release.

**Comment by n3gwg** [comment]
That is most excellent and I appreciate in no uncertain terms your most brisk and open minded outlook with respect to the software component of the PiKVM. I think it will be a useful and utilitarian improvement.

Thank you again so very much.

**Comment by n3gwg** [comment]
I am very happy with the way the changes work and thank you again.
You can close out this ticket if you wish.

Stuart
