### ISSUE TITLE
h264_bitrate in override.yaml not persisting and reverting values

### ISSUE THREAD

**Issue by trevorl-dtl** [pikvm/pikvm#869]
**Describe the bug**
when setting h264_bitrate in max_override.yaml, the setting does override the default value. However after reboot, it does not persist and defaults to an arbitrary value of "5000". User must manually drag the slider to below the max to refresh the session, thereafter pulling the slider to max then sets the max correctly. The value defaults back to 5000 after sometime too even without reboot.

**To Reproduce**
1. Set value in /etc/kvmd/override.yaml like so:
```
kvmd:
    streamer:
        h264_bitrate:
            default: 100
            max: 100
```
2. ro and reboot
3. verify the value with kvmd -m
4. go to web gui and h264_bitrate is above the max

**Expected behavior**
Max value to be as per override.yaml and not revert overtime either.

**Screenshots**
![Issue](https://user-images.githubusercontent.com/107994087/201895512-82e9219a-b5ba-4b27-936a-7731460b763e.png)

![Issue 2](https://user-images.githubusercontent.com/107994087/201895550-73db3bab-747e-43ad-bbb9-edae194f9dcd.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 106.0.5249.91 (Official Build) (64-bit)
 - VNC client: N/A

**PiKVM info:**
PiKVM V3 Pre-Assembled
kvmd 3.168-1
kvmd-fan 0.22-1
kvmd-oled 0.13-1
kvmd-platform-v3-hdmi-rpi4 3.168-1
kvmd-webterm 0.42-1
ustreamer 5.31-1
Linux <redacted>-kvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux

**Comment by mdevaev** [comment]
Fixed
