### ISSUE TITLE
Error compiling os for Pi3 board + PiKVM v3 HAT - haveged service error

### ISSUE THREAD

**Issue by TomKVM** [pikvm/pikvm#875]
Hi, I ma putting together my PiKVM using the following components:
- Raspberry Pi 3 - Model B v1.2 w/ 4Gb RAM
- PiKVM v3 HAT

I following the script on the building the OS for it and it's going thru without issue all the way up to Step 29/92  where it executes the following line : 'RNGD_OPTS="-o /dev/random -r /dev/hwrng -x jitter -x rtlsdr" ' > /etc/conf.d/rngd    && systemctl disable haveged  && systemctl enable rngd

The following error message is outputted : " Failed to disable unit, unit haveged.service does not exist.

it exited the compilation with this error. 

I am compiling this on an intel i5 laptop with Ubuntu workstation LTS 22.04. The first time this error came out, I did check the status of this Haveged service and it was not installed on Ubuntu. I went ahead and installed it and made sure the service was up and running before restarting the compilation. The error continues to occur..

Any thoughts on what could be causing this error ?

**Comment by mdevaev** [comment]
Hello. V3 HAT should be installed on Pi 4. Pi 3 is not supported. Are you sure you really want to do this?

**Comment by TomKVM** [comment]
I was under the impression that PiKVM could be used on Pi3 as well according to the documentations. Am I wrong ?

**Comment by mdevaev** [comment]
V3 HAT is only for Pi 4. To use the Pi 3, you need to go down the V2 (DIY) path with Arduino as a keyboard and mouse emulator.
