### ISSUE TITLE
On screen Keyboard + Mouse on low res display / mobile device

### ISSUE THREAD

**Issue by Testato** [pikvm/pikvm#88]
if you use pikvm on a low resolution monitor, such as a Netbook that has 1024 × 600 pixels, the onscreen keyboard and onscreen mouse automatically appear.
And it is not possible to close the keyboard because it is higher than the browser window

![photo_2020-10-04_18-53-10](https://user-images.githubusercontent.com/6893841/95021706-e7354b00-0672-11eb-8e41-6fc1327e12e0.jpg)

**Comment by mdevaev** [comment]
Should be fixed now.
