### ISSUE TITLE
Pin-out of serial port

### ISSUE THREAD

**Issue by oscni** [pikvm/pikvm#881]
I might be blind ;) but I doesn't seem to find the pin-out of the serial port. Shouldn't it be on this page?
https://docs.pikvm.org/v3/

Thanks for a great product that i've been seen searching for many years!

**Comment by mdevaev** [comment]
Hello. This is a standard Cisco-style cable, see here: https://wiki.mikrotik.com/wiki/Manual:System/Serial_Console

**Comment by mdevaev** [comment]
I've added the link to the doc :)
