### ISSUE TITLE
Add ability to mount SMB share

### ISSUE THREAD

**Issue by connected201** [pikvm/pikvm#885]
hi, it will be great if you add option to mount SMB share, where we can save img files or iso images, and use it without downloading iso to pikvm.
with choice of data path, local or remote path.

![image](https://user-images.githubusercontent.com/20506433/204514134-182a0679-90eb-4f70-929f-261bde203822.png)
somewhere here to add this option.

**Comment by mdevaev** [comment]
Duplicate: #100
