### ISSUE TITLE
Additional Keyboard Shortcuts (e.g. CTRL+ALT+F2)

### ISSUE THREAD

**Issue by GrapeFruitStudioUK** [pikvm/pikvm#888]
This may be my ignorance (if this feature already exists) however if I have a linux desktop stuck that I could reboot by pressing CTRL + ALT +F2 and getting a console I cant do this under the default setup.

Could such shortcuts be added or is there a configuration file that allows us to add our own?

**Comment by mdevaev** [comment]
Hello. I've added Ctrl+Alt+F1/F2. It will be available in the next release.
