### ISSUE TITLE
Alternative Mosfets

### ISSUE THREAD

**Issue by billwurles** [pikvm/pikvm#889]
Hi there,
I'm struggling to find the [OMRON G3VM-61A1](https://www.digikey.com/products/en?keywords=G3VM-61A1) mosfets available for a reasonable price where I am. What would be the risk of using something like an [IRF520N](https://docs.rs-online.com/c89c/0900766b80028e14.pdf), [IRLZ44N](https://docs.rs-online.com/8cf7/0900766b80028e42.pdf) or [FQP50N06](https://4donline.ihs.com/images/VipMasterIC/IC/ONSM/ONSM-S-A0003584711/ONSM-S-A0003584489-1.pdf?hkey=6D3A4C79FDBF58556ACFDE234799DDF0)?

Could someone give me a set of parameters required for the ATX pinout, in regards to Drain-Source Voltage, Drain current and gate voltage?

**Comment by mdevaev** [comment]
No need to reinvent the wheel of mosfets :) Buy any of these parts:
https://eu.mouser.com/c/optoelectronics/optocouplers-photocouplers/mosfet-output-optocouplers/?number%20of%20channels=1%20Channel&package%20%2F%20case=DIP-4&instock=y&active=y&normallystocked=y

- TLP240GA
- TLP241B
- TLP3553A
- TLP3554
- TLP3555A
- TLP3558A
