### ISSUE TITLE
Timezone Keeps Changing

### ISSUE THREAD

**Issue by vipergts450** [pikvm/pikvm#890]
Hello,

I tried to update my timezone today using timedatectl after switching to read-write mode. It accepts my new timezone and is reflected in timedatectl show and timedatectl status. After a couple of minutes, if I run timedatectl again, it has reverted to the prior value and my system time is wrong again. running ls -l /etc/localtime shows that the symbolic link has not been updated after running timedatectl and still points to the incorrect zonefile.

Is there something I'm doing wrong?

**Comment by mdevaev** [comment]
Just make it manually:
> ln -sf /usr/share/zoneinfo/**Zone/SubZone** /etc/localtime
