### ISSUE TITLE
Fan errors in log and interface

### ISSUE THREAD

**Issue by danyal** [pikvm/pikvm#900]
I'm getting this message repeatedly in the logs:
ERROR --- Can't read fan state: Cannot connect to unix socket /run/kvmd/fan.sock ssl:default [No such file or directory]
I don't have a fan connected (using a heatsink).

**Comment by mdevaev** [comment]
Which device do you use?

**Comment by danyal** [comment]
I'm using this: https://www.blicube.com/blikvm-pcie/ which has a Pi CM4. Fan is not connected because it has a heat sink.

**Comment by mdevaev** [comment]
Sorry, we don't support this hardware. Contact the hardware manufacturer.
