### ISSUE TITLE
RFE: script hooks around streamer startup/shutdown

### ISSUE THREAD

**Issue by awilliam** [pikvm/pikvm#905]
When a video stream is initiated, I'd like to be able to automatically power-on components to support that stream, ex. HDMI switches and splitter.  When the video stream terminates, I'd likewise like to be able to automatically power-off these devices.

I can currently create gpio cmds which create buttons in the UI for such events, but it's a manual process to trigger those buttons whereas I'd like something automatic.

Perhaps pre/post-hooks could be provided for various sub-processes, streamer in this case, or each process could trigger events that could be linked to buttons or gpio cmds.

**Comment by awilliam** [comment]
As an unsupported alternative, I've achieved this via an inotify script run from a simple systemd service:

```
#!/bin/bash

power_off() {
        sleep 1
        logger -t $(basename $0) "Turning video accessories OFF"
        # TURN OFF CODE HERE
}

inotifywait -mq --format '%e' /dev/kvmd-video |
while IFS= read -r events; do
        case "$events" in
                OPEN)
                        kill $(jobs -p) > /dev/null 2>&1
                        logger -t $(basename $0) "Turning video accessories ON"
                        # TURN ON CODE HERE
                        ;;
                CLOSE*)
                        power_off &
                        ;;
        esac
done
```

The power-off logic is to account for streamer restarting when it doesn't immediately get a signal, and avoids an extra power bounce.

**Comment by mdevaev** [comment]
What exactly does your code do here `# TURN ON CODE HERE`? There is one old feature that allows you to issue various GPIO signals when starting the streamer, connecting clients, and so on:
```
GPIO options:
═════════════
    --gpio-device </dev/path>  ───── Path to GPIO character device. Default: /dev/gpiochip0.

    --gpio-consumer-prefix <str>  ── Consumer prefix for GPIO outputs. Default: ustreamer.

    --gpio-prog-running <pin>  ───── Set 1 on GPIO pin while uStreamer is running. Default: disabled.

    --gpio-stream-online <pin>  ──── Set 1 while streaming. Default: disabled.

    --gpio-has-http-clients <pin>  ─ Set 1 while stream has at least one client. Default: disabled.
```

**Comment by awilliam** [comment]
I'm twiddling a remote smart power outlet via curl, but I expect to switch to mosquitto_pub since I've already broken the seal on making changes to the base system.

**Comment by mdevaev** [comment]
Hey, better late than never, isn't it? :) Available in the new release.

```yaml
kvmd:
    streamer:
        pre_start_cmd: [/bin/echo, foo]
        post_stop_cmd: [/bin/echo, bar]
```
