### ISSUE TITLE
can we add a terminal button that runs a specific command?

### ISSUE THREAD

**Issue by tedserreyn** [pikvm/pikvm#924]
Connect to my pikvm I have a 7 port usb hub that has on it usb to serial adapters connected to several external devices that only have serial consoles (think switch, firewall, routers).   This is in addtion to multiple PC consoles connected via a serial controlled KVM that is controlled by pikvm.

I would like the ability to connect minicom or other terminal problem directly to these outbound serial ports.  I can open a single terminal and run the settings and connect to the specific usb cable (using /dev/serial/by-id/* files).

As a bonus it would be great to set the serial port settings (speed/duplex/flowcontrol) on the port connected.

I would envision this as another terminal button (may serial terminal?) that we could add multiple and then define each one as needed.  This would be dynamic and people that need a single serial port could use the integrated one or add a single port and point to the serial device and set it up.  This could use the already implemented webterm with just an argument to run the program direclty. 

Clicking button would open a terminal with a serial session directly connected to the serial port.

I could also see this implemented as an add-on menu similar to the GPIO, where is could open 
This could also add different commands to to the interface to do things on the pikvm directly (run top?).

**Comment by jmott85** [comment]
Would be nice to have a button, but I created a workaround using the existing Terminal app.  

1. add to the top of /home/kvmd-webterm/.bashrc:
```
trap '' 2
<ENTER BASH SCRIPT OR COMMANDS HERE>
exit
trap 2
```

**Comment by tedserreyn** [comment]
Yeah but I need eight of them.  Can we use multiple web terms?

**Comment by mdevaev** [comment]
Now there is no such feature, and this task is already on the list, so I'm closing it as duplicate.

By the way, there is limited support for executing commands, but without output to the terminal, perhaps it will be useful to you: https://docs.pikvm.org/gpio/#cmd

**Comment by tedserreyn** [comment]
Interesting idea, I will look into it, looks like this may be non-interactive commands so I can’t try a minicom right from there?



From: Maxim Devaev ***@***.***>
Date: Monday, February 6, 2023 at 10:29 AM
To: pikvm/pikvm ***@***.***>
Cc: Ted Serreyn ***@***.***>, Author ***@***.***>
Subject: Re: [pikvm/pikvm] can we add a terminal button that runs a specific command? (Issue #924)

Now there is no such feature, and this task is already on the list, so I'm closing it as duplicate.

By the way, there is limited support for executing commands, but without output to the terminal, perhaps it will be useful to you: https://docs.pikvm.org/gpio/#cmd

**Comment by mdevaev** [comment]
Yes.

**Comment by jmott85** [comment]
Here's an example of a dialog script that could work for you.  I don't have minicom installed to test if it works correctly, but it should get you close to what you're looking for.

```
#!/bin/bash

TEMP=/tmp/answer$$

clean_up() {
    rm -f $TEMP
    exit
}

serial_menu2() {
    dialog --title "Connect to serial console" --default-item "9600" --menu "Choose baud rate" 15 25 25 \
    1200 "" 2400 "" 4800 "" 9600 "" 19200 "" 38400 "" 57600 "" 115200 "" \
    2>$TEMP

    if [ "$?" != "0" ] ; then return ; fi

    dialog --title "Connect to serial console" --msgbox "To exit, close this browser window or type <CTRL>+a <CTRL>+q" 7 50

    choice=$(cat $TEMP)
    clear
    minicom -D $dev -b $choice
    clean_up
}

serial_menu1() {
	dialog --title "Connect to serial console" --menu "Choose serial port" 15 25 25 \
	1 "/dev/ttys0" 2 "/dev/ttys1" 3 "/dev/ttys2" 4 "/dev/ttys3" \
	2>$TEMP
	
	if [ "$?" != "0" ] ; then clear; clean_up ; fi
	
	choice=$(($(cat $TEMP)-1))
	dev="/dev/ttyS$choice"
	serial_menu2
}

while true
do
    serial_menu1
done
```

**Comment by bhupiister** [comment]
## I have pasted this from [tsl0922/ttyd](https://github.com/tsl0922/ttyd/wiki/Programming-interface)

Based on this, is it possible to use something like this and launch a web terminal with custom command?

```ts
interface TtydTerminal extends Terminal {
    fit(): void;
}

declare global {
    interface Window {
        term: TtydTerminal;
    }
}
```

ttyd exposes the xterm.js [Terminal](https://xtermjs.org/docs/api/terminal/classes/terminal/) instance via `window.term`, and a `fit()` function on it (see [fit addon](https://xtermjs.org/docs/api/addons/fit/)).

## Use Cases

- Programmatically sending input from the client ([#620](https://github.com/tsl0922/ttyd/issues/620))
	```js
	var script = document.createElement('script');
	script.src = 'https://unpkg.com/keysim@latest/dist/keysim.js';
	script.onload = function() {
		var input = document.querySelector('textarea');
		var keyboard = Keysim.Keyboard.US_ENGLISH;
		keyboard.dispatchEventsForInput("ls", input);
		keyboard.dispatchEventsForAction("enter", input);
	};
	document.body.appendChild(script);
	```
