### ISSUE TITLE
RaspberryPi shortage: Support alternative SBCs

### ISSUE THREAD

**Issue by renne** [pikvm/pikvm#931]
**Is your feature request related to a problem? Please describe.**
Currently no RaspberryPi SBCs are available.

**Describe the solution you'd like**
Support alternative SBC hardware.

**Describe alternatives you've considered**
None.

**Comment by mdevaev** [comment]
Hi. Unfortunately, I can't do that. PiKVM is not just userspace software, but also kernel fixes and patches, as well as OS build system and thorough testing. Other SBCs don't have the proper level of support from manufacturers (at the Raspberry level), so we don't have the human resources for this.

I don't mind accepting patches to provide support for other SBCs (if they don't break the architecture), but I won't do it myself. If someone is willing to spend time on this, I don't mind.
