### ISSUE TITLE
Additional override options for editing kvmd-webterm.service arguments

### ISSUE THREAD

**Issue by jmott85** [pikvm/pikvm#934]
**Is your feature request related to a problem? Please describe.**
I needed a way to lock down the terminal access.  In order to do so, I had to edit the kvmd-webterm.service file and add:
--reconnect=0
-t disableLeaveAlert=true
-t disableReconnect=true

**Describe the solution you'd like**
Similar to the other "cmd_append" and "cmd_remove" features for other services, I'd like to be able to do the same for kvmd-webterm.

**Describe alternatives you've considered**
I've written a sed command to add these options to kvmd-webterm.service during buildtime.

`RUN sed -i '/^ExecStart.*/a\\t\t--reconnect=0 \\\n\t\t-t disableLeaveAlert=true \\\n\t\t-t disableReconnect=true \\' /usr/lib/systemd/system/kvmd-webterm.service`

**Additional context**
I'm using a dialog menu for the terminal app and I want to lock down access to shell.  I've also edited /home/kvmd-webterm/.bashrc to only run my shell script and then exit using the following lines at the top of the .bashrc:

```
trap '' 2
/home/kvmd-webterm/dialog.sh
exit
trap 2
```

**Comment by mdevaev** [comment]
I've added `$KVMD_WEBTERM_ARGS` that you can pass over `/etc/conf.d/kvmd-webterm`. It should solve your case.
