### ISSUE TITLE
Create image without SD card

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#935]
Is there a method to create the image (e.g. on a virtual server) without a SD card _or_ to create the image on Windows?

**Comment by mdevaev** [comment]
What image do you mean? For PiKVM OS?

**Comment by etkaar** [comment]
Yes

**Comment by mdevaev** [comment]
You can use `make image` on the virtual server, see the end of page: https://docs.pikvm.org/building_os/

**Comment by etkaar** [comment]
That will work also without an SD card?

**Comment by etkaar** [comment]
Oh, great - didn't know that! Thanks a lot.
