### ISSUE TITLE
Repository for the web frontend

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#939]
Could someone please tell me where the GitHub repository for the web frontend is? Unfortunately I am not able to find it. Did I overlook something?

**Comment by mdevaev** [comment]
Hello. It's here: https://github.com/pikvm/kvmd/tree/master/web

**Comment by etkaar** [comment]
Thank you! Are improvements and bug fixes welcome?

**Comment by mdevaev** [comment]
Yes, ofc

**Comment by etkaar** [comment]
Great! And great work by the way. One of my biggest dreams of the last 15 years became true!

**Comment by mdevaev** [comment]
:)
