### ISSUE TITLE
Layout for control of ATX <-> RPI 4

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#943]
PIKVM is able to control the ATX pins of the PC (e.g. reset, power), but I wonder where the layout sheet for that is; so that I know which phyiscal GPIO pins exactly I need to connect to the ATX pins.

**Comment by arch1mede** [comment]
Hi, our current v3 [document](https://docs.pikvm.org/v3/#atx-connection) references what goes where, but this assumes you are referring to the v3 and not something else.

**Comment by etkaar** [comment]
Well, I am using the RPI 4 with a custom HAT (shield), so I would need to exactly know which GPIO pins are respondible. Same goes for RPI 3.

**Comment by mdevaev** [comment]
Hello. Default pins are here: https://github.com/pikvm/kvmd/blob/master/kvmd/plugins/atx/gpio.py#L92

Note that values can be overwrited by the platform config, see here (kvmd/atx section): https://github.com/pikvm/kvmd/tree/master/configs/kvmd/main
