### ISSUE TITLE
PiKVM Handbook   MSD   Wim.boot for over 2.2G

### ISSUE THREAD

**Issue by peacokswiss** [pikvm/pikvm#948]
https://github.com/xe5700/kvmd-armbian/issues/12

read last post,   and expand your   Handbook for MSD and Windows  pls...

thx

That,  ubuntu-desktop und Kali-Linux don't have  network-install iso is here Problem not my...
I have debian-network-install.iso,  i am fine out,  that wy  Debian also today is uptodate !!

And if you have a home apt-cacher-ng Proxy,,  like me.... got your so fine out....

(Exluding nfs mount people,  not all are profis !!  )

**Comment by arch1mede** [comment]
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
I don't need you,  have you checked?
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
The best ist you remove your self ok
regards
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by mdevaev** [comment]
Hello. It was very difficult for me to understand the actual sequence of actions. As far as I can see, this is a special case. Thank you for the information, but we accept edits in the form of a ready-made pull request since we do not have the human resource to investigate, verify and describe each particular case.

**Comment by peacokswiss** [comment]
then you make such remarkt,   i will not do...   
in respekt,  by
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
i fick my self,,    
http://www.industrie-optimierer.ch/tmp/PiKVM/PiKVM_OrangePizero2/Readme.txt
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
some mistakes,,,  
but i make big ing stuff, in heavy Indsturie  ABB,  over 600Ampere per phase,   
so i dont need you chineese intro...
i know what i do.. 
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
If i talking about   one   1 TW    TerraWatt,    
is not importend your kidi sytem
not even a discusions...   only by alarm...status
don't talk again to me pls....  thx
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
Wennich was schreibe bleibt es,,,
ich finde auch eine unverstämte Frechheit mcih anzuficken   über email wegen git
so was doofes ist mir noch nie unter gekoommen,,,,
Ich code alles ,  alles von rockwell siemens, c bis böses Bash...   
halt bloss die Fresse..    wennich hässig werde.... dann ist das chinesen leben in Europa tot
mach mich ja nicht hässig
sicher
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
Soll ich noch ein Arschloch Papier und dir um den Arsch  wixxen.....
ist es das was du willst,  hier ist die Schweiz,  ich mach es....
  
 
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.

**Comment by peacokswiss** [comment]
Du Arschoch schon selbprogramierende  Betriebssyteme gehsehen,  ich schon in den 70er
Ich geb Dir ein Tipp,.  halt dich Fern von mir , wenn du länger leben willst,  ok  kappiert !!!
----Ursprüngliche Nachricht----
Von : ***@***.***
Datum : 25/02/2023 - 20:59 (MN)
An : ***@***.***
Cc : ***@***.***, ***@***.***
Betreff : Re: [pikvm/pikvm] PiKVM Handbook   MSD   Wim.boot for over 2.2G (Issue #948)
Hi, this is from a community member which we do not have any control over and that person does not monitor this github and at this time, no other SBC's are officially supported. I would recommend you open a request from their github and remove this.
