### ISSUE TITLE
Render problems with MSI BIOS

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#950]
Using a Raspberry Pi 4 with a CSI bridge (Geekworm) the BIOS of a modern B660 MSI mainboard looks a bit awkward.

I know that it may can be fixed by using a DisplayPort Dummy Plug (CSM can't be enabled), but why is that? How come UEFI leads to such glitches? Is this a bug from UEFI BIOS?

```
Mainboard: MSI B660M MAG MORTAR (MS-7D42)
BIOS Version: E7D42IMS.A00
BIOS Build Date: 14th December 2021
Resolution: 1280x720
```

```
Linux kvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux
```

![MSIBIOS2](https://user-images.githubusercontent.com/40885610/220758678-13df2821-112a-41f4-9296-3d76a7431a19.png)
![MSIBIOS](https://user-images.githubusercontent.com/40885610/220743345-0dcc3618-0985-4676-8270-ecd5e78e02ca.png)

CSM can't be enabled on this mainboard:

![photo_2023-02-22_22-50-50](https://user-images.githubusercontent.com/40885610/220767787-8a34e532-3ffe-46d1-af1c-d469ca72a340.jpg)

**Comment by arch1mede** [comment]
Hi, have you attempted any of the [edid](https://docs.pikvm.org/edid/) changes to see if they help?

**Comment by mdevaev** [comment]
No answer, so I'm closing it. Please use discord for similar questions.

**Comment by etkaar** [comment]
I didn't forget it ☺️ I temporarily use the PiKVM on another machine with a different mainboard, so I haven't been able yet to test it. I will soon post my results regarding this issue.

**Comment by etkaar** [comment]
Hi!

With following custom EDID (see [Tuning HDMI EDID - PiKVM Handbook](https://docs.pikvm.org/edid/#default-edid)) the MSI BIOS works:

```
1920x1080 as preferred. Useful for Gigabyte GA-H77-DS3H, Intel NUC or [ASRock H670 PG Riptide]
```
```
00FFFFFFFFFFFF005262888800888888
1C150103800000780AEE91A3544C9926
0F505425400001000100010001000100
010001010101D32C80A070381A403020
350040442100001E7E1D00A050001940
3020370080001000001E000000FC0050
492D4B564D20566964656F0A000000FD
00323D0F2E0F000000000000000001C4
02030400DE0D20A03058122030203400
F0B400000018E01500A0400016303020
3400000000000018B41400A050D01120
3020350080D810000018AB22A0A05084
1A3030203600B00E1100001800000000
00000000000000000000000000000000
00000000000000000000000000000000
00000000000000000000000000000045
```

However, no mouse support in BIOS, but in GRML. Is not really relevant in my case, but what could be the reason the mouse does not work?

**Comment by arch1mede** [comment]
Hi, I have seen this same behavior even with commercial solutions, perhaps the different mouse modes will help. https://docs.pikvm.org/mouse
