### ISSUE TITLE
Reproducible black screen issue

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#956]
I have a machine with Windows 10 installed. Once I join a Linux desktop environment (in my case *Zorin OS*) and then restart the PC, I get a black screen on the PiKVM (black, not the "NO SIGNAL" message").

- A restart of PiKVM does not work.
- A restart of the PC does not work.
- Replugging the HDMI cable does not work.
- Resetting the stream or HID does not work.

What instead works:

- Plugging out the HDMI cable, connect it to a monitor, restart the PC and then connect it back to the PiKVM.

I assume that this might be an EDID related issue.

Is there a function to _reset_ this, since in default state all worked perfectly? In a live production environment I am of course not able to unplug the HDMI and connect it to a monitor.

**Comment by mdevaev** [comment]
> Once I join a Linux desktop environment

How? Where? I don't understand.

Try this: https://docs.pikvm.org/edid

**Comment by etkaar** [comment]
> > Once I join a Linux desktop environment
> 
> How? Where? I don't understand.
> 
> Try this: https://docs.pikvm.org/edid

What I mean: Flashing an ISO image of ZorinOS (which is a Linux distribution) to USB or using the emulated Mass Storage Drive and then starting it. That all works – but when I then restart the server, I get only a black screen.

**Comment by etkaar** [comment]
Closing this for now since it is unclear if this might be a BIOS issue.
