### ISSUE TITLE
No way to disable iptables DROP in otgnet

### ISSUE THREAD

**Issue by tarasglek** [pikvm/pikvm#957]
https://github.dev/pikvm/kvmd/blob/c98a18aa7e21dd2bfd3f76ebc2e0c056ef989759/kvmd/apps/otgnet/__init__.py#L114 unconditionally issues `-A INPUT -i usb0 -j DROP` and there is no way to undo it.

This means I can't do `ssh -J pikvm 169.254.0.2` due to this firewall rule.

I would like to be able to use pikvm as a jumphost over otgnet to connect to computer without needing to enable routing.

**Comment by mdevaev** [comment]
Hello. Did you try allow_tcp?
```yaml
otgnet:
    firewall:
        allow_tcp: [22]
```

**Comment by mdevaev** [comment]
Sup?

**Comment by mdevaev** [comment]
Sup?

**Comment by tarasglek** [comment]
Sorry for slow response.
No change. This allows:
`-A INPUT -i usb0 -p tcp -m tcp --dport 22 -j ACCEPT` 
so i can ssh into pikvm from my host. Can't go from pikvm into my server.

**Comment by mdevaev** [comment]
Please update KVMD to 3.210, should be fixed now

**Comment by tarasglek** [comment]
works great, thanks!

**Comment by mdevaev** [comment]
Ur welcome
