### ISSUE TITLE
Please add the ability to disable HTTPS and access via HTTP

### ISSUE THREAD

**Issue by ipv6hack** [pikvm/pikvm#960]
I want to create an environment where PIKVM is used from the Internet via IIS reverse proxy, so I want to be able to access PIKVM via HTTP instead of HTTPS!
I would like to implement a function to switch between HTTPS and HTTP for such an access method.
Please help me.

**Comment by mdevaev** [comment]
Hello. Edit `/etc/kvmd/nginx/nginx.conf`, comment two `server` sections, and add the single one:
```nginx
	server {
		include /etc/kvmd/nginx/listen-http.conf;
		include /etc/kvmd/nginx/certbot.ctx-server.conf;
		include /etc/kvmd/nginx/kvmd.ctx-server.conf;
		include /usr/share/kvmd/extras/*/nginx.ctx-server.conf;
	}
```

**Comment by ipv6hack** [comment]
Worked well with HTTP
Thank you so much!
It helped me a lot!

**Comment by mdevaev** [comment]
:ok_hand:
