### ISSUE TITLE
How to simulate a disk or other form under Windows system so that Windows can upload and download files?

### ISSUE THREAD

**Issue by TelDragon** [pikvm/pikvm#967]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

How to simulate a disk or other form under Windows system so that Windows can upload and download files?
如何在windows系统下模拟磁盘或其它形式，使其windows可以进行上传下载文件？

This is not a simulation of the type of file drive letter that a CD or DVD wants.
在这里不是模拟cd 也不是模拟DVD 想要磁盘类型的文件盘符那种。

**Comment by etkaar** [comment]
Hi! Could you please describe your issue in English? :)

**Comment by mdevaev** [comment]
You need to create an empty image with fat filesystem and connect it with rw mode in msd ui.

https://docs.pikvm.org/msd/
