### ISSUE TITLE
Transport from audio

### ISSUE THREAD

**Issue by gitpower2017** [pikvm/pikvm#97]
there is the possibility that audio is also transmitted.
Maybe the RPI will report to the PC/server as a USB soundcard?

**Comment by gitpower2017** [comment]
sorry for doppel posting. Ther was an error on my Browser

**Comment by mdevaev** [comment]
I will do it. There are two USB and TC358743 capabilities. Both will be supported.

**Comment by torpak** [comment]
@mdevaev TC358743 would mean getting the hdmi audio channel?

**Comment by piezza** [comment]
Would it also be possible to capture sound? My usecase is to use tools like MS Teams over pikvm remotely. So playing back and capturing sound in browser window would be cool!

**Comment by mdevaev** [comment]
Not right now but I'm working on it.

**Comment by rtrombetta** [comment]
There´s a way to do bidirectional audio ?

**Comment by mdevaev** [comment]
Not yet

**Comment by mdevaev** [comment]
Just some links for me to not forget:
- https://tools.ietf.org/id/draft-nandakumar-rtcweb-sdp-01.html
- https://tools.ietf.org/id/draft-ietf-rtcweb-sdp-08.html#rfc.section.5.2.6
- https://datatracker.ietf.org/doc/html/rfc4566
- https://datatracker.ietf.org/doc/html/draft-ietf-mmusic-data-channel-sdpneg-25
- https://developer.mozilla.org/ru/docs/Web/Media/Formats/WebRTC_codecs
- https://gist.github.com/albanpeignier/104902
- https://github.com/xiph/vorbis/blob/master/examples/encoder_example.c
- https://www.uni-due.de/~be0001/rn/index_e.html

**Comment by GralfR** [comment]
I'm just getting into it with what's laying around (pi4 2GB with USB-HDMI-capture).
The first boot was good. Got my picture. And was asking for sound/audio, too.
I got my test-signal from a DVB receiver/settopbox. That could be a usecase, too, but needs audio.

Looking forward to it.

**Comment by chilman408** [comment]
Question:  When audio support is enabled, will it be enabled on V2 as well or just V3?  

If it will be enabled for V2, is the current recommended hardware applicable (like the geekworm HDMI-CSI2)?

**Comment by mdevaev** [comment]
Geekworm have some hardware bugs so audio will not work on it.

**Comment by chilman408** [comment]
> Geekworm have some hardware bugs so audio will not work on it.

Thank you, do you have a recommended hardware setup for V2?  Would the Auvidea B101 work?

**Comment by mdevaev** [comment]
B101 will work, yes.

**Comment by chilman408** [comment]
Sorry one question, will the Auvidea B102 work?

**Comment by mdevaev** [comment]
Yes

**Comment by awkspace** [comment]
Would it be possible to offer a bounty for audio support over HDMI? This would be useful to my workflow and I'd be happy to donate towards it being done.

**Comment by awkspace** [comment]
@mdevaev My understanding is that the hardware is available, but not the software, correct? I own a pre-assembled PiKVM V3 from PiShop.us, but there is no option to stream the audio from the WebUI. My question was whether I could donate to the development of the software for this.

**Comment by mdevaev** [comment]
This feature is implemented in the hardware, yes. You can donate here if you want, https://patreon.com/pikvm, I will be grateful :)

**Comment by piezza** [comment]
I just wonder if it is not also possible to use Linux USB Audio Gadget driver for audio and transfer it bi-directional over WebRTC. Having both, speaker and mic would be great. I assume over HDMI only one direction will work?

**Comment by mdevaev** [comment]
Yep, only one direction.

**Comment by mdevaev** [comment]
The reason is software only.

**Comment by mdevaev** [comment]
V3 users can test the audio right now: https://docs.pikvm.org/audio/

**Comment by bora-fsd** [comment]
Thank you @mdevaev. To confirm, is this to receive audio from the pikvm connected machine only? Or is there support to transmit microphone from web browser to pikvm as well?

**Comment by mdevaev** [comment]
This is only to recieve audio from the machine. Microphone support is not yet in the plans.

**Comment by json81** [comment]
> V3 users can test the audio right now: https://docs.pikvm.org/audio/

Tested and working!

**Comment by awkspace** [comment]
Another 👍 here. Audio is working great on my v3. Thank you so much!!

**Comment by mdevaev** [comment]
I suppose it can be considered solved now :)

**Comment by moezden** [comment]
Hi @mdevaev, regarding 

> "Reverse audio transmission, that is, from the browser towards PiKVM (for example, to emulate a microphone) is not yet supported."

Can we expect a feature for mic emulation soon?

**Comment by mdevaev** [comment]
No, sorry.

**Comment by mdevaev** [comment]
Official [PiKVM V3 and V4 devices](https://pikvm.org/buy) gets two-way audio with microphone.

Now you can use voice applications remotely, or you can just emotionally tell the server what you think about it.

**https://docs.pikvm.org/audio**

*PS: I know that many people wanted this feature. I spent all the New Year holidays on it, so if you found PiKVM useful and finally got what you wanted, you can support my work on PiKVM or just give me a beer with donation to [Patreon](https://www.patreon.com/pikvm) or [Paypal](https://paypal.me/pikvm). Happy PiKVMing!*
