### ISSUE TITLE
Password protection support by webserver

### ISSUE THREAD

**Issue by etkaar** [pikvm/pikvm#979]
Does PiKVM offer an on/off setting for password protection by the webserver? While it is not absolutely required, some users may feel safer using it as it is an additional barriere. If PiKVM does not offer it, where can the nginx configuration file be modified? I didn't find the PiKVM configuration file in `/etc/nginx`.

**Comment by mdevaev** [comment]
Password authorization will conflict with KVMD, because it also does it on its own. For the future, the nginx configuration is in `/etc/kvmd/nginx`, and we use `kvmd-nginx` service instead of just `nginx.
