### ISSUE TITLE
Document creating Tailscale certificates

### ISSUE THREAD

**Issue by vivook** [pikvm/pikvm#988]
Tailscale can now [create TLS certificates](https://tailscale.com/kb/1153/enabling-https/). It'd be helpful if the docs were updated showing how to do this.

**Comment by mdevaev** [comment]
I'll accept the patch if someone does. But it seems strange to me to move someone else's documentation to us, unless it highlights some specific steps.

**Comment by avinal** [comment]
Thanks @alethiophile, it worked for nginx. But it seems the services won't start unless you give VNC and nginx ownership of the cert. I fixed this by separately copying the certs and giving them ownership. 

With symlink, I have not tested, but I think creating group permission on the certs and adding `kvmd-nginx` and `kvmd-vnc` should work.

@mdevaev I would like to document this behavior as it differs from standard steps.

**Comment by mdevaev** [comment]
Yes please.
