### ISSUE TITLE
Give OLED longer life by making some changes to the oled script

### ISSUE THREAD

**Issue by arch1mede** [pikvm/pikvm#994]
For those of us that bought a v3 back in the day, please make it so there is even wear on the OLED pixels, maybe invert the display for an equal amount of time. This will also help v4 users.

![image](https://user-images.githubusercontent.com/3489071/232581767-16119f08-6f7f-4809-a97a-e9f9d1be244c.png)

**Comment by mdevaev** [comment]
I've reduced display contrast to 25%. I think it will be better solution now.
