### ISSUE TITLE
Regular check of Discord server invitation - Invitation has expired

### ISSUE THREAD

**Issue by smalldragoon** [pikvm/pikvm#996]
**Describe the bug**
The Invitation link for the Support discord channel has expired

**To Reproduce**
Steps to reproduce the behavior, like:
1. Go to 'https://pikvm.org/support/'
2. Click on 'click here to join the chat' 
3. Discord Window opens
4. See error : Invitation Link has expired

**Expected behavior**
Join Discord Server

**Desktop (please complete the following information):**
N/A, same behavior Desktop / Mobile

**PiKVM info:**
N/A

**Additional context**
Checked with 2 different Discord accounts

**Comment by smalldragoon** [comment]
HI, Yes still not working here 
Here are some screenshots ( Desktop & Mobile ) . 
Desktop : 
![DiscordDesktop01](https://user-images.githubusercontent.com/7382934/233209273-3b2bd908-7e22-4791-b59c-10186fc7b93b.jpg)
Mobile : ( sorry in French )
![IMG_6085](https://user-images.githubusercontent.com/7382934/233209467-dafc885b-5361-439e-8665-2420f9505369.PNG)

**Comment by mdevaev** [comment]
Try this: https://discord.gg/NG74RqV7FP

If it will not work, try this: https://stealthygaming.com/why-discord-unable-to-accept-invite/

**Comment by smalldragoon** [comment]
Same result with the link 
I reviewed the 7 reasons, none seems matching on my side 
I re-tried with 2 accounts
![image](https://user-images.githubusercontent.com/7382934/233329718-01af38e7-00ef-4147-9d8d-f11f8d7a1a39.png)

and  2nd one : 
![image](https://user-images.githubusercontent.com/7382934/233329979-d2c53ca3-1abe-4b3f-99c0-d06ead65ef71.png)

The error message on mobile indicate that " link is invalid or has expired "

**Comment by smalldragoon** [comment]
I added a phone number , no changes . Are you sure I’m not banned ?

**Comment by mdevaev** [comment]
I've just checked, you don't banned :/

**Comment by smalldragoon** [comment]
I created a Discord Ticket.I read in some forum an issue with servers you joined, left and trying to rejoin.
One workaround is to join another server and try again. I managed to join with the 2nd account I created, it will work for me for now. Will keep you posted with result from Discord

**Comment by mdevaev** [comment]
Okay

**Comment by smalldragoon** [comment]
Feedback from Discord : 
- Can you check if my IP is not banned ?
- Can you check if my account is still not part of the server ( ghost account). if so, just delete it
- Do you have a Bot to moderate ? if so, can you check if I'm not part of its own blacklist ' discord tag )?
- Thanks

**Comment by mdevaev** [comment]
What is your primary account?

**Comment by smalldragoon** [comment]
mumphrey#3233

**Comment by mdevaev** [comment]
Try again with it

**Comment by mdevaev** [comment]
Your main account has been banned. Change your password, maybe it was spam.
