### ISSUE TITLE
Mass Storage Drive not working

### ISSUE THREAD

**Issue by GreenDigit** [pikvm/pikvm#998]
**Describe the bug**
Cannot connect an iso to the server 
(note that mouse and keyboard work just fine)
**To Reproduce**
Steps to reproduce the behavior, like:
upload ISO, connect.
Using B85-HD3 MOBO 

**Expected behavior**
Able to boot from PIKVM's ISO drive

**Screenshots**

<img width="416" alt="Schermafbeelding 2023-04-22 om 23 55 57" src="https://user-images.githubusercontent.com/90311847/233808177-2165f629-887f-4d37-9391-0dbade1a6dad.png">
<img width="615" alt="Schermafbeelding 2023-04-22 om 23 58 12" src="https://user-images.githubusercontent.com/90311847/233808220-cd4c9a57-c0c6-480f-b666-71650350a1fe.png">

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser Safari
 - VNC client (if used)

**PiKVM info:**
  - Raspberry Pi board version RPI4 2GB (using geekwork PIKVM-A8)
  - PiKVM platform V4
  - Video capture type CSI bridge[e.g. CSI bridge]
  - KVMD version: `kvmd 3.173-1
kvmd-fan 0.22-1
kvmd-oled 0.13-1
kvmd-platform-v3-hdmi-rpi4 3.173-1
kvmd-webterm 0.42-1`
  - uStreamer version: `ustreamer 5.31-1`
  - Linux kernel: `Linux pikvm 5.15.68-3-rpi-ARCH #1 SMP Mon Oct 31 20:56:54 MSK 2022 armv7l GNU/Linux`

**Additional context**

**Comment by mdevaev** [comment]
Hello. I'm sorry, but since you bought a Chinese clone, we can't provide technical support for you. Please contact the manufacturer.
